##### ===================================================================================================================

#  Barack Obama Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/BarackObamaTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1219267208250941440""",https://twitter.com/barackobama/status/1219267...,2020-01-20 14:35:29,"""Every so often, I re-read Dr. King’s Letter f...",Tweet,Twitter for iPhone,50301,239729,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected
1,"""1218174463046553600""",https://twitter.com/barackobama/status/1218174...,2020-01-17 14:13:19,"""In every scene, you are my star, @MichelleOba...",Tweet,Twitter for iPhone,394988,2758964,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected
2,"""1216725015695183872""",https://twitter.com/barackobama/status/1216725...,2020-01-13 14:13:44,"""Glad to see American Factory’s Oscar nod for ...",Tweet,Twitter for iPhone,11017,127215,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected
3,"""1216428587328458754""",https://twitter.com/barackobama/status/1216428...,2020-01-12 18:35:50,"""Our fellow Americans in Puerto Rico can use o...",Tweet,Twitter for iPhone,31512,135165,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected
4,"""1215378018790707205""",https://twitter.com/barackobama/status/1215378...,2020-01-09 21:01:14,"""Here’s the thing: Even with problems of this ...",Reply,Twitter for iPhone,6389,36772,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""523207203864313856""",https://twitter.com/obamawhitehouse/status/523...,2014-10-17 20:21:32,"""Here's how President Obama's acting to protec...",Retweet,TweetDeck,659,782,"""30313925""","""White House Archived""",obamawhitehouse,Verified,https://twitter.com/obamawhitehouse,Not Protected
3196,"""523197408457416704""",https://twitter.com/barackobama/status/5231974...,2014-10-17 19:42:37,"""DYK: Raising the minimum wage would lift near...",Tweet,Twitter Web Client,813,1208,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected
3197,"""523162093378232320""",https://twitter.com/barackobama/status/5231620...,2014-10-17 17:22:17,"""Add your name if you agree: Higher wages are ...",Tweet,Twitter Web Client,747,1338,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected
3198,"""523141731252854784""",https://twitter.com/barackobama/status/5231417...,2014-10-17 16:01:22,"""Happening now: President Obama is speaking at...",Tweet,Twitter Web Client,253,592,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected
3199,"""522839459197231104""",https://twitter.com/barackobama/status/5228394...,2014-10-16 20:00:15,"""If you do one meaningful thing today, take th...",Tweet,Twitter Web Client,354,820,"""813286""","""Barack Obama""",barackobama,Verified,https://twitter.com/barackobama,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1219267208250941440""","""Barack Obama""",barackobama,"""Every so often, I re-read Dr. King’s Letter f...",50301,239729,2020-01-20 14:35:29
1,"""1218174463046553600""","""Barack Obama""",barackobama,"""In every scene, you are my star, @MichelleOba...",394988,2758964,2020-01-17 14:13:19
2,"""1216725015695183872""","""Barack Obama""",barackobama,"""Glad to see American Factory’s Oscar nod for ...",11017,127215,2020-01-13 14:13:44
3,"""1216428587328458754""","""Barack Obama""",barackobama,"""Our fellow Americans in Puerto Rico can use o...",31512,135165,2020-01-12 18:35:50
4,"""1215378018790707205""","""Barack Obama""",barackobama,"""Here’s the thing: Even with problems of this ...",6389,36772,2020-01-09 21:01:14

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1219267208250941440""","""Barack Obama""",barackobama,"""Every so often, I re-read Dr. King’s Letter f...",50301,239729,2020-01-20 14:35:29,[],[],0,0
1,"""1218174463046553600""","""Barack Obama""",barackobama,"""In every scene, you are my star, @MichelleOba...",394988,2758964,2020-01-17 14:13:19,[@MichelleObama!],[],0,1
2,"""1216725015695183872""","""Barack Obama""",barackobama,"""Glad to see American Factory’s Oscar nod for ...",11017,127215,2020-01-13 14:13:44,[],[],0,0
3,"""1216428587328458754""","""Barack Obama""",barackobama,"""Our fellow Americans in Puerto Rico can use o...",31512,135165,2020-01-12 18:35:50,[],[],0,0
4,"""1215378018790707205""","""Barack Obama""",barackobama,"""Here’s the thing: Even with problems of this ...",6389,36772,2020-01-09 21:01:14,[],[],0,0
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""523207203864313856""","""White House Archived""",obamawhitehouse,"""Here's how President Obama's acting to protec...",659,782,2014-10-17 20:21:32,[],[],0,0
3196,"""523197408457416704""","""Barack Obama""",barackobama,"""DYK: Raising the minimum wage would lift near...",813,1208,2014-10-17 19:42:37,[],"[#RaiseTheWage""]",1,0
3197,"""523162093378232320""","""Barack Obama""",barackobama,"""Add your name if you agree: Higher wages are ...",747,1338,2014-10-17 17:22:17,[],[],0,0
3198,"""523141731252854784""","""Barack Obama""",barackobama,"""Happening now: President Obama is speaking at...",253,592,2014-10-17 16:01:22,[],[],0,0
3199,"""522839459197231104""","""Barack Obama""",barackobama,"""If you do one meaningful thing today, take th...",354,820,2014-10-16 20:00:15,[],[],0,0

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1219267208250941440""","""Barack Obama""",barackobama,"""Every so often, I re-read Dr. King’s Letter f...",50301,239729,[],[],0,0,2020-01-20,14:35:29
1,"""1218174463046553600""","""Barack Obama""",barackobama,"""In every scene, you are my star, @MichelleOba...",394988,2758964,[@MichelleObama!],[],0,1,2020-01-17,14:13:19
2,"""1216725015695183872""","""Barack Obama""",barackobama,"""Glad to see American Factory’s Oscar nod for ...",11017,127215,[],[],0,0,2020-01-13,14:13:44
3,"""1216428587328458754""","""Barack Obama""",barackobama,"""Our fellow Americans in Puerto Rico can use o...",31512,135165,[],[],0,0,2020-01-12,18:35:50
4,"""1215378018790707205""","""Barack Obama""",barackobama,"""Here’s the thing: Even with problems of this ...",6389,36772,[],[],0,0,2020-01-09,21:01:14
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""523207203864313856""","""White House Archived""",obamawhitehouse,"""Here's how President Obama's acting to protec...",659,782,[],[],0,0,2014-10-17,20:21:32
3196,"""523197408457416704""","""Barack Obama""",barackobama,"""DYK: Raising the minimum wage would lift near...",813,1208,[],"[#RaiseTheWage""]",1,0,2014-10-17,19:42:37
3197,"""523162093378232320""","""Barack Obama""",barackobama,"""Add your name if you agree: Higher wages are ...",747,1338,[],[],0,0,2014-10-17,17:22:17
3198,"""523141731252854784""","""Barack Obama""",barackobama,"""Happening now: President Obama is speaking at...",253,592,[],[],0,0,2014-10-17,16:01:22
3199,"""522839459197231104""","""Barack Obama""",barackobama,"""If you do one meaningful thing today, take th...",354,820,[],[],0,0,2014-10-16,20:00:15

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/BarackObamaImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1218174463046553600""","""1218174457145188352""",https://pbs.twimg.com/media/EOfTNvCX4AA8jse.jpg,https://t.co/hgMBhHasBj
1,"""1212883749727158273""","""1212883743716732928""",https://pbs.twimg.com/media/ENUHVroU8AAsPoI.jpg,https://t.co/8QMCazx2Fs
2,"""1211694118767738886""","""1211694112862289928""",https://pbs.twimg.com/media/ENDNYDWWwAgJIkf.jpg,https://t.co/mQ2VssyDwt
3,"""1211331851358494720""","""1211331845998166019""",https://pbs.twimg.com/media/EM-D5WHWwAMzJZ_.jpg,https://t.co/PEcgwotcxm
4,"""1211033245812441091""","""1211033237050531841""",https://pbs.twimg.com/media/EM50UBGWoAEi8Xa.jpg,https://t.co/l5qTGkAPok
...,...,...,...,...
879,"""526095344955031553""","""526095343998730242""",https://pbs.twimg.com/media/B00Q7ZEIAAIOc0T.png,http://t.co/CmIJFRB8W0
880,"""525354184087203840""","""525354183365779456""",https://pbs.twimg.com/media/B0pu2KjIYAAFZQy.png,http://t.co/a5GyaHDfGo
881,"""524695722617102336""","""524695721878908928""",https://pbs.twimg.com/media/B0gX-qXCcAAQf65.png,http://t.co/v0Zy3ItSYE
882,"""524235391365160961""","""524235390639550464""",https://pbs.twimg.com/media/B0Z1T23CMAA93F_.jpg,http://t.co/p5NVoLxDZQ
883,"""523207203864313856""","""523207202757017601""",https://pbs.twimg.com/media/B0LOLchCAAEZYKQ.jpg,http://t.co/GOFRZxOoB7

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (884, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (884, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1218174463046553600"  Image added
1    "1212883749727158273"  Image added
2    "1211694118767738886"  Image added
3    "1211331851358494720"  Image added
4    "1211033245812441091"  Image added
..                     ...          ...
879   "526095344955031553"  Image added
880   "525354184087203840"  Image added
881   "524695722617102336"  Image added
882   "524235391365160961"  Image added
883   "523207203864313856"  Image added

[884 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1219267208250941440""","""Barack Obama""",barackobama,"""Every so often, I re-read Dr. King’s Letter f...",50301,239729,[],[],0,0,2020-01-20,14:35:29,NaN
1,"""1218174463046553600""","""Barack Obama""",barackobama,"""In every scene, you are my star, @MichelleOba...",394988,2758964,[@MichelleObama!],[],0,1,2020-01-17,14:13:19,Image added
2,"""1216725015695183872""","""Barack Obama""",barackobama,"""Glad to see American Factory’s Oscar nod for ...",11017,127215,[],[],0,0,2020-01-13,14:13:44,NaN
3,"""1216428587328458754""","""Barack Obama""",barackobama,"""Our fellow Americans in Puerto Rico can use o...",31512,135165,[],[],0,0,2020-01-12,18:35:50,NaN
4,"""1215378018790707205""","""Barack Obama""",barackobama,"""Here’s the thing: Even with problems of this ...",6389,36772,[],[],0,0,2020-01-09,21:01:14,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,"""523207203864313856""","""White House Archived""",obamawhitehouse,"""Here's how President Obama's acting to protec...",659,782,[],[],0,0,2014-10-17,20:21:32,Image added
3211,"""523197408457416704""","""Barack Obama""",barackobama,"""DYK: Raising the minimum wage would lift near...",813,1208,[],"[#RaiseTheWage""]",1,0,2014-10-17,19:42:37,NaN
3212,"""523162093378232320""","""Barack Obama""",barackobama,"""Add your name if you agree: Higher wages are ...",747,1338,[],[],0,0,2014-10-17,17:22:17,NaN
3213,"""523141731252854784""","""Barack Obama""",barackobama,"""Happening now: President Obama is speaking at...",253,592,[],[],0,0,2014-10-17,16:01:22,NaN
3214,"""522839459197231104""","""Barack Obama""",barackobama,"""If you do one meaningful thing today, take th...",354,820,[],[],0,0,2014-10-16,20:00:15,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/BarackObamaVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1207006717172748292""","""1207005356783800320""",https://video.twimg.com/amplify_video/12070053...,https://t.co/ywzvqox50Z
1,"""1205880457545560066""","""1205880406341509126""",https://video.twimg.com/tweet_video/ELwl1y2W4A...,https://t.co/tPDDSje2ej
2,"""1204448901291487233""","""1204393094789189633""",https://video.twimg.com/amplify_video/12043930...,https://t.co/FCU2sRJeoq
3,"""1204067567112982528""","""1204065626924421120""",https://video.twimg.com/amplify_video/12040656...,https://t.co/dVJD5WGUmY
4,"""1189289098604896257""","""1189275501812224004""",https://video.twimg.com/amplify_video/11892755...,https://t.co/vfLsBKd1WP
...,...,...,...,...
124,"""628234076214800384""","""628234075199791105""",https://video.twimg.com/tweet_video/CLfvkBgUYA...,http://t.co/IqnRnAraM8
125,"""615976319231266816""","""615976317784166400""",https://video.twimg.com/tweet_video/CIxjMouUEA...,http://t.co/u4zDyut8li
126,"""573942668750880768""","""573941997913792512""",https://video.twimg.com/ext_tw_video/573941997...,http://t.co/wR6sMr4uHf
127,"""552893734191259649""","""552891748226056193""",https://video.twimg.com/tweet_video/B6xEHZxCQA...,http://t.co/TVZWx5KEt0
128,"""528260717455998976""","""528260716159971328""",https://video.twimg.com/tweet_video/B1TCUo-CMA...,http://t.co/Zo4nobtryp

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (129, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (129, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1207006717172748292"  Video added
1    "1205880457545560066"  Video added
2    "1204448901291487233"  Video added
3    "1204067567112982528"  Video added
4    "1189289098604896257"  Video added
..                     ...          ...
124   "628234076214800384"  Video added
125   "615976319231266816"  Video added
126   "573942668750880768"  Video added
127   "552893734191259649"  Video added
128   "528260717455998976"  Video added

[129 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1219267208250941440""","""Barack Obama""",barackobama,"""Every so often, I re-read Dr. King’s Letter f...",50301,239729,[],[],0,0,2020-01-20,14:35:29,NaN,NaN
1,"""1218174463046553600""","""Barack Obama""",barackobama,"""In every scene, you are my star, @MichelleOba...",394988,2758964,[@MichelleObama!],[],0,1,2020-01-17,14:13:19,Image added,NaN
2,"""1216725015695183872""","""Barack Obama""",barackobama,"""Glad to see American Factory’s Oscar nod for ...",11017,127215,[],[],0,0,2020-01-13,14:13:44,NaN,NaN
3,"""1216428587328458754""","""Barack Obama""",barackobama,"""Our fellow Americans in Puerto Rico can use o...",31512,135165,[],[],0,0,2020-01-12,18:35:50,NaN,NaN
4,"""1215378018790707205""","""Barack Obama""",barackobama,"""Here’s the thing: Even with problems of this ...",6389,36772,[],[],0,0,2020-01-09,21:01:14,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,"""523207203864313856""","""White House Archived""",obamawhitehouse,"""Here's how President Obama's acting to protec...",659,782,[],[],0,0,2014-10-17,20:21:32,Image added,NaN
3211,"""523197408457416704""","""Barack Obama""",barackobama,"""DYK: Raising the minimum wage would lift near...",813,1208,[],"[#RaiseTheWage""]",1,0,2014-10-17,19:42:37,NaN,NaN
3212,"""523162093378232320""","""Barack Obama""",barackobama,"""Add your name if you agree: Higher wages are ...",747,1338,[],[],0,0,2014-10-17,17:22:17,NaN,NaN
3213,"""523141731252854784""","""Barack Obama""",barackobama,"""Happening now: President Obama is speaking at...",253,592,[],[],0,0,2014-10-17,16:01:22,NaN,NaN
3214,"""522839459197231104""","""Barack Obama""",barackobama,"""If you do one meaningful thing today, take th...",354,820,[],[],0,0,2014-10-16,20:00:15,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Male"

#Create an Vocation column 
Tweets_df['Vocation'] = "Politics"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3215, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1219267208250941440""","""Barack Obama""",barackobama,50301,239729,[],[],0,0,2020-01-20,14:35:29,-,-,Male,Politics
1,"""1218174463046553600""","""Barack Obama""",barackobama,394988,2758964,[@MichelleObama!],[],0,1,2020-01-17,14:13:19,Image added,-,Male,Politics
2,"""1216725015695183872""","""Barack Obama""",barackobama,11017,127215,[],[],0,0,2020-01-13,14:13:44,-,-,Male,Politics
3,"""1216428587328458754""","""Barack Obama""",barackobama,31512,135165,[],[],0,0,2020-01-12,18:35:50,-,-,Male,Politics
4,"""1215378018790707205""","""Barack Obama""",barackobama,6389,36772,[],[],0,0,2020-01-09,21:01:14,-,-,Male,Politics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,"""523207203864313856""","""White House Archived""",obamawhitehouse,659,782,[],[],0,0,2014-10-17,20:21:32,Image added,-,Male,Politics
3211,"""523197408457416704""","""Barack Obama""",barackobama,813,1208,[],"[#RaiseTheWage""]",1,0,2014-10-17,19:42:37,-,-,Male,Politics
3212,"""523162093378232320""","""Barack Obama""",barackobama,747,1338,[],[],0,0,2014-10-17,17:22:17,-,-,Male,Politics
3213,"""523141731252854784""","""Barack Obama""",barackobama,253,592,[],[],0,0,2014-10-17,16:01:22,-,-,Male,Politics
3214,"""522839459197231104""","""Barack Obama""",barackobama,354,820,[],[],0,0,2014-10-16,20:00:15,-,-,Male,Politics

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3215, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1219267208250941440""","""Barack Obama""",barackobama,Male,Politics,[],0,[],0,239729,50301,-,-,2020-01-20,14:35:29
"""1218174463046553600""","""Barack Obama""",barackobama,Male,Politics,[],0,[@MichelleObama!],1,2758964,394988,Image added,-,2020-01-17,14:13:19
"""1216725015695183872""","""Barack Obama""",barackobama,Male,Politics,[],0,[],0,127215,11017,-,-,2020-01-13,14:13:44
"""1216428587328458754""","""Barack Obama""",barackobama,Male,Politics,[],0,[],0,135165,31512,-,-,2020-01-12,18:35:50
"""1215378018790707205""","""Barack Obama""",barackobama,Male,Politics,[],0,[],0,36772,6389,-,-,2020-01-09,21:01:14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""523207203864313856""","""White House Archived""",obamawhitehouse,Male,Politics,[],0,[],0,782,659,Image added,-,2014-10-17,20:21:32
"""523197408457416704""","""Barack Obama""",barackobama,Male,Politics,"[#RaiseTheWage""]",1,[],0,1208,813,-,-,2014-10-17,19:42:37
"""523162093378232320""","""Barack Obama""",barackobama,Male,Politics,[],0,[],0,1338,747,-,-,2014-10-17,17:22:17
"""523141731252854784""","""Barack Obama""",barackobama,Male,Politics,[],0,[],0,592,253,-,-,2014-10-17,16:01:22
"""522839459197231104""","""Barack Obama""",barackobama,Male,Politics,[],0,[],0,820,354,-,-,2014-10-16,20:00:15

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/BarackObama_df.csv')