##### ===================================================================================================================

#  Bruno Mars Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/BrunoMarsTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1219387020939685890""",https://twitter.com/brunomars/status/121938702...,2020-01-20 22:31:35,"""Wanted to wish everyone a Happy Martin Luther...",Tweet,Twitter for iPhone,461,4890,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
1,"""1219384974631030785""",https://twitter.com/brunomars/status/121938497...,2020-01-20 22:23:27,"""Nah! https://t.co/a01vjusZOJ""",Tweet,Twitter for iPhone,317,3984,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
2,"""1218996607317753856""",https://twitter.com/brunomars/status/121899660...,2020-01-19 20:40:13,"""We must. ðŸ¥‚ https://t.co/2jNeKORa2o""",Tweet,Twitter for iPhone,556,5645,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
3,"""1218996210167513088""",https://twitter.com/brunomars/status/121899621...,2020-01-19 20:38:39,"""ðŸ˜¢ I miss this. https://t.co/3mKj6wVsTl""",Tweet,Twitter for iPhone,5406,36558,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
4,"""1218989063706828800""",https://twitter.com/brunomars/status/121898906...,2020-01-19 20:10:15,"""Hereâ€™s a little more sunshine for your Sunday...",Tweet,Twitter for iPhone,625,4055,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3191,"""144908780830851072""",https://twitter.com/brunomars/status/144908780...,2011-12-08 22:38:40,"""To be honest the changes aren't that bad.. Ma...",Tweet,Twitter Web Client,2232,871,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
3192,"""144907084541071360""",https://twitter.com/brunomars/status/144907084...,2011-12-08 22:31:55,"""Im so mad I just drank all the water in my po...",Tweet,Twitter Web Client,1916,722,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
3193,"""144906944249995264""",https://twitter.com/brunomars/status/144906944...,2011-12-08 22:31:22,"""Im so mad I just threw my car over the mounta...",Tweet,Twitter Web Client,1974,801,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
3194,"""144905630002581504""",https://twitter.com/brunomars/status/144905630...,2011-12-08 22:26:09,"""Dear twitter this could very well be the wors...",Tweet,Twitter Web Client,2098,768,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected
3195,"""144903492132274176""",https://twitter.com/brunomars/status/144903492...,2011-12-08 22:17:39,"""Dear Twitter, what are all these changes? Now...",Tweet,Twitter Web Client,4364,1382,"""100220864""","""Bruno Mars""",brunomars,Verified,https://twitter.com/brunomars,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3196, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3196, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1219387020939685890""","""Bruno Mars""",brunomars,"""Wanted to wish everyone a Happy Martin Luther...",461,4890,2020-01-20 22:31:35
1,"""1219384974631030785""","""Bruno Mars""",brunomars,"""Nah! https://t.co/a01vjusZOJ""",317,3984,2020-01-20 22:23:27
2,"""1218996607317753856""","""Bruno Mars""",brunomars,"""We must. ðŸ¥‚ https://t.co/2jNeKORa2o""",556,5645,2020-01-19 20:40:13
3,"""1218996210167513088""","""Bruno Mars""",brunomars,"""ðŸ˜¢ I miss this. https://t.co/3mKj6wVsTl""",5406,36558,2020-01-19 20:38:39
4,"""1218989063706828800""","""Bruno Mars""",brunomars,"""Hereâ€™s a little more sunshine for your Sunday...",625,4055,2020-01-19 20:10:15

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1219387020939685890""","""Bruno Mars""",brunomars,"""Wanted to wish everyone a Happy Martin Luther...",461,4890,2020-01-20 22:31:35,[],[],0,0
1,"""1219384974631030785""","""Bruno Mars""",brunomars,"""Nah! https://t.co/a01vjusZOJ""",317,3984,2020-01-20 22:23:27,[],[],0,0
2,"""1218996607317753856""","""Bruno Mars""",brunomars,"""We must. ðŸ¥‚ https://t.co/2jNeKORa2o""",556,5645,2020-01-19 20:40:13,[],[],0,0
3,"""1218996210167513088""","""Bruno Mars""",brunomars,"""ðŸ˜¢ I miss this. https://t.co/3mKj6wVsTl""",5406,36558,2020-01-19 20:38:39,[],[],0,0
4,"""1218989063706828800""","""Bruno Mars""",brunomars,"""Hereâ€™s a little more sunshine for your Sunday...",625,4055,2020-01-19 20:10:15,[],[#ForeverValentine],1,0
...,...,...,...,...,...,...,...,...,...,...,...
3191,"""144908780830851072""","""Bruno Mars""",brunomars,"""To be honest the changes aren't that bad.. Ma...",2232,871,2011-12-08 22:38:40,[],[],0,0
3192,"""144907084541071360""","""Bruno Mars""",brunomars,"""Im so mad I just drank all the water in my po...",1916,722,2011-12-08 22:31:55,[],"[#ThanksTwitter""]",1,0
3193,"""144906944249995264""","""Bruno Mars""",brunomars,"""Im so mad I just threw my car over the mounta...",1974,801,2011-12-08 22:31:22,[],"[#ThanksTwitter""]",1,0
3194,"""144905630002581504""","""Bruno Mars""",brunomars,"""Dear twitter this could very well be the wors...",2098,768,2011-12-08 22:26:09,[],[],0,0
3195,"""144903492132274176""","""Bruno Mars""",brunomars,"""Dear Twitter, what are all these changes? Now...",4364,1382,2011-12-08 22:17:39,[],[#DontPissMeOff],1,0

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3196, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1219387020939685890""","""Bruno Mars""",brunomars,"""Wanted to wish everyone a Happy Martin Luther...",461,4890,[],[],0,0,2020-01-20,22:31:35
1,"""1219384974631030785""","""Bruno Mars""",brunomars,"""Nah! https://t.co/a01vjusZOJ""",317,3984,[],[],0,0,2020-01-20,22:23:27
2,"""1218996607317753856""","""Bruno Mars""",brunomars,"""We must. ðŸ¥‚ https://t.co/2jNeKORa2o""",556,5645,[],[],0,0,2020-01-19,20:40:13
3,"""1218996210167513088""","""Bruno Mars""",brunomars,"""ðŸ˜¢ I miss this. https://t.co/3mKj6wVsTl""",5406,36558,[],[],0,0,2020-01-19,20:38:39
4,"""1218989063706828800""","""Bruno Mars""",brunomars,"""Hereâ€™s a little more sunshine for your Sunday...",625,4055,[],[#ForeverValentine],1,0,2020-01-19,20:10:15
...,...,...,...,...,...,...,...,...,...,...,...,...
3191,"""144908780830851072""","""Bruno Mars""",brunomars,"""To be honest the changes aren't that bad.. Ma...",2232,871,[],[],0,0,2011-12-08,22:38:40
3192,"""144907084541071360""","""Bruno Mars""",brunomars,"""Im so mad I just drank all the water in my po...",1916,722,[],"[#ThanksTwitter""]",1,0,2011-12-08,22:31:55
3193,"""144906944249995264""","""Bruno Mars""",brunomars,"""Im so mad I just threw my car over the mounta...",1974,801,[],"[#ThanksTwitter""]",1,0,2011-12-08,22:31:22
3194,"""144905630002581504""","""Bruno Mars""",brunomars,"""Dear twitter this could very well be the wors...",2098,768,[],[],0,0,2011-12-08,22:26:09
3195,"""144903492132274176""","""Bruno Mars""",brunomars,"""Dear Twitter, what are all these changes? Now...",4364,1382,[],[#DontPissMeOff],1,0,2011-12-08,22:17:39

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/BrunoMarsImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1217576062709719040""","""1217576057320067072""",https://pbs.twimg.com/media/EOWy-R-VUAAgWfu.jpg,https://t.co/warRpLLLYn
1,"""1217560280332288000""","""1217560275676585984""",https://pbs.twimg.com/media/EOWknqxUYAARdYy.jpg,https://t.co/4bnk0kygA1
2,"""1203812834980663296""","""1203812823844835328""",https://pbs.twimg.com/media/ELTNYp1U0AAYWWD.jpg,https://t.co/VFtgpwD6QB
3,"""1199284188353945600""","""1199284183484362753""",https://pbs.twimg.com/media/EKS2nF1UcAE5nJS.jpg,https://t.co/aSbXmSPPIU
4,"""1190803743945551872""","""1190803733246029824""",https://pbs.twimg.com/media/EIaVr61WsAA_sSX.jpg,https://t.co/PVOEy85rgh
...,...,...,...,...
355,"""187617733221949440""","""187617733226143745""",https://pbs.twimg.com/media/ApqNVZaCIAECvVn.jpg,http://t.co/ccwqH5oW
356,"""183243228802322434""","""183243228810711040""",https://pbs.twimg.com/media/AosCvujCEAAncr-.jpg,http://t.co/IIRkEnsY
357,"""179049108273766400""","""179049108277960704""",https://pbs.twimg.com/media/AnwcNyBCIAAAJdZ.jpg,http://t.co/XjbYt1zV
358,"""162545859018489857""","""162545859026878464""",https://pbs.twimg.com/media/AkF6mPsCAAA1uD3.jpg,http://t.co/sIP0OXOF
359,"""162181383672967168""","""162181383677161472""",https://pbs.twimg.com/media/AkAvG_NCMAAP6FA.jpg,http://t.co/XNQHMeQM

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (360, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (360, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1217576062709719040"  Image added
1    "1217560280332288000"  Image added
2    "1203812834980663296"  Image added
3    "1199284188353945600"  Image added
4    "1190803743945551872"  Image added
..                     ...          ...
355   "187617733221949440"  Image added
356   "183243228802322434"  Image added
357   "179049108273766400"  Image added
358   "162545859018489857"  Image added
359   "162181383672967168"  Image added

[360 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1219387020939685890""","""Bruno Mars""",brunomars,"""Wanted to wish everyone a Happy Martin Luther...",461,4890,[],[],0,0,2020-01-20,22:31:35,NaN
1,"""1219384974631030785""","""Bruno Mars""",brunomars,"""Nah! https://t.co/a01vjusZOJ""",317,3984,[],[],0,0,2020-01-20,22:23:27,NaN
2,"""1218996607317753856""","""Bruno Mars""",brunomars,"""We must. ðŸ¥‚ https://t.co/2jNeKORa2o""",556,5645,[],[],0,0,2020-01-19,20:40:13,NaN
3,"""1218996210167513088""","""Bruno Mars""",brunomars,"""ðŸ˜¢ I miss this. https://t.co/3mKj6wVsTl""",5406,36558,[],[],0,0,2020-01-19,20:38:39,NaN
4,"""1218989063706828800""","""Bruno Mars""",brunomars,"""Hereâ€™s a little more sunshine for your Sunday...",625,4055,[],[#ForeverValentine],1,0,2020-01-19,20:10:15,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,"""144908780830851072""","""Bruno Mars""",brunomars,"""To be honest the changes aren't that bad.. Ma...",2232,871,[],[],0,0,2011-12-08,22:38:40,NaN
3211,"""144907084541071360""","""Bruno Mars""",brunomars,"""Im so mad I just drank all the water in my po...",1916,722,[],"[#ThanksTwitter""]",1,0,2011-12-08,22:31:55,NaN
3212,"""144906944249995264""","""Bruno Mars""",brunomars,"""Im so mad I just threw my car over the mounta...",1974,801,[],"[#ThanksTwitter""]",1,0,2011-12-08,22:31:22,NaN
3213,"""144905630002581504""","""Bruno Mars""",brunomars,"""Dear twitter this could very well be the wors...",2098,768,[],[],0,0,2011-12-08,22:26:09,NaN
3214,"""144903492132274176""","""Bruno Mars""",brunomars,"""Dear Twitter, what are all these changes? Now...",4364,1382,[],[#DontPissMeOff],1,0,2011-12-08,22:17:39,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/BrunoMarsVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1213650413431345153""","""1213650340622426112""",https://video.twimg.com/ext_tw_video/121365034...,https://t.co/YwErmsMlWo
1,"""1213349342351777792""","""1176136758360231936""",https://video.twimg.com/amplify_video/11761367...,https://t.co/T81Mkuap5C
2,"""1196488287462076416""","""1196488199843065856""",https://video.twimg.com/ext_tw_video/119648819...,https://t.co/7nd1ohjruG
3,"""1167066108995588096""","""1167065935317913602""",https://video.twimg.com/ext_tw_video/116706593...,https://t.co/4OwdPkCDMg
4,"""1166078681585860608""","""1166078582013054977""",https://video.twimg.com/ext_tw_video/116607858...,https://t.co/5jQDM8l72X
5,"""1163504805475545088""","""1163504763381506048""",https://video.twimg.com/ext_tw_video/116350476...,https://t.co/sI6Rk3ECdQ
6,"""1140985667398201344""","""1140985605838508035""",https://video.twimg.com/ext_tw_video/114098560...,https://t.co/hWzHUVfNzP
7,"""1112515028052332544""","""1112500615329075201""",https://video.twimg.com/ext_tw_video/111250061...,https://t.co/mH6QABkQsp
8,"""1101522713443627009""","""1101522665997688832""",https://video.twimg.com/ext_tw_video/110152266...,https://t.co/UA6RzUpAIV
9,"""1098671282911010816""","""1098671256335863808""",https://video.twimg.com/ext_tw_video/109867125...,https://t.co/bq41jWAGIE
10,"""1096831818538594310""","""1096831745146736641""",https://video.twimg.com/ext_tw_video/109683174...,https://t.co/1zCM97p5cE
11,"""1096418757633888326""","""1096418705309908994""",https://video.twimg.com/ext_tw_video/109641870...,https://t.co/h8510oekhW
12,"""1062117137630687232""","""1062116963948756992""",https://video.twimg.com/ext_tw_video/106211696...,https://t.co/qgamcy2Bju
13,"""1061426240165302272""","""1061421780110196736""",https://video.twimg.com/ext_tw_video/106142178...,https://t.co/wlMNLfWmcC
14,"""1057664451032141824""","""1057664396946628608""",https://video.twimg.com/ext_tw_video/105766439...,https://t.co/pO6mhd3S5C
15,"""1056469228369305602""","""1056469177400061952""",https://video.twimg.com/ext_tw_video/105646917...,https://t.co/WSrGKqEJoQ
16,"""1049454903335227392""","""1049454758904377346""",https://video.twimg.com/ext_tw_video/104945475...,https://t.co/2HPHl9bW9t
17,"""1043194045323980802""","""1043194037090615296""",https://video.twimg.com/tweet_video/DnorcxyXgA...,https://t.co/jq7xvto6fL
18,"""1040630039568678912""","""1040630031943294977""",https://video.twimg.com/tweet_video/DnEPgCSVYA...,https://t.co/RLtoI3vpjy
19,"""1038250457666396160""","""1038250449718075392""",https://video.twimg.com/tweet_video/DmibSHtV4A...,https://t.co/wUEovsoZyD
20,"""1011671812252545025""","""1011671784133980161""",https://video.twimg.com/tweet_video/DgouIKqXcA...,https://t.co/YDb00NIx43
21,"""977236037754908672""","""977223663823958016""",https://video.twimg.com/tweet_video/DY_LvqRVMA...,https://t.co/GXn1Uv19Sz
22,"""976617062893281282""","""976616958622773248""",https://video.twimg.com/amplify_video/97661695...,https://t.co/c0H4yvq7kZ
23,"""968075012748931073""","""968075003789950976""",https://video.twimg.com/tweet_video/DW9LFjzVwA...,https://t.co/h6ivYo6QZr
24,"""961738959603744769""","""961738944105754624""",https://video.twimg.com/tweet_video/DVjIeWIVMA...,https://t.co/G9bytjMpEH
25,"""952586885603328000""","""952586874534559744""",https://video.twimg.com/tweet_video/DThEtyJVAA...,https://t.co/TpyS2wmzAx
26,"""950921597879275520""","""950921589926670337""",https://video.twimg.com/tweet_video/DTJaJdjUMA...,https://t.co/VpRQc0QaLF
27,"""948801557465673728""","""948801494014308352""",https://video.twimg.com/ext_tw_video/948801494...,https://t.co/VMIiZMZJXw
28,"""948773905652748289""","""948773900103704576""",https://video.twimg.com/tweet_video/DSq41dfX4A...,https://t.co/ATqDRv2nM1
29,"""940271961128697859""","""940271866631004161""",https://video.twimg.com/ext_tw_video/940271866...,https://t.co/rrpiUW0u0C
30,"""935275388082716672""","""935274789350068225""",https://video.twimg.com/ext_tw_video/935274789...,https://t.co/B0Wn7U6CNc
31,"""934507892492947459""","""934507425234898944""",https://video.twimg.com/ext_tw_video/934507425...,https://t.co/tKuD6wG0JA
32,"""933428839451119616""","""933428578787774464""",https://video.twimg.com/ext_tw_video/933428578...,https://t.co/SCWX3dXUOq
33,"""932671568626495489""","""932671327756062721""",https://video.twimg.com/ext_tw_video/932671327...,https://t.co/kZxnU4F8tA
34,"""923205876873334784""","""923205706148225026""",https://video.twimg.com/ext_tw_video/923205706...,https://t.co/EqQeXn0UKY
35,"""919395653679280128""","""919394587508166656""",https://video.twimg.com/ext_tw_video/919394587...,https://t.co/0p9dSjcrb9
36,"""879150407364116480""","""879150212442234880""",https://video.twimg.com/tweet_video/DDNeddTUIA...,https://t.co/HzwgB0VRdG
37,"""877522774658625536""","""877522758917402624""",https://video.twimg.com/ext_tw_video/877522758...,https://t.co/bDvhtFic9c
38,"""866088074916241408""","""866088042724851717""",https://video.twimg.com/tweet_video/DAT2fHLUAA...,https://t.co/84Xoes0WUx
39,"""857061992141664256""","""857061969651683328""",https://video.twimg.com/tweet_video/C-TlUguV0A...,https://t.co/fevH619W8u
40,"""854456834387656704""","""854456786044108801""",https://video.twimg.com/ext_tw_video/854456786...,https://t.co/ypOB20dAGF
41,"""838539630458777600""","""837372434768510976""",https://video.twimg.com/tweet_video/C57xyvcUwA...,https://t.co/B35KelQZMm
42,"""806971061002792960""","""806971046435786752""",https://video.twimg.com/ext_tw_video/806971046...,https://t.co/EL8I9Ja62L
43,"""803753364848656384""","""803753262318915584""",https://video.twimg.com/ext_tw_video/803753262...,https://t.co/XQLBxx5ozv
44,"""799856832692895744""","""799856724660264960""",https://video.twimg.com/ext_tw_video/799856724...,https://t.co/H1zG3mI4C0
45,"""786927991746129920""","""786708095061876737""",https://video.twimg.com/amplify_video/78670809...,https://t.co/5orckFwQYg
46,"""786195495592931329""","""786195384825634817""",https://video.twimg.com/tweet_video/CukgiXyVYA...,https://t.co/Xgmzv0QUys
47,"""782880632133263360""","""782880624470351872""",https://video.twimg.com/tweet_video/Ct1Zx7MXYA...,https://t.co/nJbKAQZe9d
48,"""782880049678651392""","""782880036718247936""",https://video.twimg.com/tweet_video/Ct1ZPtpWAA...,https://t.co/fWdYxuf1Q8
49,"""782827634262700032""","""782827627631484928""",https://video.twimg.com/tweet_video/Ct0plGlWIA...,https://t.co/WzhHQZVrGC
50,"""713098435214372864""","""713098347607932929""",https://video.twimg.com/tweet_video/CeVvK0MWwA...,https://t.co/wQmys7C4Cp
51,"""666280663994253314""","""666280525317976065""",https://video.twimg.com/tweet_video/CT8am5BWsA...,https://t.co/7CuU3crRtM

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (52, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (52, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                 Tweet Id       Videos
0   "1213650413431345153"  Video added
1   "1213349342351777792"  Video added
2   "1196488287462076416"  Video added
3   "1167066108995588096"  Video added
4   "1166078681585860608"  Video added
5   "1163504805475545088"  Video added
6   "1140985667398201344"  Video added
7   "1112515028052332544"  Video added
8   "1101522713443627009"  Video added
9   "1098671282911010816"  Video added
10  "1096831818538594310"  Video added
11  "1096418757633888326"  Video added
12  "1062117137630687232"  Video added
13  "1061426240165302272"  Video added
14  "1057664451032141824"  Video added
15  "1056469228369305602"  Video added
16  "1049454903335227392"  Video added
17  "1043194045323980802"  Video added
18  "1040630039568678912"  Video added
19  "1038250457666396160"  Video added
20  "1011671812252545025"  Video added
21   "977236037754908672"  Video added
22   "976617062893281282"  Video added
23   "968075012748931073"  Video added
24   "961738959603744769"  Video added
25   "952586885603328000"  Video added
26   "950921597879275520"  Video added
27   "948801557465673728"  Video added
28   "948773905652748289"  Video added
29   "940271961128697859"  Video added
30   "935275388082716672"  Video added
31   "934507892492947459"  Video added
32   "933428839451119616"  Video added
33   "932671568626495489"  Video added
34   "923205876873334784"  Video added
35   "919395653679280128"  Video added
36   "879150407364116480"  Video added
37   "877522774658625536"  Video added
38   "866088074916241408"  Video added
39   "857061992141664256"  Video added
40   "854456834387656704"  Video added
41   "838539630458777600"  Video added
42   "806971061002792960"  Video added
43   "803753364848656384"  Video added
44   "799856832692895744"  Video added
45   "786927991746129920"  Video added
46   "786195495592931329"  Video added
47   "782880632133263360"  Video added
48   "782880049678651392"  Video added
49   "782827634262700032"  Video added
50   "713098435214372864"  Video added
51   "666280663994253314"  Video added

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1219387020939685890""","""Bruno Mars""",brunomars,"""Wanted to wish everyone a Happy Martin Luther...",461,4890,[],[],0,0,2020-01-20,22:31:35,NaN,NaN
1,"""1219384974631030785""","""Bruno Mars""",brunomars,"""Nah! https://t.co/a01vjusZOJ""",317,3984,[],[],0,0,2020-01-20,22:23:27,NaN,NaN
2,"""1218996607317753856""","""Bruno Mars""",brunomars,"""We must. ðŸ¥‚ https://t.co/2jNeKORa2o""",556,5645,[],[],0,0,2020-01-19,20:40:13,NaN,NaN
3,"""1218996210167513088""","""Bruno Mars""",brunomars,"""ðŸ˜¢ I miss this. https://t.co/3mKj6wVsTl""",5406,36558,[],[],0,0,2020-01-19,20:38:39,NaN,NaN
4,"""1218989063706828800""","""Bruno Mars""",brunomars,"""Hereâ€™s a little more sunshine for your Sunday...",625,4055,[],[#ForeverValentine],1,0,2020-01-19,20:10:15,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,"""144908780830851072""","""Bruno Mars""",brunomars,"""To be honest the changes aren't that bad.. Ma...",2232,871,[],[],0,0,2011-12-08,22:38:40,NaN,NaN
3211,"""144907084541071360""","""Bruno Mars""",brunomars,"""Im so mad I just drank all the water in my po...",1916,722,[],"[#ThanksTwitter""]",1,0,2011-12-08,22:31:55,NaN,NaN
3212,"""144906944249995264""","""Bruno Mars""",brunomars,"""Im so mad I just threw my car over the mounta...",1974,801,[],"[#ThanksTwitter""]",1,0,2011-12-08,22:31:22,NaN,NaN
3213,"""144905630002581504""","""Bruno Mars""",brunomars,"""Dear twitter this could very well be the wors...",2098,768,[],[],0,0,2011-12-08,22:26:09,NaN,NaN
3214,"""144903492132274176""","""Bruno Mars""",brunomars,"""Dear Twitter, what are all these changes? Now...",4364,1382,[],[#DontPissMeOff],1,0,2011-12-08,22:17:39,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Male"

#Create an Vocation column 
Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3215, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1219387020939685890""","""Bruno Mars""",brunomars,461,4890,[],[],0,0,2020-01-20,22:31:35,-,-,Male,Music
1,"""1219384974631030785""","""Bruno Mars""",brunomars,317,3984,[],[],0,0,2020-01-20,22:23:27,-,-,Male,Music
2,"""1218996607317753856""","""Bruno Mars""",brunomars,556,5645,[],[],0,0,2020-01-19,20:40:13,-,-,Male,Music
3,"""1218996210167513088""","""Bruno Mars""",brunomars,5406,36558,[],[],0,0,2020-01-19,20:38:39,-,-,Male,Music
4,"""1218989063706828800""","""Bruno Mars""",brunomars,625,4055,[],[#ForeverValentine],1,0,2020-01-19,20:10:15,-,-,Male,Music
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3210,"""144908780830851072""","""Bruno Mars""",brunomars,2232,871,[],[],0,0,2011-12-08,22:38:40,-,-,Male,Music
3211,"""144907084541071360""","""Bruno Mars""",brunomars,1916,722,[],"[#ThanksTwitter""]",1,0,2011-12-08,22:31:55,-,-,Male,Music
3212,"""144906944249995264""","""Bruno Mars""",brunomars,1974,801,[],"[#ThanksTwitter""]",1,0,2011-12-08,22:31:22,-,-,Male,Music
3213,"""144905630002581504""","""Bruno Mars""",brunomars,2098,768,[],[],0,0,2011-12-08,22:26:09,-,-,Male,Music
3214,"""144903492132274176""","""Bruno Mars""",brunomars,4364,1382,[],[#DontPissMeOff],1,0,2011-12-08,22:17:39,-,-,Male,Music

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3215, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1219387020939685890""","""Bruno Mars""",brunomars,Male,Music,[],0,[],0,4890,461,-,-,2020-01-20,22:31:35
"""1219384974631030785""","""Bruno Mars""",brunomars,Male,Music,[],0,[],0,3984,317,-,-,2020-01-20,22:23:27
"""1218996607317753856""","""Bruno Mars""",brunomars,Male,Music,[],0,[],0,5645,556,-,-,2020-01-19,20:40:13
"""1218996210167513088""","""Bruno Mars""",brunomars,Male,Music,[],0,[],0,36558,5406,-,-,2020-01-19,20:38:39
"""1218989063706828800""","""Bruno Mars""",brunomars,Male,Music,[#ForeverValentine],1,[],0,4055,625,-,-,2020-01-19,20:10:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""144908780830851072""","""Bruno Mars""",brunomars,Male,Music,[],0,[],0,871,2232,-,-,2011-12-08,22:38:40
"""144907084541071360""","""Bruno Mars""",brunomars,Male,Music,"[#ThanksTwitter""]",1,[],0,722,1916,-,-,2011-12-08,22:31:55
"""144906944249995264""","""Bruno Mars""",brunomars,Male,Music,"[#ThanksTwitter""]",1,[],0,801,1974,-,-,2011-12-08,22:31:22
"""144905630002581504""","""Bruno Mars""",brunomars,Male,Music,[],0,[],0,768,2098,-,-,2011-12-08,22:26:09
"""144903492132274176""","""Bruno Mars""",brunomars,Male,Music,[#DontPissMeOff],1,[],0,1382,4364,-,-,2011-12-08,22:17:39

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/BrunoMars_df.csv')