##### ===================================================================================================================

#  Drake Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/DrakeTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1209346505959780352""",https://twitter.com/ovosound/status/1209346505...,2019-12-24 05:34:10,"""Drake “War” (Video) \nhttps://t.co/taDWx4vY6p""",Retweet,Twitter for iPhone,12100,33456,"""2675359291""","""OVO Sound""",ovosound,Verified,https://twitter.com/ovosound,Not Protected
1,"""1207898659553267712""",https://twitter.com/popcaanmusic/status/120789...,2019-12-20 05:40:56,"""We going live right now #VANQUISH out now #87...",Retweet,Twitter Web App,1002,4855,"""151588971""","""Popcaan""",popcaanmusic,Verified,https://twitter.com/popcaanmusic,Not Protected
2,"""1202701945359732737""",https://twitter.com/cargojetairways/status/120...,2019-12-05 21:31:03,"""A night of Champions celebrating Champions. O...",Retweet,Twitter for iPhone,502,5214,"""3327313925""","""CargoJet""",cargojetairways,Non-Verified,https://twitter.com/cargojetairways,Not Protected
3,"""1197922689723314181""",https://twitter.com/showtime/status/1197922689...,2019-11-22 17:00:00,"""Skills are being put to the test on and off t...",Retweet,Twitter Media Studio,563,2654,"""257548783""","""Showtime""",showtime,Verified,https://twitter.com/showtime,Not Protected
4,"""1197746382347608064""",https://twitter.com/partynextdoor/status/11977...,2019-11-22 05:19:25,"""Loyal feat. @Drake out now https://t.co/aGmBC...",Retweet,Twitter for iPhone,20386,58055,"""1346180581""","""PARTYNEXTDOOR""",partynextdoor,Verified,https://twitter.com/partynextdoor,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743,"""1409312886""",https://twitter.com/drake/status/1409312886,2009-03-28 22:57:51,"""@jheneaiko Vowed to never get involved""",Reply,Twitter Web Client,91,105,"""27195114""","""Drizzy""",drake,Verified,https://twitter.com/drake,Not Protected
1744,"""1409308328""",https://twitter.com/drake/status/1409308328,2009-03-28 22:56:51,"""@mackmaine Ya'll bus slow...I'm already in th...",Reply,Twitter Web Client,12,32,"""27195114""","""Drizzy""",drake,Verified,https://twitter.com/drake,Not Protected
1745,"""1409305026""",https://twitter.com/drake/status/1409305026,2009-03-28 22:56:07,"""@DaRealAngelLola In Vegas...waiting on that t...",Reply,Twitter Web Client,11,27,"""27195114""","""Drizzy""",drake,Verified,https://twitter.com/drake,Not Protected
1746,"""1406109879""",https://twitter.com/drake/status/1406109879,2009-03-28 08:21:10,"""HA this shit wild...it rivals the day I learn...",Tweet,Twitter Web Client,453,848,"""27195114""","""Drizzy""",drake,Verified,https://twitter.com/drake,Not Protected
1747,"""1405978002""",https://twitter.com/drake/status/1405978002,2009-03-28 07:18:19,"""Fine...you got me.""",Tweet,Twitter Web Client,25633,25274,"""27195114""","""Drizzy""",drake,Verified,https://twitter.com/drake,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1748, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1748, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1209346505959780352""","""OVO Sound""",ovosound,"""Drake “War” (Video) \nhttps://t.co/taDWx4vY6p""",12100,33456,2019-12-24 05:34:10
1,"""1207898659553267712""","""Popcaan""",popcaanmusic,"""We going live right now #VANQUISH out now #87...",1002,4855,2019-12-20 05:40:56
2,"""1202701945359732737""","""CargoJet""",cargojetairways,"""A night of Champions celebrating Champions. O...",502,5214,2019-12-05 21:31:03
3,"""1197922689723314181""","""Showtime""",showtime,"""Skills are being put to the test on and off t...",563,2654,2019-11-22 17:00:00
4,"""1197746382347608064""","""PARTYNEXTDOOR""",partynextdoor,"""Loyal feat. @Drake out now https://t.co/aGmBC...",20386,58055,2019-11-22 05:19:25

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1209346505959780352""","""OVO Sound""",ovosound,"""Drake “War” (Video) \nhttps://t.co/taDWx4vY6p""",12100,33456,2019-12-24 05:34:10,[],[],0,0
1,"""1207898659553267712""","""Popcaan""",popcaanmusic,"""We going live right now #VANQUISH out now #87...",1002,4855,2019-12-20 05:40:56,[],"[#VANQUISH, #876GUD]",2,0
2,"""1202701945359732737""","""CargoJet""",cargojetairways,"""A night of Champions celebrating Champions. O...",502,5214,2019-12-05 21:31:03,[],[#champions],1,0
3,"""1197922689723314181""","""Showtime""",showtime,"""Skills are being put to the test on and off t...",563,2654,2019-11-22 17:00:00,"[@Drake, @FutureThePrince, @DavidAyerMovies,, ...",[],0,4
4,"""1197746382347608064""","""PARTYNEXTDOOR""",partynextdoor,"""Loyal feat. @Drake out now https://t.co/aGmBC...",20386,58055,2019-11-22 05:19:25,[@Drake],[],0,1
...,...,...,...,...,...,...,...,...,...,...,...
1743,"""1409312886""","""Drizzy""",drake,"""@jheneaiko Vowed to never get involved""",91,105,2009-03-28 22:57:51,[@jheneaiko],[],0,1
1744,"""1409308328""","""Drizzy""",drake,"""@mackmaine Ya'll bus slow...I'm already in th...",12,32,2009-03-28 22:56:51,[@mackmaine],[],0,1
1745,"""1409305026""","""Drizzy""",drake,"""@DaRealAngelLola In Vegas...waiting on that t...",11,27,2009-03-28 22:56:07,[@DaRealAngelLola],[],0,1
1746,"""1406109879""","""Drizzy""",drake,"""HA this shit wild...it rivals the day I learn...",453,848,2009-03-28 08:21:10,[],[],0,0
1747,"""1405978002""","""Drizzy""",drake,"""Fine...you got me.""",25633,25274,2009-03-28 07:18:19,[],[],0,0

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1748, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1209346505959780352""","""OVO Sound""",ovosound,"""Drake “War” (Video) \nhttps://t.co/taDWx4vY6p""",12100,33456,[],[],0,0,2019-12-24,05:34:10
1,"""1207898659553267712""","""Popcaan""",popcaanmusic,"""We going live right now #VANQUISH out now #87...",1002,4855,[],"[#VANQUISH, #876GUD]",2,0,2019-12-20,05:40:56
2,"""1202701945359732737""","""CargoJet""",cargojetairways,"""A night of Champions celebrating Champions. O...",502,5214,[],[#champions],1,0,2019-12-05,21:31:03
3,"""1197922689723314181""","""Showtime""",showtime,"""Skills are being put to the test on and off t...",563,2654,"[@Drake, @FutureThePrince, @DavidAyerMovies,, ...",[],0,4,2019-11-22,17:00:00
4,"""1197746382347608064""","""PARTYNEXTDOOR""",partynextdoor,"""Loyal feat. @Drake out now https://t.co/aGmBC...",20386,58055,[@Drake],[],0,1,2019-11-22,05:19:25
...,...,...,...,...,...,...,...,...,...,...,...,...
1743,"""1409312886""","""Drizzy""",drake,"""@jheneaiko Vowed to never get involved""",91,105,[@jheneaiko],[],0,1,2009-03-28,22:57:51
1744,"""1409308328""","""Drizzy""",drake,"""@mackmaine Ya'll bus slow...I'm already in th...",12,32,[@mackmaine],[],0,1,2009-03-28,22:56:51
1745,"""1409305026""","""Drizzy""",drake,"""@DaRealAngelLola In Vegas...waiting on that t...",11,27,[@DaRealAngelLola],[],0,1,2009-03-28,22:56:07
1746,"""1406109879""","""Drizzy""",drake,"""HA this shit wild...it rivals the day I learn...",453,848,[],[],0,0,2009-03-28,08:21:10
1747,"""1405978002""","""Drizzy""",drake,"""Fine...you got me.""",25633,25274,[],[],0,0,2009-03-28,07:18:19

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/DrakeImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1207898659553267712""","""1207898614464303104""",https://pbs.twimg.com/media/EMNRY9_U0AA_KbX.jpg,https://t.co/N3YI6o1EQN
1,"""1202701945359732737""","""1202701940053942272""",https://pbs.twimg.com/media/ELDbCtOWoAA2YSW.jpg,https://t.co/td8TW1PgHR
2,"""1197746382347608064""","""1197746374013521920""",https://pbs.twimg.com/media/EJ8_-zIWkAApRg7.jpg,https://t.co/U2Olu9JRdQ
3,"""1197745906000506880""","""1197745838036062208""",https://pbs.twimg.com/media/EJ8_fmdXkAAAAVV.jpg,https://t.co/qJYzfWM8hs
4,"""1192128180330647554""","""1192128174089474048""",https://pbs.twimg.com/media/EItKQhdWkAAdJlA.jpg,https://t.co/YAUAlR3O9e
...,...,...,...,...
84,"""307389666666098688""","""307389666670292992""",https://pbs.twimg.com/media/BEQRRfGCMAAEJ1r.jpg,http://t.co/WIEYm2LEek
85,"""185458613211496450""","""185458613215690753""",https://pbs.twimg.com/media/ApLhoElCAAEn1KV.jpg,http://t.co/XZYjPQSN
86,"""153790325557706752""","""153790325561901057""",https://pbs.twimg.com/media/AiJffH0CQAEw8T3.jpg,http://t.co/h90hBcFE
87,"""142361284627800064""","""142361284631994368""",https://pbs.twimg.com/media/AfnE1YhCIAADov5.jpg,http://t.co/t2NetVRF
88,"""128318788717383680""","""128318788721577985""",https://pbs.twimg.com/media/AcfhQivCEAEU1zX.jpg,http://t.co/Ay9pzhoQ

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (89, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (89, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                 Tweet Id       Images
0   "1207898659553267712"  Image added
1   "1202701945359732737"  Image added
2   "1197746382347608064"  Image added
3   "1197745906000506880"  Image added
4   "1192128180330647554"  Image added
..                    ...          ...
84   "307389666666098688"  Image added
85   "185458613211496450"  Image added
86   "153790325557706752"  Image added
87   "142361284627800064"  Image added
88   "128318788717383680"  Image added

[89 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1209346505959780352""","""OVO Sound""",ovosound,"""Drake “War” (Video) \nhttps://t.co/taDWx4vY6p""",12100,33456,[],[],0,0,2019-12-24,05:34:10,NaN
1,"""1207898659553267712""","""Popcaan""",popcaanmusic,"""We going live right now #VANQUISH out now #87...",1002,4855,[],"[#VANQUISH, #876GUD]",2,0,2019-12-20,05:40:56,Image added
2,"""1202701945359732737""","""CargoJet""",cargojetairways,"""A night of Champions celebrating Champions. O...",502,5214,[],[#champions],1,0,2019-12-05,21:31:03,Image added
3,"""1197922689723314181""","""Showtime""",showtime,"""Skills are being put to the test on and off t...",563,2654,"[@Drake, @FutureThePrince, @DavidAyerMovies,, ...",[],0,4,2019-11-22,17:00:00,NaN
4,"""1197746382347608064""","""PARTYNEXTDOOR""",partynextdoor,"""Loyal feat. @Drake out now https://t.co/aGmBC...",20386,58055,[@Drake],[],0,1,2019-11-22,05:19:25,Image added
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,"""1409312886""","""Drizzy""",drake,"""@jheneaiko Vowed to never get involved""",91,105,[@jheneaiko],[],0,1,2009-03-28,22:57:51,NaN
1750,"""1409308328""","""Drizzy""",drake,"""@mackmaine Ya'll bus slow...I'm already in th...",12,32,[@mackmaine],[],0,1,2009-03-28,22:56:51,NaN
1751,"""1409305026""","""Drizzy""",drake,"""@DaRealAngelLola In Vegas...waiting on that t...",11,27,[@DaRealAngelLola],[],0,1,2009-03-28,22:56:07,NaN
1752,"""1406109879""","""Drizzy""",drake,"""HA this shit wild...it rivals the day I learn...",453,848,[],[],0,0,2009-03-28,08:21:10,NaN
1753,"""1405978002""","""Drizzy""",drake,"""Fine...you got me.""",25633,25274,[],[],0,0,2009-03-28,07:18:19,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/DrakeVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1197922689723314181""","""1197652662709129221""",https://video.twimg.com/amplify_video/11976526...,https://t.co/V9q5ZjkYin
1,"""1158097143216971776""","""1158097088296738817""",https://video.twimg.com/ext_tw_video/115809708...,https://t.co/CaGAvTu8ZM
2,"""1155593186258980864""","""1155593150095745024""",https://video.twimg.com/ext_tw_video/115559315...,https://t.co/F6aEmh3v0W
3,"""1153060517193236480""","""1153060490664243200""",https://video.twimg.com/ext_tw_video/115306049...,https://t.co/VWmfCcYw7d
4,"""1150521029644521474""","""1150520982718652416""",https://video.twimg.com/ext_tw_video/115052098...,https://t.co/X0c1h3HVh0
5,"""1147982331870769152""","""1147982280436015104""",https://video.twimg.com/ext_tw_video/114798228...,https://t.co/TRDwHoNVsH
6,"""1145463579505598465""","""1145463554100715520""",https://video.twimg.com/ext_tw_video/114546355...,https://t.co/BG5sCR1qo9
7,"""1145438802904641536""","""1145438432178532352""",https://video.twimg.com/ext_tw_video/114543843...,https://t.co/mWqD58mdys
8,"""1142885694471151616""","""1142884126954885120""",https://video.twimg.com/ext_tw_video/114288412...,https://t.co/faboN4pNpx
9,"""1127266376215740416""","""1127260442429145088""",https://video.twimg.com/amplify_video/11272604...,https://t.co/xfjnfrXs2c
10,"""1116385727405797376""","""1116385287163322369""",https://video.twimg.com/ext_tw_video/111638528...,https://t.co/SUlPdwxx78
11,"""1111312779577692160""","""1111312732194668544""",https://video.twimg.com/ext_tw_video/111131273...,https://t.co/KbKYd1wx66
12,"""1086299175732428800""","""1086299076067356672""",https://video.twimg.com/ext_tw_video/108629907...,https://t.co/Fd2SLVsAul
13,"""1045401485432033282""","""1045400913278431232""",https://video.twimg.com/ext_tw_video/104540091...,https://t.co/8qO4UFmFVe
14,"""1023969057907728389""","""1023968401276919814""",https://video.twimg.com/tweet_video/DjXd1fNV4A...,https://t.co/xAaYg1Edks
15,"""1015631795717656582""","""1015631622174138374""",https://video.twimg.com/ext_tw_video/101563162...,https://t.co/JGSRTnoAAS
16,"""1011435466950836224""","""1011435408003960834""",https://video.twimg.com/ext_tw_video/101143540...,https://t.co/9UqTd6NNdn
17,"""780278976317054976""","""780278339063848961""",https://video.twimg.com/ext_tw_video/780278339...,https://t.co/UPMxZ10IM3
18,"""778701401182511104""","""778701162685931521""",https://video.twimg.com/ext_tw_video/778701162...,https://t.co/MSWdTgQJDE
19,"""772263280693940224""","""772247346876911620""",https://video.twimg.com/ext_tw_video/772247346...,https://t.co/urHST0wznN
20,"""759504659518222336""","""759504614366535680""",https://video.twimg.com/ext_tw_video/759504614...,https://t.co/eHlGuWaije
21,"""728736913260220419""","""728736375269371904""",https://video.twimg.com/ext_tw_video/728736375...,https://t.co/RLmxDTzE4O
22,"""728373781182488577""","""728373745132441600""",https://video.twimg.com/ext_tw_video/728373745...,https://t.co/lCT1YwDcQ7
23,"""728028722352275456""","""728028699614978050""",https://video.twimg.com/ext_tw_video/728028699...,https://t.co/HZH3NroEUa
24,"""727647294020042752""","""727647218782478336""",https://video.twimg.com/ext_tw_video/727647218...,https://t.co/mvC1zVdZF8
25,"""725716377609314304""","""725716267726966784""",https://video.twimg.com/ext_tw_video/725716267...,https://t.co/Ob43T9bKpo
26,"""719003714271449088""","""719003382170652672""",https://video.twimg.com/ext_tw_video/719003382...,https://t.co/kHa2rerRyV
27,"""672463916119683075""","""672463872620556293""",https://video.twimg.com/ext_tw_video/672463872...,https://t.co/nNKIGnnLC0
28,"""672462943674433536""","""672462190109044736""",https://video.twimg.com/ext_tw_video/672462190...,https://t.co/2kewmD8yih
29,"""656285436223078400""","""656285401645240320""",https://video.twimg.com/ext_tw_video/656285401...,https://t.co/ZrI6HKN1tL
30,"""649428956345532416""","""649428953149501440""",https://video.twimg.com/tweet_video/CQM8MStUcA...,http://t.co/2RVibCGi56
31,"""649421074132656129""","""649421071561523200""",https://video.twimg.com/tweet_video/CQM1BhgUAA...,http://t.co/pIrLE5Dqpx

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (32, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (32, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                 Tweet Id       Videos
0   "1197922689723314181"  Video added
1   "1158097143216971776"  Video added
2   "1155593186258980864"  Video added
3   "1153060517193236480"  Video added
4   "1150521029644521474"  Video added
5   "1147982331870769152"  Video added
6   "1145463579505598465"  Video added
7   "1145438802904641536"  Video added
8   "1142885694471151616"  Video added
9   "1127266376215740416"  Video added
10  "1116385727405797376"  Video added
11  "1111312779577692160"  Video added
12  "1086299175732428800"  Video added
13  "1045401485432033282"  Video added
14  "1023969057907728389"  Video added
15  "1015631795717656582"  Video added
16  "1011435466950836224"  Video added
17   "780278976317054976"  Video added
18   "778701401182511104"  Video added
19   "772263280693940224"  Video added
20   "759504659518222336"  Video added
21   "728736913260220419"  Video added
22   "728373781182488577"  Video added
23   "728028722352275456"  Video added
24   "727647294020042752"  Video added
25   "725716377609314304"  Video added
26   "719003714271449088"  Video added
27   "672463916119683075"  Video added
28   "672462943674433536"  Video added
29   "656285436223078400"  Video added
30   "649428956345532416"  Video added
31   "649421074132656129"  Video added

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1209346505959780352""","""OVO Sound""",ovosound,"""Drake “War” (Video) \nhttps://t.co/taDWx4vY6p""",12100,33456,[],[],0,0,2019-12-24,05:34:10,NaN,NaN
1,"""1207898659553267712""","""Popcaan""",popcaanmusic,"""We going live right now #VANQUISH out now #87...",1002,4855,[],"[#VANQUISH, #876GUD]",2,0,2019-12-20,05:40:56,Image added,NaN
2,"""1202701945359732737""","""CargoJet""",cargojetairways,"""A night of Champions celebrating Champions. O...",502,5214,[],[#champions],1,0,2019-12-05,21:31:03,Image added,NaN
3,"""1197922689723314181""","""Showtime""",showtime,"""Skills are being put to the test on and off t...",563,2654,"[@Drake, @FutureThePrince, @DavidAyerMovies,, ...",[],0,4,2019-11-22,17:00:00,NaN,Video added
4,"""1197746382347608064""","""PARTYNEXTDOOR""",partynextdoor,"""Loyal feat. @Drake out now https://t.co/aGmBC...",20386,58055,[@Drake],[],0,1,2019-11-22,05:19:25,Image added,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,"""1409312886""","""Drizzy""",drake,"""@jheneaiko Vowed to never get involved""",91,105,[@jheneaiko],[],0,1,2009-03-28,22:57:51,NaN,NaN
1750,"""1409308328""","""Drizzy""",drake,"""@mackmaine Ya'll bus slow...I'm already in th...",12,32,[@mackmaine],[],0,1,2009-03-28,22:56:51,NaN,NaN
1751,"""1409305026""","""Drizzy""",drake,"""@DaRealAngelLola In Vegas...waiting on that t...",11,27,[@DaRealAngelLola],[],0,1,2009-03-28,22:56:07,NaN,NaN
1752,"""1406109879""","""Drizzy""",drake,"""HA this shit wild...it rivals the day I learn...",453,848,[],[],0,0,2009-03-28,08:21:10,NaN,NaN
1753,"""1405978002""","""Drizzy""",drake,"""Fine...you got me.""",25633,25274,[],[],0,0,2009-03-28,07:18:19,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Male"

#Create an Vocation column 
Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1754, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1209346505959780352""","""OVO Sound""",ovosound,12100,33456,[],[],0,0,2019-12-24,05:34:10,-,-,Male,Music
1,"""1207898659553267712""","""Popcaan""",popcaanmusic,1002,4855,[],"[#VANQUISH, #876GUD]",2,0,2019-12-20,05:40:56,Image added,-,Male,Music
2,"""1202701945359732737""","""CargoJet""",cargojetairways,502,5214,[],[#champions],1,0,2019-12-05,21:31:03,Image added,-,Male,Music
3,"""1197922689723314181""","""Showtime""",showtime,563,2654,"[@Drake, @FutureThePrince, @DavidAyerMovies,, ...",[],0,4,2019-11-22,17:00:00,-,Video added,Male,Music
4,"""1197746382347608064""","""PARTYNEXTDOOR""",partynextdoor,20386,58055,[@Drake],[],0,1,2019-11-22,05:19:25,Image added,-,Male,Music
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,"""1409312886""","""Drizzy""",drake,91,105,[@jheneaiko],[],0,1,2009-03-28,22:57:51,-,-,Male,Music
1750,"""1409308328""","""Drizzy""",drake,12,32,[@mackmaine],[],0,1,2009-03-28,22:56:51,-,-,Male,Music
1751,"""1409305026""","""Drizzy""",drake,11,27,[@DaRealAngelLola],[],0,1,2009-03-28,22:56:07,-,-,Male,Music
1752,"""1406109879""","""Drizzy""",drake,453,848,[],[],0,0,2009-03-28,08:21:10,-,-,Male,Music
1753,"""1405978002""","""Drizzy""",drake,25633,25274,[],[],0,0,2009-03-28,07:18:19,-,-,Male,Music

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1754, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1209346505959780352""","""OVO Sound""",ovosound,Male,Music,[],0,[],0,33456,12100,-,-,2019-12-24,05:34:10
"""1207898659553267712""","""Popcaan""",popcaanmusic,Male,Music,"[#VANQUISH, #876GUD]",2,[],0,4855,1002,Image added,-,2019-12-20,05:40:56
"""1202701945359732737""","""CargoJet""",cargojetairways,Male,Music,[#champions],1,[],0,5214,502,Image added,-,2019-12-05,21:31:03
"""1197922689723314181""","""Showtime""",showtime,Male,Music,[],0,"[@Drake, @FutureThePrince, @DavidAyerMovies,, ...",4,2654,563,-,Video added,2019-11-22,17:00:00
"""1197746382347608064""","""PARTYNEXTDOOR""",partynextdoor,Male,Music,[],0,[@Drake],1,58055,20386,Image added,-,2019-11-22,05:19:25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""1409312886""","""Drizzy""",drake,Male,Music,[],0,[@jheneaiko],1,105,91,-,-,2009-03-28,22:57:51
"""1409308328""","""Drizzy""",drake,Male,Music,[],0,[@mackmaine],1,32,12,-,-,2009-03-28,22:56:51
"""1409305026""","""Drizzy""",drake,Male,Music,[],0,[@DaRealAngelLola],1,27,11,-,-,2009-03-28,22:56:07
"""1406109879""","""Drizzy""",drake,Male,Music,[],0,[],0,848,453,-,-,2009-03-28,08:21:10
"""1405978002""","""Drizzy""",drake,Male,Music,[],0,[],0,25274,25633,-,-,2009-03-28,07:18:19

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/Drake_df.csv')