##### ===================================================================================================================

#  Instagram Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/InstagramTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220051665169965056""",https://twitter.com/instagram/status/122005166...,2020-01-22 18:32:39,"""This month, we‚Äôre looking to the future with ...",Reply,Twitter for iPhone,7,142,"""180505807""","""Instagram""",instagram,Verified,https://twitter.com/instagram,Not Protected
1,"""1220051663341285376""",https://twitter.com/instagram/status/122005166...,2020-01-22 18:32:38,"""Reality just got warped. ü§Ø #2020Vision https:...",Tweet,Twitter for iPhone,218,1564,"""180505807""","""Instagram""",instagram,Verified,https://twitter.com/instagram,Not Protected
2,"""1219687463217614849""",https://twitter.com/instagram/status/121968746...,2020-01-21 18:25:26,"""This month, we‚Äôre looking to the future with ...",Reply,Twitter for iPhone,12,163,"""180505807""","""Instagram""",instagram,Verified,https://twitter.com/instagram,Not Protected
3,"""1219687461476978689""",https://twitter.com/instagram/status/121968746...,2020-01-21 18:25:26,"""‚ÄúPart of the appeal of climbing is that I can...",Tweet,Twitter for iPhone,136,1334,"""180505807""","""Instagram""",instagram,Verified,https://twitter.com/instagram,Not Protected
4,"""1219312674086850560""",https://twitter.com/instagram/status/121931267...,2020-01-20 17:36:09,"""‚ÄúI don‚Äôt fit into any one box.‚Äù ‚Äî breakout st...",Tweet,Twitter for iPhone,75,884,"""180505807""","""Instagram""",instagram,Verified,https://twitter.com/instagram,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""793240596559388673""",https://twitter.com/newshour/status/7932405965...,2016-10-31 23:57:50,"""How did vampire bats get their name? Watch ou...",Retweet,Twitter Web Client,95,329,"""14437914""","""PBS NewsHour""",newshour,Verified,https://twitter.com/newshour,Not Protected
3196,"""793237383009464320""",https://twitter.com/instagram/status/793237383...,2016-10-31 23:45:04,"""A silhouette sitting under a tree creates a r...",Tweet,SocialFlow,105,479,"""180505807""","""Instagram""",instagram,Verified,https://twitter.com/instagram,Not Protected
3197,"""793231001174548480""",https://twitter.com/instagram/status/793231001...,2016-10-31 23:19:42,"""Featured submissions from this weekend‚Äôs hash...",Tweet,SocialFlow,153,623,"""180505807""","""Instagram""",instagram,Verified,https://twitter.com/instagram,Not Protected
3198,"""793210871975518208""",https://twitter.com/nerdist/status/79321087197...,2016-10-31 21:59:43,"""Team Nerdist is all dressed up for #Halloween...",Retweet,Twitter for iPhone,66,309,"""394216985""","""Nerdist""",nerdist,Verified,https://twitter.com/nerdist,Not Protected
3199,"""793158164338343936""",https://twitter.com/instagram/status/793158164...,2016-10-31 18:30:17,"""Happy Halloween! Spook out your feed with the...",Tweet,SocialFlow,138,569,"""180505807""","""Instagram""",instagram,Verified,https://twitter.com/instagram,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1220051665169965056""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",7,142,2020-01-22 18:32:39
1,"""1220051663341285376""","""Instagram""",instagram,"""Reality just got warped. ü§Ø #2020Vision https:...",218,1564,2020-01-22 18:32:38
2,"""1219687463217614849""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",12,163,2020-01-21 18:25:26
3,"""1219687461476978689""","""Instagram""",instagram,"""‚ÄúPart of the appeal of climbing is that I can...",136,1334,2020-01-21 18:25:26
4,"""1219312674086850560""","""Instagram""",instagram,"""‚ÄúI don‚Äôt fit into any one box.‚Äù ‚Äî breakout st...",75,884,2020-01-20 17:36:09

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1220051665169965056""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",7,142,2020-01-22 18:32:39,[],[#2020Vision.],1,0
1,"""1220051663341285376""","""Instagram""",instagram,"""Reality just got warped. ü§Ø #2020Vision https:...",218,1564,2020-01-22 18:32:38,[],[#2020Vision],1,0
2,"""1219687463217614849""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",12,163,2020-01-21 18:25:26,[],[#2020Vision.],1,0
3,"""1219687461476978689""","""Instagram""",instagram,"""‚ÄúPart of the appeal of climbing is that I can...",136,1334,2020-01-21 18:25:26,[],[],0,0
4,"""1219312674086850560""","""Instagram""",instagram,"""‚ÄúI don‚Äôt fit into any one box.‚Äù ‚Äî breakout st...",75,884,2020-01-20 17:36:09,[@ParkerKitHill],[#2020Vision],1,1
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""793240596559388673""","""PBS NewsHour""",newshour,"""How did vampire bats get their name? Watch ou...",95,329,2016-10-31 23:57:50,[@instagram],"[#InstagramStories, #trickortreat]",2,1
3196,"""793237383009464320""","""Instagram""",instagram,"""A silhouette sitting under a tree creates a r...",105,479,2016-10-31 23:45:04,[],[#TheWeekOnInstagram],1,0
3197,"""793231001174548480""","""Instagram""",instagram,"""Featured submissions from this weekend‚Äôs hash...",153,623,2016-10-31 23:19:42,[],[#WHPsupernatural],1,0
3198,"""793210871975518208""","""Nerdist""",nerdist,"""Team Nerdist is all dressed up for #Halloween...",66,309,2016-10-31 21:59:43,[@Instagram],[#Halloween!],1,1
3199,"""793158164338343936""","""Instagram""",instagram,"""Happy Halloween! Spook out your feed with the...",138,569,2016-10-31 18:30:17,[@flavorwire)],[],0,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1220051665169965056""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",7,142,[],[#2020Vision.],1,0,2020-01-22,18:32:39
1,"""1220051663341285376""","""Instagram""",instagram,"""Reality just got warped. ü§Ø #2020Vision https:...",218,1564,[],[#2020Vision],1,0,2020-01-22,18:32:38
2,"""1219687463217614849""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",12,163,[],[#2020Vision.],1,0,2020-01-21,18:25:26
3,"""1219687461476978689""","""Instagram""",instagram,"""‚ÄúPart of the appeal of climbing is that I can...",136,1334,[],[],0,0,2020-01-21,18:25:26
4,"""1219312674086850560""","""Instagram""",instagram,"""‚ÄúI don‚Äôt fit into any one box.‚Äù ‚Äî breakout st...",75,884,[@ParkerKitHill],[#2020Vision],1,1,2020-01-20,17:36:09
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""793240596559388673""","""PBS NewsHour""",newshour,"""How did vampire bats get their name? Watch ou...",95,329,[@instagram],"[#InstagramStories, #trickortreat]",2,1,2016-10-31,23:57:50
3196,"""793237383009464320""","""Instagram""",instagram,"""A silhouette sitting under a tree creates a r...",105,479,[],[#TheWeekOnInstagram],1,0,2016-10-31,23:45:04
3197,"""793231001174548480""","""Instagram""",instagram,"""Featured submissions from this weekend‚Äôs hash...",153,623,[],[#WHPsupernatural],1,0,2016-10-31,23:19:42
3198,"""793210871975518208""","""Nerdist""",nerdist,"""Team Nerdist is all dressed up for #Halloween...",66,309,[@Instagram],[#Halloween!],1,1,2016-10-31,21:59:43
3199,"""793158164338343936""","""Instagram""",instagram,"""Happy Halloween! Spook out your feed with the...",138,569,[@flavorwire)],[],0,1,2016-10-31,18:30:17

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/InstagramImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1219687461476978689""","""1219687454791237632""",https://pbs.twimg.com/media/EO0zRyfVAAADky0.jpg,https://t.co/9A6qf1NJMI
1,"""1219312674086850560""","""1219312670521753600""",https://pbs.twimg.com/media/EOveaeSVAAA7iZN.jpg,https://t.co/0xaTicLDPk
2,"""1219298422760411136""","""1219298412257931271""",https://pbs.twimg.com/media/EOvRciHU8Ac7O36.jpg,https://t.co/C18lLiDgsq
3,"""1219298422760411136""","""1219298412257931272""",https://pbs.twimg.com/media/EOvRciHU8AgFVZF.jpg,https://t.co/C18lLiDgsq
4,"""1219298422760411136""","""1219298412287287296""",https://pbs.twimg.com/media/EOvRciOU4AAjjvf.jpg,https://t.co/C18lLiDgsq
...,...,...,...,...
1248,"""793437545375883264""","""793437539654828032""",https://pbs.twimg.com/media/CwLbPQ6WAAAUJvB.jpg,https://t.co/U2rnIayks9
1249,"""793302787182309376""","""793302750494724096""",https://pbs.twimg.com/media/CwJgpgKUEAAcsIW.jpg,https://t.co/u7UdjuVtv5
1250,"""793231001174548480""","""793230998263697408""",https://pbs.twimg.com/media/CwIfY-RWEAA8jms.jpg,https://t.co/gU88g7ZcXU
1251,"""793210871975518208""","""793210864849424384""",https://pbs.twimg.com/media/CwINFDdUkAAPZps.jpg,https://t.co/1YlabujUI0
1252,"""793210871975518208""","""793210864853590016""",https://pbs.twimg.com/media/CwINFDeUIAAyZ73.jpg,https://t.co/1YlabujUI0

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1253, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1253, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                   Tweet Id       Images
0     "1219687461476978689"  Image added
1     "1219312674086850560"  Image added
2     "1219298422760411136"  Image added
3     "1219298422760411136"  Image added
4     "1219298422760411136"  Image added
...                     ...          ...
1248   "793437545375883264"  Image added
1249   "793302787182309376"  Image added
1250   "793231001174548480"  Image added
1251   "793210871975518208"  Image added
1252   "793210871975518208"  Image added

[1253 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1220051665169965056""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",7,142,[],[#2020Vision.],1,0,2020-01-22,18:32:39,NaN
1,"""1220051663341285376""","""Instagram""",instagram,"""Reality just got warped. ü§Ø #2020Vision https:...",218,1564,[],[#2020Vision],1,0,2020-01-22,18:32:38,NaN
2,"""1219687463217614849""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",12,163,[],[#2020Vision.],1,0,2020-01-21,18:25:26,NaN
3,"""1219687461476978689""","""Instagram""",instagram,"""‚ÄúPart of the appeal of climbing is that I can...",136,1334,[],[],0,0,2020-01-21,18:25:26,Image added
4,"""1219312674086850560""","""Instagram""",instagram,"""‚ÄúI don‚Äôt fit into any one box.‚Äù ‚Äî breakout st...",75,884,[@ParkerKitHill],[#2020Vision],1,1,2020-01-20,17:36:09,Image added
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3284,"""793237383009464320""","""Instagram""",instagram,"""A silhouette sitting under a tree creates a r...",105,479,[],[#TheWeekOnInstagram],1,0,2016-10-31,23:45:04,NaN
3285,"""793231001174548480""","""Instagram""",instagram,"""Featured submissions from this weekend‚Äôs hash...",153,623,[],[#WHPsupernatural],1,0,2016-10-31,23:19:42,Image added
3286,"""793210871975518208""","""Nerdist""",nerdist,"""Team Nerdist is all dressed up for #Halloween...",66,309,[@Instagram],[#Halloween!],1,1,2016-10-31,21:59:43,Image added
3287,"""793210871975518208""","""Nerdist""",nerdist,"""Team Nerdist is all dressed up for #Halloween...",66,309,[@Instagram],[#Halloween!],1,1,2016-10-31,21:59:43,Image added
3288,"""793158164338343936""","""Instagram""",instagram,"""Happy Halloween! Spook out your feed with the...",138,569,[@flavorwire)],[],0,1,2016-10-31,18:30:17,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/InstagramVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220051663341285376""","""1220051616935530503""",https://video.twimg.com/ext_tw_video/122005161...,https://t.co/TiykZQ5mxA
1,"""1218238391625506816""","""1218238355520929792""",https://video.twimg.com/ext_tw_video/121823835...,https://t.co/b8gnzpuG04
2,"""1217123762937548800""","""1217123757183008768""",https://video.twimg.com/tweet_video/EOQXm8qVAA...,https://t.co/w5Lqu7CixW
3,"""1217122535243780097""","""1217122530147721217""",https://video.twimg.com/tweet_video/EOQWfhmUYA...,https://t.co/pUYPDC6hbZ
4,"""1215719066029023232""","""1215719013491175424""",https://video.twimg.com/ext_tw_video/121571901...,https://t.co/LTbxRY41ad
...,...,...,...,...
400,"""794533441467518979""","""794533302736654336""",https://video.twimg.com/ext_tw_video/794533302...,https://t.co/N5Wi8Lh8kP
401,"""794260428872417285""","""794260383058034689""",https://video.twimg.com/ext_tw_video/794260383...,https://t.co/weXMBktObE
402,"""793561424140304392""","""793561344637296640""",https://video.twimg.com/ext_tw_video/793561344...,https://t.co/thNZfiuVTj
403,"""793554636414324740""","""793554595322720256""",https://video.twimg.com/ext_tw_video/793554595...,https://t.co/qoQsp0qcIc
404,"""793240596559388673""","""793239612927930368""",https://video.twimg.com/ext_tw_video/793239612...,https://t.co/K7AuX3g1yy

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (405, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (405, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1220051663341285376"  Video added
1    "1218238391625506816"  Video added
2    "1217123762937548800"  Video added
3    "1217122535243780097"  Video added
4    "1215719066029023232"  Video added
..                     ...          ...
400   "794533441467518979"  Video added
401   "794260428872417285"  Video added
402   "793561424140304392"  Video added
403   "793554636414324740"  Video added
404   "793240596559388673"  Video added

[405 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1220051665169965056""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",7,142,[],[#2020Vision.],1,0,2020-01-22,18:32:39,NaN,NaN
1,"""1220051663341285376""","""Instagram""",instagram,"""Reality just got warped. ü§Ø #2020Vision https:...",218,1564,[],[#2020Vision],1,0,2020-01-22,18:32:38,NaN,Video added
2,"""1219687463217614849""","""Instagram""",instagram,"""This month, we‚Äôre looking to the future with ...",12,163,[],[#2020Vision.],1,0,2020-01-21,18:25:26,NaN,NaN
3,"""1219687461476978689""","""Instagram""",instagram,"""‚ÄúPart of the appeal of climbing is that I can...",136,1334,[],[],0,0,2020-01-21,18:25:26,Image added,NaN
4,"""1219312674086850560""","""Instagram""",instagram,"""‚ÄúI don‚Äôt fit into any one box.‚Äù ‚Äî breakout st...",75,884,[@ParkerKitHill],[#2020Vision],1,1,2020-01-20,17:36:09,Image added,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3284,"""793237383009464320""","""Instagram""",instagram,"""A silhouette sitting under a tree creates a r...",105,479,[],[#TheWeekOnInstagram],1,0,2016-10-31,23:45:04,NaN,NaN
3285,"""793231001174548480""","""Instagram""",instagram,"""Featured submissions from this weekend‚Äôs hash...",153,623,[],[#WHPsupernatural],1,0,2016-10-31,23:19:42,Image added,NaN
3286,"""793210871975518208""","""Nerdist""",nerdist,"""Team Nerdist is all dressed up for #Halloween...",66,309,[@Instagram],[#Halloween!],1,1,2016-10-31,21:59:43,Image added,NaN
3287,"""793210871975518208""","""Nerdist""",nerdist,"""Team Nerdist is all dressed up for #Halloween...",66,309,[@Instagram],[#Halloween!],1,1,2016-10-31,21:59:43,Image added,NaN
3288,"""793158164338343936""","""Instagram""",instagram,"""Happy Halloween! Spook out your feed with the...",138,569,[@flavorwire)],[],0,1,2016-10-31,18:30:17,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Organisation"

#Create an Vocation column 
Tweets_df['Vocation'] = "News/Media"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3289, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1220051665169965056""","""Instagram""",instagram,7,142,[],[#2020Vision.],1,0,2020-01-22,18:32:39,-,-,Organisation,News/Media
1,"""1220051663341285376""","""Instagram""",instagram,218,1564,[],[#2020Vision],1,0,2020-01-22,18:32:38,-,Video added,Organisation,News/Media
2,"""1219687463217614849""","""Instagram""",instagram,12,163,[],[#2020Vision.],1,0,2020-01-21,18:25:26,-,-,Organisation,News/Media
3,"""1219687461476978689""","""Instagram""",instagram,136,1334,[],[],0,0,2020-01-21,18:25:26,Image added,-,Organisation,News/Media
4,"""1219312674086850560""","""Instagram""",instagram,75,884,[@ParkerKitHill],[#2020Vision],1,1,2020-01-20,17:36:09,Image added,-,Organisation,News/Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3284,"""793237383009464320""","""Instagram""",instagram,105,479,[],[#TheWeekOnInstagram],1,0,2016-10-31,23:45:04,-,-,Organisation,News/Media
3285,"""793231001174548480""","""Instagram""",instagram,153,623,[],[#WHPsupernatural],1,0,2016-10-31,23:19:42,Image added,-,Organisation,News/Media
3286,"""793210871975518208""","""Nerdist""",nerdist,66,309,[@Instagram],[#Halloween!],1,1,2016-10-31,21:59:43,Image added,-,Organisation,News/Media
3287,"""793210871975518208""","""Nerdist""",nerdist,66,309,[@Instagram],[#Halloween!],1,1,2016-10-31,21:59:43,Image added,-,Organisation,News/Media
3288,"""793158164338343936""","""Instagram""",instagram,138,569,[@flavorwire)],[],0,1,2016-10-31,18:30:17,-,-,Organisation,News/Media

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3289, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1220051665169965056""","""Instagram""",instagram,Organisation,News/Media,[#2020Vision.],1,[],0,142,7,-,-,2020-01-22,18:32:39
"""1220051663341285376""","""Instagram""",instagram,Organisation,News/Media,[#2020Vision],1,[],0,1564,218,-,Video added,2020-01-22,18:32:38
"""1219687463217614849""","""Instagram""",instagram,Organisation,News/Media,[#2020Vision.],1,[],0,163,12,-,-,2020-01-21,18:25:26
"""1219687461476978689""","""Instagram""",instagram,Organisation,News/Media,[],0,[],0,1334,136,Image added,-,2020-01-21,18:25:26
"""1219312674086850560""","""Instagram""",instagram,Organisation,News/Media,[#2020Vision],1,[@ParkerKitHill],1,884,75,Image added,-,2020-01-20,17:36:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""793237383009464320""","""Instagram""",instagram,Organisation,News/Media,[#TheWeekOnInstagram],1,[],0,479,105,-,-,2016-10-31,23:45:04
"""793231001174548480""","""Instagram""",instagram,Organisation,News/Media,[#WHPsupernatural],1,[],0,623,153,Image added,-,2016-10-31,23:19:42
"""793210871975518208""","""Nerdist""",nerdist,Organisation,News/Media,[#Halloween!],1,[@Instagram],1,309,66,Image added,-,2016-10-31,21:59:43
"""793210871975518208""","""Nerdist""",nerdist,Organisation,News/Media,[#Halloween!],1,[@Instagram],1,309,66,Image added,-,2016-10-31,21:59:43
"""793158164338343936""","""Instagram""",instagram,Organisation,News/Media,[],0,[@flavorwire)],1,569,138,-,-,2016-10-31,18:30:17

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/Instagram_df.csv')