##### ===================================================================================================================

#  Justin TimberLake Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/JustinTimberLakeTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1218185336603529217""",https://twitter.com/jtimberlake/status/1218185...,2020-01-17 14:56:31,"""https://t.co/XKS2HL5sHY https://t.co/nA7DDWzojJ""",Tweet,Twitter for iPhone,553,5758,"""26565946""","""Justin Timberlake""",jtimberlake,Verified,https://twitter.com/jtimberlake,Not Protected
1,"""1212492165844291585""",https://twitter.com/timbaland/status/121249216...,2020-01-01 21:53:54,"""Since we in 2020 whatâ€™s yâ€™all fav song off th...",Retweet,Twitter for iPhone,2121,21507,"""207923746""","""Timbaland""",timbaland,Verified,https://twitter.com/timbaland,Not Protected
2,"""1211717959334408194""",https://twitter.com/jtimberlake/status/1211717...,2019-12-30 18:37:28,"""What a year. Happy birthday @TigerWoods ðŸ™Œ htt...",Tweet,Twitter for iPhone,259,3130,"""26565946""","""Justin Timberlake""",jtimberlake,Verified,https://twitter.com/jtimberlake,Not Protected
3,"""1209512769491554305""",https://twitter.com/complex/status/12095127694...,2019-12-24 16:34:50,"""The latest trailer for Michael Jordan's doc #...",Retweet,SocialFlow,268,1583,"""13049362""","""Complex""",complex,Verified,https://twitter.com/complex,Not Protected
4,"""1194993347930345474""",https://twitter.com/jtimberlake/status/1194993...,2019-11-14 14:59:50,"""#TrollsWorldTour ðŸ¤˜ New trailer drops in ONE H...",Tweet,Twitter for iPhone,616,4480,"""26565946""","""Justin Timberlake""",jtimberlake,Verified,https://twitter.com/jtimberlake,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""215974474837798913""",https://twitter.com/kelly_miller/status/215974...,2012-06-22 01:08:22,"""@jtimberlake as much as I hate to say it ( Im...",Retweet,Twitter for Android,33,30,"""27341831""","""Kelly Miller""",kelly_miller,Non-Verified,https://twitter.com/kelly_miller,Not Protected
3196,"""215974296642789376""",https://twitter.com/prophecymaster/status/2159...,2012-06-22 01:07:39,"""@jtimberlake I think LeBron will force to win...",Retweet,Twitter for iPhone,25,20,"""104680144""","""Marlon Bautista""",prophecymaster,Non-Verified,https://twitter.com/prophecymaster,Not Protected
3197,"""215974282872889344""",https://twitter.com/rees1025/status/2159742828...,2012-06-22 01:07:36,"""@jtimberlake HYFR!!""",Retweet,Twitter for Android,14,17,"""325669429""","""MoWaysThanAlilBit""",rees1025,Non-Verified,https://twitter.com/rees1025,Not Protected
3198,"""215974100986904576""",https://twitter.com/trevorlloyd92/status/21597...,2012-06-22 01:06:52,"""@jtimberlake yeah he is getting his ring toni...",Retweet,Twitter for BlackBerryÂ®,16,21,"""414946002""","""Trevor Lloyd""",trevorlloyd92,Non-Verified,https://twitter.com/trevorlloyd92,Not Protected
3199,"""215973780676296707""",https://twitter.com/bambi_allsmiles/status/215...,2012-06-22 01:05:36,"""@jtimberlake yessssssss!!!!""",Retweet,Twitter for iPhone,14,17,"""244706714""","""Maira Guifarro""",bambi_allsmiles,Non-Verified,https://twitter.com/bambi_allsmiles,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1218185336603529217""","""Justin Timberlake""",jtimberlake,"""https://t.co/XKS2HL5sHY https://t.co/nA7DDWzojJ""",553,5758,2020-01-17 14:56:31
1,"""1212492165844291585""","""Timbaland""",timbaland,"""Since we in 2020 whatâ€™s yâ€™all fav song off th...",2121,21507,2020-01-01 21:53:54
2,"""1211717959334408194""","""Justin Timberlake""",jtimberlake,"""What a year. Happy birthday @TigerWoods ðŸ™Œ htt...",259,3130,2019-12-30 18:37:28
3,"""1209512769491554305""","""Complex""",complex,"""The latest trailer for Michael Jordan's doc #...",268,1583,2019-12-24 16:34:50
4,"""1194993347930345474""","""Justin Timberlake""",jtimberlake,"""#TrollsWorldTour ðŸ¤˜ New trailer drops in ONE H...",616,4480,2019-11-14 14:59:50

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1218185336603529217""","""Justin Timberlake""",jtimberlake,"""https://t.co/XKS2HL5sHY https://t.co/nA7DDWzojJ""",553,5758,2020-01-17 14:56:31,[],[],0,0
1,"""1212492165844291585""","""Timbaland""",timbaland,"""Since we in 2020 whatâ€™s yâ€™all fav song off th...",2121,21507,2020-01-01 21:53:54,[],[],0,0
2,"""1211717959334408194""","""Justin Timberlake""",jtimberlake,"""What a year. Happy birthday @TigerWoods ðŸ™Œ htt...",259,3130,2019-12-30 18:37:28,[@TigerWoods],[],0,1
3,"""1209512769491554305""","""Complex""",complex,"""The latest trailer for Michael Jordan's doc #...",268,1583,2019-12-24 16:34:50,[],[#TheLastDance],1,0
4,"""1194993347930345474""","""Justin Timberlake""",jtimberlake,"""#TrollsWorldTour ðŸ¤˜ New trailer drops in ONE H...",616,4480,2019-11-14 14:59:50,[],[#TrollsWorldTour],1,0
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""215974474837798913""","""Kelly Miller""",kelly_miller,"""@jtimberlake as much as I hate to say it ( Im...",33,30,2012-06-22 01:08:22,[@jtimberlake],[],0,1
3196,"""215974296642789376""","""Marlon Bautista""",prophecymaster,"""@jtimberlake I think LeBron will force to win...",25,20,2012-06-22 01:07:39,[@jtimberlake],"[#NBAFinals""]",1,1
3197,"""215974282872889344""","""MoWaysThanAlilBit""",rees1025,"""@jtimberlake HYFR!!""",14,17,2012-06-22 01:07:36,[@jtimberlake],[],0,1
3198,"""215974100986904576""","""Trevor Lloyd""",trevorlloyd92,"""@jtimberlake yeah he is getting his ring toni...",16,21,2012-06-22 01:06:52,[@jtimberlake],[],0,1
3199,"""215973780676296707""","""Maira Guifarro""",bambi_allsmiles,"""@jtimberlake yessssssss!!!!""",14,17,2012-06-22 01:05:36,[@jtimberlake],[],0,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1218185336603529217""","""Justin Timberlake""",jtimberlake,"""https://t.co/XKS2HL5sHY https://t.co/nA7DDWzojJ""",553,5758,[],[],0,0,2020-01-17,14:56:31
1,"""1212492165844291585""","""Timbaland""",timbaland,"""Since we in 2020 whatâ€™s yâ€™all fav song off th...",2121,21507,[],[],0,0,2020-01-01,21:53:54
2,"""1211717959334408194""","""Justin Timberlake""",jtimberlake,"""What a year. Happy birthday @TigerWoods ðŸ™Œ htt...",259,3130,[@TigerWoods],[],0,1,2019-12-30,18:37:28
3,"""1209512769491554305""","""Complex""",complex,"""The latest trailer for Michael Jordan's doc #...",268,1583,[],[#TheLastDance],1,0,2019-12-24,16:34:50
4,"""1194993347930345474""","""Justin Timberlake""",jtimberlake,"""#TrollsWorldTour ðŸ¤˜ New trailer drops in ONE H...",616,4480,[],[#TrollsWorldTour],1,0,2019-11-14,14:59:50
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""215974474837798913""","""Kelly Miller""",kelly_miller,"""@jtimberlake as much as I hate to say it ( Im...",33,30,[@jtimberlake],[],0,1,2012-06-22,01:08:22
3196,"""215974296642789376""","""Marlon Bautista""",prophecymaster,"""@jtimberlake I think LeBron will force to win...",25,20,[@jtimberlake],"[#NBAFinals""]",1,1,2012-06-22,01:07:39
3197,"""215974282872889344""","""MoWaysThanAlilBit""",rees1025,"""@jtimberlake HYFR!!""",14,17,[@jtimberlake],[],0,1,2012-06-22,01:07:36
3198,"""215974100986904576""","""Trevor Lloyd""",trevorlloyd92,"""@jtimberlake yeah he is getting his ring toni...",16,21,[@jtimberlake],[],0,1,2012-06-22,01:06:52
3199,"""215973780676296707""","""Maira Guifarro""",bambi_allsmiles,"""@jtimberlake yessssssss!!!!""",14,17,[@jtimberlake],[],0,1,2012-06-22,01:05:36

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/JustinTimberLakeImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1218185336603529217""","""1218185333457727489""",https://pbs.twimg.com/media/EOfdG0dWsAEe4jA.jpg,https://t.co/nA7DDWzojJ
1,"""1212492165844291585""","""1212492160408473600""",https://pbs.twimg.com/media/ENOjMiIX0AAzAVa.jpg,https://t.co/YFxrNjBkQC
2,"""1194993347930345474""","""1194993343396294656""",https://pbs.twimg.com/media/EJV4HU4XsAAqOc1.jpg,https://t.co/zylxywguSi
3,"""1187860402148757510""","""1187860398357106688""",https://pbs.twimg.com/media/EHwgvR7UUAAR09m.jpg,https://t.co/3GDFfZP1IB
4,"""1178010321757364225""","""1178010315876900864""",https://pbs.twimg.com/media/EFkiJBOWoAAb_Vg.jpg,https://t.co/XVg4jGvzar
...,...,...,...,...
662,"""228647020167041025""","""228647020171235328""",https://pbs.twimg.com/media/AyxRQOBCEAAkRxU.jpg,http://t.co/KpXTxBCQ
663,"""225028877968351233""","""225028877976739840""",https://pbs.twimg.com/media/Ax92koACIAA-Kyw.jpg,http://t.co/oT078wMJ
664,"""224348987954692096""","""224341026188439553""",https://pbs.twimg.com/media/Ax0E-YaCMAEuqBu.jpg,http://t.co/lp9Maauu
665,"""224201213892243458""","""223939373782147072""",https://pbs.twimg.com/media/AxuXrImCIAArU-e.jpg,http://t.co/u2XJ1fy0
666,"""218713452741537794""","""218713452749926400""",https://pbs.twimg.com/media/AwkGufrCMAAfGGF.jpg,http://t.co/cGcSS82B

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (667, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (667, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1218185336603529217"  Image added
1    "1212492165844291585"  Image added
2    "1194993347930345474"  Image added
3    "1187860402148757510"  Image added
4    "1178010321757364225"  Image added
..                     ...          ...
662   "228647020167041025"  Image added
663   "225028877968351233"  Image added
664   "224348987954692096"  Image added
665   "224201213892243458"  Image added
666   "218713452741537794"  Image added

[667 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1218185336603529217""","""Justin Timberlake""",jtimberlake,"""https://t.co/XKS2HL5sHY https://t.co/nA7DDWzojJ""",553,5758,[],[],0,0,2020-01-17,14:56:31,Image added
1,"""1212492165844291585""","""Timbaland""",timbaland,"""Since we in 2020 whatâ€™s yâ€™all fav song off th...",2121,21507,[],[],0,0,2020-01-01,21:53:54,Image added
2,"""1211717959334408194""","""Justin Timberlake""",jtimberlake,"""What a year. Happy birthday @TigerWoods ðŸ™Œ htt...",259,3130,[@TigerWoods],[],0,1,2019-12-30,18:37:28,NaN
3,"""1209512769491554305""","""Complex""",complex,"""The latest trailer for Michael Jordan's doc #...",268,1583,[],[#TheLastDance],1,0,2019-12-24,16:34:50,NaN
4,"""1194993347930345474""","""Justin Timberlake""",jtimberlake,"""#TrollsWorldTour ðŸ¤˜ New trailer drops in ONE H...",616,4480,[],[#TrollsWorldTour],1,0,2019-11-14,14:59:50,Image added
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3264,"""215974474837798913""","""Kelly Miller""",kelly_miller,"""@jtimberlake as much as I hate to say it ( Im...",33,30,[@jtimberlake],[],0,1,2012-06-22,01:08:22,NaN
3265,"""215974296642789376""","""Marlon Bautista""",prophecymaster,"""@jtimberlake I think LeBron will force to win...",25,20,[@jtimberlake],"[#NBAFinals""]",1,1,2012-06-22,01:07:39,NaN
3266,"""215974282872889344""","""MoWaysThanAlilBit""",rees1025,"""@jtimberlake HYFR!!""",14,17,[@jtimberlake],[],0,1,2012-06-22,01:07:36,NaN
3267,"""215974100986904576""","""Trevor Lloyd""",trevorlloyd92,"""@jtimberlake yeah he is getting his ring toni...",16,21,[@jtimberlake],[],0,1,2012-06-22,01:06:52,NaN
3268,"""215973780676296707""","""Maira Guifarro""",bambi_allsmiles,"""@jtimberlake yessssssss!!!!""",14,17,[@jtimberlake],[],0,1,2012-06-22,01:05:36,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/JustinTimberLakeVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1209512769491554305""","""1209512744422199297""",https://video.twimg.com/tweet_video/EMkNbsqX0A...,https://t.co/sbq8GUp46x
1,"""1194646104626909185""","""1194455914016731137""",https://video.twimg.com/amplify_video/11944559...,https://t.co/0PPEU0LMpn
2,"""1186717435606392832""","""1186716606111469569""",https://video.twimg.com/amplify_video/11867166...,https://t.co/yEQ5eLSL7y
3,"""1179759810935427074""","""1179759775950807040""",https://video.twimg.com/ext_tw_video/117975977...,https://t.co/t6NmGghoSI
4,"""1178023569642725376""","""1177943702716715008""",https://video.twimg.com/amplify_video/11779437...,https://t.co/0Zj72Ndx04
...,...,...,...,...
222,"""625002098007015424""","""625002003056332800""",https://video.twimg.com/ext_tw_video/625002003...,http://t.co/6pPircl5WT
223,"""583691516511551488""","""583691483556904960""",https://video.twimg.com/ext_tw_video/583691483...,http://t.co/NvsSAIpI6c
224,"""580036669082087424""","""580036552815955969""",https://video.twimg.com/ext_tw_video/580036552...,http://t.co/dMtIKk644R
225,"""563362123619655682""","""563362121811894273""",https://video.twimg.com/tweet_video/B9F23W6CIA...,http://t.co/8tWj33sr4v
226,"""561674082849402880""","""561674082295758849""",https://video.twimg.com/tweet_video/B8t3mhrIQA...,http://t.co/NdQ1FVLhW4

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (227, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (227, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1209512769491554305"  Video added
1    "1194646104626909185"  Video added
2    "1186717435606392832"  Video added
3    "1179759810935427074"  Video added
4    "1178023569642725376"  Video added
..                     ...          ...
222   "625002098007015424"  Video added
223   "583691516511551488"  Video added
224   "580036669082087424"  Video added
225   "563362123619655682"  Video added
226   "561674082849402880"  Video added

[227 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1218185336603529217""","""Justin Timberlake""",jtimberlake,"""https://t.co/XKS2HL5sHY https://t.co/nA7DDWzojJ""",553,5758,[],[],0,0,2020-01-17,14:56:31,Image added,NaN
1,"""1212492165844291585""","""Timbaland""",timbaland,"""Since we in 2020 whatâ€™s yâ€™all fav song off th...",2121,21507,[],[],0,0,2020-01-01,21:53:54,Image added,NaN
2,"""1211717959334408194""","""Justin Timberlake""",jtimberlake,"""What a year. Happy birthday @TigerWoods ðŸ™Œ htt...",259,3130,[@TigerWoods],[],0,1,2019-12-30,18:37:28,NaN,NaN
3,"""1209512769491554305""","""Complex""",complex,"""The latest trailer for Michael Jordan's doc #...",268,1583,[],[#TheLastDance],1,0,2019-12-24,16:34:50,NaN,Video added
4,"""1194993347930345474""","""Justin Timberlake""",jtimberlake,"""#TrollsWorldTour ðŸ¤˜ New trailer drops in ONE H...",616,4480,[],[#TrollsWorldTour],1,0,2019-11-14,14:59:50,Image added,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3264,"""215974474837798913""","""Kelly Miller""",kelly_miller,"""@jtimberlake as much as I hate to say it ( Im...",33,30,[@jtimberlake],[],0,1,2012-06-22,01:08:22,NaN,NaN
3265,"""215974296642789376""","""Marlon Bautista""",prophecymaster,"""@jtimberlake I think LeBron will force to win...",25,20,[@jtimberlake],"[#NBAFinals""]",1,1,2012-06-22,01:07:39,NaN,NaN
3266,"""215974282872889344""","""MoWaysThanAlilBit""",rees1025,"""@jtimberlake HYFR!!""",14,17,[@jtimberlake],[],0,1,2012-06-22,01:07:36,NaN,NaN
3267,"""215974100986904576""","""Trevor Lloyd""",trevorlloyd92,"""@jtimberlake yeah he is getting his ring toni...",16,21,[@jtimberlake],[],0,1,2012-06-22,01:06:52,NaN,NaN
3268,"""215973780676296707""","""Maira Guifarro""",bambi_allsmiles,"""@jtimberlake yessssssss!!!!""",14,17,[@jtimberlake],[],0,1,2012-06-22,01:05:36,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Male"

#Create an Vocation column 
Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3269, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1218185336603529217""","""Justin Timberlake""",jtimberlake,553,5758,[],[],0,0,2020-01-17,14:56:31,Image added,-,Male,Music
1,"""1212492165844291585""","""Timbaland""",timbaland,2121,21507,[],[],0,0,2020-01-01,21:53:54,Image added,-,Male,Music
2,"""1211717959334408194""","""Justin Timberlake""",jtimberlake,259,3130,[@TigerWoods],[],0,1,2019-12-30,18:37:28,-,-,Male,Music
3,"""1209512769491554305""","""Complex""",complex,268,1583,[],[#TheLastDance],1,0,2019-12-24,16:34:50,-,Video added,Male,Music
4,"""1194993347930345474""","""Justin Timberlake""",jtimberlake,616,4480,[],[#TrollsWorldTour],1,0,2019-11-14,14:59:50,Image added,-,Male,Music
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3264,"""215974474837798913""","""Kelly Miller""",kelly_miller,33,30,[@jtimberlake],[],0,1,2012-06-22,01:08:22,-,-,Male,Music
3265,"""215974296642789376""","""Marlon Bautista""",prophecymaster,25,20,[@jtimberlake],"[#NBAFinals""]",1,1,2012-06-22,01:07:39,-,-,Male,Music
3266,"""215974282872889344""","""MoWaysThanAlilBit""",rees1025,14,17,[@jtimberlake],[],0,1,2012-06-22,01:07:36,-,-,Male,Music
3267,"""215974100986904576""","""Trevor Lloyd""",trevorlloyd92,16,21,[@jtimberlake],[],0,1,2012-06-22,01:06:52,-,-,Male,Music
3268,"""215973780676296707""","""Maira Guifarro""",bambi_allsmiles,14,17,[@jtimberlake],[],0,1,2012-06-22,01:05:36,-,-,Male,Music

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3269, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1218185336603529217""","""Justin Timberlake""",jtimberlake,Male,Music,[],0,[],0,5758,553,Image added,-,2020-01-17,14:56:31
"""1212492165844291585""","""Timbaland""",timbaland,Male,Music,[],0,[],0,21507,2121,Image added,-,2020-01-01,21:53:54
"""1211717959334408194""","""Justin Timberlake""",jtimberlake,Male,Music,[],0,[@TigerWoods],1,3130,259,-,-,2019-12-30,18:37:28
"""1209512769491554305""","""Complex""",complex,Male,Music,[#TheLastDance],1,[],0,1583,268,-,Video added,2019-12-24,16:34:50
"""1194993347930345474""","""Justin Timberlake""",jtimberlake,Male,Music,[#TrollsWorldTour],1,[],0,4480,616,Image added,-,2019-11-14,14:59:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""215974474837798913""","""Kelly Miller""",kelly_miller,Male,Music,[],0,[@jtimberlake],1,30,33,-,-,2012-06-22,01:08:22
"""215974296642789376""","""Marlon Bautista""",prophecymaster,Male,Music,"[#NBAFinals""]",1,[@jtimberlake],1,20,25,-,-,2012-06-22,01:07:39
"""215974282872889344""","""MoWaysThanAlilBit""",rees1025,Male,Music,[],0,[@jtimberlake],1,17,14,-,-,2012-06-22,01:07:36
"""215974100986904576""","""Trevor Lloyd""",trevorlloyd92,Male,Music,[],0,[@jtimberlake],1,21,16,-,-,2012-06-22,01:06:52
"""215973780676296707""","""Maira Guifarro""",bambi_allsmiles,Male,Music,[],0,[@jtimberlake],1,17,14,-,-,2012-06-22,01:05:36

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/JustinTimberLake_df.csv')