##### ===================================================================================================================

#  Kevin Hart Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/KevinHartTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220060656264785922""",https://twitter.com/kevinhart4real/status/1220...,2020-01-22 19:08:22,"""The Winter Olympics ain't got shit on the col...",Tweet,Instagram,35,539,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
1,"""1219330669387698176""",https://twitter.com/kevinhart4real/status/1219...,2020-01-20 18:47:40,"""Happy MLK Day.... #HartBeatProductions #Laugh...",Tweet,Instagram,93,1396,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
2,"""1218585360797556736""",https://twitter.com/kevinhart4real/status/1218...,2020-01-18 17:26:04,"""Big Shit coming in 2020....Stay tuned""",Tweet,Twitter for iPhone,804,11275,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
3,"""1217958222885195777""",https://twitter.com/kevinhart4real/status/1217...,2020-01-16 23:54:03,"""I am so excited about the partnership between...",Tweet,Instagram,95,1619,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
4,"""1217951440238301184""",https://twitter.com/kevinhart4real/status/1217...,2020-01-16 23:27:06,"""BREAKING NEWS ‚ÄºÔ∏è My @LOLNetwork just partnere...",Tweet,Twitter for iPhone,134,1569,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""987118723118006272""",https://twitter.com/kevinhart4real/status/9871...,2018-04-20 00:00:18,"""Even tho I didn't make it to Miami I felt the...",Tweet,Instagram,22,434,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
3196,"""987110711254859776""",https://twitter.com/kevinhart4real/status/9871...,2018-04-19 23:28:27,"""https://t.co/ACiQ53OCLa""",Reply,Twitter for iPhone,73,610,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
3197,"""987110701196918785""",https://twitter.com/kevinhart4real/status/9871...,2018-04-19 23:28:25,"""Heads up Miami! Bringing the heat tonight wit...",Tweet,Twitter for iPhone,33,294,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
3198,"""987107607033741312""",https://twitter.com/kevinhart4real/status/9871...,2018-04-19 23:16:07,"""üòÇüòÇüòÇüòÇüòÇüòÇ https://t.co/LFvbSJi1R0""",Tweet,Twitter for iPhone,202,2025,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected
3199,"""987106774581788673""",https://twitter.com/kevinhart4real/status/9871...,2018-04-19 23:12:49,"""Game time....Lets gooooooooo SIXERS!!!!! Stan...",Tweet,Twitter for iPhone,181,1446,"""23151437""","""Kevin Hart""",kevinhart4real,Verified,https://twitter.com/kevinhart4real,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1220060656264785922""","""Kevin Hart""",kevinhart4real,"""The Winter Olympics ain't got shit on the col...",35,539,2020-01-22 19:08:22
1,"""1219330669387698176""","""Kevin Hart""",kevinhart4real,"""Happy MLK Day.... #HartBeatProductions #Laugh...",93,1396,2020-01-20 18:47:40
2,"""1218585360797556736""","""Kevin Hart""",kevinhart4real,"""Big Shit coming in 2020....Stay tuned""",804,11275,2020-01-18 17:26:04
3,"""1217958222885195777""","""Kevin Hart""",kevinhart4real,"""I am so excited about the partnership between...",95,1619,2020-01-16 23:54:03
4,"""1217951440238301184""","""Kevin Hart""",kevinhart4real,"""BREAKING NEWS ‚ÄºÔ∏è My @LOLNetwork just partnere...",134,1569,2020-01-16 23:27:06

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1220060656264785922""","""Kevin Hart""",kevinhart4real,"""The Winter Olympics ain't got shit on the col...",35,539,2020-01-22 19:08:22,[@lolojones],"[#PoweredbyOldSpice, #CABSeason3, #OnlyonLOLNe...",3,1
1,"""1219330669387698176""","""Kevin Hart""",kevinhart4real,"""Happy MLK Day.... #HartBeatProductions #Laugh...",93,1396,2020-01-20 18:47:40,[],"[#HartBeatProductions, #LaughOutLoud, #BestBos...",3,0
2,"""1218585360797556736""","""Kevin Hart""",kevinhart4real,"""Big Shit coming in 2020....Stay tuned""",804,11275,2020-01-18 17:26:04,[],[],0,0
3,"""1217958222885195777""","""Kevin Hart""",kevinhart4real,"""I am so excited about the partnership between...",95,1619,2020-01-16 23:54:03,[],[],0,0
4,"""1217951440238301184""","""Kevin Hart""",kevinhart4real,"""BREAKING NEWS ‚ÄºÔ∏è My @LOLNetwork just partnere...",134,1569,2020-01-16 23:27:06,"[@LOLNetwork, @peacockTV]",[],0,2
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""987118723118006272""","""Kevin Hart""",kevinhart4real,"""Even tho I didn't make it to Miami I felt the...",22,434,2018-04-20 00:00:18,[],[],0,0
3196,"""987110711254859776""","""Kevin Hart""",kevinhart4real,"""https://t.co/ACiQ53OCLa""",73,610,2018-04-19 23:28:27,[],[],0,0
3197,"""987110701196918785""","""Kevin Hart""",kevinhart4real,"""Heads up Miami! Bringing the heat tonight wit...",33,294,2018-04-19 23:28:25,[@MountainDew],"[#CantBeBanned, #MtnDewKickstart, #TrustThePro...",4,1
3198,"""987107607033741312""","""Kevin Hart""",kevinhart4real,"""üòÇüòÇüòÇüòÇüòÇüòÇ https://t.co/LFvbSJi1R0""",202,2025,2018-04-19 23:16:07,[],[],0,0
3199,"""987106774581788673""","""Kevin Hart""",kevinhart4real,"""Game time....Lets gooooooooo SIXERS!!!!! Stan...",181,1446,2018-04-19 23:12:49,[],[],0,0

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1220060656264785922""","""Kevin Hart""",kevinhart4real,"""The Winter Olympics ain't got shit on the col...",35,539,[@lolojones],"[#PoweredbyOldSpice, #CABSeason3, #OnlyonLOLNe...",3,1,2020-01-22,19:08:22
1,"""1219330669387698176""","""Kevin Hart""",kevinhart4real,"""Happy MLK Day.... #HartBeatProductions #Laugh...",93,1396,[],"[#HartBeatProductions, #LaughOutLoud, #BestBos...",3,0,2020-01-20,18:47:40
2,"""1218585360797556736""","""Kevin Hart""",kevinhart4real,"""Big Shit coming in 2020....Stay tuned""",804,11275,[],[],0,0,2020-01-18,17:26:04
3,"""1217958222885195777""","""Kevin Hart""",kevinhart4real,"""I am so excited about the partnership between...",95,1619,[],[],0,0,2020-01-16,23:54:03
4,"""1217951440238301184""","""Kevin Hart""",kevinhart4real,"""BREAKING NEWS ‚ÄºÔ∏è My @LOLNetwork just partnere...",134,1569,"[@LOLNetwork, @peacockTV]",[],0,2,2020-01-16,23:27:06
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""987118723118006272""","""Kevin Hart""",kevinhart4real,"""Even tho I didn't make it to Miami I felt the...",22,434,[],[],0,0,2018-04-20,00:00:18
3196,"""987110711254859776""","""Kevin Hart""",kevinhart4real,"""https://t.co/ACiQ53OCLa""",73,610,[],[],0,0,2018-04-19,23:28:27
3197,"""987110701196918785""","""Kevin Hart""",kevinhart4real,"""Heads up Miami! Bringing the heat tonight wit...",33,294,[@MountainDew],"[#CantBeBanned, #MtnDewKickstart, #TrustThePro...",4,1,2018-04-19,23:28:25
3198,"""987107607033741312""","""Kevin Hart""",kevinhart4real,"""üòÇüòÇüòÇüòÇüòÇüòÇ https://t.co/LFvbSJi1R0""",202,2025,[],[],0,0,2018-04-19,23:16:07
3199,"""987106774581788673""","""Kevin Hart""",kevinhart4real,"""Game time....Lets gooooooooo SIXERS!!!!! Stan...",181,1446,[],[],0,0,2018-04-19,23:12:49

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/KevinHartImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1211276589217923074""","""1211276586063822853""",https://pbs.twimg.com/media/EM9Roy0VAAUMy4N.jpg,https://t.co/eZ6yykTw6S
1,"""1211214096009506816""","""1211214091496411136""",https://pbs.twimg.com/media/EM8YzIaXUAAq0VC.jpg,https://t.co/raBcfwpsnN
2,"""1210821489181593600""","""1210821461142720513""",https://pbs.twimg.com/media/EM2ztCXU0AEFuzR.jpg,https://t.co/1sdoxIG4N7
3,"""1206317456349728768""","""1206317446862258178""",https://pbs.twimg.com/media/EL2zU5qUwAIpGQq.jpg,https://t.co/gQAolPap44
4,"""1205707106038538240""","""1205707098631356416""",https://pbs.twimg.com/media/ELuIN9UWwAApJDQ.jpg,https://t.co/sjLhbgsMvU
...,...,...,...,...
139,"""993103592633651201""","""993103590993645569""",https://pbs.twimg.com/media/Dcg2dE5XUAEK8yx.jpg,https://t.co/85FRY6xndg
140,"""991648319284895745""","""991648002526863362""",https://pbs.twimg.com/media/DcMKmrTW4AIifEg.jpg,https://t.co/6KUyEEtlYd
141,"""988175615143669760""","""988116007817379841""",https://pbs.twimg.com/media/DbZ-RhrVAAEuvyX.jpg,https://t.co/M2ourloKTW
142,"""987127008575488001""","""987127002363846656""",https://pbs.twimg.com/media/DbL6x1QX4AASFv8.jpg,https://t.co/euuKyQn2vL
143,"""987110711254859776""","""987110705324150784""",https://pbs.twimg.com/media/DbLr9ODU0AA7y41.jpg,https://t.co/ACiQ53OCLa

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (144, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (144, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1211276589217923074"  Image added
1    "1211214096009506816"  Image added
2    "1210821489181593600"  Image added
3    "1206317456349728768"  Image added
4    "1205707106038538240"  Image added
..                     ...          ...
139   "993103592633651201"  Image added
140   "991648319284895745"  Image added
141   "988175615143669760"  Image added
142   "987127008575488001"  Image added
143   "987110711254859776"  Image added

[144 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1220060656264785922""","""Kevin Hart""",kevinhart4real,"""The Winter Olympics ain't got shit on the col...",35,539,[@lolojones],"[#PoweredbyOldSpice, #CABSeason3, #OnlyonLOLNe...",3,1,2020-01-22,19:08:22,NaN
1,"""1219330669387698176""","""Kevin Hart""",kevinhart4real,"""Happy MLK Day.... #HartBeatProductions #Laugh...",93,1396,[],"[#HartBeatProductions, #LaughOutLoud, #BestBos...",3,0,2020-01-20,18:47:40,NaN
2,"""1218585360797556736""","""Kevin Hart""",kevinhart4real,"""Big Shit coming in 2020....Stay tuned""",804,11275,[],[],0,0,2020-01-18,17:26:04,NaN
3,"""1217958222885195777""","""Kevin Hart""",kevinhart4real,"""I am so excited about the partnership between...",95,1619,[],[],0,0,2020-01-16,23:54:03,NaN
4,"""1217951440238301184""","""Kevin Hart""",kevinhart4real,"""BREAKING NEWS ‚ÄºÔ∏è My @LOLNetwork just partnere...",134,1569,"[@LOLNetwork, @peacockTV]",[],0,2,2020-01-16,23:27:06,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,"""987118723118006272""","""Kevin Hart""",kevinhart4real,"""Even tho I didn't make it to Miami I felt the...",22,434,[],[],0,0,2018-04-20,00:00:18,NaN
3209,"""987110711254859776""","""Kevin Hart""",kevinhart4real,"""https://t.co/ACiQ53OCLa""",73,610,[],[],0,0,2018-04-19,23:28:27,Image added
3210,"""987110701196918785""","""Kevin Hart""",kevinhart4real,"""Heads up Miami! Bringing the heat tonight wit...",33,294,[@MountainDew],"[#CantBeBanned, #MtnDewKickstart, #TrustThePro...",4,1,2018-04-19,23:28:25,NaN
3211,"""987107607033741312""","""Kevin Hart""",kevinhart4real,"""üòÇüòÇüòÇüòÇüòÇüòÇ https://t.co/LFvbSJi1R0""",202,2025,[],[],0,0,2018-04-19,23:16:07,NaN
3212,"""987106774581788673""","""Kevin Hart""",kevinhart4real,"""Game time....Lets gooooooooo SIXERS!!!!! Stan...",181,1446,[],[],0,0,2018-04-19,23:12:49,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/KevinHartVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1214391274310008834""","""1214391204558716928""",https://video.twimg.com/ext_tw_video/121439120...,https://t.co/F00qFwuaV3
1,"""1210349719697809408""","""1210349105685250050""",https://video.twimg.com/ext_tw_video/121034910...,https://t.co/oNevBxV2Vi
2,"""1206593145825304578""","""1206581162359037952""",https://video.twimg.com/amplify_video/12065811...,https://t.co/7LRjfMxe03
3,"""1206029896796868608""","""1206027248936964097""",https://video.twimg.com/amplify_video/12060272...,https://t.co/WRdTW5o2hS
4,"""1205683487715549190""","""1205683469776502784""",https://video.twimg.com/tweet_video/ELtyuk-WwA...,https://t.co/jGk9P1Eoco
...,...,...,...,...
182,"""996173098561892352""","""995013539268984832""",https://video.twimg.com/amplify_video/99501353...,https://t.co/nrLjUN7uas
183,"""992101335385260033""","""992098934796435456""",https://video.twimg.com/ext_tw_video/992098934...,https://t.co/4lJLAJO1qR
184,"""988142303628820480""","""988140785907322880""",https://video.twimg.com/amplify_video/98814078...,https://t.co/ZmRhv2NaJF
185,"""987540133980327936""","""987540120147517440""",https://video.twimg.com/tweet_video/DbRygc7W4A...,https://t.co/wtEeUBsd28
186,"""987375395874975747""","""987368884217970698""",https://video.twimg.com/amplify_video/98736888...,https://t.co/mh2fJDgY52

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (187, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (187, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1214391274310008834"  Video added
1    "1210349719697809408"  Video added
2    "1206593145825304578"  Video added
3    "1206029896796868608"  Video added
4    "1205683487715549190"  Video added
..                     ...          ...
182   "996173098561892352"  Video added
183   "992101335385260033"  Video added
184   "988142303628820480"  Video added
185   "987540133980327936"  Video added
186   "987375395874975747"  Video added

[187 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1220060656264785922""","""Kevin Hart""",kevinhart4real,"""The Winter Olympics ain't got shit on the col...",35,539,[@lolojones],"[#PoweredbyOldSpice, #CABSeason3, #OnlyonLOLNe...",3,1,2020-01-22,19:08:22,NaN,NaN
1,"""1219330669387698176""","""Kevin Hart""",kevinhart4real,"""Happy MLK Day.... #HartBeatProductions #Laugh...",93,1396,[],"[#HartBeatProductions, #LaughOutLoud, #BestBos...",3,0,2020-01-20,18:47:40,NaN,NaN
2,"""1218585360797556736""","""Kevin Hart""",kevinhart4real,"""Big Shit coming in 2020....Stay tuned""",804,11275,[],[],0,0,2020-01-18,17:26:04,NaN,NaN
3,"""1217958222885195777""","""Kevin Hart""",kevinhart4real,"""I am so excited about the partnership between...",95,1619,[],[],0,0,2020-01-16,23:54:03,NaN,NaN
4,"""1217951440238301184""","""Kevin Hart""",kevinhart4real,"""BREAKING NEWS ‚ÄºÔ∏è My @LOLNetwork just partnere...",134,1569,"[@LOLNetwork, @peacockTV]",[],0,2,2020-01-16,23:27:06,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,"""987118723118006272""","""Kevin Hart""",kevinhart4real,"""Even tho I didn't make it to Miami I felt the...",22,434,[],[],0,0,2018-04-20,00:00:18,NaN,NaN
3209,"""987110711254859776""","""Kevin Hart""",kevinhart4real,"""https://t.co/ACiQ53OCLa""",73,610,[],[],0,0,2018-04-19,23:28:27,Image added,NaN
3210,"""987110701196918785""","""Kevin Hart""",kevinhart4real,"""Heads up Miami! Bringing the heat tonight wit...",33,294,[@MountainDew],"[#CantBeBanned, #MtnDewKickstart, #TrustThePro...",4,1,2018-04-19,23:28:25,NaN,NaN
3211,"""987107607033741312""","""Kevin Hart""",kevinhart4real,"""üòÇüòÇüòÇüòÇüòÇüòÇ https://t.co/LFvbSJi1R0""",202,2025,[],[],0,0,2018-04-19,23:16:07,NaN,NaN
3212,"""987106774581788673""","""Kevin Hart""",kevinhart4real,"""Game time....Lets gooooooooo SIXERS!!!!! Stan...",181,1446,[],[],0,0,2018-04-19,23:12:49,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Male"

#Create an Vocation column 
Tweets_df['Vocation'] = "Entertainment"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3213, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1220060656264785922""","""Kevin Hart""",kevinhart4real,35,539,[@lolojones],"[#PoweredbyOldSpice, #CABSeason3, #OnlyonLOLNe...",3,1,2020-01-22,19:08:22,-,-,Male,Entertainment
1,"""1219330669387698176""","""Kevin Hart""",kevinhart4real,93,1396,[],"[#HartBeatProductions, #LaughOutLoud, #BestBos...",3,0,2020-01-20,18:47:40,-,-,Male,Entertainment
2,"""1218585360797556736""","""Kevin Hart""",kevinhart4real,804,11275,[],[],0,0,2020-01-18,17:26:04,-,-,Male,Entertainment
3,"""1217958222885195777""","""Kevin Hart""",kevinhart4real,95,1619,[],[],0,0,2020-01-16,23:54:03,-,-,Male,Entertainment
4,"""1217951440238301184""","""Kevin Hart""",kevinhart4real,134,1569,"[@LOLNetwork, @peacockTV]",[],0,2,2020-01-16,23:27:06,-,-,Male,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,"""987118723118006272""","""Kevin Hart""",kevinhart4real,22,434,[],[],0,0,2018-04-20,00:00:18,-,-,Male,Entertainment
3209,"""987110711254859776""","""Kevin Hart""",kevinhart4real,73,610,[],[],0,0,2018-04-19,23:28:27,Image added,-,Male,Entertainment
3210,"""987110701196918785""","""Kevin Hart""",kevinhart4real,33,294,[@MountainDew],"[#CantBeBanned, #MtnDewKickstart, #TrustThePro...",4,1,2018-04-19,23:28:25,-,-,Male,Entertainment
3211,"""987107607033741312""","""Kevin Hart""",kevinhart4real,202,2025,[],[],0,0,2018-04-19,23:16:07,-,-,Male,Entertainment
3212,"""987106774581788673""","""Kevin Hart""",kevinhart4real,181,1446,[],[],0,0,2018-04-19,23:12:49,-,-,Male,Entertainment

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3213, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1220060656264785922""","""Kevin Hart""",kevinhart4real,Male,Entertainment,"[#PoweredbyOldSpice, #CABSeason3, #OnlyonLOLNe...",3,[@lolojones],1,539,35,-,-,2020-01-22,19:08:22
"""1219330669387698176""","""Kevin Hart""",kevinhart4real,Male,Entertainment,"[#HartBeatProductions, #LaughOutLoud, #BestBos...",3,[],0,1396,93,-,-,2020-01-20,18:47:40
"""1218585360797556736""","""Kevin Hart""",kevinhart4real,Male,Entertainment,[],0,[],0,11275,804,-,-,2020-01-18,17:26:04
"""1217958222885195777""","""Kevin Hart""",kevinhart4real,Male,Entertainment,[],0,[],0,1619,95,-,-,2020-01-16,23:54:03
"""1217951440238301184""","""Kevin Hart""",kevinhart4real,Male,Entertainment,[],0,"[@LOLNetwork, @peacockTV]",2,1569,134,-,-,2020-01-16,23:27:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""987118723118006272""","""Kevin Hart""",kevinhart4real,Male,Entertainment,[],0,[],0,434,22,-,-,2018-04-20,00:00:18
"""987110711254859776""","""Kevin Hart""",kevinhart4real,Male,Entertainment,[],0,[],0,610,73,Image added,-,2018-04-19,23:28:27
"""987110701196918785""","""Kevin Hart""",kevinhart4real,Male,Entertainment,"[#CantBeBanned, #MtnDewKickstart, #TrustThePro...",4,[@MountainDew],1,294,33,-,-,2018-04-19,23:28:25
"""987107607033741312""","""Kevin Hart""",kevinhart4real,Male,Entertainment,[],0,[],0,2025,202,-,-,2018-04-19,23:16:07
"""987106774581788673""","""Kevin Hart""",kevinhart4real,Male,Entertainment,[],0,[],0,1446,181,-,-,2018-04-19,23:12:49

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/KevinHart_df.csv')

PermissionError: [Errno 13] Permission denied: 'NewDataframes/KevinHart_df.csv'