##### ===================================================================================================================

#  Lady Gaga Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/LadyGagaTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220142182595620865""",https://twitter.com/ladygaga/status/1220142182...,2020-01-23 00:32:20,"""can y’all stop https://t.co/1jvZLdY6jV""",Tweet,Twitter for iPhone,53486,230775,"""14230524""","""Lady Gaga""",ladygaga,Verified,https://twitter.com/ladygaga,Not Protected
1,"""1218234214052585472""",https://twitter.com/hauslabs/status/1218234214...,2020-01-17 18:10:44,"""ENTER NOW via our latest post on Instagram #H...",Retweet,Twitter for iPhone,999,6296,"""582519519""","""HAUS LABORATORIES""",hauslabs,Verified,https://twitter.com/hauslabs,Not Protected
2,"""1216101829584359424""",https://twitter.com/ladygaga/status/1216101829...,2020-01-11 20:57:24,"""Thank you @Oprah for caring, and for helping ...",Tweet,Twitter for iPhone,13821,88193,"""14230524""","""Lady Gaga""",ladygaga,Verified,https://twitter.com/ladygaga,Not Protected
3,"""1209210336152211456""",https://twitter.com/hauslabs/status/1209210336...,2019-12-23 20:33:04,"""Our BURLESQUE SET is SOLD OUT on https://t.co...",Retweet,Twitter for iPhone,759,5833,"""582519519""","""HAUS LABORATORIES""",hauslabs,Verified,https://twitter.com/hauslabs,Not Protected
4,"""1207502813657366529""",https://twitter.com/ladygaga/status/1207502813...,2019-12-19 03:27:59,"""#LG6\nmy assistant: when’s the last time you ...",Tweet,Twitter for iPhone,15570,113812,"""14230524""","""Lady Gaga""",ladygaga,Verified,https://twitter.com/ladygaga,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""531242897392558080""",https://twitter.com/stephaniehurts/status/5312...,2014-11-09 00:32:31,"""The best night of my life. A party full of ar...",Retweet,Twitter for iPhone,1045,2076,"""235594994""","""Estefanía""",stephaniehurts,Non-Verified,https://twitter.com/stephaniehurts,Not Protected
3196,"""531175474660392962""",https://twitter.com/ladygaga/status/5311754746...,2014-11-08 20:04:36,""":( 7 more shows. here we go Barcelona, I cann...",Tweet,Instagram,2924,4121,"""14230524""","""Lady Gaga""",ladygaga,Verified,https://twitter.com/ladygaga,Not Protected
3197,"""531074690044149760""",https://twitter.com/ladygaga/status/5310746900...,2014-11-08 13:24:07,"""Yes I love it!! RT @HAUSofUNICORN_: @ladygaga...",Reply,Twitter for iPhone,3313,5316,"""14230524""","""Lady Gaga""",ladygaga,Verified,https://twitter.com/ladygaga,Not Protected
3198,"""531014677565018112""",https://twitter.com/igagaswife/status/53101467...,2014-11-08 09:25:39,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",Retweet,Twitter for Android,1096,1990,"""290819219""","""Sophie""",igagaswife,Non-Verified,https://twitter.com/igagaswife,Not Protected
3199,"""530787941455376384""",https://twitter.com/ladygaga/status/5307879414...,2014-11-07 18:24:41,"""When they ask me, I tell them no. Show busine...",Tweet,Instagram,2443,3523,"""14230524""","""Lady Gaga""",ladygaga,Verified,https://twitter.com/ladygaga,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1220142182595620865""","""Lady Gaga""",ladygaga,"""can y’all stop https://t.co/1jvZLdY6jV""",53486,230775,2020-01-23 00:32:20
1,"""1218234214052585472""","""HAUS LABORATORIES""",hauslabs,"""ENTER NOW via our latest post on Instagram #H...",999,6296,2020-01-17 18:10:44
2,"""1216101829584359424""","""Lady Gaga""",ladygaga,"""Thank you @Oprah for caring, and for helping ...",13821,88193,2020-01-11 20:57:24
3,"""1209210336152211456""","""HAUS LABORATORIES""",hauslabs,"""Our BURLESQUE SET is SOLD OUT on https://t.co...",759,5833,2019-12-23 20:33:04
4,"""1207502813657366529""","""Lady Gaga""",ladygaga,"""#LG6\nmy assistant: when’s the last time you ...",15570,113812,2019-12-19 03:27:59

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1220142182595620865""","""Lady Gaga""",ladygaga,"""can y’all stop https://t.co/1jvZLdY6jV""",53486,230775,2020-01-23 00:32:20,[],[],0,0
1,"""1218234214052585472""","""HAUS LABORATORIES""",hauslabs,"""ENTER NOW via our latest post on Instagram #H...",999,6296,2020-01-17 18:10:44,[],[#HAUSCALL],1,0
2,"""1216101829584359424""","""Lady Gaga""",ladygaga,"""Thank you @Oprah for caring, and for helping ...",13821,88193,2020-01-11 20:57:24,[@Oprah],[],0,1
3,"""1209210336152211456""","""HAUS LABORATORIES""",hauslabs,"""Our BURLESQUE SET is SOLD OUT on https://t.co...",759,5833,2019-12-23 20:33:04,[@amazon],[],0,1
4,"""1207502813657366529""","""Lady Gaga""",ladygaga,"""#LG6\nmy assistant: when’s the last time you ...",15570,113812,2019-12-19 03:27:59,[],[#LG6],1,0
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""531242897392558080""","""Estefanía""",stephaniehurts,"""The best night of my life. A party full of ar...",1045,2076,2014-11-09 00:32:31,[@ladygaga],"[#artRAVEBarcelona""]",1,1
3196,"""531175474660392962""","""Lady Gaga""",ladygaga,""":( 7 more shows. here we go Barcelona, I cann...",2924,4121,2014-11-08 20:04:36,[],[],0,0
3197,"""531074690044149760""","""Lady Gaga""",ladygaga,"""Yes I love it!! RT @HAUSofUNICORN_: @ladygaga...",3313,5316,2014-11-08 13:24:07,"[@HAUSofUNICORN_:, @ladygaga]",[],0,2
3198,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,2014-11-08 09:25:39,"[@ladygaga, @itstonybennett]",[],0,2
3199,"""530787941455376384""","""Lady Gaga""",ladygaga,"""When they ask me, I tell them no. Show busine...",2443,3523,2014-11-07 18:24:41,[],[],0,0

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1220142182595620865""","""Lady Gaga""",ladygaga,"""can y’all stop https://t.co/1jvZLdY6jV""",53486,230775,[],[],0,0,2020-01-23,00:32:20
1,"""1218234214052585472""","""HAUS LABORATORIES""",hauslabs,"""ENTER NOW via our latest post on Instagram #H...",999,6296,[],[#HAUSCALL],1,0,2020-01-17,18:10:44
2,"""1216101829584359424""","""Lady Gaga""",ladygaga,"""Thank you @Oprah for caring, and for helping ...",13821,88193,[@Oprah],[],0,1,2020-01-11,20:57:24
3,"""1209210336152211456""","""HAUS LABORATORIES""",hauslabs,"""Our BURLESQUE SET is SOLD OUT on https://t.co...",759,5833,[@amazon],[],0,1,2019-12-23,20:33:04
4,"""1207502813657366529""","""Lady Gaga""",ladygaga,"""#LG6\nmy assistant: when’s the last time you ...",15570,113812,[],[#LG6],1,0,2019-12-19,03:27:59
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""531242897392558080""","""Estefanía""",stephaniehurts,"""The best night of my life. A party full of ar...",1045,2076,[@ladygaga],"[#artRAVEBarcelona""]",1,1,2014-11-09,00:32:31
3196,"""531175474660392962""","""Lady Gaga""",ladygaga,""":( 7 more shows. here we go Barcelona, I cann...",2924,4121,[],[],0,0,2014-11-08,20:04:36
3197,"""531074690044149760""","""Lady Gaga""",ladygaga,"""Yes I love it!! RT @HAUSofUNICORN_: @ladygaga...",3313,5316,"[@HAUSofUNICORN_:, @ladygaga]",[],0,2,2014-11-08,13:24:07
3198,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39
3199,"""530787941455376384""","""Lady Gaga""",ladygaga,"""When they ask me, I tell them no. Show busine...",2443,3523,[],[],0,0,2014-11-07,18:24:41

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/LadyGagaImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220142182595620865""","""1220142178535493632""",https://pbs.twimg.com/media/EO7Q2McUUAA1xzL.jpg,https://t.co/1jvZLdY6jV
1,"""1218234214052585472""","""1218234209573040129""",https://pbs.twimg.com/media/EOgJjyLUcAEMTCT.jpg,https://t.co/T2CW4NmREy
2,"""1209210336152211456""","""1209210313968476160""",https://pbs.twimg.com/media/EMf6X7bUYAAhMiu.jpg,https://t.co/OnR1a9wXig
3,"""1204525063610847233""","""1204525058850340864""",https://pbs.twimg.com/media/ELdVKL_UwAABVYx.jpg,https://t.co/C0A69guFaP
4,"""1204493362029400064""","""1204493355813457920""",https://pbs.twimg.com/media/ELc4U0-UUAA3VN1.jpg,https://t.co/XbMAmQMAGA
...,...,...,...,...
1224,"""531074690044149760""","""531073100087967744""",https://pbs.twimg.com/media/B17AK7iCQAAIF47.jpg,http://t.co/9e517QzFjK
1225,"""531014677565018112""","""531012738982891520""",https://pbs.twimg.com/media/B16JRc5IUAAiKmF.jpg,http://t.co/v2V7oKylOt
1226,"""531014677565018112""","""531013032219246592""",https://pbs.twimg.com/media/B16JihSIAAAyqre.jpg,http://t.co/v2V7oKylOt
1227,"""531014677565018112""","""531013520192962560""",https://pbs.twimg.com/media/B16J-7IIAAAv1Rd.jpg,http://t.co/v2V7oKylOt
1228,"""531014677565018112""","""531014060754874368""",https://pbs.twimg.com/media/B16KeY4IMAAv60F.jpg,http://t.co/v2V7oKylOt

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1229, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1229, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                   Tweet Id       Images
0     "1220142182595620865"  Image added
1     "1218234214052585472"  Image added
2     "1209210336152211456"  Image added
3     "1204525063610847233"  Image added
4     "1204493362029400064"  Image added
...                     ...          ...
1224   "531074690044149760"  Image added
1225   "531014677565018112"  Image added
1226   "531014677565018112"  Image added
1227   "531014677565018112"  Image added
1228   "531014677565018112"  Image added

[1229 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1220142182595620865""","""Lady Gaga""",ladygaga,"""can y’all stop https://t.co/1jvZLdY6jV""",53486,230775,[],[],0,0,2020-01-23,00:32:20,Image added
1,"""1218234214052585472""","""HAUS LABORATORIES""",hauslabs,"""ENTER NOW via our latest post on Instagram #H...",999,6296,[],[#HAUSCALL],1,0,2020-01-17,18:10:44,Image added
2,"""1216101829584359424""","""Lady Gaga""",ladygaga,"""Thank you @Oprah for caring, and for helping ...",13821,88193,[@Oprah],[],0,1,2020-01-11,20:57:24,NaN
3,"""1209210336152211456""","""HAUS LABORATORIES""",hauslabs,"""Our BURLESQUE SET is SOLD OUT on https://t.co...",759,5833,[@amazon],[],0,1,2019-12-23,20:33:04,Image added
4,"""1207502813657366529""","""Lady Gaga""",ladygaga,"""#LG6\nmy assistant: when’s the last time you ...",15570,113812,[],[#LG6],1,0,2019-12-19,03:27:59,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added
3447,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added
3448,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added
3449,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added
3450,"""530787941455376384""","""Lady Gaga""",ladygaga,"""When they ask me, I tell them no. Show busine...",2443,3523,[],[],0,0,2014-11-07,18:24:41,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/LadyGagaVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1216101829584359424""","""1216101733090226176""",https://video.twimg.com/ext_tw_video/121610173...,https://t.co/BMbq9U473H
1,"""1203373835640176645""","""1203369749427539969""",https://video.twimg.com/amplify_video/12033697...,https://t.co/r0rbId3t6r
2,"""1203032157452734464""","""1203031951134875648""",https://video.twimg.com/ext_tw_video/120303195...,https://t.co/oxhKtnmuHi
3,"""1200490207377678337""","""1200490170455216129""",https://video.twimg.com/ext_tw_video/120049017...,https://t.co/TawKIlR8zm
4,"""1197297465906458624""","""1197297421962764288""",https://video.twimg.com/ext_tw_video/119729742...,https://t.co/RgZ4KON4pV
...,...,...,...,...
266,"""601731039900336129""","""601730801483456512""",https://video.twimg.com/ext_tw_video/601730801...,http://t.co/CuQlzADagD
267,"""585486076996939777""","""585485998756388865""",https://video.twimg.com/tweet_video/CCAQafDW4A...,http://t.co/qwQpVDRXKL
268,"""555408907234197505""","""555408906201989120""",https://video.twimg.com/tweet_video/B7U1dR9CAA...,http://t.co/byXzJ9K38v
269,"""537397968819998720""","""537397911273738240""",https://video.twimg.com/tweet_video/B3U4jZSCEA...,http://t.co/m21ocgcJeL
270,"""531876499063066624""","""531876466401615873""",https://video.twimg.com/tweet_video/B2Ga1ARCIA...,http://t.co/ACKUQociKe

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (271, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (271, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1216101829584359424"  Video added
1    "1203373835640176645"  Video added
2    "1203032157452734464"  Video added
3    "1200490207377678337"  Video added
4    "1197297465906458624"  Video added
..                     ...          ...
266   "601731039900336129"  Video added
267   "585486076996939777"  Video added
268   "555408907234197505"  Video added
269   "537397968819998720"  Video added
270   "531876499063066624"  Video added

[271 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1220142182595620865""","""Lady Gaga""",ladygaga,"""can y’all stop https://t.co/1jvZLdY6jV""",53486,230775,[],[],0,0,2020-01-23,00:32:20,Image added,NaN
1,"""1218234214052585472""","""HAUS LABORATORIES""",hauslabs,"""ENTER NOW via our latest post on Instagram #H...",999,6296,[],[#HAUSCALL],1,0,2020-01-17,18:10:44,Image added,NaN
2,"""1216101829584359424""","""Lady Gaga""",ladygaga,"""Thank you @Oprah for caring, and for helping ...",13821,88193,[@Oprah],[],0,1,2020-01-11,20:57:24,NaN,Video added
3,"""1209210336152211456""","""HAUS LABORATORIES""",hauslabs,"""Our BURLESQUE SET is SOLD OUT on https://t.co...",759,5833,[@amazon],[],0,1,2019-12-23,20:33:04,Image added,NaN
4,"""1207502813657366529""","""Lady Gaga""",ladygaga,"""#LG6\nmy assistant: when’s the last time you ...",15570,113812,[],[#LG6],1,0,2019-12-19,03:27:59,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added,NaN
3447,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added,NaN
3448,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added,NaN
3449,"""531014677565018112""","""Sophie""",igagaswife,"""LADY GAGA &amp; TONY BENNETT on the cover of ...",1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added,NaN
3450,"""530787941455376384""","""Lady Gaga""",ladygaga,"""When they ask me, I tell them no. Show busine...",2443,3523,[],[],0,0,2014-11-07,18:24:41,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Female"

#Create an Vocation column 
Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3451, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1220142182595620865""","""Lady Gaga""",ladygaga,53486,230775,[],[],0,0,2020-01-23,00:32:20,Image added,-,Female,Music
1,"""1218234214052585472""","""HAUS LABORATORIES""",hauslabs,999,6296,[],[#HAUSCALL],1,0,2020-01-17,18:10:44,Image added,-,Female,Music
2,"""1216101829584359424""","""Lady Gaga""",ladygaga,13821,88193,[@Oprah],[],0,1,2020-01-11,20:57:24,-,Video added,Female,Music
3,"""1209210336152211456""","""HAUS LABORATORIES""",hauslabs,759,5833,[@amazon],[],0,1,2019-12-23,20:33:04,Image added,-,Female,Music
4,"""1207502813657366529""","""Lady Gaga""",ladygaga,15570,113812,[],[#LG6],1,0,2019-12-19,03:27:59,-,-,Female,Music
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3446,"""531014677565018112""","""Sophie""",igagaswife,1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added,-,Female,Music
3447,"""531014677565018112""","""Sophie""",igagaswife,1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added,-,Female,Music
3448,"""531014677565018112""","""Sophie""",igagaswife,1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added,-,Female,Music
3449,"""531014677565018112""","""Sophie""",igagaswife,1096,1990,"[@ladygaga, @itstonybennett]",[],0,2,2014-11-08,09:25:39,Image added,-,Female,Music
3450,"""530787941455376384""","""Lady Gaga""",ladygaga,2443,3523,[],[],0,0,2014-11-07,18:24:41,-,-,Female,Music

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3451, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1220142182595620865""","""Lady Gaga""",ladygaga,Female,Music,[],0,[],0,230775,53486,Image added,-,2020-01-23,00:32:20
"""1218234214052585472""","""HAUS LABORATORIES""",hauslabs,Female,Music,[#HAUSCALL],1,[],0,6296,999,Image added,-,2020-01-17,18:10:44
"""1216101829584359424""","""Lady Gaga""",ladygaga,Female,Music,[],0,[@Oprah],1,88193,13821,-,Video added,2020-01-11,20:57:24
"""1209210336152211456""","""HAUS LABORATORIES""",hauslabs,Female,Music,[],0,[@amazon],1,5833,759,Image added,-,2019-12-23,20:33:04
"""1207502813657366529""","""Lady Gaga""",ladygaga,Female,Music,[#LG6],1,[],0,113812,15570,-,-,2019-12-19,03:27:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""531014677565018112""","""Sophie""",igagaswife,Female,Music,[],0,"[@ladygaga, @itstonybennett]",2,1990,1096,Image added,-,2014-11-08,09:25:39
"""531014677565018112""","""Sophie""",igagaswife,Female,Music,[],0,"[@ladygaga, @itstonybennett]",2,1990,1096,Image added,-,2014-11-08,09:25:39
"""531014677565018112""","""Sophie""",igagaswife,Female,Music,[],0,"[@ladygaga, @itstonybennett]",2,1990,1096,Image added,-,2014-11-08,09:25:39
"""531014677565018112""","""Sophie""",igagaswife,Female,Music,[],0,"[@ladygaga, @itstonybennett]",2,1990,1096,Image added,-,2014-11-08,09:25:39
"""530787941455376384""","""Lady Gaga""",ladygaga,Female,Music,[],0,[],0,3523,2443,-,-,2014-11-07,18:24:41

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/LadyGaga_df.csv')