##### ===================================================================================================================

#  LeBron James Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/LeBronJamesTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1219997728480153600""",https://twitter.com/kingjames/status/121999772...,2020-01-22 14:58:19,"""Y‚Äôall know I love this city. Was great to be ...",Tweet,Twitter for iPhone,1378,15014,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected
1,"""1219398135698554882""",https://twitter.com/kingjames/status/121939813...,2020-01-20 23:15:45,"""Hating has no age limit! ü§¶üèæ‚Äç‚ôÇÔ∏è. #JamesGang is...",Tweet,Twitter for iPhone,23430,165848,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected
2,"""1218770028499210240""",https://twitter.com/kingjames/status/121877002...,2020-01-19 05:39:53,"""Welcome back Champ!! @TheNotoriousMMA. üôèüèæüí™üèæ""",Tweet,Twitter for iPhone,33026,224869,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected
3,"""1218274115921928193""",https://twitter.com/kingjames/status/121827411...,2020-01-17 20:49:18,"""Trailblazing right along!! Let‚Äôs Go Boys! üôèüèæüí™...",Tweet,Twitter for iPhone,928,12521,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected
4,"""1217598936342507523""",https://twitter.com/ipromiseschool/status/1217...,2020-01-16 00:06:22,"""From a ‚Äúpetting zoo‚Äù filled with instruments ...",Retweet,Twitter for iPhone,75,638,"""1019672184929902592""","""I PROMISE School""",ipromiseschool,Verified,https://twitter.com/ipromiseschool,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""399172384453701634""",https://twitter.com/kingjames/status/399172384...,2013-11-09 13:51:27,"""Good morning people! Before u do anything, St...",Tweet,Instagram,881,981,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected
3196,"""398315132339900416""",https://twitter.com/kingjames/status/398315132...,2013-11-07 05:05:02,"""Huge S/O @MikeWiLLMadeIt for the track on my ...",Tweet,Twitter for Android,337,606,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected
3197,"""398134815809343488""",https://twitter.com/kingjames/status/398134815...,2013-11-06 17:08:31,"""This is what my off day will consist of today...",Tweet,Instagram,545,847,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected
3198,"""398008098851659776""",https://twitter.com/kingjames/status/398008098...,2013-11-06 08:45:00,"""Post game after our good road win earlier ton...",Tweet,Instagram,281,656,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected
3199,"""397013151973384194""",https://twitter.com/kingjames/status/397013151...,2013-11-03 14:51:26,"""@suzcbryant1 that's one heck of a road trip! ...",Reply,Twitter for Android,46,130,"""23083404""","""LeBron James""",kingjames,Verified,https://twitter.com/kingjames,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1219997728480153600""","""LeBron James""",kingjames,"""Y‚Äôall know I love this city. Was great to be ...",1378,15014,2020-01-22 14:58:19
1,"""1219398135698554882""","""LeBron James""",kingjames,"""Hating has no age limit! ü§¶üèæ‚Äç‚ôÇÔ∏è. #JamesGang is...",23430,165848,2020-01-20 23:15:45
2,"""1218770028499210240""","""LeBron James""",kingjames,"""Welcome back Champ!! @TheNotoriousMMA. üôèüèæüí™üèæ""",33026,224869,2020-01-19 05:39:53
3,"""1218274115921928193""","""LeBron James""",kingjames,"""Trailblazing right along!! Let‚Äôs Go Boys! üôèüèæüí™...",928,12521,2020-01-17 20:49:18
4,"""1217598936342507523""","""I PROMISE School""",ipromiseschool,"""From a ‚Äúpetting zoo‚Äù filled with instruments ...",75,638,2020-01-16 00:06:22

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1219997728480153600""","""LeBron James""",kingjames,"""Y‚Äôall know I love this city. Was great to be ...",1378,15014,2020-01-22 14:58:19,[],[],0,0
1,"""1219398135698554882""","""LeBron James""",kingjames,"""Hating has no age limit! ü§¶üèæ‚Äç‚ôÇÔ∏è. #JamesGang is...",23430,165848,2020-01-20 23:15:45,[],[#JamesGang],1,0
2,"""1218770028499210240""","""LeBron James""",kingjames,"""Welcome back Champ!! @TheNotoriousMMA. üôèüèæüí™üèæ""",33026,224869,2020-01-19 05:39:53,[@TheNotoriousMMA.],[],0,1
3,"""1218274115921928193""","""LeBron James""",kingjames,"""Trailblazing right along!! Let‚Äôs Go Boys! üôèüèæüí™...",928,12521,2020-01-17 20:49:18,[],[],0,0
4,"""1217598936342507523""","""I PROMISE School""",ipromiseschool,"""From a ‚Äúpetting zoo‚Äù filled with instruments ...",75,638,2020-01-16 00:06:22,[],[#WeAreFamily],1,0
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""399172384453701634""","""LeBron James""",kingjames,"""Good morning people! Before u do anything, St...",881,981,2013-11-09 13:51:27,[],[#StriveForGreatness‚Ä¶],1,0
3196,"""398315132339900416""","""LeBron James""",kingjames,"""Huge S/O @MikeWiLLMadeIt for the track on my ...",337,606,2013-11-07 05:05:02,[@MikeWiLLMadeIt],"[#StriveForGreatness""]",1,1
3197,"""398134815809343488""","""LeBron James""",kingjames,"""This is what my off day will consist of today...",545,847,2013-11-06 17:08:31,[],"[#CallofDutyGhosts, #Game.]",2,0
3198,"""398008098851659776""","""LeBron James""",kingjames,"""Post game after our good road win earlier ton...",281,656,2013-11-06 08:45:00,"[@dwyanewade, @IMABIG0]",[#Heatles‚Ä¶],1,2
3199,"""397013151973384194""","""LeBron James""",kingjames,"""@suzcbryant1 that's one heck of a road trip! ...",46,130,2013-11-03 14:51:26,[@suzcbryant1],"[#StriveForGreatness""]",1,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1219997728480153600""","""LeBron James""",kingjames,"""Y‚Äôall know I love this city. Was great to be ...",1378,15014,[],[],0,0,2020-01-22,14:58:19
1,"""1219398135698554882""","""LeBron James""",kingjames,"""Hating has no age limit! ü§¶üèæ‚Äç‚ôÇÔ∏è. #JamesGang is...",23430,165848,[],[#JamesGang],1,0,2020-01-20,23:15:45
2,"""1218770028499210240""","""LeBron James""",kingjames,"""Welcome back Champ!! @TheNotoriousMMA. üôèüèæüí™üèæ""",33026,224869,[@TheNotoriousMMA.],[],0,1,2020-01-19,05:39:53
3,"""1218274115921928193""","""LeBron James""",kingjames,"""Trailblazing right along!! Let‚Äôs Go Boys! üôèüèæüí™...",928,12521,[],[],0,0,2020-01-17,20:49:18
4,"""1217598936342507523""","""I PROMISE School""",ipromiseschool,"""From a ‚Äúpetting zoo‚Äù filled with instruments ...",75,638,[],[#WeAreFamily],1,0,2020-01-16,00:06:22
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""399172384453701634""","""LeBron James""",kingjames,"""Good morning people! Before u do anything, St...",881,981,[],[#StriveForGreatness‚Ä¶],1,0,2013-11-09,13:51:27
3196,"""398315132339900416""","""LeBron James""",kingjames,"""Huge S/O @MikeWiLLMadeIt for the track on my ...",337,606,[@MikeWiLLMadeIt],"[#StriveForGreatness""]",1,1,2013-11-07,05:05:02
3197,"""398134815809343488""","""LeBron James""",kingjames,"""This is what my off day will consist of today...",545,847,[],"[#CallofDutyGhosts, #Game.]",2,0,2013-11-06,17:08:31
3198,"""398008098851659776""","""LeBron James""",kingjames,"""Post game after our good road win earlier ton...",281,656,"[@dwyanewade, @IMABIG0]",[#Heatles‚Ä¶],1,2,2013-11-06,08:45:00
3199,"""397013151973384194""","""LeBron James""",kingjames,"""@suzcbryant1 that's one heck of a road trip! ...",46,130,[@suzcbryant1],"[#StriveForGreatness""]",1,1,2013-11-03,14:51:26

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/LeBronJamesImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1217598936342507523""","""1217598854989799425""",https://pbs.twimg.com/media/EOXHtR6W4AEici4.jpg,https://t.co/W2kJD7uufZ
1,"""1217598936342507523""","""1217598854817816577""",https://pbs.twimg.com/media/EOXHtRRWoAET87t.jpg,https://t.co/W2kJD7uufZ
2,"""1217598936342507523""","""1217598854813691912""",https://pbs.twimg.com/media/EOXHtRQXsAgNe3b.jpg,https://t.co/W2kJD7uufZ
3,"""1217598936342507523""","""1217598854817820673""",https://pbs.twimg.com/media/EOXHtRRWsAE4otO.jpg,https://t.co/W2kJD7uufZ
4,"""1217598290872741889""","""1217598276209463296""",https://pbs.twimg.com/media/EOXHLlyX0AALYh5.jpg,https://t.co/bQTu0ZmY6g
...,...,...,...,...
678,"""423249818501120000""","""423249818333347840""",https://pbs.twimg.com/media/Bd-vd6ECAAADQJ2.jpg,http://t.co/7r7w7jxXQS
679,"""420998997156052992""","""420998997084745728""",https://pbs.twimg.com/media/BdewW3gIMAA_EX1.jpg,http://t.co/fHGB9FFEk4
680,"""412071126378876928""","""412071126244659201""",https://pbs.twimg.com/media/Bbf4gY4CEAE_l2U.jpg,http://t.co/asuctitFyU
681,"""411659562274418688""","""411659561854984192""",https://pbs.twimg.com/media/BbaCMMDCYAACnQq.jpg,http://t.co/1V4UWXbNJV
682,"""404807971433377792""","""404795453705039872""",https://pbs.twimg.com/media/BZ4fUgjIMAA9RPE.jpg,http://t.co/VBxWKCNCaz

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (683, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (683, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1217598936342507523"  Image added
1    "1217598936342507523"  Image added
2    "1217598936342507523"  Image added
3    "1217598936342507523"  Image added
4    "1217598290872741889"  Image added
..                     ...          ...
678   "423249818501120000"  Image added
679   "420998997156052992"  Image added
680   "412071126378876928"  Image added
681   "411659562274418688"  Image added
682   "404807971433377792"  Image added

[683 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1219997728480153600""","""LeBron James""",kingjames,"""Y‚Äôall know I love this city. Was great to be ...",1378,15014,[],[],0,0,2020-01-22,14:58:19,NaN
1,"""1219398135698554882""","""LeBron James""",kingjames,"""Hating has no age limit! ü§¶üèæ‚Äç‚ôÇÔ∏è. #JamesGang is...",23430,165848,[],[#JamesGang],1,0,2020-01-20,23:15:45,NaN
2,"""1218770028499210240""","""LeBron James""",kingjames,"""Welcome back Champ!! @TheNotoriousMMA. üôèüèæüí™üèæ""",33026,224869,[@TheNotoriousMMA.],[],0,1,2020-01-19,05:39:53,NaN
3,"""1218274115921928193""","""LeBron James""",kingjames,"""Trailblazing right along!! Let‚Äôs Go Boys! üôèüèæüí™...",928,12521,[],[],0,0,2020-01-17,20:49:18,NaN
4,"""1217598936342507523""","""I PROMISE School""",ipromiseschool,"""From a ‚Äúpetting zoo‚Äù filled with instruments ...",75,638,[],[#WeAreFamily],1,0,2020-01-16,00:06:22,Image added
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,"""399172384453701634""","""LeBron James""",kingjames,"""Good morning people! Before u do anything, St...",881,981,[],[#StriveForGreatness‚Ä¶],1,0,2013-11-09,13:51:27,NaN
3486,"""398315132339900416""","""LeBron James""",kingjames,"""Huge S/O @MikeWiLLMadeIt for the track on my ...",337,606,[@MikeWiLLMadeIt],"[#StriveForGreatness""]",1,1,2013-11-07,05:05:02,NaN
3487,"""398134815809343488""","""LeBron James""",kingjames,"""This is what my off day will consist of today...",545,847,[],"[#CallofDutyGhosts, #Game.]",2,0,2013-11-06,17:08:31,NaN
3488,"""398008098851659776""","""LeBron James""",kingjames,"""Post game after our good road win earlier ton...",281,656,"[@dwyanewade, @IMABIG0]",[#Heatles‚Ä¶],1,2,2013-11-06,08:45:00,NaN
3489,"""397013151973384194""","""LeBron James""",kingjames,"""@suzcbryant1 that's one heck of a road trip! ...",46,130,[@suzcbryant1],"[#StriveForGreatness""]",1,1,2013-11-03,14:51:26,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/LeBronJamesVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1207724982580596736""","""1207724378730795008""",https://video.twimg.com/amplify_video/12077243...,https://t.co/aw3WIupetu
1,"""1207684719606992896""","""1207680112797372416""",https://video.twimg.com/ext_tw_video/120768011...,https://t.co/49JeOnftdH
2,"""1207683305572884482""","""1207683178296750080""",https://video.twimg.com/ext_tw_video/120768317...,https://t.co/aIAMKHDihC
3,"""1207680369086095360""","""1207680112797372416""",https://video.twimg.com/ext_tw_video/120768011...,https://t.co/WFqi6nZLc7
4,"""1206630507137470464""","""1206628503535247360""",https://video.twimg.com/amplify_video/12066285...,https://t.co/lWJgObjwHL
...,...,...,...,...
160,"""748557523985137664""","""748556960975319042""",https://video.twimg.com/tweet_video/CmNolwkUcA...,https://t.co/k6owk5J2SF
161,"""720314082864144385""","""720312930596564996""",https://video.twimg.com/tweet_video/Cf8Qy0NUMA...,https://t.co/g6RklVxl3o
162,"""712416389097721856""","""712416053662449664""",https://video.twimg.com/ext_tw_video/712416053...,https://t.co/OwCEfQKub7
163,"""655561051585515520""","""655560959092727808""",https://video.twimg.com/tweet_video/CRkFOA9WIA...,http://t.co/ZnIANVuI01
164,"""538799063588536320""","""538798928221589504""",https://video.twimg.com/tweet_video/B3oyxUICUA...,http://t.co/RpkJbYJq1Z

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (165, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (165, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1207724982580596736"  Video added
1    "1207684719606992896"  Video added
2    "1207683305572884482"  Video added
3    "1207680369086095360"  Video added
4    "1206630507137470464"  Video added
..                     ...          ...
160   "748557523985137664"  Video added
161   "720314082864144385"  Video added
162   "712416389097721856"  Video added
163   "655561051585515520"  Video added
164   "538799063588536320"  Video added

[165 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1219997728480153600""","""LeBron James""",kingjames,"""Y‚Äôall know I love this city. Was great to be ...",1378,15014,[],[],0,0,2020-01-22,14:58:19,NaN,NaN
1,"""1219398135698554882""","""LeBron James""",kingjames,"""Hating has no age limit! ü§¶üèæ‚Äç‚ôÇÔ∏è. #JamesGang is...",23430,165848,[],[#JamesGang],1,0,2020-01-20,23:15:45,NaN,NaN
2,"""1218770028499210240""","""LeBron James""",kingjames,"""Welcome back Champ!! @TheNotoriousMMA. üôèüèæüí™üèæ""",33026,224869,[@TheNotoriousMMA.],[],0,1,2020-01-19,05:39:53,NaN,NaN
3,"""1218274115921928193""","""LeBron James""",kingjames,"""Trailblazing right along!! Let‚Äôs Go Boys! üôèüèæüí™...",928,12521,[],[],0,0,2020-01-17,20:49:18,NaN,NaN
4,"""1217598936342507523""","""I PROMISE School""",ipromiseschool,"""From a ‚Äúpetting zoo‚Äù filled with instruments ...",75,638,[],[#WeAreFamily],1,0,2020-01-16,00:06:22,Image added,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,"""399172384453701634""","""LeBron James""",kingjames,"""Good morning people! Before u do anything, St...",881,981,[],[#StriveForGreatness‚Ä¶],1,0,2013-11-09,13:51:27,NaN,NaN
3486,"""398315132339900416""","""LeBron James""",kingjames,"""Huge S/O @MikeWiLLMadeIt for the track on my ...",337,606,[@MikeWiLLMadeIt],"[#StriveForGreatness""]",1,1,2013-11-07,05:05:02,NaN,NaN
3487,"""398134815809343488""","""LeBron James""",kingjames,"""This is what my off day will consist of today...",545,847,[],"[#CallofDutyGhosts, #Game.]",2,0,2013-11-06,17:08:31,NaN,NaN
3488,"""398008098851659776""","""LeBron James""",kingjames,"""Post game after our good road win earlier ton...",281,656,"[@dwyanewade, @IMABIG0]",[#Heatles‚Ä¶],1,2,2013-11-06,08:45:00,NaN,NaN
3489,"""397013151973384194""","""LeBron James""",kingjames,"""@suzcbryant1 that's one heck of a road trip! ...",46,130,[@suzcbryant1],"[#StriveForGreatness""]",1,1,2013-11-03,14:51:26,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Male"

#Create an Vocation column 
Tweets_df['Vocation'] = "Sports"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3490, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1219997728480153600""","""LeBron James""",kingjames,1378,15014,[],[],0,0,2020-01-22,14:58:19,-,-,Male,Sports
1,"""1219398135698554882""","""LeBron James""",kingjames,23430,165848,[],[#JamesGang],1,0,2020-01-20,23:15:45,-,-,Male,Sports
2,"""1218770028499210240""","""LeBron James""",kingjames,33026,224869,[@TheNotoriousMMA.],[],0,1,2020-01-19,05:39:53,-,-,Male,Sports
3,"""1218274115921928193""","""LeBron James""",kingjames,928,12521,[],[],0,0,2020-01-17,20:49:18,-,-,Male,Sports
4,"""1217598936342507523""","""I PROMISE School""",ipromiseschool,75,638,[],[#WeAreFamily],1,0,2020-01-16,00:06:22,Image added,-,Male,Sports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,"""399172384453701634""","""LeBron James""",kingjames,881,981,[],[#StriveForGreatness‚Ä¶],1,0,2013-11-09,13:51:27,-,-,Male,Sports
3486,"""398315132339900416""","""LeBron James""",kingjames,337,606,[@MikeWiLLMadeIt],"[#StriveForGreatness""]",1,1,2013-11-07,05:05:02,-,-,Male,Sports
3487,"""398134815809343488""","""LeBron James""",kingjames,545,847,[],"[#CallofDutyGhosts, #Game.]",2,0,2013-11-06,17:08:31,-,-,Male,Sports
3488,"""398008098851659776""","""LeBron James""",kingjames,281,656,"[@dwyanewade, @IMABIG0]",[#Heatles‚Ä¶],1,2,2013-11-06,08:45:00,-,-,Male,Sports
3489,"""397013151973384194""","""LeBron James""",kingjames,46,130,[@suzcbryant1],"[#StriveForGreatness""]",1,1,2013-11-03,14:51:26,-,-,Male,Sports

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3490, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1219997728480153600""","""LeBron James""",kingjames,Male,Sports,[],0,[],0,15014,1378,-,-,2020-01-22,14:58:19
"""1219398135698554882""","""LeBron James""",kingjames,Male,Sports,[#JamesGang],1,[],0,165848,23430,-,-,2020-01-20,23:15:45
"""1218770028499210240""","""LeBron James""",kingjames,Male,Sports,[],0,[@TheNotoriousMMA.],1,224869,33026,-,-,2020-01-19,05:39:53
"""1218274115921928193""","""LeBron James""",kingjames,Male,Sports,[],0,[],0,12521,928,-,-,2020-01-17,20:49:18
"""1217598936342507523""","""I PROMISE School""",ipromiseschool,Male,Sports,[#WeAreFamily],1,[],0,638,75,Image added,-,2020-01-16,00:06:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""399172384453701634""","""LeBron James""",kingjames,Male,Sports,[#StriveForGreatness‚Ä¶],1,[],0,981,881,-,-,2013-11-09,13:51:27
"""398315132339900416""","""LeBron James""",kingjames,Male,Sports,"[#StriveForGreatness""]",1,[@MikeWiLLMadeIt],1,606,337,-,-,2013-11-07,05:05:02
"""398134815809343488""","""LeBron James""",kingjames,Male,Sports,"[#CallofDutyGhosts, #Game.]",2,[],0,847,545,-,-,2013-11-06,17:08:31
"""398008098851659776""","""LeBron James""",kingjames,Male,Sports,[#Heatles‚Ä¶],1,"[@dwyanewade, @IMABIG0]",2,656,281,-,-,2013-11-06,08:45:00
"""397013151973384194""","""LeBron James""",kingjames,Male,Sports,"[#StriveForGreatness""]",1,[@suzcbryant1],1,130,46,-,-,2013-11-03,14:51:26

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/LeBronJames_df.csv')