##### ===================================================================================================================

#  NY Times Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/NYTimesTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220264933335732226""",https://twitter.com/nytimes/status/12202649333...,2020-01-23 08:40:06,"""The extraordinary meeting of world leaders in...",Tweet,SocialFlow,22,75,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected
1,"""1220262461485539330""",https://twitter.com/nytimes/status/12202624614...,2020-01-23 08:30:16,"""Live Updates: Wuhan Railway Station, usually ...",Tweet,SocialFlow,30,45,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected
2,"""1220259901609476099""",https://twitter.com/nytimes/status/12202599016...,2020-01-23 08:20:06,"""Pictures of 5 starving lions in a park in Sud...",Tweet,SocialFlow,89,165,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected
3,"""1220257379264102401""",https://twitter.com/nytimes/status/12202573792...,2020-01-23 08:10:05,"""Europe morning briefing: Here's what you need...",Tweet,SocialFlow,19,68,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected
4,"""1220254899562254336""",https://twitter.com/nytimes/status/12202548995...,2020-01-23 08:00:13,"""A gateway to alpine vacationlands since train...",Tweet,SocialFlow,18,67,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1207296498742054913""",https://twitter.com/katie_thomas/status/120729...,2019-12-18 13:48:10,"""The Trump administration will move ahead with...",Retweet,Twitter for iPhone,44,56,"""18318642""","""Katie Thomas""",katie_thomas,Non-Verified,https://twitter.com/katie_thomas,Not Protected
3196,"""1207294460767408128""",https://twitter.com/nytimes/status/12072944607...,2019-12-18 13:40:04,"""The battle over impeachment is playing out fr...",Tweet,SocialFlow,42,119,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected
3197,"""1207292607988224002""",https://twitter.com/nytimes/status/12072926079...,2019-12-18 13:32:42,"""China is ramping up its ability to spy on its...",Tweet,Twitter Web App,1036,1106,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected
3198,"""1207289438977613827""",https://twitter.com/nytimes/status/12072894389...,2019-12-18 13:20:07,"""In a victory for Hurricane Harvey victims, a ...",Tweet,SocialFlow,85,215,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected
3199,"""1207286899368484866""",https://twitter.com/nytimes/status/12072868993...,2019-12-18 13:10:01,"""Here's a rundown of the highlights worth watc...",Tweet,SocialFlow,50,162,"""807095""","""The New York Times""",nytimes,Verified,https://twitter.com/nytimes,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1220264933335732226""","""The New York Times""",nytimes,"""The extraordinary meeting of world leaders in...",22,75,2020-01-23 08:40:06
1,"""1220262461485539330""","""The New York Times""",nytimes,"""Live Updates: Wuhan Railway Station, usually ...",30,45,2020-01-23 08:30:16
2,"""1220259901609476099""","""The New York Times""",nytimes,"""Pictures of 5 starving lions in a park in Sud...",89,165,2020-01-23 08:20:06
3,"""1220257379264102401""","""The New York Times""",nytimes,"""Europe morning briefing: Here's what you need...",19,68,2020-01-23 08:10:05
4,"""1220254899562254336""","""The New York Times""",nytimes,"""A gateway to alpine vacationlands since train...",18,67,2020-01-23 08:00:13

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1220264933335732226""","""The New York Times""",nytimes,"""The extraordinary meeting of world leaders in...",22,75,2020-01-23 08:40:06,[],[],0,0
1,"""1220262461485539330""","""The New York Times""",nytimes,"""Live Updates: Wuhan Railway Station, usually ...",30,45,2020-01-23 08:30:16,[@ChuBailiang.],[],0,1
2,"""1220259901609476099""","""The New York Times""",nytimes,"""Pictures of 5 starving lions in a park in Sud...",89,165,2020-01-23 08:20:06,[],[],0,0
3,"""1220257379264102401""","""The New York Times""",nytimes,"""Europe morning briefing: Here's what you need...",19,68,2020-01-23 08:10:05,[],[],0,0
4,"""1220254899562254336""","""The New York Times""",nytimes,"""A gateway to alpine vacationlands since train...",18,67,2020-01-23 08:00:13,[],[],0,0
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1207296498742054913""","""Katie Thomas""",katie_thomas,"""The Trump administration will move ahead with...",44,56,2019-12-18 13:48:10,[],[],0,0
3196,"""1207294460767408128""","""The New York Times""",nytimes,"""The battle over impeachment is playing out fr...",42,119,2019-12-18 13:40:04,[],[],0,0
3197,"""1207292607988224002""","""The New York Times""",nytimes,"""China is ramping up its ability to spy on its...",1036,1106,2019-12-18 13:32:42,[],[],0,0
3198,"""1207289438977613827""","""The New York Times""",nytimes,"""In a victory for Hurricane Harvey victims, a ...",85,215,2019-12-18 13:20:07,[],[],0,0
3199,"""1207286899368484866""","""The New York Times""",nytimes,"""Here's a rundown of the highlights worth watc...",50,162,2019-12-18 13:10:01,[],[],0,0

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1220264933335732226""","""The New York Times""",nytimes,"""The extraordinary meeting of world leaders in...",22,75,[],[],0,0,2020-01-23,08:40:06
1,"""1220262461485539330""","""The New York Times""",nytimes,"""Live Updates: Wuhan Railway Station, usually ...",30,45,[@ChuBailiang.],[],0,1,2020-01-23,08:30:16
2,"""1220259901609476099""","""The New York Times""",nytimes,"""Pictures of 5 starving lions in a park in Sud...",89,165,[],[],0,0,2020-01-23,08:20:06
3,"""1220257379264102401""","""The New York Times""",nytimes,"""Europe morning briefing: Here's what you need...",19,68,[],[],0,0,2020-01-23,08:10:05
4,"""1220254899562254336""","""The New York Times""",nytimes,"""A gateway to alpine vacationlands since train...",18,67,[],[],0,0,2020-01-23,08:00:13
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1207296498742054913""","""Katie Thomas""",katie_thomas,"""The Trump administration will move ahead with...",44,56,[],[],0,0,2019-12-18,13:48:10
3196,"""1207294460767408128""","""The New York Times""",nytimes,"""The battle over impeachment is playing out fr...",42,119,[],[],0,0,2019-12-18,13:40:04
3197,"""1207292607988224002""","""The New York Times""",nytimes,"""China is ramping up its ability to spy on its...",1036,1106,[],[],0,0,2019-12-18,13:32:42
3198,"""1207289438977613827""","""The New York Times""",nytimes,"""In a victory for Hurricane Harvey victims, a ...",85,215,[],[],0,0,2019-12-18,13:20:07
3199,"""1207286899368484866""","""The New York Times""",nytimes,"""Here's a rundown of the highlights worth watc...",50,162,[],[],0,0,2019-12-18,13:10:01

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/NYTimesImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220221489913294848""","""1220220730031259649""",https://pbs.twimg.com/media/EO8YSfkUwAElWg1.jpg,https://t.co/9Hcr6DlvrH
1,"""1220159796160204800""","""1220158999640887297""",https://pbs.twimg.com/media/EO7gJT8XUAEjIDb.jpg,https://t.co/MJKFopMkJQ
2,"""1220081601020923904""","""1220081598399422466""",https://pbs.twimg.com/media/EO6Zv92WoAIo3aS.jpg,https://t.co/kLekNNORzX
3,"""1220080886915510273""","""1220080885233528833""",https://pbs.twimg.com/media/EO6ZGdGWsAECXgd.jpg,https://t.co/Yc5hj2b45y
4,"""1220064867580882944""","""1220064865567625216""",https://pbs.twimg.com/media/EO6Kh_MX0AAJxCt.jpg,https://t.co/1IqY01Ujjq
...,...,...,...,...
112,"""1207498501258665985""","""1207498492060545025""",https://pbs.twimg.com/media/EMHlex4WsAEWYxv.jpg,https://t.co/kCtNDjcmT5
113,"""1207498501258665985""","""1207498492068945922""",https://pbs.twimg.com/media/EMHlex6W4AIJ4GU.jpg,https://t.co/kCtNDjcmT5
114,"""1207490769424207873""","""1207490766588788736""",https://pbs.twimg.com/media/EMHedGQWwAAisTT.jpg,https://t.co/loMTZwvJOz
115,"""1207469399952764928""","""1207469396454780928""",https://pbs.twimg.com/media/EMHLBMTXsAAQkBE.jpg,https://t.co/OFByrTPE1P
116,"""1207429108495507457""","""1207429088157294594""",https://pbs.twimg.com/media/EMGmW8MW4AI9gdO.jpg,https://t.co/OXsA6THrMY

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (117, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

The dataframes 'shape' is represented as: (117, 2)

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1220221489913294848"  Image added
1    "1220159796160204800"  Image added
2    "1220081601020923904"  Image added
3    "1220080886915510273"  Image added
4    "1220064867580882944"  Image added
..                     ...          ...
112  "1207498501258665985"  Image added
113  "1207498501258665985"  Image added
114  "1207490769424207873"  Image added
115  "1207469399952764928"  Image added
116  "1207429108495507457"  Image added

[117 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1220264933335732226""","""The New York Times""",nytimes,"""The extraordinary meeting of world leaders in...",22,75,[],[],0,0,2020-01-23,08:40:06,NaN
1,"""1220262461485539330""","""The New York Times""",nytimes,"""Live Updates: Wuhan Railway Station, usually ...",30,45,[@ChuBailiang.],[],0,1,2020-01-23,08:30:16,NaN
2,"""1220259901609476099""","""The New York Times""",nytimes,"""Pictures of 5 starving lions in a park in Sud...",89,165,[],[],0,0,2020-01-23,08:20:06,NaN
3,"""1220257379264102401""","""The New York Times""",nytimes,"""Europe morning briefing: Here's what you need...",19,68,[],[],0,0,2020-01-23,08:10:05,NaN
4,"""1220254899562254336""","""The New York Times""",nytimes,"""A gateway to alpine vacationlands since train...",18,67,[],[],0,0,2020-01-23,08:00:13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3200,"""1207296498742054913""","""Katie Thomas""",katie_thomas,"""The Trump administration will move ahead with...",44,56,[],[],0,0,2019-12-18,13:48:10,NaN
3201,"""1207294460767408128""","""The New York Times""",nytimes,"""The battle over impeachment is playing out fr...",42,119,[],[],0,0,2019-12-18,13:40:04,NaN
3202,"""1207292607988224002""","""The New York Times""",nytimes,"""China is ramping up its ability to spy on its...",1036,1106,[],[],0,0,2019-12-18,13:32:42,NaN
3203,"""1207289438977613827""","""The New York Times""",nytimes,"""In a victory for Hurricane Harvey victims, a ...",85,215,[],[],0,0,2019-12-18,13:20:07,NaN
3204,"""1207286899368484866""","""The New York Times""",nytimes,"""Here's a rundown of the highlights worth watc...",50,162,[],[],0,0,2019-12-18,13:10:01,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/NYTimesVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220134096111919105""","""1220116366663081985""",https://video.twimg.com/amplify_video/12201163...,https://t.co/0nLoV3kjL1
1,"""1219636926078246917""","""1219636660390039553""",https://video.twimg.com/amplify_video/12196366...,https://t.co/BWVZAzmHkb
2,"""1219102178817773568""","""1219083541499301888""",https://video.twimg.com/amplify_video/12190835...,https://t.co/rEpzG9wlEC
3,"""1219084631384850432""","""1218272109253812224""",https://video.twimg.com/amplify_video/12182721...,https://t.co/vE10BzNm4L
4,"""1218523455878057991""","""1216822232791601159""",https://video.twimg.com/amplify_video/12168222...,https://t.co/Xl0TeS3cdI
5,"""1218240366866059264""","""1218240100045377541""",https://video.twimg.com/amplify_video/12182401...,https://t.co/l6shOtzUvS
6,"""1217529397441249280""","""1217521788378402822""",https://video.twimg.com/amplify_video/12175217...,https://t.co/E3IS5yAJPL
7,"""1217446387702468613""","""1215783271667322880""",https://video.twimg.com/amplify_video/12157832...,https://t.co/5T9IONOPTp
8,"""1217251432275021830""","""1217251409084796928""",https://video.twimg.com/ext_tw_video/121725140...,https://t.co/NIMaLZNdf8
9,"""1216721562264457216""","""1215480670149017601""",https://video.twimg.com/amplify_video/12154806...,https://t.co/Svu319hBdl
10,"""1216687730471645185""","""1216687622409551872""",https://video.twimg.com/ext_tw_video/121668762...,https://t.co/s8Bs8wNI6a
11,"""1216560248330379266""","""1216560199353409538""",https://video.twimg.com/ext_tw_video/121656019...,https://t.co/dR9KrAAwUu
12,"""1216525266824110080""","""1215631831762120705""",https://video.twimg.com/amplify_video/12156318...,https://t.co/mR5Xe0IRoJ
13,"""1216493033278996480""","""1216493007060398080""",https://video.twimg.com/tweet_video/EOHZ8dWU8A...,https://t.co/BfxjEnE0Xb
14,"""1216404474039820290""","""1215332552405372933""",https://video.twimg.com/amplify_video/12153325...,https://t.co/ar2pcVYIaQ
15,"""1216042084722868224""","""1215665071956922369""",https://video.twimg.com/amplify_video/12156650...,https://t.co/pO0MTmeKJR
16,"""1216027032640987143""","""1215284948271235072""",https://video.twimg.com/amplify_video/12152849...,https://t.co/pD4KLNuwN4
17,"""1215991774516326401""","""1214960670170664961""",https://video.twimg.com/amplify_video/12149606...,https://t.co/DaFJt24mTz
18,"""1215921321135214592""","""1215029681235333120""",https://video.twimg.com/amplify_video/12150296...,https://t.co/O4REUnJaDl
19,"""1215297196876271616""","""1214960670170664961""",https://video.twimg.com/amplify_video/12149606...,https://t.co/V2opXvZmNY
20,"""1215226745412030465""","""1215029681235333120""",https://video.twimg.com/amplify_video/12150296...,https://t.co/ap10vYgEo8
21,"""1215035481534160899""","""1215014911950163977""",https://video.twimg.com/amplify_video/12150149...,https://t.co/fvEm1aCFmR
22,"""1215032954973544450""","""1215031128744189953""",https://video.twimg.com/amplify_video/12150311...,https://t.co/8zazre4bqh
23,"""1215015381066276865""","""1214960670170664961""",https://video.twimg.com/amplify_video/12149606...,https://t.co/6ZqXAfugh3
24,"""1214763672805036033""","""1214661036177051650""",https://video.twimg.com/amplify_video/12146610...,https://t.co/ZFZEXu9hIt
25,"""1214640830570516483""","""1214640772345192450""",https://video.twimg.com/ext_tw_video/121464077...,https://t.co/iKS8nG7Gup
26,"""1214242743427444736""","""1214239902704947200""",https://video.twimg.com/amplify_video/12142399...,https://t.co/vjvFyFIHo1
27,"""1213956785951907840""","""1213956523711455243""",https://video.twimg.com/amplify_video/12139565...,https://t.co/4Wpl1NfUxc
28,"""1213203414169145349""","""1213198222254100480""",https://video.twimg.com/amplify_video/12131982...,https://t.co/rKfajKSJD7
29,"""1212417195894026241""","""1212417091611049986""",https://video.twimg.com/ext_tw_video/121241709...,https://t.co/qOQcreOtV2
30,"""1212161513739431938""","""1209180509529657345""",https://video.twimg.com/amplify_video/12091805...,https://t.co/MiBvCTGPnI
31,"""1212156518193340416""","""1212148668519899138""",https://video.twimg.com/amplify_video/12121486...,https://t.co/XKECtdnAVY
32,"""1212064658162626560""","""1212062923444674566""",https://video.twimg.com/amplify_video/12120629...,https://t.co/N94vrZzEVQ
33,"""1211967698017685504""","""1211966462178549760""",https://video.twimg.com/amplify_video/12119664...,https://t.co/XvCMXvFTyD
34,"""1211733713534488577""","""1211728216391659520""",https://video.twimg.com/amplify_video/12117282...,https://t.co/xLOBk6ytCO
35,"""1211670558712254464""","""1211670522506952705""",https://video.twimg.com/tweet_video/ENC366bWwA...,https://t.co/ui7ypAQQYZ
36,"""1211484552281174016""","""1209266849818587136""",https://video.twimg.com/amplify_video/12092668...,https://t.co/vKC1A5V4zG
37,"""1211331041824268289""","""1208932497645559810""",https://video.twimg.com/amplify_video/12089324...,https://t.co/Vkx9a2YLri
38,"""1210606265891610624""","""1208922327263653890""",https://video.twimg.com/amplify_video/12089223...,https://t.co/hU6JmUKUBR
39,"""1210530767518027777""","""1209267472479719424""",https://video.twimg.com/amplify_video/12092674...,https://t.co/vOh7hsnIcF
40,"""1209813609083219969""","""1209813590737408000""",https://video.twimg.com/tweet_video/EMofDQhX0A...,https://t.co/odNnBnkYdI
41,"""1209494899835449345""","""1209494841849200640""",https://video.twimg.com/tweet_video/EMj9JoYWwA...,https://t.co/fk2zcaPHgg
42,"""1209418468354875397""","""1209418448851353601""",https://video.twimg.com/tweet_video/EMi3q-SWwA...,https://t.co/1eZy79nuM4
43,"""1209300177749729281""","""1209297869292867585""",https://video.twimg.com/amplify_video/12092978...,https://t.co/LUhRHLdVB7
44,"""1208109845519511553""","""1208107829682462720""",https://video.twimg.com/amplify_video/12081078...,https://t.co/mDiQvvgbFh
45,"""1208067504549093376""","""1208067474861821953""",https://video.twimg.com/tweet_video/EMPq97_XkA...,https://t.co/ZLcRbtiHLM
46,"""1208051460853907462""","""1208051192691142657""",https://video.twimg.com/amplify_video/12080511...,https://t.co/lErRkzUyRz
47,"""1208000976336150528""","""1207996240966934528""",https://video.twimg.com/tweet_video/EMOqLlDXYA...,https://t.co/htfS3nSQMI
48,"""1207858943923490816""","""1207858674640805888""",https://video.twimg.com/amplify_video/12078586...,https://t.co/oz63enLQkq
49,"""1207844738663100416""","""1207844480042389505""",https://video.twimg.com/amplify_video/12078444...,https://t.co/K0WrGCtxnE
50,"""1207709713221201924""","""1207606782643834880""",https://video.twimg.com/amplify_video/12076067...,https://t.co/dOLU2oV4AX
51,"""1207653794462535680""","""1207653745712087040""",https://video.twimg.com/tweet_video/EMJyruzWwA...,https://t.co/0GB3KnhQcR
52,"""1207636302444814336""","""1207636261843935232""",https://video.twimg.com/ext_tw_video/120763626...,https://t.co/yrIbSZi2Ki
53,"""1207636007761465344""","""1207635954586062849""",https://video.twimg.com/ext_tw_video/120763595...,https://t.co/2MYBRc2rrG
54,"""1207382543617712129""","""1207380882430025728""",https://video.twimg.com/amplify_video/12073808...,https://t.co/QsEa8x2vka

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (55, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (55, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                 Tweet Id       Videos
0   "1220134096111919105"  Video added
1   "1219636926078246917"  Video added
2   "1219102178817773568"  Video added
3   "1219084631384850432"  Video added
4   "1218523455878057991"  Video added
5   "1218240366866059264"  Video added
6   "1217529397441249280"  Video added
7   "1217446387702468613"  Video added
8   "1217251432275021830"  Video added
9   "1216721562264457216"  Video added
10  "1216687730471645185"  Video added
11  "1216560248330379266"  Video added
12  "1216525266824110080"  Video added
13  "1216493033278996480"  Video added
14  "1216404474039820290"  Video added
15  "1216042084722868224"  Video added
16  "1216027032640987143"  Video added
17  "1215991774516326401"  Video added
18  "1215921321135214592"  Video added
19  "1215297196876271616"  Video added
20  "1215226745412030465"  Video added
21  "1215035481534160899"  Video added
22  "1215032954973544450"  Video added
23  "1215015381066276865"  Video added
24  "1214763672805036033"  Video added
25  "1214640830570516483"  Video added
26  "1214242743427444736"  Video added
27  "1213956785951907840"  Video added
28  "1213203414169145349"  Video added
29  "1212417195894026241"  Video added
30  "1212161513739431938"  Video added
31  "1212156518193340416"  Video added
32  "1212064658162626560"  Video added
33  "1211967698017685504"  Video added
34  "1211733713534488577"  Video added
35  "1211670558712254464"  Video added
36  "1211484552281174016"  Video added
37  "1211331041824268289"  Video added
38  "1210606265891610624"  Video added
39  "1210530767518027777"  Video added
40  "1209813609083219969"  Video added
41  "1209494899835449345"  Video added
42  "1209418468354875397"  Video added
43  "1209300177749729281"  Video added
44  "1208109845519511553"  Video added
45  "1208067504549093376"  Video added
46  "1208051460853907462"  Video added
47  "1208000976336150528"  Video added
48  "1207858943923490816"  Video added
49  "1207844738663100416"  Video added
50  "1207709713221201924"  Video added
51  "1207653794462535680"  Video added
52  "1207636302444814336"  Video added
53  "1207636007761465344"  Video added
54  "1207382543617712129"  Video added

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1220264933335732226""","""The New York Times""",nytimes,"""The extraordinary meeting of world leaders in...",22,75,[],[],0,0,2020-01-23,08:40:06,NaN,NaN
1,"""1220262461485539330""","""The New York Times""",nytimes,"""Live Updates: Wuhan Railway Station, usually ...",30,45,[@ChuBailiang.],[],0,1,2020-01-23,08:30:16,NaN,NaN
2,"""1220259901609476099""","""The New York Times""",nytimes,"""Pictures of 5 starving lions in a park in Sud...",89,165,[],[],0,0,2020-01-23,08:20:06,NaN,NaN
3,"""1220257379264102401""","""The New York Times""",nytimes,"""Europe morning briefing: Here's what you need...",19,68,[],[],0,0,2020-01-23,08:10:05,NaN,NaN
4,"""1220254899562254336""","""The New York Times""",nytimes,"""A gateway to alpine vacationlands since train...",18,67,[],[],0,0,2020-01-23,08:00:13,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3200,"""1207296498742054913""","""Katie Thomas""",katie_thomas,"""The Trump administration will move ahead with...",44,56,[],[],0,0,2019-12-18,13:48:10,NaN,NaN
3201,"""1207294460767408128""","""The New York Times""",nytimes,"""The battle over impeachment is playing out fr...",42,119,[],[],0,0,2019-12-18,13:40:04,NaN,NaN
3202,"""1207292607988224002""","""The New York Times""",nytimes,"""China is ramping up its ability to spy on its...",1036,1106,[],[],0,0,2019-12-18,13:32:42,NaN,NaN
3203,"""1207289438977613827""","""The New York Times""",nytimes,"""In a victory for Hurricane Harvey victims, a ...",85,215,[],[],0,0,2019-12-18,13:20:07,NaN,NaN
3204,"""1207286899368484866""","""The New York Times""",nytimes,"""Here's a rundown of the highlights worth watc...",50,162,[],[],0,0,2019-12-18,13:10:01,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Organisation"

#Create an Vocation column 
Tweets_df['Vocation'] = "News/Media"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3205, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1220264933335732226""","""The New York Times""",nytimes,22,75,[],[],0,0,2020-01-23,08:40:06,-,-,Organisation,News/Media
1,"""1220262461485539330""","""The New York Times""",nytimes,30,45,[@ChuBailiang.],[],0,1,2020-01-23,08:30:16,-,-,Organisation,News/Media
2,"""1220259901609476099""","""The New York Times""",nytimes,89,165,[],[],0,0,2020-01-23,08:20:06,-,-,Organisation,News/Media
3,"""1220257379264102401""","""The New York Times""",nytimes,19,68,[],[],0,0,2020-01-23,08:10:05,-,-,Organisation,News/Media
4,"""1220254899562254336""","""The New York Times""",nytimes,18,67,[],[],0,0,2020-01-23,08:00:13,-,-,Organisation,News/Media
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3200,"""1207296498742054913""","""Katie Thomas""",katie_thomas,44,56,[],[],0,0,2019-12-18,13:48:10,-,-,Organisation,News/Media
3201,"""1207294460767408128""","""The New York Times""",nytimes,42,119,[],[],0,0,2019-12-18,13:40:04,-,-,Organisation,News/Media
3202,"""1207292607988224002""","""The New York Times""",nytimes,1036,1106,[],[],0,0,2019-12-18,13:32:42,-,-,Organisation,News/Media
3203,"""1207289438977613827""","""The New York Times""",nytimes,85,215,[],[],0,0,2019-12-18,13:20:07,-,-,Organisation,News/Media
3204,"""1207286899368484866""","""The New York Times""",nytimes,50,162,[],[],0,0,2019-12-18,13:10:01,-,-,Organisation,News/Media

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3205, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1220264933335732226""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[],0,75,22,-,-,2020-01-23,08:40:06
"""1220262461485539330""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[@ChuBailiang.],1,45,30,-,-,2020-01-23,08:30:16
"""1220259901609476099""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[],0,165,89,-,-,2020-01-23,08:20:06
"""1220257379264102401""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[],0,68,19,-,-,2020-01-23,08:10:05
"""1220254899562254336""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[],0,67,18,-,-,2020-01-23,08:00:13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""1207296498742054913""","""Katie Thomas""",katie_thomas,Organisation,News/Media,[],0,[],0,56,44,-,-,2019-12-18,13:48:10
"""1207294460767408128""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[],0,119,42,-,-,2019-12-18,13:40:04
"""1207292607988224002""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[],0,1106,1036,-,-,2019-12-18,13:32:42
"""1207289438977613827""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[],0,215,85,-,-,2019-12-18,13:20:07
"""1207286899368484866""","""The New York Times""",nytimes,Organisation,News/Media,[],0,[],0,162,50,-,-,2019-12-18,13:10:01

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/NYTimes_df.csv')