##### ===================================================================================================================

#  Oprah Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/OprahTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220191949010980865""",https://twitter.com/oprah/status/1220191949010...,2020-01-23 03:50:05,"""My conversation with @amyschumer this past Sa...",Tweet,Twitter Web App,62,688,"""19397785""","""Oprah Winfrey""",oprah,Verified,https://twitter.com/oprah,Not Protected
1,"""1219620561086631937""",https://twitter.com/oprahsbookclub/status/1219...,2020-01-21 13:59:35,"""Our next book club selection is “American Dir...",Retweet,Twitter for iPhone,134,803,"""1174003243287859200""","""Oprah's Book Club""",oprahsbookclub,Verified,https://twitter.com/oprahsbookclub,Not Protected
2,"""1219618754742693888""",https://twitter.com/cbsthismorning/status/1219...,2020-01-21 13:52:25,"""Best-selling author @jeaninecummins joins @Op...",Retweet,SnapStream TV Search,103,491,"""17134268""","""CBS This Morning""",cbsthismorning,Verified,https://twitter.com/cbsthismorning,Not Protected
3,"""1219618533421854720""",https://twitter.com/oprah/status/1219618533421...,2020-01-21 13:51:32,"""Grab yourself a copy here: https://t.co/oEsW1...",Reply,Twitter for iPhone,26,297,"""19397785""","""Oprah Winfrey""",oprah,Verified,https://twitter.com/oprah,Not Protected
4,"""1219618257411493890""",https://twitter.com/oprah/status/1219618257411...,2020-01-21 13:50:26,"""Like so many of us, I’ve read newspaper artic...",Reply,Twitter for iPhone,58,575,"""19397785""","""Oprah Winfrey""",oprah,Verified,https://twitter.com/oprah,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""518578434994606081""",https://twitter.com/sixbrownchicks/status/5185...,2014-10-05 01:48:28,"""This isn't reality tv. It's transformation. #...",Retweet,Hootsuite,137,240,"""243328891""","""SixBrownChicks""",sixbrownchicks,Non-Verified,https://twitter.com/sixbrownchicks,Not Protected
3196,"""518577756893093888""",https://twitter.com/oprah/status/5185777568930...,2014-10-05 01:45:46,"""@JuneRochelle1 @IyanlaVanzant agree ""Priceles...",Reply,Twitter for iPad,94,8,"""19397785""","""Oprah Winfrey""",oprah,Verified,https://twitter.com/oprah,Not Protected
3197,"""518577724835627008""",https://twitter.com/go__within/status/51857772...,2014-10-05 01:45:38,"""@Oprah @IyanlaVanzant #FixMyLife Wow to see a...",Retweet,Twitter for iPhone,106,129,"""2471772473""","""Go Within""",go__within,Non-Verified,https://twitter.com/go__within,Not Protected
3198,"""518576853389680640""",https://twitter.com/oprah/status/5185768533896...,2014-10-05 01:42:11,"""A Lot of men never transformed from boyhood t...",Tweet,Twitter for iPad,1447,1423,"""19397785""","""Oprah Winfrey""",oprah,Verified,https://twitter.com/oprah,Not Protected
3199,"""518575913580392449""",https://twitter.com/oprah/status/5185759135803...,2014-10-05 01:38:27,""".@IyanlaVanzant just spoke the heart of aba...",Tweet,Twitter for iPad,238,376,"""19397785""","""Oprah Winfrey""",oprah,Verified,https://twitter.com/oprah,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1220191949010980865""","""Oprah Winfrey""",oprah,"""My conversation with @amyschumer this past Sa...",62,688,2020-01-23 03:50:05
1,"""1219620561086631937""","""Oprah's Book Club""",oprahsbookclub,"""Our next book club selection is “American Dir...",134,803,2020-01-21 13:59:35
2,"""1219618754742693888""","""CBS This Morning""",cbsthismorning,"""Best-selling author @jeaninecummins joins @Op...",103,491,2020-01-21 13:52:25
3,"""1219618533421854720""","""Oprah Winfrey""",oprah,"""Grab yourself a copy here: https://t.co/oEsW1...",26,297,2020-01-21 13:51:32
4,"""1219618257411493890""","""Oprah Winfrey""",oprah,"""Like so many of us, I’ve read newspaper artic...",58,575,2020-01-21 13:50:26

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1220191949010980865""","""Oprah Winfrey""",oprah,"""My conversation with @amyschumer this past Sa...",62,688,2020-01-23 03:50:05,[@amyschumer],[#Oprahs2020VisionTour],1,1
1,"""1219620561086631937""","""Oprah's Book Club""",oprahsbookclub,"""Our next book club selection is “American Dir...",134,803,2020-01-21 13:59:35,"[@jeaninecummins., @applebooks, @Flatironbooks...","[#ReadWithUs:, #AmericanDirt]",2,4
2,"""1219618754742693888""","""CBS This Morning""",cbsthismorning,"""Best-selling author @jeaninecummins joins @Op...",103,491,2020-01-21 13:52:25,"[@jeaninecummins, @Oprah, @CBSThisMorning, @op...",[#ReadWithUs],1,4
3,"""1219618533421854720""","""Oprah Winfrey""",oprah,"""Grab yourself a copy here: https://t.co/oEsW1...",26,297,2020-01-21 13:51:32,[@oprahsbookclub],"[#ReadWithUs""]",1,1
4,"""1219618257411493890""","""Oprah Winfrey""",oprah,"""Like so many of us, I’ve read newspaper artic...",58,575,2020-01-21 13:50:26,[],[],0,0
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""518578434994606081""","""SixBrownChicks""",sixbrownchicks,"""This isn't reality tv. It's transformation. #...",137,240,2014-10-05 01:48:28,"[@Oprah, @IyanlaVanzant, @OWN]",[#FixMyLife],1,3
3196,"""518577756893093888""","""Oprah Winfrey""",oprah,"""@JuneRochelle1 @IyanlaVanzant agree ""Priceles...",94,8,2014-10-05 01:45:46,"[@JuneRochelle1, @IyanlaVanzant]",[],0,2
3197,"""518577724835627008""","""Go Within""",go__within,"""@Oprah @IyanlaVanzant #FixMyLife Wow to see a...",106,129,2014-10-05 01:45:38,"[@Oprah, @IyanlaVanzant]","[#FixMyLife, #love""]",2,2
3198,"""518576853389680640""","""Oprah Winfrey""",oprah,"""A Lot of men never transformed from boyhood t...",1447,1423,2014-10-05 01:42:11,[],"[#FixMyLife""]",1,0
3199,"""518575913580392449""","""Oprah Winfrey""",oprah,""".@IyanlaVanzant just spoke the heart of aba...",238,376,2014-10-05 01:38:27,[@IyanlaVanzant],"[#FixMyLife""]",1,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1220191949010980865""","""Oprah Winfrey""",oprah,"""My conversation with @amyschumer this past Sa...",62,688,[@amyschumer],[#Oprahs2020VisionTour],1,1,2020-01-23,03:50:05
1,"""1219620561086631937""","""Oprah's Book Club""",oprahsbookclub,"""Our next book club selection is “American Dir...",134,803,"[@jeaninecummins., @applebooks, @Flatironbooks...","[#ReadWithUs:, #AmericanDirt]",2,4,2020-01-21,13:59:35
2,"""1219618754742693888""","""CBS This Morning""",cbsthismorning,"""Best-selling author @jeaninecummins joins @Op...",103,491,"[@jeaninecummins, @Oprah, @CBSThisMorning, @op...",[#ReadWithUs],1,4,2020-01-21,13:52:25
3,"""1219618533421854720""","""Oprah Winfrey""",oprah,"""Grab yourself a copy here: https://t.co/oEsW1...",26,297,[@oprahsbookclub],"[#ReadWithUs""]",1,1,2020-01-21,13:51:32
4,"""1219618257411493890""","""Oprah Winfrey""",oprah,"""Like so many of us, I’ve read newspaper artic...",58,575,[],[],0,0,2020-01-21,13:50:26
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""518578434994606081""","""SixBrownChicks""",sixbrownchicks,"""This isn't reality tv. It's transformation. #...",137,240,"[@Oprah, @IyanlaVanzant, @OWN]",[#FixMyLife],1,3,2014-10-05,01:48:28
3196,"""518577756893093888""","""Oprah Winfrey""",oprah,"""@JuneRochelle1 @IyanlaVanzant agree ""Priceles...",94,8,"[@JuneRochelle1, @IyanlaVanzant]",[],0,2,2014-10-05,01:45:46
3197,"""518577724835627008""","""Go Within""",go__within,"""@Oprah @IyanlaVanzant #FixMyLife Wow to see a...",106,129,"[@Oprah, @IyanlaVanzant]","[#FixMyLife, #love""]",2,2,2014-10-05,01:45:38
3198,"""518576853389680640""","""Oprah Winfrey""",oprah,"""A Lot of men never transformed from boyhood t...",1447,1423,[],"[#FixMyLife""]",1,0,2014-10-05,01:42:11
3199,"""518575913580392449""","""Oprah Winfrey""",oprah,""".@IyanlaVanzant just spoke the heart of aba...",238,376,[@IyanlaVanzant],"[#FixMyLife""]",1,1,2014-10-05,01:38:27

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/OprahImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1219618182417260546""","""1219618176906027008""",https://pbs.twimg.com/media/EOz0RSQX4AAm4BQ.jpg,https://t.co/uonqIa3QRK
1,"""1216847081094041601""","""1216847077231058944""",https://pbs.twimg.com/media/EOMb-DhUYAAu4PW.jpg,https://t.co/CKoTa5ysh1
2,"""1203346725697736704""","""1203346719875973121""",https://pbs.twimg.com/media/ELMld1PWwAE-WAP.jpg,https://t.co/En4t40bCy3
3,"""1192660207517732865""","""1192660188316209153""",https://pbs.twimg.com/media/EI0uH05WkAEY7qr.jpg,https://t.co/kGCl25FVEH
4,"""1192437784239325184""","""1192437779373928448""",https://pbs.twimg.com/media/EIxj17BWsAATORI.jpg,https://t.co/o02z1XKFuE
...,...,...,...,...
297,"""529841625695285248""","""529841625456185344""",https://pbs.twimg.com/media/B1pgJrCIEAAx_VU.jpg,http://t.co/N3CiUF3IEa
298,"""524292582621184001""","""524292574895304704""",https://pbs.twimg.com/media/B0apUa0CcAAGR06.jpg,http://t.co/XhiSQIKtJz
299,"""523333455472779264""","""523333450066325504""",https://pbs.twimg.com/media/B0NBAAZIcAA7pTf.jpg,http://t.co/iJP06dXePu
300,"""521740001088774145""","""521739998828052480""",https://pbs.twimg.com/media/Bz2Xw79CQAAGjqH.jpg,http://t.co/YWKnXPEhLX
301,"""521712942975160320""","""521712941712683008""",https://pbs.twimg.com/media/Bz1_KAWCMAAKXhF.jpg,http://t.co/BP3qA0E0eT

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (302, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (302, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1219618182417260546"  Image added
1    "1216847081094041601"  Image added
2    "1203346725697736704"  Image added
3    "1192660207517732865"  Image added
4    "1192437784239325184"  Image added
..                     ...          ...
297   "529841625695285248"  Image added
298   "524292582621184001"  Image added
299   "523333455472779264"  Image added
300   "521740001088774145"  Image added
301   "521712942975160320"  Image added

[302 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1220191949010980865""","""Oprah Winfrey""",oprah,"""My conversation with @amyschumer this past Sa...",62,688,[@amyschumer],[#Oprahs2020VisionTour],1,1,2020-01-23,03:50:05,NaN
1,"""1219620561086631937""","""Oprah's Book Club""",oprahsbookclub,"""Our next book club selection is “American Dir...",134,803,"[@jeaninecummins., @applebooks, @Flatironbooks...","[#ReadWithUs:, #AmericanDirt]",2,4,2020-01-21,13:59:35,NaN
2,"""1219618754742693888""","""CBS This Morning""",cbsthismorning,"""Best-selling author @jeaninecummins joins @Op...",103,491,"[@jeaninecummins, @Oprah, @CBSThisMorning, @op...",[#ReadWithUs],1,4,2020-01-21,13:52:25,NaN
3,"""1219618533421854720""","""Oprah Winfrey""",oprah,"""Grab yourself a copy here: https://t.co/oEsW1...",26,297,[@oprahsbookclub],"[#ReadWithUs""]",1,1,2020-01-21,13:51:32,NaN
4,"""1219618257411493890""","""Oprah Winfrey""",oprah,"""Like so many of us, I’ve read newspaper artic...",58,575,[],[],0,0,2020-01-21,13:50:26,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3224,"""518578434994606081""","""SixBrownChicks""",sixbrownchicks,"""This isn't reality tv. It's transformation. #...",137,240,"[@Oprah, @IyanlaVanzant, @OWN]",[#FixMyLife],1,3,2014-10-05,01:48:28,NaN
3225,"""518577756893093888""","""Oprah Winfrey""",oprah,"""@JuneRochelle1 @IyanlaVanzant agree ""Priceles...",94,8,"[@JuneRochelle1, @IyanlaVanzant]",[],0,2,2014-10-05,01:45:46,NaN
3226,"""518577724835627008""","""Go Within""",go__within,"""@Oprah @IyanlaVanzant #FixMyLife Wow to see a...",106,129,"[@Oprah, @IyanlaVanzant]","[#FixMyLife, #love""]",2,2,2014-10-05,01:45:38,NaN
3227,"""518576853389680640""","""Oprah Winfrey""",oprah,"""A Lot of men never transformed from boyhood t...",1447,1423,[],"[#FixMyLife""]",1,0,2014-10-05,01:42:11,NaN
3228,"""518575913580392449""","""Oprah Winfrey""",oprah,""".@IyanlaVanzant just spoke the heart of aba...",238,376,[@IyanlaVanzant],"[#FixMyLife""]",1,1,2014-10-05,01:38:27,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/OprahVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220191949010980865""","""1220191667216580608""",https://video.twimg.com/ext_tw_video/122019166...,https://t.co/F4arVr2ywQ
1,"""1219620561086631937""","""1219620244873826305""",https://video.twimg.com/ext_tw_video/121962024...,https://t.co/v6K23tEyPM
2,"""1219618754742693888""","""1219618628921892864""",https://video.twimg.com/amplify_video/12196186...,https://t.co/lesnvzUYnR
3,"""1219039749014507520""","""1219039599214972928""",https://video.twimg.com/ext_tw_video/121903959...,https://t.co/7bpfrr8gpj
4,"""1218927057268281344""","""1218926930428407809""",https://video.twimg.com/ext_tw_video/121892693...,https://t.co/4IkZX28oZm
...,...,...,...,...
270,"""733099241548054528""","""733099191480651777""",https://video.twimg.com/tweet_video/Cix91J1UkA...,https://t.co/Lrw5gc22zr
271,"""655791854756040704""","""655791759679590400""",https://video.twimg.com/ext_tw_video/655791759...,http://t.co/eCUXN0O2Sg
272,"""654419863952314368""","""654419811292827648""",https://video.twimg.com/ext_tw_video/654419811...,http://t.co/idB3qBT9M5
273,"""642814680642129921""","""642814556314562561""",https://video.twimg.com/ext_tw_video/642814556...,http://t.co/xZfcOKnWHV
274,"""570648067428511744""","""570648023182610432""",https://video.twimg.com/ext_tw_video/570648023...,http://t.co/ixW1Dxx9iz

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (275, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (275, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1220191949010980865"  Video added
1    "1219620561086631937"  Video added
2    "1219618754742693888"  Video added
3    "1219039749014507520"  Video added
4    "1218927057268281344"  Video added
..                     ...          ...
270   "733099241548054528"  Video added
271   "655791854756040704"  Video added
272   "654419863952314368"  Video added
273   "642814680642129921"  Video added
274   "570648067428511744"  Video added

[275 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1220191949010980865""","""Oprah Winfrey""",oprah,"""My conversation with @amyschumer this past Sa...",62,688,[@amyschumer],[#Oprahs2020VisionTour],1,1,2020-01-23,03:50:05,NaN,Video added
1,"""1219620561086631937""","""Oprah's Book Club""",oprahsbookclub,"""Our next book club selection is “American Dir...",134,803,"[@jeaninecummins., @applebooks, @Flatironbooks...","[#ReadWithUs:, #AmericanDirt]",2,4,2020-01-21,13:59:35,NaN,Video added
2,"""1219618754742693888""","""CBS This Morning""",cbsthismorning,"""Best-selling author @jeaninecummins joins @Op...",103,491,"[@jeaninecummins, @Oprah, @CBSThisMorning, @op...",[#ReadWithUs],1,4,2020-01-21,13:52:25,NaN,Video added
3,"""1219618533421854720""","""Oprah Winfrey""",oprah,"""Grab yourself a copy here: https://t.co/oEsW1...",26,297,[@oprahsbookclub],"[#ReadWithUs""]",1,1,2020-01-21,13:51:32,NaN,NaN
4,"""1219618257411493890""","""Oprah Winfrey""",oprah,"""Like so many of us, I’ve read newspaper artic...",58,575,[],[],0,0,2020-01-21,13:50:26,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3224,"""518578434994606081""","""SixBrownChicks""",sixbrownchicks,"""This isn't reality tv. It's transformation. #...",137,240,"[@Oprah, @IyanlaVanzant, @OWN]",[#FixMyLife],1,3,2014-10-05,01:48:28,NaN,NaN
3225,"""518577756893093888""","""Oprah Winfrey""",oprah,"""@JuneRochelle1 @IyanlaVanzant agree ""Priceles...",94,8,"[@JuneRochelle1, @IyanlaVanzant]",[],0,2,2014-10-05,01:45:46,NaN,NaN
3226,"""518577724835627008""","""Go Within""",go__within,"""@Oprah @IyanlaVanzant #FixMyLife Wow to see a...",106,129,"[@Oprah, @IyanlaVanzant]","[#FixMyLife, #love""]",2,2,2014-10-05,01:45:38,NaN,NaN
3227,"""518576853389680640""","""Oprah Winfrey""",oprah,"""A Lot of men never transformed from boyhood t...",1447,1423,[],"[#FixMyLife""]",1,0,2014-10-05,01:42:11,NaN,NaN
3228,"""518575913580392449""","""Oprah Winfrey""",oprah,""".@IyanlaVanzant just spoke the heart of aba...",238,376,[@IyanlaVanzant],"[#FixMyLife""]",1,1,2014-10-05,01:38:27,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Female"

#Create an Vocation column 
Tweets_df['Vocation'] = "Entertainment"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3229, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1220191949010980865""","""Oprah Winfrey""",oprah,62,688,[@amyschumer],[#Oprahs2020VisionTour],1,1,2020-01-23,03:50:05,-,Video added,Female,Entertainment
1,"""1219620561086631937""","""Oprah's Book Club""",oprahsbookclub,134,803,"[@jeaninecummins., @applebooks, @Flatironbooks...","[#ReadWithUs:, #AmericanDirt]",2,4,2020-01-21,13:59:35,-,Video added,Female,Entertainment
2,"""1219618754742693888""","""CBS This Morning""",cbsthismorning,103,491,"[@jeaninecummins, @Oprah, @CBSThisMorning, @op...",[#ReadWithUs],1,4,2020-01-21,13:52:25,-,Video added,Female,Entertainment
3,"""1219618533421854720""","""Oprah Winfrey""",oprah,26,297,[@oprahsbookclub],"[#ReadWithUs""]",1,1,2020-01-21,13:51:32,-,-,Female,Entertainment
4,"""1219618257411493890""","""Oprah Winfrey""",oprah,58,575,[],[],0,0,2020-01-21,13:50:26,-,-,Female,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3224,"""518578434994606081""","""SixBrownChicks""",sixbrownchicks,137,240,"[@Oprah, @IyanlaVanzant, @OWN]",[#FixMyLife],1,3,2014-10-05,01:48:28,-,-,Female,Entertainment
3225,"""518577756893093888""","""Oprah Winfrey""",oprah,94,8,"[@JuneRochelle1, @IyanlaVanzant]",[],0,2,2014-10-05,01:45:46,-,-,Female,Entertainment
3226,"""518577724835627008""","""Go Within""",go__within,106,129,"[@Oprah, @IyanlaVanzant]","[#FixMyLife, #love""]",2,2,2014-10-05,01:45:38,-,-,Female,Entertainment
3227,"""518576853389680640""","""Oprah Winfrey""",oprah,1447,1423,[],"[#FixMyLife""]",1,0,2014-10-05,01:42:11,-,-,Female,Entertainment
3228,"""518575913580392449""","""Oprah Winfrey""",oprah,238,376,[@IyanlaVanzant],"[#FixMyLife""]",1,1,2014-10-05,01:38:27,-,-,Female,Entertainment

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3229, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1220191949010980865""","""Oprah Winfrey""",oprah,Female,Entertainment,[#Oprahs2020VisionTour],1,[@amyschumer],1,688,62,-,Video added,2020-01-23,03:50:05
"""1219620561086631937""","""Oprah's Book Club""",oprahsbookclub,Female,Entertainment,"[#ReadWithUs:, #AmericanDirt]",2,"[@jeaninecummins., @applebooks, @Flatironbooks...",4,803,134,-,Video added,2020-01-21,13:59:35
"""1219618754742693888""","""CBS This Morning""",cbsthismorning,Female,Entertainment,[#ReadWithUs],1,"[@jeaninecummins, @Oprah, @CBSThisMorning, @op...",4,491,103,-,Video added,2020-01-21,13:52:25
"""1219618533421854720""","""Oprah Winfrey""",oprah,Female,Entertainment,"[#ReadWithUs""]",1,[@oprahsbookclub],1,297,26,-,-,2020-01-21,13:51:32
"""1219618257411493890""","""Oprah Winfrey""",oprah,Female,Entertainment,[],0,[],0,575,58,-,-,2020-01-21,13:50:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""518578434994606081""","""SixBrownChicks""",sixbrownchicks,Female,Entertainment,[#FixMyLife],1,"[@Oprah, @IyanlaVanzant, @OWN]",3,240,137,-,-,2014-10-05,01:48:28
"""518577756893093888""","""Oprah Winfrey""",oprah,Female,Entertainment,[],0,"[@JuneRochelle1, @IyanlaVanzant]",2,8,94,-,-,2014-10-05,01:45:46
"""518577724835627008""","""Go Within""",go__within,Female,Entertainment,"[#FixMyLife, #love""]",2,"[@Oprah, @IyanlaVanzant]",2,129,106,-,-,2014-10-05,01:45:38
"""518576853389680640""","""Oprah Winfrey""",oprah,Female,Entertainment,"[#FixMyLife""]",1,[],0,1423,1447,-,-,2014-10-05,01:42:11
"""518575913580392449""","""Oprah Winfrey""",oprah,Female,Entertainment,"[#FixMyLife""]",1,[@IyanlaVanzant],1,376,238,-,-,2014-10-05,01:38:27

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/Oprah_df.csv')