##### ===================================================================================================================

#  Pink Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/PinkTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1219660451614617606""",https://twitter.com/pink/status/12196604516146...,2020-01-21 16:38:06,"""Willz is becoming quite the baker üòçüòçüòç https:/...",Tweet,Twitter for iPhone,242,12076,"""28706024""","""P!nk""",pink,Verified,https://twitter.com/pink,Not Protected
1,"""1219521150390128640""",https://twitter.com/pink/status/12195211503901...,2020-01-21 07:24:34,"""This was so fun to watch for real thanks @bil...",Tweet,Twitter for iPhone,2790,25811,"""28706024""","""P!nk""",pink,Verified,https://twitter.com/pink,Not Protected
2,"""1219517598317985792""",https://twitter.com/pink/status/12195175983179...,2020-01-21 07:10:27,"""Do you mean promising NOT TO? https://t.co/rb...",Tweet,Twitter for iPhone,530,11140,"""28706024""","""P!nk""",pink,Verified,https://twitter.com/pink,Not Protected
3,"""1219517497495310336""",https://twitter.com/pink/status/12195174974953...,2020-01-21 07:10:03,"""Deal! https://t.co/0MT2eFt1zR""",Tweet,Twitter for iPhone,215,7175,"""28706024""","""P!nk""",pink,Verified,https://twitter.com/pink,Not Protected
4,"""1219133489770942464""",https://twitter.com/pink/status/12191334897709...,2020-01-20 05:44:09,"""I‚Äôm fortunate because I‚Äôve never really depen...",Tweet,Twitter for iPhone,3614,75095,"""28706024""","""P!nk""",pink,Verified,https://twitter.com/pink,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""324589537659600896""",https://twitter.com/pink/status/32458953765960...,2013-04-17 18:25:51,"""‚Äú@PinkFans_: @Pink I would offer a congratula...",Reply,Twitter for iPhone,193,276,"""28706024""","""P!nk""",pink,Verified,https://twitter.com/pink,Not Protected
3196,"""324588230307622912""",https://twitter.com/pink/status/32458823030762...,2013-04-17 18:20:39,"""Ha!!!!! Mama just got a Billboard Hot 100 #1!...",Tweet,Twitter for iPhone,2223,2407,"""28706024""","""P!nk""",pink,Verified,https://twitter.com/pink,Not Protected
3197,"""324286143594110977""",https://twitter.com/huffpostparents/status/324...,2013-04-16 22:20:16,"""How the explosions at the Boston Marathon cha...",Retweet,The Huffington Post,510,203,"""16581734""","""HuffPost Parents""",huffpostparents,Verified,https://twitter.com/huffpostparents,Not Protected
3198,"""324179337496625152""",https://twitter.com/pink/status/32417933749662...,2013-04-16 15:15:51,"""Congrats to @butchwalker for your Top 10 song...",Tweet,Twitter for iPhone,637,737,"""28706024""","""P!nk""",pink,Verified,https://twitter.com/pink,Not Protected
3199,"""324144354065264640""",https://twitter.com/caketin85/status/324144354...,2013-04-16 12:56:50,"""Patton Oswalt Responds To The Boston Marathon...",Retweet,Hootsuite,327,164,"""18933433""","""Caitlin Flint""",caketin85,Non-Verified,https://twitter.com/caketin85,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1219660451614617606""","""P!nk""",pink,"""Willz is becoming quite the baker üòçüòçüòç https:/...",242,12076,2020-01-21 16:38:06
1,"""1219521150390128640""","""P!nk""",pink,"""This was so fun to watch for real thanks @bil...",2790,25811,2020-01-21 07:24:34
2,"""1219517598317985792""","""P!nk""",pink,"""Do you mean promising NOT TO? https://t.co/rb...",530,11140,2020-01-21 07:10:27
3,"""1219517497495310336""","""P!nk""",pink,"""Deal! https://t.co/0MT2eFt1zR""",215,7175,2020-01-21 07:10:03
4,"""1219133489770942464""","""P!nk""",pink,"""I‚Äôm fortunate because I‚Äôve never really depen...",3614,75095,2020-01-20 05:44:09

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1219660451614617606""","""P!nk""",pink,"""Willz is becoming quite the baker üòçüòçüòç https:/...",242,12076,2020-01-21 16:38:06,[],[],0,0
1,"""1219521150390128640""","""P!nk""",pink,"""This was so fun to watch for real thanks @bil...",2790,25811,2020-01-21 07:24:34,[@billboard],[],0,1
2,"""1219517598317985792""","""P!nk""",pink,"""Do you mean promising NOT TO? https://t.co/rb...",530,11140,2020-01-21 07:10:27,[],[],0,0
3,"""1219517497495310336""","""P!nk""",pink,"""Deal! https://t.co/0MT2eFt1zR""",215,7175,2020-01-21 07:10:03,[],[],0,0
4,"""1219133489770942464""","""P!nk""",pink,"""I‚Äôm fortunate because I‚Äôve never really depen...",3614,75095,2020-01-20 05:44:09,[],[],0,0
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""324589537659600896""","""P!nk""",pink,"""‚Äú@PinkFans_: @Pink I would offer a congratula...",193,276,2013-04-17 18:25:51,"[@PinkFans_:, @Pink]",[],0,2
3196,"""324588230307622912""","""P!nk""",pink,"""Ha!!!!! Mama just got a Billboard Hot 100 #1!...",2223,2407,2013-04-17 18:20:39,[],[#1!!!!!!!!!!!!],1,0
3197,"""324286143594110977""","""HuffPost Parents""",huffpostparents,"""How the explosions at the Boston Marathon cha...",510,203,2013-04-16 22:20:16,[@drClaire],[],0,1
3198,"""324179337496625152""","""P!nk""",pink,"""Congrats to @butchwalker for your Top 10 song...",637,737,2013-04-16 15:15:51,[@butchwalker],[#1],1,1
3199,"""324144354065264640""","""Caitlin Flint""",caketin85,"""Patton Oswalt Responds To The Boston Marathon...",327,164,2013-04-16 12:56:50,[@hellogiggles],[],0,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1219660451614617606""","""P!nk""",pink,"""Willz is becoming quite the baker üòçüòçüòç https:/...",242,12076,[],[],0,0,2020-01-21,16:38:06
1,"""1219521150390128640""","""P!nk""",pink,"""This was so fun to watch for real thanks @bil...",2790,25811,[@billboard],[],0,1,2020-01-21,07:24:34
2,"""1219517598317985792""","""P!nk""",pink,"""Do you mean promising NOT TO? https://t.co/rb...",530,11140,[],[],0,0,2020-01-21,07:10:27
3,"""1219517497495310336""","""P!nk""",pink,"""Deal! https://t.co/0MT2eFt1zR""",215,7175,[],[],0,0,2020-01-21,07:10:03
4,"""1219133489770942464""","""P!nk""",pink,"""I‚Äôm fortunate because I‚Äôve never really depen...",3614,75095,[],[],0,0,2020-01-20,05:44:09
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""324589537659600896""","""P!nk""",pink,"""‚Äú@PinkFans_: @Pink I would offer a congratula...",193,276,"[@PinkFans_:, @Pink]",[],0,2,2013-04-17,18:25:51
3196,"""324588230307622912""","""P!nk""",pink,"""Ha!!!!! Mama just got a Billboard Hot 100 #1!...",2223,2407,[],[#1!!!!!!!!!!!!],1,0,2013-04-17,18:20:39
3197,"""324286143594110977""","""HuffPost Parents""",huffpostparents,"""How the explosions at the Boston Marathon cha...",510,203,[@drClaire],[],0,1,2013-04-16,22:20:16
3198,"""324179337496625152""","""P!nk""",pink,"""Congrats to @butchwalker for your Top 10 song...",637,737,[@butchwalker],[#1],1,1,2013-04-16,15:15:51
3199,"""324144354065264640""","""Caitlin Flint""",caketin85,"""Patton Oswalt Responds To The Boston Marathon...",327,164,[@hellogiggles],[],0,1,2013-04-16,12:56:50

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/PinkImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1219660451614617606""","""1219660445797060608""",https://pbs.twimg.com/media/EO0atqJUEAAaFV6.jpg,https://t.co/6cMZuiGUBM
1,"""1218957039562448896""","""1218956936038600705""",https://pbs.twimg.com/media/EOqa4AEUUAEZ-Tn.jpg,https://t.co/oEl0JfRHAB
2,"""1218957039562448896""","""1218956936105713664""",https://pbs.twimg.com/media/EOqa4AUUYAADGbR.jpg,https://t.co/oEl0JfRHAB
3,"""1218957039562448896""","""1218956936088961024""",https://pbs.twimg.com/media/EOqa4AQUwAAejZj.jpg,https://t.co/oEl0JfRHAB
4,"""1215480742509105152""","""1215480739417882625""",https://pbs.twimg.com/media/EN5BSuhVAAEKSVf.jpg,https://t.co/3zYgU7fcKA
...,...,...,...,...
525,"""330800539136819200""","""330800539141013506""",https://pbs.twimg.com/media/BJc9VnMCAAI7GSX.jpg,http://t.co/o4cKaJ1VKS
526,"""330800488104751104""","""330800488108945408""",https://pbs.twimg.com/media/BJc9SpFCcAAn-gZ.jpg,http://t.co/fREJUhO5aE
527,"""330800448523083777""","""330800448531472384""",https://pbs.twimg.com/media/BJc9QVpCIAA1Sab.jpg,http://t.co/2qO5m3jaYf
528,"""329668376450433024""","""329658606544883712""",https://pbs.twimg.com/media/BJMuwYxCEAADrQP.jpg,http://t.co/8N5P0bZtYX
529,"""324847811269111808""","""324847811277500417""",https://pbs.twimg.com/media/BIIXXP1CMAE2fiI.jpg,http://t.co/mLS2huQVfh

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (530, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (530, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1219660451614617606"  Image added
1    "1218957039562448896"  Image added
2    "1218957039562448896"  Image added
3    "1218957039562448896"  Image added
4    "1215480742509105152"  Image added
..                     ...          ...
525   "330800539136819200"  Image added
526   "330800488104751104"  Image added
527   "330800448523083777"  Image added
528   "329668376450433024"  Image added
529   "324847811269111808"  Image added

[530 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1219660451614617606""","""P!nk""",pink,"""Willz is becoming quite the baker üòçüòçüòç https:/...",242,12076,[],[],0,0,2020-01-21,16:38:06,Image added
1,"""1219521150390128640""","""P!nk""",pink,"""This was so fun to watch for real thanks @bil...",2790,25811,[@billboard],[],0,1,2020-01-21,07:24:34,NaN
2,"""1219517598317985792""","""P!nk""",pink,"""Do you mean promising NOT TO? https://t.co/rb...",530,11140,[],[],0,0,2020-01-21,07:10:27,NaN
3,"""1219517497495310336""","""P!nk""",pink,"""Deal! https://t.co/0MT2eFt1zR""",215,7175,[],[],0,0,2020-01-21,07:10:03,NaN
4,"""1219133489770942464""","""P!nk""",pink,"""I‚Äôm fortunate because I‚Äôve never really depen...",3614,75095,[],[],0,0,2020-01-20,05:44:09,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3209,"""324589537659600896""","""P!nk""",pink,"""‚Äú@PinkFans_: @Pink I would offer a congratula...",193,276,"[@PinkFans_:, @Pink]",[],0,2,2013-04-17,18:25:51,NaN
3210,"""324588230307622912""","""P!nk""",pink,"""Ha!!!!! Mama just got a Billboard Hot 100 #1!...",2223,2407,[],[#1!!!!!!!!!!!!],1,0,2013-04-17,18:20:39,NaN
3211,"""324286143594110977""","""HuffPost Parents""",huffpostparents,"""How the explosions at the Boston Marathon cha...",510,203,[@drClaire],[],0,1,2013-04-16,22:20:16,NaN
3212,"""324179337496625152""","""P!nk""",pink,"""Congrats to @butchwalker for your Top 10 song...",637,737,[@butchwalker],[#1],1,1,2013-04-16,15:15:51,NaN
3213,"""324144354065264640""","""Caitlin Flint""",caketin85,"""Patton Oswalt Responds To The Boston Marathon...",327,164,[@hellogiggles],[],0,1,2013-04-16,12:56:50,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/PinkVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1202086896358309888""","""1202086832462278656""",https://video.twimg.com/ext_tw_video/120208683...,https://t.co/Vqep6TxKXe
1,"""1201903703512367109""","""1201903522947559424""",https://video.twimg.com/ext_tw_video/120190352...,https://t.co/VuakXx3mGy
2,"""1187504161719349250""","""1187504084670017536""",https://video.twimg.com/ext_tw_video/118750408...,https://t.co/jGqz3YPT0H
3,"""1180720426760192000""","""1180703999747477505""",https://video.twimg.com/amplify_video/11807039...,https://t.co/O9QO4axTzv
4,"""1177587325796118529""","""1177587190039076870""",https://video.twimg.com/ext_tw_video/117758719...,https://t.co/ONCe9QpDfI
...,...,...,...,...
100,"""721082204701364224""","""721081980981411840""",https://video.twimg.com/ext_tw_video/721081980...,https://t.co/SahGvdHK1q
101,"""695417625900265479""","""695417594493308928""",https://video.twimg.com/ext_tw_video/695417594...,https://t.co/l1X1VT9Wou
102,"""637137895418040320""","""637137719018131456""",https://video.twimg.com/ext_tw_video/637137719...,http://t.co/STxThh72Gj
103,"""615004811503669248""","""615004345369690112""",https://video.twimg.com/ext_tw_video/615004345...,http://t.co/biSd3bgE99
104,"""598913068337233920""","""598912941610520576""",https://video.twimg.com/ext_tw_video/598912941...,http://t.co/4oLpLuUwpu

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (105, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (105, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1202086896358309888"  Video added
1    "1201903703512367109"  Video added
2    "1187504161719349250"  Video added
3    "1180720426760192000"  Video added
4    "1177587325796118529"  Video added
..                     ...          ...
100   "721082204701364224"  Video added
101   "695417625900265479"  Video added
102   "637137895418040320"  Video added
103   "615004811503669248"  Video added
104   "598913068337233920"  Video added

[105 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1219660451614617606""","""P!nk""",pink,"""Willz is becoming quite the baker üòçüòçüòç https:/...",242,12076,[],[],0,0,2020-01-21,16:38:06,Image added,NaN
1,"""1219521150390128640""","""P!nk""",pink,"""This was so fun to watch for real thanks @bil...",2790,25811,[@billboard],[],0,1,2020-01-21,07:24:34,NaN,NaN
2,"""1219517598317985792""","""P!nk""",pink,"""Do you mean promising NOT TO? https://t.co/rb...",530,11140,[],[],0,0,2020-01-21,07:10:27,NaN,NaN
3,"""1219517497495310336""","""P!nk""",pink,"""Deal! https://t.co/0MT2eFt1zR""",215,7175,[],[],0,0,2020-01-21,07:10:03,NaN,NaN
4,"""1219133489770942464""","""P!nk""",pink,"""I‚Äôm fortunate because I‚Äôve never really depen...",3614,75095,[],[],0,0,2020-01-20,05:44:09,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3209,"""324589537659600896""","""P!nk""",pink,"""‚Äú@PinkFans_: @Pink I would offer a congratula...",193,276,"[@PinkFans_:, @Pink]",[],0,2,2013-04-17,18:25:51,NaN,NaN
3210,"""324588230307622912""","""P!nk""",pink,"""Ha!!!!! Mama just got a Billboard Hot 100 #1!...",2223,2407,[],[#1!!!!!!!!!!!!],1,0,2013-04-17,18:20:39,NaN,NaN
3211,"""324286143594110977""","""HuffPost Parents""",huffpostparents,"""How the explosions at the Boston Marathon cha...",510,203,[@drClaire],[],0,1,2013-04-16,22:20:16,NaN,NaN
3212,"""324179337496625152""","""P!nk""",pink,"""Congrats to @butchwalker for your Top 10 song...",637,737,[@butchwalker],[#1],1,1,2013-04-16,15:15:51,NaN,NaN
3213,"""324144354065264640""","""Caitlin Flint""",caketin85,"""Patton Oswalt Responds To The Boston Marathon...",327,164,[@hellogiggles],[],0,1,2013-04-16,12:56:50,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Female"

#Create an Vocation column 
Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3214, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1219660451614617606""","""P!nk""",pink,242,12076,[],[],0,0,2020-01-21,16:38:06,Image added,-,Female,Music
1,"""1219521150390128640""","""P!nk""",pink,2790,25811,[@billboard],[],0,1,2020-01-21,07:24:34,-,-,Female,Music
2,"""1219517598317985792""","""P!nk""",pink,530,11140,[],[],0,0,2020-01-21,07:10:27,-,-,Female,Music
3,"""1219517497495310336""","""P!nk""",pink,215,7175,[],[],0,0,2020-01-21,07:10:03,-,-,Female,Music
4,"""1219133489770942464""","""P!nk""",pink,3614,75095,[],[],0,0,2020-01-20,05:44:09,-,-,Female,Music
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3209,"""324589537659600896""","""P!nk""",pink,193,276,"[@PinkFans_:, @Pink]",[],0,2,2013-04-17,18:25:51,-,-,Female,Music
3210,"""324588230307622912""","""P!nk""",pink,2223,2407,[],[#1!!!!!!!!!!!!],1,0,2013-04-17,18:20:39,-,-,Female,Music
3211,"""324286143594110977""","""HuffPost Parents""",huffpostparents,510,203,[@drClaire],[],0,1,2013-04-16,22:20:16,-,-,Female,Music
3212,"""324179337496625152""","""P!nk""",pink,637,737,[@butchwalker],[#1],1,1,2013-04-16,15:15:51,-,-,Female,Music
3213,"""324144354065264640""","""Caitlin Flint""",caketin85,327,164,[@hellogiggles],[],0,1,2013-04-16,12:56:50,-,-,Female,Music

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3214, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1219660451614617606""","""P!nk""",pink,Female,Music,[],0,[],0,12076,242,Image added,-,2020-01-21,16:38:06
"""1219521150390128640""","""P!nk""",pink,Female,Music,[],0,[@billboard],1,25811,2790,-,-,2020-01-21,07:24:34
"""1219517598317985792""","""P!nk""",pink,Female,Music,[],0,[],0,11140,530,-,-,2020-01-21,07:10:27
"""1219517497495310336""","""P!nk""",pink,Female,Music,[],0,[],0,7175,215,-,-,2020-01-21,07:10:03
"""1219133489770942464""","""P!nk""",pink,Female,Music,[],0,[],0,75095,3614,-,-,2020-01-20,05:44:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""324589537659600896""","""P!nk""",pink,Female,Music,[],0,"[@PinkFans_:, @Pink]",2,276,193,-,-,2013-04-17,18:25:51
"""324588230307622912""","""P!nk""",pink,Female,Music,[#1!!!!!!!!!!!!],1,[],0,2407,2223,-,-,2013-04-17,18:20:39
"""324286143594110977""","""HuffPost Parents""",huffpostparents,Female,Music,[],0,[@drClaire],1,203,510,-,-,2013-04-16,22:20:16
"""324179337496625152""","""P!nk""",pink,Female,Music,[#1],1,[@butchwalker],1,737,637,-,-,2013-04-16,15:15:51
"""324144354065264640""","""Caitlin Flint""",caketin85,Female,Music,[],0,[@hellogiggles],1,164,327,-,-,2013-04-16,12:56:50

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/Pink_df.csv')