##### ===================================================================================================================

#  Salman Khan Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/SalmanKhanTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1218463651138539520""",https://twitter.com/beingsalmankhan/status/121...,2020-01-18 09:22:27,"""Aaj ki taaza khabar....\nHamara Being Strong ...",Tweet,Twitter for iPhone,3784,33403,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
1,"""1216358418153271297""",https://twitter.com/beingsalmankhan/status/121...,2020-01-12 13:57:00,"""Ouiii ma .... jhakaas trailer\nhttps://t.co/u...",Tweet,Twitter for iPhone,3227,36484,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
2,"""1216324931925041153""",https://twitter.com/beingsalmankhan/status/121...,2020-01-12 11:43:56,"""Mumbaikars, aa gaya hai #SwachhSurvekshan2020...",Tweet,Twitter for iPhone,2613,23579,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
3,"""1215547133102841857""",https://twitter.com/beingsalmankhan/status/121...,2020-01-10 08:13:14,"""Announcing my next film... KABHI EID KABHI DI...",Tweet,Twitter for iPhone,9487,81542,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
4,"""1215136475391700995""",https://twitter.com/beingsalmankhan/status/121...,2020-01-09 05:01:26,"""Best wishes for the film! \n\nhttps://t.co/CU...",Tweet,Twitter for iPhone,1994,17697,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""427604739262386177""",https://twitter.com/beingsalmankhan/status/427...,2014-01-27 00:51:29,"""@BeingSonaa This Republic Day, remember, you ...",Reply,GraphityCampaignSalman,2,2,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
3196,"""427604635998642176""",https://twitter.com/beingsalmankhan/status/427...,2014-01-27 00:51:04,"""@BeingSonaa This Republic Day, remember, you ...",Reply,GraphityCampaignSalman,1,1,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
3197,"""427604518763630592""",https://twitter.com/beingsalmankhan/status/427...,2014-01-27 00:50:36,"""@Norah_alsorour This Republic Day, remember, ...",Reply,GraphityCampaignSalman,1,2,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
3198,"""427604275082960896""",https://twitter.com/beingsalmankhan/status/427...,2014-01-27 00:49:38,"""@hebasiraj This Republic Day, remember, you d...",Reply,GraphityCampaignSalman,1,2,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected
3199,"""427604124029288448""",https://twitter.com/beingsalmankhan/status/427...,2014-01-27 00:49:02,"""@hebasiraj This Republic Day, remember, you d...",Reply,GraphityCampaignSalman,1,2,"""132385468""","""Salman Khan""",beingsalmankhan,Verified,https://twitter.com/beingsalmankhan,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1218463651138539520""","""Salman Khan""",beingsalmankhan,"""Aaj ki taaza khabar....\nHamara Being Strong ...",3784,33403,2020-01-18 09:22:27
1,"""1216358418153271297""","""Salman Khan""",beingsalmankhan,"""Ouiii ma .... jhakaas trailer\nhttps://t.co/u...",3227,36484,2020-01-12 13:57:00
2,"""1216324931925041153""","""Salman Khan""",beingsalmankhan,"""Mumbaikars, aa gaya hai #SwachhSurvekshan2020...",2613,23579,2020-01-12 11:43:56
3,"""1215547133102841857""","""Salman Khan""",beingsalmankhan,"""Announcing my next film... KABHI EID KABHI DI...",9487,81542,2020-01-10 08:13:14
4,"""1215136475391700995""","""Salman Khan""",beingsalmankhan,"""Best wishes for the film! \n\nhttps://t.co/CU...",1994,17697,2020-01-09 05:01:26

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1218463651138539520""","""Salman Khan""",beingsalmankhan,"""Aaj ki taaza khabar....\nHamara Being Strong ...",3784,33403,2020-01-18 09:22:27,"[@beingstrongind, @JeraiFitness247]",[#SK27Gym],1,2
1,"""1216358418153271297""","""Salman Khan""",beingsalmankhan,"""Ouiii ma .... jhakaas trailer\nhttps://t.co/u...",3227,36484,2020-01-12 13:57:00,"[@AnilKapoor, @DishPatani, @kunalkemmu, @mohit...",[#AdityaRoyKapur],1,11
2,"""1216324931925041153""","""Salman Khan""",beingsalmankhan,"""Mumbaikars, aa gaya hai #SwachhSurvekshan2020...",2613,23579,2020-01-12 11:43:56,[],"[#SwachhSurvekshan2020Mumbai, #AnythingForMumb...",2,0
3,"""1215547133102841857""","""Salman Khan""",beingsalmankhan,"""Announcing my next film... KABHI EID KABHI DI...",9487,81542,2020-01-10 08:13:14,"[@NGEMovies, @farhad_samji, @WardaNadiadwala, ...",[#SajidNadiadwala],1,4
4,"""1215136475391700995""","""Salman Khan""",beingsalmankhan,"""Best wishes for the film! \n\nhttps://t.co/CU...",1994,17697,2020-01-09 05:01:26,"[@soniamaan01, @honeybhagnani, @kumartaurani, ...","[#HimeshReshammiya, #Raka, #SabitaManakchand]",3,6
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""427604739262386177""","""Salman Khan""",beingsalmankhan,"""@BeingSonaa This Republic Day, remember, you ...",2,2,2014-01-27 00:51:29,[@BeingSonaa],[],0,1
3196,"""427604635998642176""","""Salman Khan""",beingsalmankhan,"""@BeingSonaa This Republic Day, remember, you ...",1,1,2014-01-27 00:51:04,[@BeingSonaa],[],0,1
3197,"""427604518763630592""","""Salman Khan""",beingsalmankhan,"""@Norah_alsorour This Republic Day, remember, ...",1,2,2014-01-27 00:50:36,[@Norah_alsorour],[],0,1
3198,"""427604275082960896""","""Salman Khan""",beingsalmankhan,"""@hebasiraj This Republic Day, remember, you d...",1,2,2014-01-27 00:49:38,[@hebasiraj],[],0,1
3199,"""427604124029288448""","""Salman Khan""",beingsalmankhan,"""@hebasiraj This Republic Day, remember, you d...",1,2,2014-01-27 00:49:02,[@hebasiraj],[],0,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1218463651138539520""","""Salman Khan""",beingsalmankhan,"""Aaj ki taaza khabar....\nHamara Being Strong ...",3784,33403,"[@beingstrongind, @JeraiFitness247]",[#SK27Gym],1,2,2020-01-18,09:22:27
1,"""1216358418153271297""","""Salman Khan""",beingsalmankhan,"""Ouiii ma .... jhakaas trailer\nhttps://t.co/u...",3227,36484,"[@AnilKapoor, @DishPatani, @kunalkemmu, @mohit...",[#AdityaRoyKapur],1,11,2020-01-12,13:57:00
2,"""1216324931925041153""","""Salman Khan""",beingsalmankhan,"""Mumbaikars, aa gaya hai #SwachhSurvekshan2020...",2613,23579,[],"[#SwachhSurvekshan2020Mumbai, #AnythingForMumb...",2,0,2020-01-12,11:43:56
3,"""1215547133102841857""","""Salman Khan""",beingsalmankhan,"""Announcing my next film... KABHI EID KABHI DI...",9487,81542,"[@NGEMovies, @farhad_samji, @WardaNadiadwala, ...",[#SajidNadiadwala],1,4,2020-01-10,08:13:14
4,"""1215136475391700995""","""Salman Khan""",beingsalmankhan,"""Best wishes for the film! \n\nhttps://t.co/CU...",1994,17697,"[@soniamaan01, @honeybhagnani, @kumartaurani, ...","[#HimeshReshammiya, #Raka, #SabitaManakchand]",3,6,2020-01-09,05:01:26
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""427604739262386177""","""Salman Khan""",beingsalmankhan,"""@BeingSonaa This Republic Day, remember, you ...",2,2,[@BeingSonaa],[],0,1,2014-01-27,00:51:29
3196,"""427604635998642176""","""Salman Khan""",beingsalmankhan,"""@BeingSonaa This Republic Day, remember, you ...",1,1,[@BeingSonaa],[],0,1,2014-01-27,00:51:04
3197,"""427604518763630592""","""Salman Khan""",beingsalmankhan,"""@Norah_alsorour This Republic Day, remember, ...",1,2,[@Norah_alsorour],[],0,1,2014-01-27,00:50:36
3198,"""427604275082960896""","""Salman Khan""",beingsalmankhan,"""@hebasiraj This Republic Day, remember, you d...",1,2,[@hebasiraj],[],0,1,2014-01-27,00:49:38
3199,"""427604124029288448""","""Salman Khan""",beingsalmankhan,"""@hebasiraj This Republic Day, remember, you d...",1,2,[@hebasiraj],[],0,1,2014-01-27,00:49:02

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/SalmanKhanImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1218463651138539520""","""1218463640749248512""",https://pbs.twimg.com/media/EOjaOb6WkAAwK3U.jpg,https://t.co/ADebKHpCEJ
1,"""1203727256373407745""","""1203727246718046208""",https://pbs.twimg.com/media/ELR_jaMWkAA3aKN.jpg,https://t.co/bpJcRYoO3G
2,"""1200696203064664064""","""1200696192872714240""",https://pbs.twimg.com/media/EKm602tXkAAqe5H.jpg,https://t.co/OAXQ8CfOYj
3,"""1196147999359025163""","""1196147962252054528""",https://pbs.twimg.com/media/EJmSO_TXUAAvG35.jpg,https://t.co/ctRpMHgqIx
4,"""1190195751105646597""","""1190195741773500424""",https://pbs.twimg.com/media/EIRsuKGXkAg3hLy.jpg,https://t.co/rup4OZFr2I
...,...,...,...,...
581,"""446388387138641921""","""446388386962493440""",https://pbs.twimg.com/media/BjHj33TCUAAHK3H.jpg,http://t.co/HeA8Km9Q24
582,"""446386919149031424""","""446386918972862464""",https://pbs.twimg.com/media/BjHiianCMAApiEo.jpg,http://t.co/gxBWbEWRwF
583,"""446384618732675072""","""446384618602639360""",https://pbs.twimg.com/media/BjHgchECMAAEi4P.jpg,http://t.co/OUGma2RTBs
584,"""446383832799776768""","""446383832678137856""",https://pbs.twimg.com/media/BjHfuxRCAAAXXyl.jpg,http://t.co/HM4dMvt8Uo
585,"""445180167280148480""","""445180167124946944""",https://pbs.twimg.com/media/Bi2ZANqIEAAWQLF.jpg,http://t.co/YzeSoTGtfO

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (586, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (586, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1218463651138539520"  Image added
1    "1203727256373407745"  Image added
2    "1200696203064664064"  Image added
3    "1196147999359025163"  Image added
4    "1190195751105646597"  Image added
..                     ...          ...
581   "446388387138641921"  Image added
582   "446386919149031424"  Image added
583   "446384618732675072"  Image added
584   "446383832799776768"  Image added
585   "445180167280148480"  Image added

[586 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1218463651138539520""","""Salman Khan""",beingsalmankhan,"""Aaj ki taaza khabar....\nHamara Being Strong ...",3784,33403,"[@beingstrongind, @JeraiFitness247]",[#SK27Gym],1,2,2020-01-18,09:22:27,Image added
1,"""1216358418153271297""","""Salman Khan""",beingsalmankhan,"""Ouiii ma .... jhakaas trailer\nhttps://t.co/u...",3227,36484,"[@AnilKapoor, @DishPatani, @kunalkemmu, @mohit...",[#AdityaRoyKapur],1,11,2020-01-12,13:57:00,NaN
2,"""1216324931925041153""","""Salman Khan""",beingsalmankhan,"""Mumbaikars, aa gaya hai #SwachhSurvekshan2020...",2613,23579,[],"[#SwachhSurvekshan2020Mumbai, #AnythingForMumb...",2,0,2020-01-12,11:43:56,NaN
3,"""1215547133102841857""","""Salman Khan""",beingsalmankhan,"""Announcing my next film... KABHI EID KABHI DI...",9487,81542,"[@NGEMovies, @farhad_samji, @WardaNadiadwala, ...",[#SajidNadiadwala],1,4,2020-01-10,08:13:14,NaN
4,"""1215136475391700995""","""Salman Khan""",beingsalmankhan,"""Best wishes for the film! \n\nhttps://t.co/CU...",1994,17697,"[@soniamaan01, @honeybhagnani, @kumartaurani, ...","[#HimeshReshammiya, #Raka, #SabitaManakchand]",3,6,2020-01-09,05:01:26,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3247,"""427604739262386177""","""Salman Khan""",beingsalmankhan,"""@BeingSonaa This Republic Day, remember, you ...",2,2,[@BeingSonaa],[],0,1,2014-01-27,00:51:29,NaN
3248,"""427604635998642176""","""Salman Khan""",beingsalmankhan,"""@BeingSonaa This Republic Day, remember, you ...",1,1,[@BeingSonaa],[],0,1,2014-01-27,00:51:04,NaN
3249,"""427604518763630592""","""Salman Khan""",beingsalmankhan,"""@Norah_alsorour This Republic Day, remember, ...",1,2,[@Norah_alsorour],[],0,1,2014-01-27,00:50:36,NaN
3250,"""427604275082960896""","""Salman Khan""",beingsalmankhan,"""@hebasiraj This Republic Day, remember, you d...",1,2,[@hebasiraj],[],0,1,2014-01-27,00:49:38,NaN
3251,"""427604124029288448""","""Salman Khan""",beingsalmankhan,"""@hebasiraj This Republic Day, remember, you d...",1,2,[@hebasiraj],[],0,1,2014-01-27,00:49:02,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/SalmanKhanVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1210458007374422017""","""1210457922745946113""",https://video.twimg.com/ext_tw_video/121045792...,https://t.co/RoCksjOgUl
1,"""1210132240077856771""","""1210132104731910145""",https://video.twimg.com/ext_tw_video/121013210...,https://t.co/PnKObouyb8
2,"""1209739009423020032""","""1209738848005230593""",https://video.twimg.com/ext_tw_video/120973884...,https://t.co/cFdvgBtH4z
3,"""1209486566940434432""","""1209486446152880129""",https://video.twimg.com/ext_tw_video/120948644...,https://t.co/nLiKNusmS5
4,"""1208290169553481728""","""1208290103627526144""",https://video.twimg.com/ext_tw_video/120829010...,https://t.co/lcRiDEBaYE
...,...,...,...,...
242,"""663432442632499200""","""663432160024485888""",https://video.twimg.com/ext_tw_video/663432160...,https://t.co/Wf2hpiKCmh
243,"""663432085139361792""","""663431826480885760""",https://video.twimg.com/ext_tw_video/663431826...,https://t.co/YPO3hELcfA
244,"""662932762454814720""","""662932658654158848""",https://video.twimg.com/ext_tw_video/662932658...,https://t.co/Qj3wLR7pVE
245,"""662140159450722305""","""662139936515096578""",https://video.twimg.com/ext_tw_video/662139936...,https://t.co/PvyufQ0Vhu
246,"""656503831518314496""","""656501698286850048""",https://video.twimg.com/ext_tw_video/656501698...,https://t.co/6xOFvFqfft

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (247, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (247, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1210458007374422017"  Video added
1    "1210132240077856771"  Video added
2    "1209739009423020032"  Video added
3    "1209486566940434432"  Video added
4    "1208290169553481728"  Video added
..                     ...          ...
242   "663432442632499200"  Video added
243   "663432085139361792"  Video added
244   "662932762454814720"  Video added
245   "662140159450722305"  Video added
246   "656503831518314496"  Video added

[247 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1218463651138539520""","""Salman Khan""",beingsalmankhan,"""Aaj ki taaza khabar....\nHamara Being Strong ...",3784,33403,"[@beingstrongind, @JeraiFitness247]",[#SK27Gym],1,2,2020-01-18,09:22:27,Image added,NaN
1,"""1216358418153271297""","""Salman Khan""",beingsalmankhan,"""Ouiii ma .... jhakaas trailer\nhttps://t.co/u...",3227,36484,"[@AnilKapoor, @DishPatani, @kunalkemmu, @mohit...",[#AdityaRoyKapur],1,11,2020-01-12,13:57:00,NaN,NaN
2,"""1216324931925041153""","""Salman Khan""",beingsalmankhan,"""Mumbaikars, aa gaya hai #SwachhSurvekshan2020...",2613,23579,[],"[#SwachhSurvekshan2020Mumbai, #AnythingForMumb...",2,0,2020-01-12,11:43:56,NaN,NaN
3,"""1215547133102841857""","""Salman Khan""",beingsalmankhan,"""Announcing my next film... KABHI EID KABHI DI...",9487,81542,"[@NGEMovies, @farhad_samji, @WardaNadiadwala, ...",[#SajidNadiadwala],1,4,2020-01-10,08:13:14,NaN,NaN
4,"""1215136475391700995""","""Salman Khan""",beingsalmankhan,"""Best wishes for the film! \n\nhttps://t.co/CU...",1994,17697,"[@soniamaan01, @honeybhagnani, @kumartaurani, ...","[#HimeshReshammiya, #Raka, #SabitaManakchand]",3,6,2020-01-09,05:01:26,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3247,"""427604739262386177""","""Salman Khan""",beingsalmankhan,"""@BeingSonaa This Republic Day, remember, you ...",2,2,[@BeingSonaa],[],0,1,2014-01-27,00:51:29,NaN,NaN
3248,"""427604635998642176""","""Salman Khan""",beingsalmankhan,"""@BeingSonaa This Republic Day, remember, you ...",1,1,[@BeingSonaa],[],0,1,2014-01-27,00:51:04,NaN,NaN
3249,"""427604518763630592""","""Salman Khan""",beingsalmankhan,"""@Norah_alsorour This Republic Day, remember, ...",1,2,[@Norah_alsorour],[],0,1,2014-01-27,00:50:36,NaN,NaN
3250,"""427604275082960896""","""Salman Khan""",beingsalmankhan,"""@hebasiraj This Republic Day, remember, you d...",1,2,[@hebasiraj],[],0,1,2014-01-27,00:49:38,NaN,NaN
3251,"""427604124029288448""","""Salman Khan""",beingsalmankhan,"""@hebasiraj This Republic Day, remember, you d...",1,2,[@hebasiraj],[],0,1,2014-01-27,00:49:02,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Male"

#Create an Vocation column 
Tweets_df['Vocation'] = "Entertainment"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3252, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1218463651138539520""","""Salman Khan""",beingsalmankhan,3784,33403,"[@beingstrongind, @JeraiFitness247]",[#SK27Gym],1,2,2020-01-18,09:22:27,Image added,-,Male,Entertainment
1,"""1216358418153271297""","""Salman Khan""",beingsalmankhan,3227,36484,"[@AnilKapoor, @DishPatani, @kunalkemmu, @mohit...",[#AdityaRoyKapur],1,11,2020-01-12,13:57:00,-,-,Male,Entertainment
2,"""1216324931925041153""","""Salman Khan""",beingsalmankhan,2613,23579,[],"[#SwachhSurvekshan2020Mumbai, #AnythingForMumb...",2,0,2020-01-12,11:43:56,-,-,Male,Entertainment
3,"""1215547133102841857""","""Salman Khan""",beingsalmankhan,9487,81542,"[@NGEMovies, @farhad_samji, @WardaNadiadwala, ...",[#SajidNadiadwala],1,4,2020-01-10,08:13:14,-,-,Male,Entertainment
4,"""1215136475391700995""","""Salman Khan""",beingsalmankhan,1994,17697,"[@soniamaan01, @honeybhagnani, @kumartaurani, ...","[#HimeshReshammiya, #Raka, #SabitaManakchand]",3,6,2020-01-09,05:01:26,-,-,Male,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3247,"""427604739262386177""","""Salman Khan""",beingsalmankhan,2,2,[@BeingSonaa],[],0,1,2014-01-27,00:51:29,-,-,Male,Entertainment
3248,"""427604635998642176""","""Salman Khan""",beingsalmankhan,1,1,[@BeingSonaa],[],0,1,2014-01-27,00:51:04,-,-,Male,Entertainment
3249,"""427604518763630592""","""Salman Khan""",beingsalmankhan,1,2,[@Norah_alsorour],[],0,1,2014-01-27,00:50:36,-,-,Male,Entertainment
3250,"""427604275082960896""","""Salman Khan""",beingsalmankhan,1,2,[@hebasiraj],[],0,1,2014-01-27,00:49:38,-,-,Male,Entertainment
3251,"""427604124029288448""","""Salman Khan""",beingsalmankhan,1,2,[@hebasiraj],[],0,1,2014-01-27,00:49:02,-,-,Male,Entertainment

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3252, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1218463651138539520""","""Salman Khan""",beingsalmankhan,Male,Entertainment,[#SK27Gym],1,"[@beingstrongind, @JeraiFitness247]",2,33403,3784,Image added,-,2020-01-18,09:22:27
"""1216358418153271297""","""Salman Khan""",beingsalmankhan,Male,Entertainment,[#AdityaRoyKapur],1,"[@AnilKapoor, @DishPatani, @kunalkemmu, @mohit...",11,36484,3227,-,-,2020-01-12,13:57:00
"""1216324931925041153""","""Salman Khan""",beingsalmankhan,Male,Entertainment,"[#SwachhSurvekshan2020Mumbai, #AnythingForMumb...",2,[],0,23579,2613,-,-,2020-01-12,11:43:56
"""1215547133102841857""","""Salman Khan""",beingsalmankhan,Male,Entertainment,[#SajidNadiadwala],1,"[@NGEMovies, @farhad_samji, @WardaNadiadwala, ...",4,81542,9487,-,-,2020-01-10,08:13:14
"""1215136475391700995""","""Salman Khan""",beingsalmankhan,Male,Entertainment,"[#HimeshReshammiya, #Raka, #SabitaManakchand]",3,"[@soniamaan01, @honeybhagnani, @kumartaurani, ...",6,17697,1994,-,-,2020-01-09,05:01:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""427604739262386177""","""Salman Khan""",beingsalmankhan,Male,Entertainment,[],0,[@BeingSonaa],1,2,2,-,-,2014-01-27,00:51:29
"""427604635998642176""","""Salman Khan""",beingsalmankhan,Male,Entertainment,[],0,[@BeingSonaa],1,1,1,-,-,2014-01-27,00:51:04
"""427604518763630592""","""Salman Khan""",beingsalmankhan,Male,Entertainment,[],0,[@Norah_alsorour],1,2,1,-,-,2014-01-27,00:50:36
"""427604275082960896""","""Salman Khan""",beingsalmankhan,Male,Entertainment,[],0,[@hebasiraj],1,2,1,-,-,2014-01-27,00:49:38
"""427604124029288448""","""Salman Khan""",beingsalmankhan,Male,Entertainment,[],0,[@hebasiraj],1,2,1,-,-,2014-01-27,00:49:02

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/SalmanKhan_df.csv')