##### ===================================================================================================================

#  Shakira Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/ShakiraTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220173541783625729""",https://twitter.com/shakira/status/12201735417...,2020-01-23 02:36:56,"""Avanza la construcción de nuestro colegio @fp...",Tweet,Twitter for iPhone,578,5606,"""44409004""","""Shakira""",shakira,Verified,https://twitter.com/shakira,Not Protected
1,"""1220112032613257216""",https://twitter.com/shakira/status/12201120326...,2020-01-22 22:32:31,"""Componiendo Me Gusta! Composing Me Gusta! @an...",Tweet,Twitter Media Studio,723,4737,"""44409004""","""Shakira""",shakira,Verified,https://twitter.com/shakira,Not Protected
2,"""1219711517328801792""",https://twitter.com/sonymusiclatin/status/1219...,2020-01-21 20:01:01,"""Di: ""Alexa play #MeGusta by \n@shakira y @Anu...",Retweet,Gain Platform,132,814,"""44399838""","""Sony Music Latin""",sonymusiclatin,Verified,https://twitter.com/sonymusiclatin,Not Protected
3,"""1219711263355305986""",https://twitter.com/amazonmusic/status/1219711...,2020-01-21 20:00:00,""".@shakira is kicking off 2020 with new music,...",Retweet,Sprinklr,145,842,"""14740219""","""Amazon Music""",amazonmusic,Verified,https://twitter.com/amazonmusic,Not Protected
4,"""1219656296821067777""",https://twitter.com/shakira/status/12196562968...,2020-01-21 16:21:35,""".@TheAnnaKaiser rules: turn off your phone un...",Tweet,Twitter for iPhone,342,3908,"""44409004""","""Shakira""",shakira,Verified,https://twitter.com/shakira,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3160,"""590521927401340928""",https://twitter.com/shakira/status/59052192740...,2015-04-21 14:26:13,"""""Sabías que es más fácil enseñarle a leer a u...",Tweet,Twitter Web Client,859,2050,"""44409004""","""Shakira""",shakira,Verified,https://twitter.com/shakira,Not Protected
3161,"""590271806239612928""",https://twitter.com/shakira/status/59027180623...,2015-04-20 21:52:19,"""Acabo de recibir mis 3 @GWR récord enmarcados...",Tweet,Twitter for iPhone,1224,3236,"""44409004""","""Shakira""",shakira,Verified,https://twitter.com/shakira,Not Protected
3162,"""590271463862755328""",https://twitter.com/shakira/status/59027146386...,2015-04-20 21:50:58,"""Just got my 3 @GWR records framed! So, logica...",Tweet,Twitter for iPhone,971,2661,"""44409004""","""Shakira""",shakira,Verified,https://twitter.com/shakira,Not Protected
3163,"""588817413338058752""",https://twitter.com/shakira/status/58881741333...,2015-04-16 21:33:05,"""Just 15 days left to nominate the most extrao...",Tweet,Twitter for iPhone,457,1360,"""44409004""","""Shakira""",shakira,Verified,https://twitter.com/shakira,Not Protected
3164,"""588817259478458368""",https://twitter.com/shakira/status/58881725947...,2015-04-16 21:32:29,"""Quedan solo 15 días para nominar a los premio...",Tweet,Twitter for iPhone,399,1240,"""44409004""","""Shakira""",shakira,Verified,https://twitter.com/shakira,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3165, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3165, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1220173541783625729""","""Shakira""",shakira,"""Avanza la construcción de nuestro colegio @fp...",578,5606,2020-01-23 02:36:56
1,"""1220112032613257216""","""Shakira""",shakira,"""Componiendo Me Gusta! Composing Me Gusta! @an...",723,4737,2020-01-22 22:32:31
2,"""1219711517328801792""","""Sony Music Latin""",sonymusiclatin,"""Di: ""Alexa play #MeGusta by \n@shakira y @Anu...",132,814,2020-01-21 20:01:01
3,"""1219711263355305986""","""Amazon Music""",amazonmusic,""".@shakira is kicking off 2020 with new music,...",145,842,2020-01-21 20:00:00
4,"""1219656296821067777""","""Shakira""",shakira,""".@TheAnnaKaiser rules: turn off your phone un...",342,3908,2020-01-21 16:21:35

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1220173541783625729""","""Shakira""",shakira,"""Avanza la construcción de nuestro colegio @fp...",578,5606,2020-01-23 02:36:56,[@fpiesdescalzos],[],0,1
1,"""1220112032613257216""","""Shakira""",shakira,"""Componiendo Me Gusta! Composing Me Gusta! @an...",723,4737,2020-01-22 22:32:31,[@anuel_2blea],[],0,1
2,"""1219711517328801792""","""Sony Music Latin""",sonymusiclatin,"""Di: ""Alexa play #MeGusta by \n@shakira y @Anu...",132,814,2020-01-21 20:01:01,"[@shakira, @Anuel_2bleA""]",[#MeGusta],1,2
3,"""1219711263355305986""","""Amazon Music""",amazonmusic,""".@shakira is kicking off 2020 with new music,...",145,842,2020-01-21 20:00:00,"[@shakira, @Anuel_2bleA.]",[],0,2
4,"""1219656296821067777""","""Shakira""",shakira,""".@TheAnnaKaiser rules: turn off your phone un...",342,3908,2020-01-21 16:21:35,"[@TheAnnaKaiser, @theaktstudios]",[],0,2
...,...,...,...,...,...,...,...,...,...,...,...
3160,"""590521927401340928""","""Shakira""",shakira,"""""Sabías que es más fácil enseñarle a leer a u...",859,2050,2015-04-21 14:26:13,[],[],0,0
3161,"""590271806239612928""","""Shakira""",shakira,"""Acabo de recibir mis 3 @GWR récord enmarcados...",1224,3236,2015-04-20 21:52:19,[@GWR],[],0,1
3162,"""590271463862755328""","""Shakira""",shakira,"""Just got my 3 @GWR records framed! So, logica...",971,2661,2015-04-20 21:50:58,[@GWR],[],0,1
3163,"""588817413338058752""","""Shakira""",shakira,"""Just 15 days left to nominate the most extrao...",457,1360,2015-04-16 21:33:05,"[@MovimientoALAS""]",[],0,1
3164,"""588817259478458368""","""Shakira""",shakira,"""Quedan solo 15 días para nominar a los premio...",399,1240,2015-04-16 21:32:29,"[@MovimientoALAS""]",[],0,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3165, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1220173541783625729""","""Shakira""",shakira,"""Avanza la construcción de nuestro colegio @fp...",578,5606,[@fpiesdescalzos],[],0,1,2020-01-23,02:36:56
1,"""1220112032613257216""","""Shakira""",shakira,"""Componiendo Me Gusta! Composing Me Gusta! @an...",723,4737,[@anuel_2blea],[],0,1,2020-01-22,22:32:31
2,"""1219711517328801792""","""Sony Music Latin""",sonymusiclatin,"""Di: ""Alexa play #MeGusta by \n@shakira y @Anu...",132,814,"[@shakira, @Anuel_2bleA""]",[#MeGusta],1,2,2020-01-21,20:01:01
3,"""1219711263355305986""","""Amazon Music""",amazonmusic,""".@shakira is kicking off 2020 with new music,...",145,842,"[@shakira, @Anuel_2bleA.]",[],0,2,2020-01-21,20:00:00
4,"""1219656296821067777""","""Shakira""",shakira,""".@TheAnnaKaiser rules: turn off your phone un...",342,3908,"[@TheAnnaKaiser, @theaktstudios]",[],0,2,2020-01-21,16:21:35
...,...,...,...,...,...,...,...,...,...,...,...,...
3160,"""590521927401340928""","""Shakira""",shakira,"""""Sabías que es más fácil enseñarle a leer a u...",859,2050,[],[],0,0,2015-04-21,14:26:13
3161,"""590271806239612928""","""Shakira""",shakira,"""Acabo de recibir mis 3 @GWR récord enmarcados...",1224,3236,[@GWR],[],0,1,2015-04-20,21:52:19
3162,"""590271463862755328""","""Shakira""",shakira,"""Just got my 3 @GWR records framed! So, logica...",971,2661,[@GWR],[],0,1,2015-04-20,21:50:58
3163,"""588817413338058752""","""Shakira""",shakira,"""Just 15 days left to nominate the most extrao...",457,1360,"[@MovimientoALAS""]",[],0,1,2015-04-16,21:33:05
3164,"""588817259478458368""","""Shakira""",shakira,"""Quedan solo 15 días para nominar a los premio...",399,1240,"[@MovimientoALAS""]",[],0,1,2015-04-16,21:32:29

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/ShakiraImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220173541783625729""","""1220173536247144448""",https://pbs.twimg.com/media/EO7tXdBX4AAAUGc.jpg,https://t.co/HHvfRj3Z2H
1,"""1220173541783625729""","""1220173536247132161""",https://pbs.twimg.com/media/EO7tXdBXsAEAOqM.jpg,https://t.co/HHvfRj3Z2H
2,"""1219711517328801792""","""1219711513709158400""",https://pbs.twimg.com/media/EO1JKM8WoAAs4aJ.jpg,https://t.co/XKNAOHdqKg
3,"""1219711263355305986""","""1219711261677584385""",https://pbs.twimg.com/media/EO1I7iDWAAENfFZ.png,https://t.co/7bYW1y9erO
4,"""1219398149913096194""","""1219398146142490629""",https://pbs.twimg.com/media/EOwsJzyX0AUBleI.png,https://t.co/plrrte2FIN
...,...,...,...,...
1881,"""596003317093834752""","""596003266544054272""",https://pbs.twimg.com/media/CEVt0CtUsAA4tch.jpg,http://t.co/1mdnmzjQNc
1882,"""594569045145362432""","""594569015894233088""",https://pbs.twimg.com/media/CEBVXqrUUAAbQHm.jpg,http://t.co/i1cm9FbyvK
1883,"""590619554797199360""","""590619553509593088""",https://pbs.twimg.com/media/CDJNWsxW0AAIwyq.jpg,http://t.co/TIJgGVIo2g
1884,"""590271806239612928""","""590271797150494721""",https://pbs.twimg.com/media/CDEREnYWMAEM1dS.jpg,http://t.co/0SEQB1aKxE
1885,"""590271463862755328""","""590271454572376064""",https://pbs.twimg.com/media/CDEQwrLW8AASZ1q.jpg,http://t.co/bUBBzzWX7y

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1886, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1886, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                   Tweet Id       Images
0     "1220173541783625729"  Image added
1     "1220173541783625729"  Image added
2     "1219711517328801792"  Image added
3     "1219711263355305986"  Image added
4     "1219398149913096194"  Image added
...                     ...          ...
1881   "596003317093834752"  Image added
1882   "594569045145362432"  Image added
1883   "590619554797199360"  Image added
1884   "590271806239612928"  Image added
1885   "590271463862755328"  Image added

[1886 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1220173541783625729""","""Shakira""",shakira,"""Avanza la construcción de nuestro colegio @fp...",578,5606,[@fpiesdescalzos],[],0,1,2020-01-23,02:36:56,Image added
1,"""1220173541783625729""","""Shakira""",shakira,"""Avanza la construcción de nuestro colegio @fp...",578,5606,[@fpiesdescalzos],[],0,1,2020-01-23,02:36:56,Image added
2,"""1220112032613257216""","""Shakira""",shakira,"""Componiendo Me Gusta! Composing Me Gusta! @an...",723,4737,[@anuel_2blea],[],0,1,2020-01-22,22:32:31,NaN
3,"""1219711517328801792""","""Sony Music Latin""",sonymusiclatin,"""Di: ""Alexa play #MeGusta by \n@shakira y @Anu...",132,814,"[@shakira, @Anuel_2bleA""]",[#MeGusta],1,2,2020-01-21,20:01:01,Image added
4,"""1219711263355305986""","""Amazon Music""",amazonmusic,""".@shakira is kicking off 2020 with new music,...",145,842,"[@shakira, @Anuel_2bleA.]",[],0,2,2020-01-21,20:00:00,Image added
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3601,"""590521927401340928""","""Shakira""",shakira,"""""Sabías que es más fácil enseñarle a leer a u...",859,2050,[],[],0,0,2015-04-21,14:26:13,NaN
3602,"""590271806239612928""","""Shakira""",shakira,"""Acabo de recibir mis 3 @GWR récord enmarcados...",1224,3236,[@GWR],[],0,1,2015-04-20,21:52:19,Image added
3603,"""590271463862755328""","""Shakira""",shakira,"""Just got my 3 @GWR records framed! So, logica...",971,2661,[@GWR],[],0,1,2015-04-20,21:50:58,Image added
3604,"""588817413338058752""","""Shakira""",shakira,"""Just 15 days left to nominate the most extrao...",457,1360,"[@MovimientoALAS""]",[],0,1,2015-04-16,21:33:05,NaN
3605,"""588817259478458368""","""Shakira""",shakira,"""Quedan solo 15 días para nominar a los premio...",399,1240,"[@MovimientoALAS""]",[],0,1,2015-04-16,21:32:29,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/ShakiraVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220112032613257216""","""1220109688525795331""",https://video.twimg.com/amplify_video/12201096...,https://t.co/VMZg4VuxqR
1,"""1219656296821067777""","""1219656213874597890""",https://video.twimg.com/ext_tw_video/121965621...,https://t.co/J8k96Dib7m
2,"""1219434507885076481""","""1219434452302147585""",https://video.twimg.com/ext_tw_video/121943445...,https://t.co/uj1w298Wxt
3,"""1218965260926963715""","""1218964620834234371""",https://video.twimg.com/ext_tw_video/121896462...,https://t.co/BFyLPDbfJF
4,"""1218921301441683456""","""1218920667548213248""",https://video.twimg.com/ext_tw_video/121892066...,https://t.co/ZfNlkvLBY2
...,...,...,...,...
925,"""644585848562941952""","""644585848407781377""",https://video.twimg.com/tweet_video/CPIHafmW8A...,http://t.co/GpZuPOFLiO
926,"""644536235566960640""","""644536234677809152""",https://video.twimg.com/tweet_video/CPHaSmDWsA...,http://t.co/Zp9s2N3GMx
927,"""626427268286578688""","""626426972386795521""",https://video.twimg.com/ext_tw_video/626426972...,http://t.co/90JIoMD4QZ
928,"""611640532398415872""","""611638960104845313""",https://video.twimg.com/ext_tw_video/611638960...,http://t.co/N3tdWlTkWr
929,"""602260669040336896""","""602260400353124353""",https://video.twimg.com/ext_tw_video/602260400...,http://t.co/OihlCUeZyb

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (930, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (930, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1220112032613257216"  Video added
1    "1219656296821067777"  Video added
2    "1219434507885076481"  Video added
3    "1218965260926963715"  Video added
4    "1218921301441683456"  Video added
..                     ...          ...
925   "644585848562941952"  Video added
926   "644536235566960640"  Video added
927   "626427268286578688"  Video added
928   "611640532398415872"  Video added
929   "602260669040336896"  Video added

[930 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1220173541783625729""","""Shakira""",shakira,"""Avanza la construcción de nuestro colegio @fp...",578,5606,[@fpiesdescalzos],[],0,1,2020-01-23,02:36:56,Image added,NaN
1,"""1220173541783625729""","""Shakira""",shakira,"""Avanza la construcción de nuestro colegio @fp...",578,5606,[@fpiesdescalzos],[],0,1,2020-01-23,02:36:56,Image added,NaN
2,"""1220112032613257216""","""Shakira""",shakira,"""Componiendo Me Gusta! Composing Me Gusta! @an...",723,4737,[@anuel_2blea],[],0,1,2020-01-22,22:32:31,NaN,Video added
3,"""1219711517328801792""","""Sony Music Latin""",sonymusiclatin,"""Di: ""Alexa play #MeGusta by \n@shakira y @Anu...",132,814,"[@shakira, @Anuel_2bleA""]",[#MeGusta],1,2,2020-01-21,20:01:01,Image added,NaN
4,"""1219711263355305986""","""Amazon Music""",amazonmusic,""".@shakira is kicking off 2020 with new music,...",145,842,"[@shakira, @Anuel_2bleA.]",[],0,2,2020-01-21,20:00:00,Image added,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3601,"""590521927401340928""","""Shakira""",shakira,"""""Sabías que es más fácil enseñarle a leer a u...",859,2050,[],[],0,0,2015-04-21,14:26:13,NaN,NaN
3602,"""590271806239612928""","""Shakira""",shakira,"""Acabo de recibir mis 3 @GWR récord enmarcados...",1224,3236,[@GWR],[],0,1,2015-04-20,21:52:19,Image added,NaN
3603,"""590271463862755328""","""Shakira""",shakira,"""Just got my 3 @GWR records framed! So, logica...",971,2661,[@GWR],[],0,1,2015-04-20,21:50:58,Image added,NaN
3604,"""588817413338058752""","""Shakira""",shakira,"""Just 15 days left to nominate the most extrao...",457,1360,"[@MovimientoALAS""]",[],0,1,2015-04-16,21:33:05,NaN,NaN
3605,"""588817259478458368""","""Shakira""",shakira,"""Quedan solo 15 días para nominar a los premio...",399,1240,"[@MovimientoALAS""]",[],0,1,2015-04-16,21:32:29,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Female"

#Create an Vocation column 
Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3606, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1220173541783625729""","""Shakira""",shakira,578,5606,[@fpiesdescalzos],[],0,1,2020-01-23,02:36:56,Image added,-,Female,Music
1,"""1220173541783625729""","""Shakira""",shakira,578,5606,[@fpiesdescalzos],[],0,1,2020-01-23,02:36:56,Image added,-,Female,Music
2,"""1220112032613257216""","""Shakira""",shakira,723,4737,[@anuel_2blea],[],0,1,2020-01-22,22:32:31,-,Video added,Female,Music
3,"""1219711517328801792""","""Sony Music Latin""",sonymusiclatin,132,814,"[@shakira, @Anuel_2bleA""]",[#MeGusta],1,2,2020-01-21,20:01:01,Image added,-,Female,Music
4,"""1219711263355305986""","""Amazon Music""",amazonmusic,145,842,"[@shakira, @Anuel_2bleA.]",[],0,2,2020-01-21,20:00:00,Image added,-,Female,Music
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3601,"""590521927401340928""","""Shakira""",shakira,859,2050,[],[],0,0,2015-04-21,14:26:13,-,-,Female,Music
3602,"""590271806239612928""","""Shakira""",shakira,1224,3236,[@GWR],[],0,1,2015-04-20,21:52:19,Image added,-,Female,Music
3603,"""590271463862755328""","""Shakira""",shakira,971,2661,[@GWR],[],0,1,2015-04-20,21:50:58,Image added,-,Female,Music
3604,"""588817413338058752""","""Shakira""",shakira,457,1360,"[@MovimientoALAS""]",[],0,1,2015-04-16,21:33:05,-,-,Female,Music
3605,"""588817259478458368""","""Shakira""",shakira,399,1240,"[@MovimientoALAS""]",[],0,1,2015-04-16,21:32:29,-,-,Female,Music

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3606, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1220173541783625729""","""Shakira""",shakira,Female,Music,[],0,[@fpiesdescalzos],1,5606,578,Image added,-,2020-01-23,02:36:56
"""1220173541783625729""","""Shakira""",shakira,Female,Music,[],0,[@fpiesdescalzos],1,5606,578,Image added,-,2020-01-23,02:36:56
"""1220112032613257216""","""Shakira""",shakira,Female,Music,[],0,[@anuel_2blea],1,4737,723,-,Video added,2020-01-22,22:32:31
"""1219711517328801792""","""Sony Music Latin""",sonymusiclatin,Female,Music,[#MeGusta],1,"[@shakira, @Anuel_2bleA""]",2,814,132,Image added,-,2020-01-21,20:01:01
"""1219711263355305986""","""Amazon Music""",amazonmusic,Female,Music,[],0,"[@shakira, @Anuel_2bleA.]",2,842,145,Image added,-,2020-01-21,20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""590521927401340928""","""Shakira""",shakira,Female,Music,[],0,[],0,2050,859,-,-,2015-04-21,14:26:13
"""590271806239612928""","""Shakira""",shakira,Female,Music,[],0,[@GWR],1,3236,1224,Image added,-,2015-04-20,21:52:19
"""590271463862755328""","""Shakira""",shakira,Female,Music,[],0,[@GWR],1,2661,971,Image added,-,2015-04-20,21:50:58
"""588817413338058752""","""Shakira""",shakira,Female,Music,[],0,"[@MovimientoALAS""]",1,1360,457,-,-,2015-04-16,21:33:05
"""588817259478458368""","""Shakira""",shakira,Female,Music,[],0,"[@MovimientoALAS""]",1,1240,399,-,-,2015-04-16,21:32:29

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/Shakira_df.csv')