##### ===================================================================================================================

#  Sports Center Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/SportsCenterTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220229853557018625""",https://twitter.com/sportscenter/status/122022...,2020-01-23 06:20:42,"""‚ÄúCoach, I can win the game for this team. Lea...",Tweet,Khoros,876,4834,"""26257166""","""SportsCenter""",sportscenter,Verified,https://twitter.com/sportscenter,Not Protected
1,"""1220222069020991489""",https://twitter.com/sportscenter/status/122022...,2020-01-23 05:49:46,"""‚ö°Ô∏è 22 Pts\n‚ö°Ô∏è 8-11 FG\n‚ö°Ô∏è 4-4 3-PT FG\n‚ö°Ô∏è 7 R...",Tweet,Twitter Media Studio,1649,10240,"""26257166""","""SportsCenter""",sportscenter,Verified,https://twitter.com/sportscenter,Not Protected
2,"""1220206449479028737""",https://twitter.com/sportscenter/status/122020...,2020-01-23 04:47:42,"""ZION IS TAKING OVER üî•\n\n17 STRAIGHT üò± https:...",Tweet,Khoros,4595,25871,"""26257166""","""SportsCenter""",sportscenter,Verified,https://twitter.com/sportscenter,Not Protected
3,"""1220200064896970752""",https://twitter.com/sportscenter/status/122020...,2020-01-23 04:22:20,"""LeBron was asked about possibly playing for t...",Tweet,Khoros,3449,27910,"""26257166""","""SportsCenter""",sportscenter,Verified,https://twitter.com/sportscenter,Not Protected
4,"""1220187706791165952""",https://twitter.com/sportscenter/status/122018...,2020-01-23 03:33:13,"""Coach Cal was there to see D-Rose in Detroit ...",Tweet,Khoros,1350,15035,"""26257166""","""SportsCenter""",sportscenter,Verified,https://twitter.com/sportscenter,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1170365477257961472""",https://twitter.com/sportscenter/status/117036...,2019-09-07 15:57:28,"""Breaking: The Raiders have released Antonio B...",Tweet,Spredfast app,16123,49688,"""26257166""","""SportsCenter""",sportscenter,Verified,https://twitter.com/sportscenter,Not Protected
3196,"""1170360002638471169""",https://twitter.com/sportscenter/status/117036...,2019-09-07 15:35:43,"""CLEAN RIGHT HAND KO\n\n#UFC242 ON ESPN+ ‚û°Ô∏è ht...",Tweet,Twitter Media Studio,212,1021,"""26257166""","""SportsCenter""",sportscenter,Verified,https://twitter.com/sportscenter,Not Protected
3197,"""1170340635674415107""",https://twitter.com/diannaespn/status/11703406...,2019-09-07 14:18:46,"""Spoke to a source in the Raiders building abo...",Retweet,Twitter for iPhone,673,2823,"""117189498""","""Dianna""",diannaespn,Verified,https://twitter.com/diannaespn,Not Protected
3198,"""1170328579349143553""",https://twitter.com/jeffdarlington/status/1170...,2019-09-07 13:30:51,"""I just got an email from Antonio Brown. He te...",Retweet,Echofon,8964,28549,"""26144265""","""Jeff Darlington""",jeffdarlington,Verified,https://twitter.com/jeffdarlington,Not Protected
3199,"""1170326488174006272""",https://twitter.com/adamschefter/status/117032...,2019-09-07 13:22:33,"""By fining Antonio Brown $215,073.53 last nigh...",Retweet,Twitter for iPhone,10571,32940,"""51263592""","""Adam Schefter""",adamschefter,Verified,https://twitter.com/adamschefter,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1220229853557018625""","""SportsCenter""",sportscenter,"""‚ÄúCoach, I can win the game for this team. Lea...",876,4834,2020-01-23 06:20:42
1,"""1220222069020991489""","""SportsCenter""",sportscenter,"""‚ö°Ô∏è 22 Pts\n‚ö°Ô∏è 8-11 FG\n‚ö°Ô∏è 4-4 3-PT FG\n‚ö°Ô∏è 7 R...",1649,10240,2020-01-23 05:49:46
2,"""1220206449479028737""","""SportsCenter""",sportscenter,"""ZION IS TAKING OVER üî•\n\n17 STRAIGHT üò± https:...",4595,25871,2020-01-23 04:47:42
3,"""1220200064896970752""","""SportsCenter""",sportscenter,"""LeBron was asked about possibly playing for t...",3449,27910,2020-01-23 04:22:20
4,"""1220187706791165952""","""SportsCenter""",sportscenter,"""Coach Cal was there to see D-Rose in Detroit ...",1350,15035,2020-01-23 03:33:13

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1220229853557018625""","""SportsCenter""",sportscenter,"""‚ÄúCoach, I can win the game for this team. Lea...",876,4834,2020-01-23 06:20:42,[@MarcJSpearsESPN)],[],0,1
1,"""1220222069020991489""","""SportsCenter""",sportscenter,"""‚ö°Ô∏è 22 Pts\n‚ö°Ô∏è 8-11 FG\n‚ö°Ô∏è 4-4 3-PT FG\n‚ö°Ô∏è 7 R...",1649,10240,2020-01-23 05:49:46,[],[],0,0
2,"""1220206449479028737""","""SportsCenter""",sportscenter,"""ZION IS TAKING OVER üî•\n\n17 STRAIGHT üò± https:...",4595,25871,2020-01-23 04:47:42,[],[],0,0
3,"""1220200064896970752""","""SportsCenter""",sportscenter,"""LeBron was asked about possibly playing for t...",3449,27910,2020-01-23 04:22:20,[],[],0,0
4,"""1220187706791165952""","""SportsCenter""",sportscenter,"""Coach Cal was there to see D-Rose in Detroit ...",1350,15035,2020-01-23 03:33:13,[],[],0,0
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1170365477257961472""","""SportsCenter""",sportscenter,"""Breaking: The Raiders have released Antonio B...",16123,49688,2019-09-07 15:57:28,[],[],0,0
3196,"""1170360002638471169""","""SportsCenter""",sportscenter,"""CLEAN RIGHT HAND KO\n\n#UFC242 ON ESPN+ ‚û°Ô∏è ht...",212,1021,2019-09-07 15:35:43,[],[#UFC242],1,0
3197,"""1170340635674415107""","""Dianna""",diannaespn,"""Spoke to a source in the Raiders building abo...",673,2823,2019-09-07 14:18:46,[],"[#Raiders""]",1,0
3198,"""1170328579349143553""","""Jeff Darlington""",jeffdarlington,"""I just got an email from Antonio Brown. He te...",8964,28549,2019-09-07 13:30:51,[],[],0,0
3199,"""1170326488174006272""","""Adam Schefter""",adamschefter,"""By fining Antonio Brown $215,073.53 last nigh...",10571,32940,2019-09-07 13:22:33,[],[],0,0

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1220229853557018625""","""SportsCenter""",sportscenter,"""‚ÄúCoach, I can win the game for this team. Lea...",876,4834,[@MarcJSpearsESPN)],[],0,1,2020-01-23,06:20:42
1,"""1220222069020991489""","""SportsCenter""",sportscenter,"""‚ö°Ô∏è 22 Pts\n‚ö°Ô∏è 8-11 FG\n‚ö°Ô∏è 4-4 3-PT FG\n‚ö°Ô∏è 7 R...",1649,10240,[],[],0,0,2020-01-23,05:49:46
2,"""1220206449479028737""","""SportsCenter""",sportscenter,"""ZION IS TAKING OVER üî•\n\n17 STRAIGHT üò± https:...",4595,25871,[],[],0,0,2020-01-23,04:47:42
3,"""1220200064896970752""","""SportsCenter""",sportscenter,"""LeBron was asked about possibly playing for t...",3449,27910,[],[],0,0,2020-01-23,04:22:20
4,"""1220187706791165952""","""SportsCenter""",sportscenter,"""Coach Cal was there to see D-Rose in Detroit ...",1350,15035,[],[],0,0,2020-01-23,03:33:13
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1170365477257961472""","""SportsCenter""",sportscenter,"""Breaking: The Raiders have released Antonio B...",16123,49688,[],[],0,0,2019-09-07,15:57:28
3196,"""1170360002638471169""","""SportsCenter""",sportscenter,"""CLEAN RIGHT HAND KO\n\n#UFC242 ON ESPN+ ‚û°Ô∏è ht...",212,1021,[],[#UFC242],1,0,2019-09-07,15:35:43
3197,"""1170340635674415107""","""Dianna""",diannaespn,"""Spoke to a source in the Raiders building abo...",673,2823,[],"[#Raiders""]",1,0,2019-09-07,14:18:46
3198,"""1170328579349143553""","""Jeff Darlington""",jeffdarlington,"""I just got an email from Antonio Brown. He te...",8964,28549,[],[],0,0,2019-09-07,13:30:51
3199,"""1170326488174006272""","""Adam Schefter""",adamschefter,"""By fining Antonio Brown $215,073.53 last nigh...",10571,32940,[],[],0,0,2019-09-07,13:22:33

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/SportsCenterImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220174981595877376""","""1220174974771781632""",https://pbs.twimg.com/media/EO7urL8X4AAXzur.jpg,https://t.co/YJAYltIWoM
1,"""1220174981595877376""","""1220174978865410050""",https://pbs.twimg.com/media/EO7urbMXsAIF25Z.jpg,https://t.co/YJAYltIWoM
2,"""1220174835281731584""","""1220174831896932352""",https://pbs.twimg.com/media/EO7ui3sWsAApOk4.jpg,https://t.co/iXszAO9S2H
3,"""1220164231758336000""","""1220164229778550785""",https://pbs.twimg.com/media/EO7k5vuWsAEE0pq.jpg,https://t.co/Clmayens3c
4,"""1220127900466401280""","""1220127898381836288""",https://pbs.twimg.com/media/EO7D2-uX4AAkh0V.jpg,https://t.co/aONh5w4V5B
...,...,...,...,...
1136,"""1170441883228807168""","""1170441879999176705""",https://pbs.twimg.com/media/ED4-sEeXYAEzrzO.jpg,https://t.co/WMcbDxcECb
1137,"""1170437834018369536""","""1170437832109957120""",https://pbs.twimg.com/media/ED47Ac6XoAAYfSm.jpg,https://t.co/63oM2yydS2
1138,"""1170416671745556481""","""1170416670126608386""",https://pbs.twimg.com/media/ED4nwqYXkAIz5b9.jpg,https://t.co/OcQFKYG61q
1139,"""1170381181273198592""","""1170381179364810755""",https://pbs.twimg.com/media/ED4He0_XoAMxc3N.jpg,https://t.co/9LI4XdRTuY
1140,"""1170365477257961472""","""1170365475173359616""",https://pbs.twimg.com/media/ED35MuUW4AAQJqD.jpg,https://t.co/ppeTh2biUP

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1141, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1141, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                   Tweet Id       Images
0     "1220174981595877376"  Image added
1     "1220174981595877376"  Image added
2     "1220174835281731584"  Image added
3     "1220164231758336000"  Image added
4     "1220127900466401280"  Image added
...                     ...          ...
1136  "1170441883228807168"  Image added
1137  "1170437834018369536"  Image added
1138  "1170416671745556481"  Image added
1139  "1170381181273198592"  Image added
1140  "1170365477257961472"  Image added

[1141 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1220229853557018625""","""SportsCenter""",sportscenter,"""‚ÄúCoach, I can win the game for this team. Lea...",876,4834,[@MarcJSpearsESPN)],[],0,1,2020-01-23,06:20:42,NaN
1,"""1220222069020991489""","""SportsCenter""",sportscenter,"""‚ö°Ô∏è 22 Pts\n‚ö°Ô∏è 8-11 FG\n‚ö°Ô∏è 4-4 3-PT FG\n‚ö°Ô∏è 7 R...",1649,10240,[],[],0,0,2020-01-23,05:49:46,NaN
2,"""1220206449479028737""","""SportsCenter""",sportscenter,"""ZION IS TAKING OVER üî•\n\n17 STRAIGHT üò± https:...",4595,25871,[],[],0,0,2020-01-23,04:47:42,NaN
3,"""1220200064896970752""","""SportsCenter""",sportscenter,"""LeBron was asked about possibly playing for t...",3449,27910,[],[],0,0,2020-01-23,04:22:20,NaN
4,"""1220187706791165952""","""SportsCenter""",sportscenter,"""Coach Cal was there to see D-Rose in Detroit ...",1350,15035,[],[],0,0,2020-01-23,03:33:13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3300,"""1170365477257961472""","""SportsCenter""",sportscenter,"""Breaking: The Raiders have released Antonio B...",16123,49688,[],[],0,0,2019-09-07,15:57:28,Image added
3301,"""1170360002638471169""","""SportsCenter""",sportscenter,"""CLEAN RIGHT HAND KO\n\n#UFC242 ON ESPN+ ‚û°Ô∏è ht...",212,1021,[],[#UFC242],1,0,2019-09-07,15:35:43,NaN
3302,"""1170340635674415107""","""Dianna""",diannaespn,"""Spoke to a source in the Raiders building abo...",673,2823,[],"[#Raiders""]",1,0,2019-09-07,14:18:46,NaN
3303,"""1170328579349143553""","""Jeff Darlington""",jeffdarlington,"""I just got an email from Antonio Brown. He te...",8964,28549,[],[],0,0,2019-09-07,13:30:51,NaN
3304,"""1170326488174006272""","""Adam Schefter""",adamschefter,"""By fining Antonio Brown $215,073.53 last nigh...",10571,32940,[],[],0,0,2019-09-07,13:22:33,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/SportsCenterVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220229853557018625""","""1220229766281695232""",https://video.twimg.com/ext_tw_video/122022976...,https://t.co/DyQ2WvUGU4
1,"""1220222069020991489""","""1220220113187672064""",https://video.twimg.com/amplify_video/12202201...,https://t.co/9NhQ2yJnEu
2,"""1220206449479028737""","""1220206373700620288""",https://video.twimg.com/ext_tw_video/122020637...,https://t.co/2EuO0xpJaF
3,"""1220200064896970752""","""1220199993237221377""",https://video.twimg.com/ext_tw_video/122019999...,https://t.co/4U8bGQ7tu9
4,"""1220187706791165952""","""1220187633328033794""",https://video.twimg.com/ext_tw_video/122018763...,https://t.co/wiXlIBQm6h
...,...,...,...,...
1795,"""1170476954656694273""","""1170476861115260928""",https://video.twimg.com/ext_tw_video/117047686...,https://t.co/9s2wX2Wspo
1796,"""1170450089569128448""","""1170450008249950208""",https://video.twimg.com/ext_tw_video/117045000...,https://t.co/xXr50Z4gvs
1797,"""1170408929349832704""","""1170408903030562816""",https://video.twimg.com/ext_tw_video/117040890...,https://t.co/oGn394TMUa
1798,"""1170374391412199425""","""1170372503723810816""",https://video.twimg.com/amplify_video/11703725...,https://t.co/fTcm5LBRQB
1799,"""1170360002638471169""","""1170359395429113857""",https://video.twimg.com/amplify_video/11703593...,https://t.co/gFr6nCLf33

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1800, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1800, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                   Tweet Id       Videos
0     "1220229853557018625"  Video added
1     "1220222069020991489"  Video added
2     "1220206449479028737"  Video added
3     "1220200064896970752"  Video added
4     "1220187706791165952"  Video added
...                     ...          ...
1795  "1170476954656694273"  Video added
1796  "1170450089569128448"  Video added
1797  "1170408929349832704"  Video added
1798  "1170374391412199425"  Video added
1799  "1170360002638471169"  Video added

[1800 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1220229853557018625""","""SportsCenter""",sportscenter,"""‚ÄúCoach, I can win the game for this team. Lea...",876,4834,[@MarcJSpearsESPN)],[],0,1,2020-01-23,06:20:42,NaN,Video added
1,"""1220222069020991489""","""SportsCenter""",sportscenter,"""‚ö°Ô∏è 22 Pts\n‚ö°Ô∏è 8-11 FG\n‚ö°Ô∏è 4-4 3-PT FG\n‚ö°Ô∏è 7 R...",1649,10240,[],[],0,0,2020-01-23,05:49:46,NaN,Video added
2,"""1220206449479028737""","""SportsCenter""",sportscenter,"""ZION IS TAKING OVER üî•\n\n17 STRAIGHT üò± https:...",4595,25871,[],[],0,0,2020-01-23,04:47:42,NaN,Video added
3,"""1220200064896970752""","""SportsCenter""",sportscenter,"""LeBron was asked about possibly playing for t...",3449,27910,[],[],0,0,2020-01-23,04:22:20,NaN,Video added
4,"""1220187706791165952""","""SportsCenter""",sportscenter,"""Coach Cal was there to see D-Rose in Detroit ...",1350,15035,[],[],0,0,2020-01-23,03:33:13,NaN,Video added
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3300,"""1170365477257961472""","""SportsCenter""",sportscenter,"""Breaking: The Raiders have released Antonio B...",16123,49688,[],[],0,0,2019-09-07,15:57:28,Image added,NaN
3301,"""1170360002638471169""","""SportsCenter""",sportscenter,"""CLEAN RIGHT HAND KO\n\n#UFC242 ON ESPN+ ‚û°Ô∏è ht...",212,1021,[],[#UFC242],1,0,2019-09-07,15:35:43,NaN,Video added
3302,"""1170340635674415107""","""Dianna""",diannaespn,"""Spoke to a source in the Raiders building abo...",673,2823,[],"[#Raiders""]",1,0,2019-09-07,14:18:46,NaN,NaN
3303,"""1170328579349143553""","""Jeff Darlington""",jeffdarlington,"""I just got an email from Antonio Brown. He te...",8964,28549,[],[],0,0,2019-09-07,13:30:51,NaN,NaN
3304,"""1170326488174006272""","""Adam Schefter""",adamschefter,"""By fining Antonio Brown $215,073.53 last nigh...",10571,32940,[],[],0,0,2019-09-07,13:22:33,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Organisation"

#Create an Vocation column 
Tweets_df['Vocation'] = "Sports"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3305, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1220229853557018625""","""SportsCenter""",sportscenter,876,4834,[@MarcJSpearsESPN)],[],0,1,2020-01-23,06:20:42,-,Video added,Organisation,Sports
1,"""1220222069020991489""","""SportsCenter""",sportscenter,1649,10240,[],[],0,0,2020-01-23,05:49:46,-,Video added,Organisation,Sports
2,"""1220206449479028737""","""SportsCenter""",sportscenter,4595,25871,[],[],0,0,2020-01-23,04:47:42,-,Video added,Organisation,Sports
3,"""1220200064896970752""","""SportsCenter""",sportscenter,3449,27910,[],[],0,0,2020-01-23,04:22:20,-,Video added,Organisation,Sports
4,"""1220187706791165952""","""SportsCenter""",sportscenter,1350,15035,[],[],0,0,2020-01-23,03:33:13,-,Video added,Organisation,Sports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3300,"""1170365477257961472""","""SportsCenter""",sportscenter,16123,49688,[],[],0,0,2019-09-07,15:57:28,Image added,-,Organisation,Sports
3301,"""1170360002638471169""","""SportsCenter""",sportscenter,212,1021,[],[#UFC242],1,0,2019-09-07,15:35:43,-,Video added,Organisation,Sports
3302,"""1170340635674415107""","""Dianna""",diannaespn,673,2823,[],"[#Raiders""]",1,0,2019-09-07,14:18:46,-,-,Organisation,Sports
3303,"""1170328579349143553""","""Jeff Darlington""",jeffdarlington,8964,28549,[],[],0,0,2019-09-07,13:30:51,-,-,Organisation,Sports
3304,"""1170326488174006272""","""Adam Schefter""",adamschefter,10571,32940,[],[],0,0,2019-09-07,13:22:33,-,-,Organisation,Sports

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3305, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1220229853557018625""","""SportsCenter""",sportscenter,Organisation,Sports,[],0,[@MarcJSpearsESPN)],1,4834,876,-,Video added,2020-01-23,06:20:42
"""1220222069020991489""","""SportsCenter""",sportscenter,Organisation,Sports,[],0,[],0,10240,1649,-,Video added,2020-01-23,05:49:46
"""1220206449479028737""","""SportsCenter""",sportscenter,Organisation,Sports,[],0,[],0,25871,4595,-,Video added,2020-01-23,04:47:42
"""1220200064896970752""","""SportsCenter""",sportscenter,Organisation,Sports,[],0,[],0,27910,3449,-,Video added,2020-01-23,04:22:20
"""1220187706791165952""","""SportsCenter""",sportscenter,Organisation,Sports,[],0,[],0,15035,1350,-,Video added,2020-01-23,03:33:13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""1170365477257961472""","""SportsCenter""",sportscenter,Organisation,Sports,[],0,[],0,49688,16123,Image added,-,2019-09-07,15:57:28
"""1170360002638471169""","""SportsCenter""",sportscenter,Organisation,Sports,[#UFC242],1,[],0,1021,212,-,Video added,2019-09-07,15:35:43
"""1170340635674415107""","""Dianna""",diannaespn,Organisation,Sports,"[#Raiders""]",1,[],0,2823,673,-,-,2019-09-07,14:18:46
"""1170328579349143553""","""Jeff Darlington""",jeffdarlington,Organisation,Sports,[],0,[],0,28549,8964,-,-,2019-09-07,13:30:51
"""1170326488174006272""","""Adam Schefter""",adamschefter,Organisation,Sports,[],0,[],0,32940,10571,-,-,2019-09-07,13:22:33

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/SportsCenter_df.csv')