##### ===================================================================================================================

#  Twitter Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/TwitterTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1238533432998838275""",https://twitter.com/twitter/status/12385334329...,2020-03-13 18:32:35,"""@litskinayo turns out you're not the only per...",Reply,Sprinklr,17,79,"""783214""","""Twitter""",twitter,Verified,https://twitter.com/twitter,Not Protected
1,"""1238206067143827457""",https://twitter.com/twitter/status/12382060671...,2020-03-12 20:51:45,"""@alicegoldfuss and remember we're all in this...",Reply,Sprinklr,1,27,"""783214""","""Twitter""",twitter,Verified,https://twitter.com/twitter,Not Protected
2,"""1237864548587069451""",https://twitter.com/twitter/status/12378645485...,2020-03-11 22:14:41,"""@cryingyoon yeah they give us the confidence ...",Reply,Sprinklr,52,1034,"""783214""","""Twitter""",twitter,Verified,https://twitter.com/twitter,Not Protected
3,"""1237766891915087872""",https://twitter.com/twitter/status/12377668919...,2020-03-11 15:46:38,"""@illustjuan come for the memes, stay for the ...",Reply,Sprinklr,0,72,"""783214""","""Twitter""",twitter,Verified,https://twitter.com/twitter,Not Protected
4,"""1237512543817457664""",https://twitter.com/twitter/status/12375125438...,2020-03-10 22:55:56,"""@tobiomine could've sworn they were just there""",Reply,Sprinklr,5,46,"""783214""","""Twitter""",twitter,Verified,https://twitter.com/twitter,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1126680301693022208""",https://twitter.com/trevor_norris0/status/1126...,2019-05-10 02:48:11,"""Hello my name is Trevor Norris and I am here ...",Retweet,Twitter for iPhone,836,8225,"""1794348475""","""Trevor Norris""",trevor_norris0,Non-Verified,https://twitter.com/trevor_norris0,Not Protected
3196,"""1126607219049598978""",https://twitter.com/cosmis/status/112660721904...,2019-05-09 21:57:47,"""When you send your own tweet to the group DM ...",Retweet,Twitter for Android,2198,14563,"""22081681""","""Otto Porter Junior Senior""",cosmis,Non-Verified,https://twitter.com/cosmis,Not Protected
3197,"""1126597589028282380""",https://twitter.com/twitter/status/11265975890...,2019-05-09 21:19:31,"""@snuglytae Our final exam is on Tweeting""",Reply,Twitter Web App,10,127,"""783214""","""Twitter""",twitter,Verified,https://twitter.com/twitter,Not Protected
3198,"""1126597501358940175""",https://twitter.com/twitter/status/11265975013...,2019-05-09 21:19:10,"""@goodmiad Never let them catch you off guard""",Reply,Twitter Web App,5,23,"""783214""","""Twitter""",twitter,Verified,https://twitter.com/twitter,Not Protected
3199,"""1126580932813705217""",https://twitter.com/twitter/status/11265809328...,2019-05-09 20:13:19,"""@Rwnllpry Twitter: 92% + 8%""",Reply,Twitter Web App,1,23,"""783214""","""Twitter""",twitter,Verified,https://twitter.com/twitter,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1238533432998838275""","""Twitter""",twitter,"""@litskinayo turns out you're not the only per...",17,79,2020-03-13 18:32:35
1,"""1238206067143827457""","""Twitter""",twitter,"""@alicegoldfuss and remember we're all in this...",1,27,2020-03-12 20:51:45
2,"""1237864548587069451""","""Twitter""",twitter,"""@cryingyoon yeah they give us the confidence ...",52,1034,2020-03-11 22:14:41
3,"""1237766891915087872""","""Twitter""",twitter,"""@illustjuan come for the memes, stay for the ...",0,72,2020-03-11 15:46:38
4,"""1237512543817457664""","""Twitter""",twitter,"""@tobiomine could've sworn they were just there""",5,46,2020-03-10 22:55:56

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1238533432998838275""","""Twitter""",twitter,"""@litskinayo turns out you're not the only per...",17,79,2020-03-13 18:32:35,[@litskinayo],[],0,1
1,"""1238206067143827457""","""Twitter""",twitter,"""@alicegoldfuss and remember we're all in this...",1,27,2020-03-12 20:51:45,[@alicegoldfuss],[],0,1
2,"""1237864548587069451""","""Twitter""",twitter,"""@cryingyoon yeah they give us the confidence ...",52,1034,2020-03-11 22:14:41,[@cryingyoon],[],0,1
3,"""1237766891915087872""","""Twitter""",twitter,"""@illustjuan come for the memes, stay for the ...",0,72,2020-03-11 15:46:38,[@illustjuan],[],0,1
4,"""1237512543817457664""","""Twitter""",twitter,"""@tobiomine could've sworn they were just there""",5,46,2020-03-10 22:55:56,[@tobiomine],[],0,1
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1126680301693022208""","""Trevor Norris""",trevor_norris0,"""Hello my name is Trevor Norris and I am here ...",836,8225,2019-05-10 02:48:11,[@twitter],[],0,1
3196,"""1126607219049598978""","""Otto Porter Junior Senior""",cosmis,"""When you send your own tweet to the group DM ...",2198,14563,2019-05-09 21:57:47,[],[],0,0
3197,"""1126597589028282380""","""Twitter""",twitter,"""@snuglytae Our final exam is on Tweeting""",10,127,2019-05-09 21:19:31,[@snuglytae],[],0,1
3198,"""1126597501358940175""","""Twitter""",twitter,"""@goodmiad Never let them catch you off guard""",5,23,2019-05-09 21:19:10,[@goodmiad],[],0,1
3199,"""1126580932813705217""","""Twitter""",twitter,"""@Rwnllpry Twitter: 92% + 8%""",1,23,2019-05-09 20:13:19,[@Rwnllpry],[],0,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1238533432998838275""","""Twitter""",twitter,"""@litskinayo turns out you're not the only per...",17,79,[@litskinayo],[],0,1,2020-03-13,18:32:35
1,"""1238206067143827457""","""Twitter""",twitter,"""@alicegoldfuss and remember we're all in this...",1,27,[@alicegoldfuss],[],0,1,2020-03-12,20:51:45
2,"""1237864548587069451""","""Twitter""",twitter,"""@cryingyoon yeah they give us the confidence ...",52,1034,[@cryingyoon],[],0,1,2020-03-11,22:14:41
3,"""1237766891915087872""","""Twitter""",twitter,"""@illustjuan come for the memes, stay for the ...",0,72,[@illustjuan],[],0,1,2020-03-11,15:46:38
4,"""1237512543817457664""","""Twitter""",twitter,"""@tobiomine could've sworn they were just there""",5,46,[@tobiomine],[],0,1,2020-03-10,22:55:56
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""1126680301693022208""","""Trevor Norris""",trevor_norris0,"""Hello my name is Trevor Norris and I am here ...",836,8225,[@twitter],[],0,1,2019-05-10,02:48:11
3196,"""1126607219049598978""","""Otto Porter Junior Senior""",cosmis,"""When you send your own tweet to the group DM ...",2198,14563,[],[],0,0,2019-05-09,21:57:47
3197,"""1126597589028282380""","""Twitter""",twitter,"""@snuglytae Our final exam is on Tweeting""",10,127,[@snuglytae],[],0,1,2019-05-09,21:19:31
3198,"""1126597501358940175""","""Twitter""",twitter,"""@goodmiad Never let them catch you off guard""",5,23,[@goodmiad],[],0,1,2019-05-09,21:19:10
3199,"""1126580932813705217""","""Twitter""",twitter,"""@Rwnllpry Twitter: 92% + 8%""",1,23,[@Rwnllpry],[],0,1,2019-05-09,20:13:19

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/TwitterImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1233108795636801536""","""1233108792419766272""",https://pbs.twimg.com/media/ERzh6dWXUAAbjK_.jpg,https://t.co/hAINNvJgWx
1,"""1233108794416279554""","""1233108792428105731""",https://pbs.twimg.com/media/ERzh6dYWkAMuJw8.jpg,https://t.co/GVCZc7IZ0V
2,"""1233102909862268929""","""1233102907890860032""",https://pbs.twimg.com/media/ERzcj7xWAAAwX5g.jpg,https://t.co/04BtpIRFiq
3,"""1233102909245665281""","""1233102906200674304""",https://pbs.twimg.com/media/ERzcj1eX0AAPzR_.jpg,https://t.co/tke6LG2HVn
4,"""1233102908587233281""","""1233102906175426560""",https://pbs.twimg.com/media/ERzcj1YWkAAJ9Sb.jpg,https://t.co/IGdEl4NT9V
...,...,...,...,...
125,"""1134063285928636416""","""1134063281407242241""",https://pbs.twimg.com/media/D70Ai8EXsAE3RAY.jpg,https://t.co/v5UKn5K4E6
126,"""1134063285928636416""","""1134063281411411968""",https://pbs.twimg.com/media/D70Ai8FXUAAIeI8.jpg,https://t.co/v5UKn5K4E6
127,"""1128417739113152512""","""1128417737439698944""",https://pbs.twimg.com/media/D6jx9B5X4AASBu_.jpg,https://t.co/DCxoALipVY
128,"""1126680301693022208""","""1126680290687094784""",https://pbs.twimg.com/media/D6LFwUXWkAAe0gh.jpg,https://t.co/qdCyt44hMp
129,"""1126607219049598978""","""1126607217271218182""",https://pbs.twimg.com/media/D6KDS4rXoAYlz8D.jpg,https://t.co/iLQKhB4xAx

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (130, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (130, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1233108795636801536"  Image added
1    "1233108794416279554"  Image added
2    "1233102909862268929"  Image added
3    "1233102909245665281"  Image added
4    "1233102908587233281"  Image added
..                     ...          ...
125  "1134063285928636416"  Image added
126  "1134063285928636416"  Image added
127  "1128417739113152512"  Image added
128  "1126680301693022208"  Image added
129  "1126607219049598978"  Image added

[130 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1238533432998838275""","""Twitter""",twitter,"""@litskinayo turns out you're not the only per...",17,79,[@litskinayo],[],0,1,2020-03-13,18:32:35,NaN
1,"""1238206067143827457""","""Twitter""",twitter,"""@alicegoldfuss and remember we're all in this...",1,27,[@alicegoldfuss],[],0,1,2020-03-12,20:51:45,NaN
2,"""1237864548587069451""","""Twitter""",twitter,"""@cryingyoon yeah they give us the confidence ...",52,1034,[@cryingyoon],[],0,1,2020-03-11,22:14:41,NaN
3,"""1237766891915087872""","""Twitter""",twitter,"""@illustjuan come for the memes, stay for the ...",0,72,[@illustjuan],[],0,1,2020-03-11,15:46:38,NaN
4,"""1237512543817457664""","""Twitter""",twitter,"""@tobiomine could've sworn they were just there""",5,46,[@tobiomine],[],0,1,2020-03-10,22:55:56,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3213,"""1126680301693022208""","""Trevor Norris""",trevor_norris0,"""Hello my name is Trevor Norris and I am here ...",836,8225,[@twitter],[],0,1,2019-05-10,02:48:11,Image added
3214,"""1126607219049598978""","""Otto Porter Junior Senior""",cosmis,"""When you send your own tweet to the group DM ...",2198,14563,[],[],0,0,2019-05-09,21:57:47,Image added
3215,"""1126597589028282380""","""Twitter""",twitter,"""@snuglytae Our final exam is on Tweeting""",10,127,[@snuglytae],[],0,1,2019-05-09,21:19:31,NaN
3216,"""1126597501358940175""","""Twitter""",twitter,"""@goodmiad Never let them catch you off guard""",5,23,[@goodmiad],[],0,1,2019-05-09,21:19:10,NaN
3217,"""1126580932813705217""","""Twitter""",twitter,"""@Rwnllpry Twitter: 92% + 8%""",1,23,[@Rwnllpry],[],0,1,2019-05-09,20:13:19,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/TwitterVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1234142094400212992""","""1234139472704393216""",https://video.twimg.com/tweet_video/ESCLT8nVUA...,https://t.co/9wXXfj1k1z
1,"""1230267622903689225""","""1230267571569676289""",https://video.twimg.com/tweet_video/ERLJ1o4X0A...,https://t.co/j3ktAN6t5o
2,"""1223623969611190273""","""1223623924807634944""",https://video.twimg.com/tweet_video/EPsvegDUEA...,https://t.co/6hqBdeiLVC
3,"""1204827212731625473""","""1204816991636402176""",https://video.twimg.com/amplify_video/12048169...,https://t.co/D8TIfsBwyd
4,"""1197551185894559744""","""1197551094341292033""",https://video.twimg.com/tweet_video/EJ6OYBqX0A...,https://t.co/0Cfe4NMVPj
5,"""1194015365845700608""","""1194015284270698496""",https://video.twimg.com/ext_tw_video/119401528...,https://t.co/3tVBRFuTYd
6,"""1188832461544775680""","""1188832393005658112""",https://video.twimg.com/ext_tw_video/118883239...,https://t.co/Lzsl3VD0aX
7,"""1186690182017437696""","""1186690157291999234""",https://video.twimg.com/tweet_video/EHf4aSPXkA...,https://t.co/RpvstZvdnr
8,"""1184938571116900352""","""1184938497595133962""",https://video.twimg.com/tweet_video/EHG_SRXX0A...,https://t.co/Qewadtmcsb
9,"""1184932951081078796""","""1184116249569026048""",https://video.twimg.com/ext_tw_video/118411624...,https://t.co/RnUECXuKqM
10,"""1176612568196091908""","""1176612444153831429""",https://video.twimg.com/ext_tw_video/117661244...,https://t.co/nuz9WDOHwF
11,"""1176225981067071489""","""1176225896941936640""",https://video.twimg.com/tweet_video/EFLLOKrW4A...,https://t.co/gNdfNE1DCl
12,"""1174478270181597184""","""1174151835772497922""",https://video.twimg.com/ext_tw_video/117415183...,https://t.co/rh1T4qCOjY
13,"""1173316185850429445""","""1173082291465261056""",https://video.twimg.com/ext_tw_video/117308229...,https://t.co/ILAFpJ8vjw
14,"""1171560988874891264""","""1171560943689588739""",https://video.twimg.com/tweet_video/EEI4eJlW4A...,https://t.co/mllwmPb6dx
15,"""1166372715831296006""","""1035344874118107136""",https://video.twimg.com/ext_tw_video/103534487...,https://t.co/kjEvzHnXVz
16,"""1162114957762150400""","""1162114927642808320""",https://video.twimg.com/tweet_video/ECCpXppUEA...,https://t.co/Sg5idjdeVv
17,"""1161692603345252352""","""1161692551692378112""",https://video.twimg.com/tweet_video/EB8pOInXYA...,https://t.co/vwGlBjz4B5
18,"""1161669861837365250""","""1161669850848288768""",https://video.twimg.com/tweet_video/EB8UkxYX4A...,https://t.co/uzpRZszp29
19,"""1161384682459672576""","""1161384586498252800""",https://video.twimg.com/tweet_video/EB4RIM3XoA...,https://t.co/tSuEjlqWDs
20,"""1159593626294525954""","""1159593028216119296""",https://video.twimg.com/tweet_video/EBeztyLXYA...,https://t.co/MabdFoItxc
21,"""1157001333175660545""","""1157001164438867969""",https://video.twimg.com/ext_tw_video/115700116...,https://t.co/WoldOPZ23D
22,"""1155864090918735872""","""1155862900654903302""",https://video.twimg.com/amplify_video/11558629...,https://t.co/AazVBE6n8X
23,"""1155069318075260929""","""1155034094004080640""",https://video.twimg.com/amplify_video/11550340...,https://t.co/kY1xudWtxQ
24,"""1153738821256785920""","""1153738747218976768""",https://video.twimg.com/tweet_video/EALnRx-XYA...,https://t.co/9wV1zOjcOq
25,"""1151221192977780736""","""1151220926903545856""",https://video.twimg.com/tweet_video/D_n1VWYU8A...,https://t.co/VlFTiV15ea
26,"""1150950109942882305""","""1150949761622663168""",https://video.twimg.com/ext_tw_video/115094976...,https://t.co/iuK9R4Coyf
27,"""1150885580869447680""","""1150885518311399425""",https://video.twimg.com/ext_tw_video/115088551...,https://t.co/qG6d54V5Dd
28,"""1150812293124546561""","""1150759971900002305""",https://video.twimg.com/amplify_video/11507599...,https://t.co/8y4TMzqBGa
29,"""1150767881845690369""","""1150767837931364352""",https://video.twimg.com/tweet_video/D_hZQGbX4A...,https://t.co/LRnQ8JGysw
30,"""1144340785246146561""","""1143823914918916097""",https://video.twimg.com/ext_tw_video/114382391...,https://t.co/Auz9Lt2ieK
31,"""1143624280401502208""","""1143624045025513475""",https://video.twimg.com/tweet_video/D974AoBXUA...,https://t.co/g5WMaNZ57N
32,"""1143276915169488897""","""1143276242629623808""",https://video.twimg.com/ext_tw_video/114327624...,https://t.co/WjzKpGiPcl
33,"""1141813717476265985""","""1141813702083207168""",https://video.twimg.com/tweet_video/D9iJgzBX4A...,https://t.co/5XegAIQ4lo
34,"""1140945201529348096""","""1140945093018431488""",https://video.twimg.com/tweet_video/D9VzhGGWsA...,https://t.co/YpPWP4Aq7a
35,"""1138500378234949634""","""1138500351378755586""",https://video.twimg.com/tweet_video/D8zECZyWkA...,https://t.co/d6hpgYMpMs
36,"""1138389828167274496""","""1138380033771286528""",https://video.twimg.com/amplify_video/11383800...,https://t.co/X3CpOsSbw4
37,"""1134807066185555968""","""1134804634491654144""",https://video.twimg.com/tweet_video/D7-izXhXkA...,https://t.co/m2AavxveyI
38,"""1133786992628719616""","""1133771003270713345""",https://video.twimg.com/amplify_video/11337710...,https://t.co/CB5qSLebwq
39,"""1129059497132068867""","""1129059475472736263""",https://video.twimg.com/ext_tw_video/112905947...,https://t.co/43LQsKej3e
40,"""1127651397229535233""","""1127651344914030593""",https://video.twimg.com/ext_tw_video/112765134...,https://t.co/xqa1LH7YzP

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (41, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (41, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                 Tweet Id       Videos
0   "1234142094400212992"  Video added
1   "1230267622903689225"  Video added
2   "1223623969611190273"  Video added
3   "1204827212731625473"  Video added
4   "1197551185894559744"  Video added
5   "1194015365845700608"  Video added
6   "1188832461544775680"  Video added
7   "1186690182017437696"  Video added
8   "1184938571116900352"  Video added
9   "1184932951081078796"  Video added
10  "1176612568196091908"  Video added
11  "1176225981067071489"  Video added
12  "1174478270181597184"  Video added
13  "1173316185850429445"  Video added
14  "1171560988874891264"  Video added
15  "1166372715831296006"  Video added
16  "1162114957762150400"  Video added
17  "1161692603345252352"  Video added
18  "1161669861837365250"  Video added
19  "1161384682459672576"  Video added
20  "1159593626294525954"  Video added
21  "1157001333175660545"  Video added
22  "1155864090918735872"  Video added
23  "1155069318075260929"  Video added
24  "1153738821256785920"  Video added
25  "1151221192977780736"  Video added
26  "1150950109942882305"  Video added
27  "1150885580869447680"  Video added
28  "1150812293124546561"  Video added
29  "1150767881845690369"  Video added
30  "1144340785246146561"  Video added
31  "1143624280401502208"  Video added
32  "1143276915169488897"  Video added
33  "1141813717476265985"  Video added
34  "1140945201529348096"  Video added
35  "1138500378234949634"  Video added
36  "1138389828167274496"  Video added
37  "1134807066185555968"  Video added
38  "1133786992628719616"  Video added
39  "1129059497132068867"  Video added
40  "1127651397229535233"  Video added

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1238533432998838275""","""Twitter""",twitter,"""@litskinayo turns out you're not the only per...",17,79,[@litskinayo],[],0,1,2020-03-13,18:32:35,NaN,NaN
1,"""1238206067143827457""","""Twitter""",twitter,"""@alicegoldfuss and remember we're all in this...",1,27,[@alicegoldfuss],[],0,1,2020-03-12,20:51:45,NaN,NaN
2,"""1237864548587069451""","""Twitter""",twitter,"""@cryingyoon yeah they give us the confidence ...",52,1034,[@cryingyoon],[],0,1,2020-03-11,22:14:41,NaN,NaN
3,"""1237766891915087872""","""Twitter""",twitter,"""@illustjuan come for the memes, stay for the ...",0,72,[@illustjuan],[],0,1,2020-03-11,15:46:38,NaN,NaN
4,"""1237512543817457664""","""Twitter""",twitter,"""@tobiomine could've sworn they were just there""",5,46,[@tobiomine],[],0,1,2020-03-10,22:55:56,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3213,"""1126680301693022208""","""Trevor Norris""",trevor_norris0,"""Hello my name is Trevor Norris and I am here ...",836,8225,[@twitter],[],0,1,2019-05-10,02:48:11,Image added,NaN
3214,"""1126607219049598978""","""Otto Porter Junior Senior""",cosmis,"""When you send your own tweet to the group DM ...",2198,14563,[],[],0,0,2019-05-09,21:57:47,Image added,NaN
3215,"""1126597589028282380""","""Twitter""",twitter,"""@snuglytae Our final exam is on Tweeting""",10,127,[@snuglytae],[],0,1,2019-05-09,21:19:31,NaN,NaN
3216,"""1126597501358940175""","""Twitter""",twitter,"""@goodmiad Never let them catch you off guard""",5,23,[@goodmiad],[],0,1,2019-05-09,21:19:10,NaN,NaN
3217,"""1126580932813705217""","""Twitter""",twitter,"""@Rwnllpry Twitter: 92% + 8%""",1,23,[@Rwnllpry],[],0,1,2019-05-09,20:13:19,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Organisation"

#Create an Vocation column 
Tweets_df['Vocation'] = "Entertainment"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3218, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1238533432998838275""","""Twitter""",twitter,17,79,[@litskinayo],[],0,1,2020-03-13,18:32:35,-,-,Organisation,Entertainment
1,"""1238206067143827457""","""Twitter""",twitter,1,27,[@alicegoldfuss],[],0,1,2020-03-12,20:51:45,-,-,Organisation,Entertainment
2,"""1237864548587069451""","""Twitter""",twitter,52,1034,[@cryingyoon],[],0,1,2020-03-11,22:14:41,-,-,Organisation,Entertainment
3,"""1237766891915087872""","""Twitter""",twitter,0,72,[@illustjuan],[],0,1,2020-03-11,15:46:38,-,-,Organisation,Entertainment
4,"""1237512543817457664""","""Twitter""",twitter,5,46,[@tobiomine],[],0,1,2020-03-10,22:55:56,-,-,Organisation,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3213,"""1126680301693022208""","""Trevor Norris""",trevor_norris0,836,8225,[@twitter],[],0,1,2019-05-10,02:48:11,Image added,-,Organisation,Entertainment
3214,"""1126607219049598978""","""Otto Porter Junior Senior""",cosmis,2198,14563,[],[],0,0,2019-05-09,21:57:47,Image added,-,Organisation,Entertainment
3215,"""1126597589028282380""","""Twitter""",twitter,10,127,[@snuglytae],[],0,1,2019-05-09,21:19:31,-,-,Organisation,Entertainment
3216,"""1126597501358940175""","""Twitter""",twitter,5,23,[@goodmiad],[],0,1,2019-05-09,21:19:10,-,-,Organisation,Entertainment
3217,"""1126580932813705217""","""Twitter""",twitter,1,23,[@Rwnllpry],[],0,1,2019-05-09,20:13:19,-,-,Organisation,Entertainment

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3218, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1238533432998838275""","""Twitter""",twitter,Organisation,Entertainment,[],0,[@litskinayo],1,79,17,-,-,2020-03-13,18:32:35
"""1238206067143827457""","""Twitter""",twitter,Organisation,Entertainment,[],0,[@alicegoldfuss],1,27,1,-,-,2020-03-12,20:51:45
"""1237864548587069451""","""Twitter""",twitter,Organisation,Entertainment,[],0,[@cryingyoon],1,1034,52,-,-,2020-03-11,22:14:41
"""1237766891915087872""","""Twitter""",twitter,Organisation,Entertainment,[],0,[@illustjuan],1,72,0,-,-,2020-03-11,15:46:38
"""1237512543817457664""","""Twitter""",twitter,Organisation,Entertainment,[],0,[@tobiomine],1,46,5,-,-,2020-03-10,22:55:56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""1126680301693022208""","""Trevor Norris""",trevor_norris0,Organisation,Entertainment,[],0,[@twitter],1,8225,836,Image added,-,2019-05-10,02:48:11
"""1126607219049598978""","""Otto Porter Junior Senior""",cosmis,Organisation,Entertainment,[],0,[],0,14563,2198,Image added,-,2019-05-09,21:57:47
"""1126597589028282380""","""Twitter""",twitter,Organisation,Entertainment,[],0,[@snuglytae],1,127,10,-,-,2019-05-09,21:19:31
"""1126597501358940175""","""Twitter""",twitter,Organisation,Entertainment,[],0,[@goodmiad],1,23,5,-,-,2019-05-09,21:19:10
"""1126580932813705217""","""Twitter""",twitter,Organisation,Entertainment,[],0,[@Rwnllpry],1,23,1,-,-,2019-05-09,20:13:19

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/Twitter_df.csv')