##### ===================================================================================================================

#  Virat Kohli Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/ViratKohliTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1219870407676678144""",https://twitter.com/imvkohli/status/1219870407...,2020-01-22 06:32:23,"""Stylish, elegant and classy. An absolute beas...",Tweet,Twitter for Android,1707,35917,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
1,"""1219814892170964992""",https://twitter.com/imvkohli/status/1219814892...,2020-01-22 02:51:48,"""Top team gym session and a good meal out in b...",Tweet,Twitter for Android,3515,81896,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
2,"""1219631268738084868""",https://twitter.com/imvkohli/status/1219631268...,2020-01-21 14:42:08,"""Touchdown Auckland. Let‚Äôs go üáÆüá≥ @imShard @Shr...",Tweet,Twitter for Android,3598,79331,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
3,"""1219175442898276352""",https://twitter.com/imvkohli/status/1219175442...,2020-01-20 08:30:51,"""üëäüèºüëäüèºüëäüèº https://t.co/ot4qLbfkvM""",Tweet,Twitter for Android,1889,31973,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
4,"""1218938883745837056""",https://twitter.com/imvkohli/status/1218938883...,2020-01-19 16:50:51,"""Soaring High üèÜüáÆüá≥üíô #IndvAus https://t.co/Zjo3m...",Tweet,Twitter for Android,14067,189812,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051,"""4168829709""",https://twitter.com/imvkohli/status/4168829709,2009-09-22 09:44:31,"""@yuvsingh09 Hello Mr.Bond \nwatched it you we...",Reply,Twitter Web Client,10,36,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
2052,"""4168263153""",https://twitter.com/imvkohli/status/4168263153,2009-09-22 08:46:33,"""@hulk7174 ??????""",Reply,Twitter Web Client,9,44,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
2053,"""4167514786""",https://twitter.com/imvkohli/status/4167514786,2009-09-22 07:32:46,"""Time for Training....""",Tweet,Twitter Web Client,51,86,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
2054,"""3889494504""",https://twitter.com/imvkohli/status/3889494504,2009-09-10 15:36:10,"""Will be heading to SriLanka Woohoo !!!""",Tweet,Twitter Web Client,63,117,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected
2055,"""3754340192""",https://twitter.com/imvkohli/status/3754340192,2009-09-04 10:31:36,"""@yuvsingh09 Aiieeeeeee me too me too""",Reply,Twitter Web Client,166,241,"""71201743""","""Virat Kohli""",imvkohli,Verified,https://twitter.com/imvkohli,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (2056, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (2056, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1219870407676678144""","""Virat Kohli""",imvkohli,"""Stylish, elegant and classy. An absolute beas...",1707,35917,2020-01-22 06:32:23
1,"""1219814892170964992""","""Virat Kohli""",imvkohli,"""Top team gym session and a good meal out in b...",3515,81896,2020-01-22 02:51:48
2,"""1219631268738084868""","""Virat Kohli""",imvkohli,"""Touchdown Auckland. Let‚Äôs go üáÆüá≥ @imShard @Shr...",3598,79331,2020-01-21 14:42:08
3,"""1219175442898276352""","""Virat Kohli""",imvkohli,"""üëäüèºüëäüèºüëäüèº https://t.co/ot4qLbfkvM""",1889,31973,2020-01-20 08:30:51
4,"""1218938883745837056""","""Virat Kohli""",imvkohli,"""Soaring High üèÜüáÆüá≥üíô #IndvAus https://t.co/Zjo3m...",14067,189812,2020-01-19 16:50:51

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1219870407676678144""","""Virat Kohli""",imvkohli,"""Stylish, elegant and classy. An absolute beas...",1707,35917,2020-01-22 06:32:23,[@AudiIN],"[#AudiQ8, #8thDimension]",2,1
1,"""1219814892170964992""","""Virat Kohli""",imvkohli,"""Top team gym session and a good meal out in b...",3515,81896,2020-01-22 02:51:48,"[@im_manishpandey, @imjadeja, @klrahul11]",[],0,3
2,"""1219631268738084868""","""Virat Kohli""",imvkohli,"""Touchdown Auckland. Let‚Äôs go üáÆüá≥ @imShard @Shr...",3598,79331,2020-01-21 14:42:08,"[@imShard, @ShreyasIyer15]",[],0,2
3,"""1219175442898276352""","""Virat Kohli""",imvkohli,"""üëäüèºüëäüèºüëäüèº https://t.co/ot4qLbfkvM""",1889,31973,2020-01-20 08:30:51,[],[],0,0
4,"""1218938883745837056""","""Virat Kohli""",imvkohli,"""Soaring High üèÜüáÆüá≥üíô #IndvAus https://t.co/Zjo3m...",14067,189812,2020-01-19 16:50:51,[],[#IndvAus],1,0
...,...,...,...,...,...,...,...,...,...,...,...
2051,"""4168829709""","""Virat Kohli""",imvkohli,"""@yuvsingh09 Hello Mr.Bond \nwatched it you we...",10,36,2009-09-22 09:44:31,[@yuvsingh09],[],0,1
2052,"""4168263153""","""Virat Kohli""",imvkohli,"""@hulk7174 ??????""",9,44,2009-09-22 08:46:33,[@hulk7174],[],0,1
2053,"""4167514786""","""Virat Kohli""",imvkohli,"""Time for Training....""",51,86,2009-09-22 07:32:46,[],[],0,0
2054,"""3889494504""","""Virat Kohli""",imvkohli,"""Will be heading to SriLanka Woohoo !!!""",63,117,2009-09-10 15:36:10,[],[],0,0
2055,"""3754340192""","""Virat Kohli""",imvkohli,"""@yuvsingh09 Aiieeeeeee me too me too""",166,241,2009-09-04 10:31:36,[@yuvsingh09],[],0,1

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (2056, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1219870407676678144""","""Virat Kohli""",imvkohli,"""Stylish, elegant and classy. An absolute beas...",1707,35917,[@AudiIN],"[#AudiQ8, #8thDimension]",2,1,2020-01-22,06:32:23
1,"""1219814892170964992""","""Virat Kohli""",imvkohli,"""Top team gym session and a good meal out in b...",3515,81896,"[@im_manishpandey, @imjadeja, @klrahul11]",[],0,3,2020-01-22,02:51:48
2,"""1219631268738084868""","""Virat Kohli""",imvkohli,"""Touchdown Auckland. Let‚Äôs go üáÆüá≥ @imShard @Shr...",3598,79331,"[@imShard, @ShreyasIyer15]",[],0,2,2020-01-21,14:42:08
3,"""1219175442898276352""","""Virat Kohli""",imvkohli,"""üëäüèºüëäüèºüëäüèº https://t.co/ot4qLbfkvM""",1889,31973,[],[],0,0,2020-01-20,08:30:51
4,"""1218938883745837056""","""Virat Kohli""",imvkohli,"""Soaring High üèÜüáÆüá≥üíô #IndvAus https://t.co/Zjo3m...",14067,189812,[],[#IndvAus],1,0,2020-01-19,16:50:51
...,...,...,...,...,...,...,...,...,...,...,...,...
2051,"""4168829709""","""Virat Kohli""",imvkohli,"""@yuvsingh09 Hello Mr.Bond \nwatched it you we...",10,36,[@yuvsingh09],[],0,1,2009-09-22,09:44:31
2052,"""4168263153""","""Virat Kohli""",imvkohli,"""@hulk7174 ??????""",9,44,[@hulk7174],[],0,1,2009-09-22,08:46:33
2053,"""4167514786""","""Virat Kohli""",imvkohli,"""Time for Training....""",51,86,[],[],0,0,2009-09-22,07:32:46
2054,"""3889494504""","""Virat Kohli""",imvkohli,"""Will be heading to SriLanka Woohoo !!!""",63,117,[],[],0,0,2009-09-10,15:36:10
2055,"""3754340192""","""Virat Kohli""",imvkohli,"""@yuvsingh09 Aiieeeeeee me too me too""",166,241,[@yuvsingh09],[],0,1,2009-09-04,10:31:36

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/ViratKohliImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1219870407676678144""","""1219870396649897984""",https://pbs.twimg.com/media/EO3ZqaBVAAAwg0V.jpg,https://t.co/Tg0XJVeErX
1,"""1219814892170964992""","""1219814880116498433""",https://pbs.twimg.com/media/EO2nK60UYAEfchE.jpg,https://t.co/nAuA1ro58h
2,"""1219631268738084868""","""1219631256633331716""",https://pbs.twimg.com/media/EO0AKoCX0AQyG4o.jpg,https://t.co/8Lo2c1usmM
3,"""1218938883745837056""","""1218938873931161600""",https://pbs.twimg.com/media/EOqKcpeU4AAeFYn.jpg,https://t.co/Zjo3mReSWD
4,"""1218215402121113604""","""1218215375537496067""",https://pbs.twimg.com/media/EOf4bf7U4AMjSC6.jpg,https://t.co/JWMMgFGQpd
...,...,...,...,...
772,"""258137648768634880""","""258137648772829184""",https://pbs.twimg.com/media/A5UW0upCUAA9ogj.jpg,http://t.co/GX7eYoWU
773,"""258137385420877825""","""258137385425072128""",https://pbs.twimg.com/media/A5UWlZmCcAAWB3u.jpg,http://t.co/173KVHXw
774,"""236082414668099585""","""236082414672293889""",https://pbs.twimg.com/media/A0a7tJBCMAE45hr.jpg,http://t.co/yJrvoqMO
775,"""207508150398623744""","""207508150402818048""",https://pbs.twimg.com/media/AuE3kDjCIAA9KJl.jpg,http://t.co/2vjb4kZZ
776,"""156693353503797249""","""156693353512185856""",https://pbs.twimg.com/media/AiyvxlrCMAA3c74.png,http://t.co/j6VkrdN3

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (777, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (777, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1219870407676678144"  Image added
1    "1219814892170964992"  Image added
2    "1219631268738084868"  Image added
3    "1218938883745837056"  Image added
4    "1218215402121113604"  Image added
..                     ...          ...
772   "258137648768634880"  Image added
773   "258137385420877825"  Image added
774   "236082414668099585"  Image added
775   "207508150398623744"  Image added
776   "156693353503797249"  Image added

[777 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1219870407676678144""","""Virat Kohli""",imvkohli,"""Stylish, elegant and classy. An absolute beas...",1707,35917,[@AudiIN],"[#AudiQ8, #8thDimension]",2,1,2020-01-22,06:32:23,Image added
1,"""1219814892170964992""","""Virat Kohli""",imvkohli,"""Top team gym session and a good meal out in b...",3515,81896,"[@im_manishpandey, @imjadeja, @klrahul11]",[],0,3,2020-01-22,02:51:48,Image added
2,"""1219631268738084868""","""Virat Kohli""",imvkohli,"""Touchdown Auckland. Let‚Äôs go üáÆüá≥ @imShard @Shr...",3598,79331,"[@imShard, @ShreyasIyer15]",[],0,2,2020-01-21,14:42:08,Image added
3,"""1219175442898276352""","""Virat Kohli""",imvkohli,"""üëäüèºüëäüèºüëäüèº https://t.co/ot4qLbfkvM""",1889,31973,[],[],0,0,2020-01-20,08:30:51,NaN
4,"""1218938883745837056""","""Virat Kohli""",imvkohli,"""Soaring High üèÜüáÆüá≥üíô #IndvAus https://t.co/Zjo3m...",14067,189812,[],[#IndvAus],1,0,2020-01-19,16:50:51,Image added
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,"""4168829709""","""Virat Kohli""",imvkohli,"""@yuvsingh09 Hello Mr.Bond \nwatched it you we...",10,36,[@yuvsingh09],[],0,1,2009-09-22,09:44:31,NaN
2200,"""4168263153""","""Virat Kohli""",imvkohli,"""@hulk7174 ??????""",9,44,[@hulk7174],[],0,1,2009-09-22,08:46:33,NaN
2201,"""4167514786""","""Virat Kohli""",imvkohli,"""Time for Training....""",51,86,[],[],0,0,2009-09-22,07:32:46,NaN
2202,"""3889494504""","""Virat Kohli""",imvkohli,"""Will be heading to SriLanka Woohoo !!!""",63,117,[],[],0,0,2009-09-10,15:36:10,NaN
2203,"""3754340192""","""Virat Kohli""",imvkohli,"""@yuvsingh09 Aiieeeeeee me too me too""",166,241,[@yuvsingh09],[],0,1,2009-09-04,10:31:36,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/ViratKohliVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1218409278949613569""","""1218409199845044225""",https://video.twimg.com/ext_tw_video/121840919...,https://t.co/2Ik2zrRmgu
1,"""1210610311671111680""","""1210610264829071360""",https://video.twimg.com/ext_tw_video/121061026...,https://t.co/MtaaO0vDDt
2,"""1207927652079812608""","""1207921832839520256""",https://video.twimg.com/amplify_video/12079218...,https://t.co/VF8ltmDZPm
3,"""1205463037492248576""","""1205462680401612801""",https://video.twimg.com/ext_tw_video/120546268...,https://t.co/hZe85qpyCw
4,"""1202187084238188544""","""1202186818575204352""",https://video.twimg.com/ext_tw_video/120218681...,https://t.co/qciouada9F
...,...,...,...,...
227,"""729212916092768256""","""729212291380555776""",https://video.twimg.com/ext_tw_video/729212291...,https://t.co/x4ZprPxopt
228,"""726088331214372865""","""726087925029568512""",https://video.twimg.com/ext_tw_video/726087925...,https://t.co/SNW4kcpqhr
229,"""708620162946064384""","""708620023565135872""",https://video.twimg.com/ext_tw_video/708620023...,https://t.co/1dj46NDsmh
230,"""682603815313473536""","""682603649281966080""",https://video.twimg.com/ext_tw_video/682603649...,https://t.co/b0LufbFvUM
231,"""680363304368377856""","""680363097874427904""",https://video.twimg.com/ext_tw_video/680363097...,https://t.co/oUU7dcrJ1p

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (232, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (232, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                  Tweet Id       Videos
0    "1218409278949613569"  Video added
1    "1210610311671111680"  Video added
2    "1207927652079812608"  Video added
3    "1205463037492248576"  Video added
4    "1202187084238188544"  Video added
..                     ...          ...
227   "729212916092768256"  Video added
228   "726088331214372865"  Video added
229   "708620162946064384"  Video added
230   "682603815313473536"  Video added
231   "680363304368377856"  Video added

[232 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1219870407676678144""","""Virat Kohli""",imvkohli,"""Stylish, elegant and classy. An absolute beas...",1707,35917,[@AudiIN],"[#AudiQ8, #8thDimension]",2,1,2020-01-22,06:32:23,Image added,NaN
1,"""1219814892170964992""","""Virat Kohli""",imvkohli,"""Top team gym session and a good meal out in b...",3515,81896,"[@im_manishpandey, @imjadeja, @klrahul11]",[],0,3,2020-01-22,02:51:48,Image added,NaN
2,"""1219631268738084868""","""Virat Kohli""",imvkohli,"""Touchdown Auckland. Let‚Äôs go üáÆüá≥ @imShard @Shr...",3598,79331,"[@imShard, @ShreyasIyer15]",[],0,2,2020-01-21,14:42:08,Image added,NaN
3,"""1219175442898276352""","""Virat Kohli""",imvkohli,"""üëäüèºüëäüèºüëäüèº https://t.co/ot4qLbfkvM""",1889,31973,[],[],0,0,2020-01-20,08:30:51,NaN,NaN
4,"""1218938883745837056""","""Virat Kohli""",imvkohli,"""Soaring High üèÜüáÆüá≥üíô #IndvAus https://t.co/Zjo3m...",14067,189812,[],[#IndvAus],1,0,2020-01-19,16:50:51,Image added,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,"""4168829709""","""Virat Kohli""",imvkohli,"""@yuvsingh09 Hello Mr.Bond \nwatched it you we...",10,36,[@yuvsingh09],[],0,1,2009-09-22,09:44:31,NaN,NaN
2200,"""4168263153""","""Virat Kohli""",imvkohli,"""@hulk7174 ??????""",9,44,[@hulk7174],[],0,1,2009-09-22,08:46:33,NaN,NaN
2201,"""4167514786""","""Virat Kohli""",imvkohli,"""Time for Training....""",51,86,[],[],0,0,2009-09-22,07:32:46,NaN,NaN
2202,"""3889494504""","""Virat Kohli""",imvkohli,"""Will be heading to SriLanka Woohoo !!!""",63,117,[],[],0,0,2009-09-10,15:36:10,NaN,NaN
2203,"""3754340192""","""Virat Kohli""",imvkohli,"""@yuvsingh09 Aiieeeeeee me too me too""",166,241,[@yuvsingh09],[],0,1,2009-09-04,10:31:36,NaN,NaN

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Male"

#Create an Vocation column 
Tweets_df['Vocation'] = "Sports"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (2204, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1219870407676678144""","""Virat Kohli""",imvkohli,1707,35917,[@AudiIN],"[#AudiQ8, #8thDimension]",2,1,2020-01-22,06:32:23,Image added,-,Male,Sports
1,"""1219814892170964992""","""Virat Kohli""",imvkohli,3515,81896,"[@im_manishpandey, @imjadeja, @klrahul11]",[],0,3,2020-01-22,02:51:48,Image added,-,Male,Sports
2,"""1219631268738084868""","""Virat Kohli""",imvkohli,3598,79331,"[@imShard, @ShreyasIyer15]",[],0,2,2020-01-21,14:42:08,Image added,-,Male,Sports
3,"""1219175442898276352""","""Virat Kohli""",imvkohli,1889,31973,[],[],0,0,2020-01-20,08:30:51,-,-,Male,Sports
4,"""1218938883745837056""","""Virat Kohli""",imvkohli,14067,189812,[],[#IndvAus],1,0,2020-01-19,16:50:51,Image added,-,Male,Sports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,"""4168829709""","""Virat Kohli""",imvkohli,10,36,[@yuvsingh09],[],0,1,2009-09-22,09:44:31,-,-,Male,Sports
2200,"""4168263153""","""Virat Kohli""",imvkohli,9,44,[@hulk7174],[],0,1,2009-09-22,08:46:33,-,-,Male,Sports
2201,"""4167514786""","""Virat Kohli""",imvkohli,51,86,[],[],0,0,2009-09-22,07:32:46,-,-,Male,Sports
2202,"""3889494504""","""Virat Kohli""",imvkohli,63,117,[],[],0,0,2009-09-10,15:36:10,-,-,Male,Sports
2203,"""3754340192""","""Virat Kohli""",imvkohli,166,241,[@yuvsingh09],[],0,1,2009-09-04,10:31:36,-,-,Male,Sports

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (2204, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1219870407676678144""","""Virat Kohli""",imvkohli,Male,Sports,"[#AudiQ8, #8thDimension]",2,[@AudiIN],1,35917,1707,Image added,-,2020-01-22,06:32:23
"""1219814892170964992""","""Virat Kohli""",imvkohli,Male,Sports,[],0,"[@im_manishpandey, @imjadeja, @klrahul11]",3,81896,3515,Image added,-,2020-01-22,02:51:48
"""1219631268738084868""","""Virat Kohli""",imvkohli,Male,Sports,[],0,"[@imShard, @ShreyasIyer15]",2,79331,3598,Image added,-,2020-01-21,14:42:08
"""1219175442898276352""","""Virat Kohli""",imvkohli,Male,Sports,[],0,[],0,31973,1889,-,-,2020-01-20,08:30:51
"""1218938883745837056""","""Virat Kohli""",imvkohli,Male,Sports,[#IndvAus],1,[],0,189812,14067,Image added,-,2020-01-19,16:50:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""4168829709""","""Virat Kohli""",imvkohli,Male,Sports,[],0,[@yuvsingh09],1,36,10,-,-,2009-09-22,09:44:31
"""4168263153""","""Virat Kohli""",imvkohli,Male,Sports,[],0,[@hulk7174],1,44,9,-,-,2009-09-22,08:46:33
"""4167514786""","""Virat Kohli""",imvkohli,Male,Sports,[],0,[],0,86,51,-,-,2009-09-22,07:32:46
"""3889494504""","""Virat Kohli""",imvkohli,Male,Sports,[],0,[],0,117,63,-,-,2009-09-10,15:36:10
"""3754340192""","""Virat Kohli""",imvkohli,Male,Sports,[],0,[@yuvsingh09],1,241,166,-,-,2009-09-04,10:31:36

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/ViratKohli_df.csv')