##### ===================================================================================================================

#  YouTube Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

##### READ THE TWEETS CSV

In [2]:
#Create reference to CSV file
csv_path = "RenamedTweets/YouTubeTweets.csv"

#Import the CSV into a pandas DataFrame
Tweets_df = pd.read_csv(csv_path, low_memory = False)
Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220238435861970944""",https://twitter.com/youtube/status/12202384358...,2020-01-23 06:54:48,"""Lunar New Year is almost here! üßßüê≠\nFind out w...",Tweet,Twitter Media Studio,105,636,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
1,"""1220140861486333952""",https://twitter.com/youtube/status/12201408614...,2020-01-23 00:27:05,"""Do it! https://t.co/FK8d5AEfzC""",Tweet,Twitter Web App,180,3651,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
2,"""1220133186048389121""",https://twitter.com/youtube/status/12201331860...,2020-01-22 23:56:35,"""@__gvby HI DAD!""",Reply,Twitter Web App,0,4,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
3,"""1220114272316878848""",https://twitter.com/youtube/status/12201142723...,2020-01-22 22:41:25,"""@DunkinJy OR do you know everything?""",Reply,Twitter Web App,0,2,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
4,"""1220051182338465792""",https://twitter.com/youtube/status/12200511823...,2020-01-22 18:30:43,"""So proud of you @nikkietutorials. üíû Watch her...",Tweet,Twitter Media Studio,65,795,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""939962963053727746""",https://twitter.com/youtube/status/93996296305...,2017-12-10 21:00:08,"""That one friend who treats your house like th...",Tweet,Sprinklr,156,1166,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
3196,"""939932776463257601""",https://twitter.com/youtube/status/93993277646...,2017-12-10 19:00:11,"""Anyway, here‚Äôs wonderwall. https://t.co/tNMUc...",Tweet,Sprinklr,179,1519,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
3197,"""939902534210252800""",https://twitter.com/youtube/status/93990253421...,2017-12-10 17:00:01,"""It‚Äôs #HumanRightsDay!\n\nJoin us as we spread...",Tweet,Sprinklr,536,1905,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
3198,"""939600568217194498""",https://twitter.com/youtube/status/93960056821...,2017-12-09 21:00:07,"""WARNING: This might give you the meat sweats ...",Tweet,Sprinklr,83,818,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected
3199,"""939540173104263168""",https://twitter.com/youtube/status/93954017310...,2017-12-09 17:00:07,"""‚ÄúFor me it‚Äôs not a bench. It‚Äôs something wher...",Tweet,Sprinklr,77,736,"""10228272""","""YouTube""",youtube,Verified,https://twitter.com/youtube,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Tweet Content", "Retweets received", "Likes received",
                       "Tweet Posted Time"]]
# "User Id",
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 7)

In [5]:
#Print the dataframe
Tweets_df.head()

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time
0,"""1220238435861970944""","""YouTube""",youtube,"""Lunar New Year is almost here! üßßüê≠\nFind out w...",105,636,2020-01-23 06:54:48
1,"""1220140861486333952""","""YouTube""",youtube,"""Do it! https://t.co/FK8d5AEfzC""",180,3651,2020-01-23 00:27:05
2,"""1220133186048389121""","""YouTube""",youtube,"""@__gvby HI DAD!""",0,4,2020-01-22 23:56:35
3,"""1220114272316878848""","""YouTube""",youtube,"""@DunkinJy OR do you know everything?""",0,2,2020-01-22 22:41:25
4,"""1220051182338465792""","""YouTube""",youtube,"""So proud of you @nikkietutorials. üíû Watch her...",65,795,2020-01-22 18:30:43

##### FILTER THROUGH TWEET CONTENTS TO EXTRACT HASHTAGS (#) AND MENTIONS(@)

In [6]:
df1 = Tweets_df[['Tweet Content']]
mention = df1['Tweet Content'].str.findall(r'@.*?(?=\s|$)')
hashtag = df1['Tweet Content'].str.findall(r'#.*?(?=\s|$)')
Tweets_df['Mentions(@)'] = mention
Tweets_df['Hashtags(#)'] = hashtag
#Tweets_df.head()

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

##### CREATE COLUMNS FOR THE COUNT OF #COMMENTS AND @MENTIONS PER ROW

In [7]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "#" in tag:
                count+=1
    return count 
                
Tweets_df['Total #'] = Tweets_df['Hashtags(#)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [8]:
#Count the amount of #comment's per Row
def totals(hashtag):
    count = 0
    if hashtag!= []:
        for tag in hashtag:
            if "@" in tag:
                count+=1
    return count 
                
Tweets_df['Total @'] = Tweets_df['Mentions(@)'].apply(totals)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [9]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Tweet Posted Time,Mentions(@),Hashtags(#),Total #,Total @
0,"""1220238435861970944""","""YouTube""",youtube,"""Lunar New Year is almost here! üßßüê≠\nFind out w...",105,636,2020-01-23 06:54:48,[],[],0,0
1,"""1220140861486333952""","""YouTube""",youtube,"""Do it! https://t.co/FK8d5AEfzC""",180,3651,2020-01-23 00:27:05,[],[],0,0
2,"""1220133186048389121""","""YouTube""",youtube,"""@__gvby HI DAD!""",0,4,2020-01-22 23:56:35,[@__gvby],[],0,1
3,"""1220114272316878848""","""YouTube""",youtube,"""@DunkinJy OR do you know everything?""",0,2,2020-01-22 22:41:25,[@DunkinJy],[],0,1
4,"""1220051182338465792""","""YouTube""",youtube,"""So proud of you @nikkietutorials. üíû Watch her...",65,795,2020-01-22 18:30:43,"[@nikkietutorials., @TheEllenShow]",[],0,2
...,...,...,...,...,...,...,...,...,...,...,...
3195,"""939962963053727746""","""YouTube""",youtube,"""That one friend who treats your house like th...",156,1166,2017-12-10 21:00:08,[],[],0,0
3196,"""939932776463257601""","""YouTube""",youtube,"""Anyway, here‚Äôs wonderwall. https://t.co/tNMUc...",179,1519,2017-12-10 19:00:11,[],[],0,0
3197,"""939902534210252800""","""YouTube""",youtube,"""It‚Äôs #HumanRightsDay!\n\nJoin us as we spread...",536,1905,2017-12-10 17:00:01,[],"[#HumanRightsDay!, #StandUp4HumanRights]",2,0
3198,"""939600568217194498""","""YouTube""",youtube,"""WARNING: This might give you the meat sweats ...",83,818,2017-12-09 21:00:07,[],[],0,0
3199,"""939540173104263168""","""YouTube""",youtube,"""‚ÄúFor me it‚Äôs not a bench. It‚Äôs something wher...",77,736,2017-12-09 17:00:07,[],[],0,0

##### SEPERATE THE DATE AND TIME

In [10]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Tweets_df['Tweet Posted Time'] = Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Tweets_df["Date"] = date

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Tweets_df["Time"] = time

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 12)

In [12]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time
0,"""1220238435861970944""","""YouTube""",youtube,"""Lunar New Year is almost here! üßßüê≠\nFind out w...",105,636,[],[],0,0,2020-01-23,06:54:48
1,"""1220140861486333952""","""YouTube""",youtube,"""Do it! https://t.co/FK8d5AEfzC""",180,3651,[],[],0,0,2020-01-23,00:27:05
2,"""1220133186048389121""","""YouTube""",youtube,"""@__gvby HI DAD!""",0,4,[@__gvby],[],0,1,2020-01-22,23:56:35
3,"""1220114272316878848""","""YouTube""",youtube,"""@DunkinJy OR do you know everything?""",0,2,[@DunkinJy],[],0,1,2020-01-22,22:41:25
4,"""1220051182338465792""","""YouTube""",youtube,"""So proud of you @nikkietutorials. üíû Watch her...",65,795,"[@nikkietutorials., @TheEllenShow]",[],0,2,2020-01-22,18:30:43
...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""939962963053727746""","""YouTube""",youtube,"""That one friend who treats your house like th...",156,1166,[],[],0,0,2017-12-10,21:00:08
3196,"""939932776463257601""","""YouTube""",youtube,"""Anyway, here‚Äôs wonderwall. https://t.co/tNMUc...",179,1519,[],[],0,0,2017-12-10,19:00:11
3197,"""939902534210252800""","""YouTube""",youtube,"""It‚Äôs #HumanRightsDay!\n\nJoin us as we spread...",536,1905,[],"[#HumanRightsDay!, #StandUp4HumanRights]",2,0,2017-12-10,17:00:01
3198,"""939600568217194498""","""YouTube""",youtube,"""WARNING: This might give you the meat sweats ...",83,818,[],[],0,0,2017-12-09,21:00:07
3199,"""939540173104263168""","""YouTube""",youtube,"""‚ÄúFor me it‚Äôs not a bench. It‚Äôs something wher...",77,736,[],[],0,0,2017-12-09,17:00:07

##### ===================================================================================================================

##### READ THE IMAGES CSV

In [13]:
#Create reference to CSV file
csv_path = "RenamedImages/YouTubeImages.csv"

#Import the CSV into a pandas DataFrame
Images_df = pd.read_csv(csv_path, low_memory = False)
Images_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1218810554053201920""","""1218810549401792513""",https://pbs.twimg.com/media/EOoVvLWXsAEqtOV.jpg,https://t.co/2GYbRugXWe
1,"""1217955693610831879""","""1217955685347938305""",https://pbs.twimg.com/media/EOcMPilU0AESWW3.jpg,https://t.co/QMlJDHxTqV
2,"""1216881176184442880""","""1216881173084790784""",https://pbs.twimg.com/media/EOM6-seUYAA-RzL.jpg,https://t.co/empqDQORQ8
3,"""1216854786353418240""","""1216854746708922368""",https://pbs.twimg.com/media/EOMi8ejVUAACIuV.jpg,https://t.co/QJkwbS5IZR
4,"""1214351045582671873""","""1214350969435066369""",https://pbs.twimg.com/media/ENo9xdXUEAETZpl.jpg,https://t.co/RFySu61QNx
...,...,...,...,...
440,"""941065196788965376""","""941065193630691328""",https://pbs.twimg.com/media/DQ9VzsDXcAAQbJp.jpg,https://t.co/l1BbwI0zM8
441,"""940691483295932417""","""940691481139879937""",https://pbs.twimg.com/media/DQ4B6wiUIAE-RrY.jpg,https://t.co/y1fNVBvbft
442,"""940657511211982850""","""940657508128919552""",https://pbs.twimg.com/media/DQ3jBRNUEAA82Wl.jpg,https://t.co/uy4Hb3kg4Q
443,"""940627314152476673""","""940627311216529410""",https://pbs.twimg.com/media/DQ3Hjk8XkAI7fEw.jpg,https://t.co/Lf7cky7F5I
444,"""939902534210252800""","""939902532117319680""",https://pbs.twimg.com/media/DQs0X4ZX0AAHEzh.jpg,https://t.co/dgQZN1YGUi

##### COLLECT ONLY REQUIRED COLUMNS

In [14]:
#Select only columns we need
Images_df = Images_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (445, 1)

##### ADD A IMAGES COLUMN TO THE DATAFRAME AND POPULATE

In [15]:
#Create an Images column for images
Images_df['Images'] = "Image added"

#Show the 'shape' of the dataframe
shape = Images_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (445, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Print the dataframe
Images_df

                  Tweet Id       Images
0    "1218810554053201920"  Image added
1    "1217955693610831879"  Image added
2    "1216881176184442880"  Image added
3    "1216854786353418240"  Image added
4    "1214351045582671873"  Image added
..                     ...          ...
440   "941065196788965376"  Image added
441   "940691483295932417"  Image added
442   "940657511211982850"  Image added
443   "940627314152476673"  Image added
444   "939902534210252800"  Image added

[445 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [17]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Images_df, on = 'Tweet Id', how = 'left')

In [18]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images
0,"""1220238435861970944""","""YouTube""",youtube,"""Lunar New Year is almost here! üßßüê≠\nFind out w...",105,636,[],[],0,0,2020-01-23,06:54:48,NaN
1,"""1220140861486333952""","""YouTube""",youtube,"""Do it! https://t.co/FK8d5AEfzC""",180,3651,[],[],0,0,2020-01-23,00:27:05,NaN
2,"""1220133186048389121""","""YouTube""",youtube,"""@__gvby HI DAD!""",0,4,[@__gvby],[],0,1,2020-01-22,23:56:35,NaN
3,"""1220114272316878848""","""YouTube""",youtube,"""@DunkinJy OR do you know everything?""",0,2,[@DunkinJy],[],0,1,2020-01-22,22:41:25,NaN
4,"""1220051182338465792""","""YouTube""",youtube,"""So proud of you @nikkietutorials. üíû Watch her...",65,795,"[@nikkietutorials., @TheEllenShow]",[],0,2,2020-01-22,18:30:43,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3306,"""939962963053727746""","""YouTube""",youtube,"""That one friend who treats your house like th...",156,1166,[],[],0,0,2017-12-10,21:00:08,NaN
3307,"""939932776463257601""","""YouTube""",youtube,"""Anyway, here‚Äôs wonderwall. https://t.co/tNMUc...",179,1519,[],[],0,0,2017-12-10,19:00:11,NaN
3308,"""939902534210252800""","""YouTube""",youtube,"""It‚Äôs #HumanRightsDay!\n\nJoin us as we spread...",536,1905,[],"[#HumanRightsDay!, #StandUp4HumanRights]",2,0,2017-12-10,17:00:01,Image added
3309,"""939600568217194498""","""YouTube""",youtube,"""WARNING: This might give you the meat sweats ...",83,818,[],[],0,0,2017-12-09,21:00:07,NaN
3310,"""939540173104263168""","""YouTube""",youtube,"""‚ÄúFor me it‚Äôs not a bench. It‚Äôs something wher...",77,736,[],[],0,0,2017-12-09,17:00:07,NaN

##### ===================================================================================================================

##### READ THE VIDEOS CSV

In [19]:
#Create reference to CSV file
csv_path = "RenamedVideos/YouTubeVideos.csv"

#Import the CSV into a pandas DataFrame
Videos_df = pd.read_csv(csv_path, low_memory = False)
Videos_df

,Tweet Id,Media Id,Media URL,Tweet URL
0,"""1220238435861970944""","""1220219952411500544""",https://video.twimg.com/amplify_video/12202199...,https://t.co/YIPJnHiYk5
1,"""1220051182338465792""","""1220050915773698048""",https://video.twimg.com/amplify_video/12200509...,https://t.co/YVOCIUNEqQ
2,"""1219893854406492160""","""1219893792615976961""",https://video.twimg.com/ext_tw_video/121989379...,https://t.co/9WlAA5A7To
3,"""1219763241259171840""","""1219763103249793024""",https://video.twimg.com/amplify_video/12197631...,https://t.co/3mQ3oYvpUA
4,"""1219575470062260224""","""1219575463036837888""",https://video.twimg.com/tweet_video/EOzNbAsX4A...,https://t.co/1G3ngq3mtq
...,...,...,...,...
1494,"""940264951708573696""","""940264919198457856""",https://video.twimg.com/tweet_video/DQx99leV4A...,https://t.co/wQymFBITtu
1495,"""939962963053727746""","""939962932716191744""",https://video.twimg.com/tweet_video/DQtrTqKVQA...,https://t.co/nQq3sNpZlu
1496,"""939932776463257601""","""939932730929876992""",https://video.twimg.com/amplify_video/93993273...,https://t.co/IYizrvxCRY
1497,"""939600568217194498""","""939600540954251264""",https://video.twimg.com/tweet_video/DQohtrpX0A...,https://t.co/GMT9LmmEEQ
1498,"""939540173104263168""","""939540143827853313""",https://video.twimg.com/tweet_video/DQnqyG0UIA...,https://t.co/qVbSmXRoJD

##### COLLECT ONLY REQUIRED COLUMNS

In [20]:
#Select only columns we need
Videos_df = Videos_df[["Tweet Id"]]

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1499, 1)

##### ADD A VIDEOS COLUMN TO THE DATAFRAME AND POPULATE

In [21]:
#Create an Videos column for images
Videos_df['Videos'] = "Video added"

#Show the 'shape' of the dataframe
shape = Videos_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (1499, 2)

C:\Users\booda\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
#Print the dataframe
Videos_df

                   Tweet Id       Videos
0     "1220238435861970944"  Video added
1     "1220051182338465792"  Video added
2     "1219893854406492160"  Video added
3     "1219763241259171840"  Video added
4     "1219575470062260224"  Video added
...                     ...          ...
1494   "940264951708573696"  Video added
1495   "939962963053727746"  Video added
1496   "939932776463257601"  Video added
1497   "939600568217194498"  Video added
1498   "939540173104263168"  Video added

[1499 rows x 2 columns]

##### MERGE IMAGES_DF WITH TWEET_DF

In [23]:
#Merge the 2 dataframes together
Tweets_df = Tweets_df.merge(Videos_df, on = 'Tweet Id', how = 'left')

In [24]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Tweet Content,Retweets received,Likes received,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos
0,"""1220238435861970944""","""YouTube""",youtube,"""Lunar New Year is almost here! üßßüê≠\nFind out w...",105,636,[],[],0,0,2020-01-23,06:54:48,NaN,Video added
1,"""1220140861486333952""","""YouTube""",youtube,"""Do it! https://t.co/FK8d5AEfzC""",180,3651,[],[],0,0,2020-01-23,00:27:05,NaN,NaN
2,"""1220133186048389121""","""YouTube""",youtube,"""@__gvby HI DAD!""",0,4,[@__gvby],[],0,1,2020-01-22,23:56:35,NaN,NaN
3,"""1220114272316878848""","""YouTube""",youtube,"""@DunkinJy OR do you know everything?""",0,2,[@DunkinJy],[],0,1,2020-01-22,22:41:25,NaN,NaN
4,"""1220051182338465792""","""YouTube""",youtube,"""So proud of you @nikkietutorials. üíû Watch her...",65,795,"[@nikkietutorials., @TheEllenShow]",[],0,2,2020-01-22,18:30:43,NaN,Video added
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3306,"""939962963053727746""","""YouTube""",youtube,"""That one friend who treats your house like th...",156,1166,[],[],0,0,2017-12-10,21:00:08,NaN,Video added
3307,"""939932776463257601""","""YouTube""",youtube,"""Anyway, here‚Äôs wonderwall. https://t.co/tNMUc...",179,1519,[],[],0,0,2017-12-10,19:00:11,NaN,Video added
3308,"""939902534210252800""","""YouTube""",youtube,"""It‚Äôs #HumanRightsDay!\n\nJoin us as we spread...",536,1905,[],"[#HumanRightsDay!, #StandUp4HumanRights]",2,0,2017-12-10,17:00:01,Image added,NaN
3309,"""939600568217194498""","""YouTube""",youtube,"""WARNING: This might give you the meat sweats ...",83,818,[],[],0,0,2017-12-09,21:00:07,NaN,Video added
3310,"""939540173104263168""","""YouTube""",youtube,"""‚ÄúFor me it‚Äôs not a bench. It‚Äôs something wher...",77,736,[],[],0,0,2017-12-09,17:00:07,NaN,Video added

##### ===================================================================================================================

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND POPULATE

In [25]:
#Create an Gender column 
Tweets_df['Gender'] = "Organisation"

#Create an Vocation column 
Tweets_df['Vocation'] = "Entertainment"

#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3311, 16)

In [26]:
#REPLACE ALL "NaN" FOR "-"
Tweets_df['Images'] = Tweets_df['Images'].fillna("-")
Tweets_df['Videos'] = Tweets_df['Videos'].fillna("-")

##### RENAME THE COLUMNS FOR VISUAL PURPOSES

In [27]:
Tweets_df = Tweets_df.rename(columns={"Tweet Content":"Tweets"})
Tweets_df = Tweets_df.rename(columns={"Retweets received":"Retweets"})
Tweets_df = Tweets_df.rename(columns={"Likes received":"Likes"})

##### REMOVE THE TWEETS COLUMN

In [28]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Tweets_df = Tweets_df.drop(['Tweets'], axis = 1)

In [29]:
#Print the dataframe
Tweets_df

,Tweet Id,Name,Username,Retweets,Likes,Mentions(@),Hashtags(#),Total #,Total @,Date,Time,Images,Videos,Gender,Vocation
0,"""1220238435861970944""","""YouTube""",youtube,105,636,[],[],0,0,2020-01-23,06:54:48,-,Video added,Organisation,Entertainment
1,"""1220140861486333952""","""YouTube""",youtube,180,3651,[],[],0,0,2020-01-23,00:27:05,-,-,Organisation,Entertainment
2,"""1220133186048389121""","""YouTube""",youtube,0,4,[@__gvby],[],0,1,2020-01-22,23:56:35,-,-,Organisation,Entertainment
3,"""1220114272316878848""","""YouTube""",youtube,0,2,[@DunkinJy],[],0,1,2020-01-22,22:41:25,-,-,Organisation,Entertainment
4,"""1220051182338465792""","""YouTube""",youtube,65,795,"[@nikkietutorials., @TheEllenShow]",[],0,2,2020-01-22,18:30:43,-,Video added,Organisation,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3306,"""939962963053727746""","""YouTube""",youtube,156,1166,[],[],0,0,2017-12-10,21:00:08,-,Video added,Organisation,Entertainment
3307,"""939932776463257601""","""YouTube""",youtube,179,1519,[],[],0,0,2017-12-10,19:00:11,-,Video added,Organisation,Entertainment
3308,"""939902534210252800""","""YouTube""",youtube,536,1905,[],"[#HumanRightsDay!, #StandUp4HumanRights]",2,0,2017-12-10,17:00:01,Image added,-,Organisation,Entertainment
3309,"""939600568217194498""","""YouTube""",youtube,83,818,[],[],0,0,2017-12-09,21:00:07,-,Video added,Organisation,Entertainment
3310,"""939540173104263168""","""YouTube""",youtube,77,736,[],[],0,0,2017-12-09,17:00:07,-,Video added,Organisation,Entertainment

##### RE-ORDER THE COLUMNS FOR VISUAL PURPOSES

In [30]:
#Re-organise the columns for visual purposes
Tweets_df = Tweets_df[["Tweet Id", "Name", "Username", "Gender", "Vocation", "Hashtags(#)", "Total #", "Mentions(@)", 
                       "Total @", "Likes", "Retweets", "Images", "Videos", "Date", "Time"]]

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [31]:
#The original dataframe had an index, so re-arrange the index 
Tweets_df = Tweets_df.set_index('Tweet Id')
#Show the 'shape' of the dataframe
shape = Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3311, 14)

In [32]:
#Print the dataframe
Tweets_df

,Name,Username,Gender,Vocation,Hashtags(#),Total #,Mentions(@),Total @,Likes,Retweets,Images,Videos,Date,Time
Tweet Id,,,,,,,,,,,,,,
"""1220238435861970944""","""YouTube""",youtube,Organisation,Entertainment,[],0,[],0,636,105,-,Video added,2020-01-23,06:54:48
"""1220140861486333952""","""YouTube""",youtube,Organisation,Entertainment,[],0,[],0,3651,180,-,-,2020-01-23,00:27:05
"""1220133186048389121""","""YouTube""",youtube,Organisation,Entertainment,[],0,[@__gvby],1,4,0,-,-,2020-01-22,23:56:35
"""1220114272316878848""","""YouTube""",youtube,Organisation,Entertainment,[],0,[@DunkinJy],1,2,0,-,-,2020-01-22,22:41:25
"""1220051182338465792""","""YouTube""",youtube,Organisation,Entertainment,[],0,"[@nikkietutorials., @TheEllenShow]",2,795,65,-,Video added,2020-01-22,18:30:43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""939962963053727746""","""YouTube""",youtube,Organisation,Entertainment,[],0,[],0,1166,156,-,Video added,2017-12-10,21:00:08
"""939932776463257601""","""YouTube""",youtube,Organisation,Entertainment,[],0,[],0,1519,179,-,Video added,2017-12-10,19:00:11
"""939902534210252800""","""YouTube""",youtube,Organisation,Entertainment,"[#HumanRightsDay!, #StandUp4HumanRights]",2,[],0,1905,536,Image added,-,2017-12-10,17:00:01
"""939600568217194498""","""YouTube""",youtube,Organisation,Entertainment,[],0,[],0,818,83,-,Video added,2017-12-09,21:00:07
"""939540173104263168""","""YouTube""",youtube,Organisation,Entertainment,[],0,[],0,736,77,-,Video added,2017-12-09,17:00:07

##### SAVE DATAFRAME TO CSV

In [33]:
#Save dataframe as csv file
Tweets_df.to_csv('NewDataframes/YouTube_df.csv')