##### ===================================================================================================================

# BBC Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

In [2]:
#Create reference to CSV file
csv_path = "BBCTweets.csv"

#Import the CSV into a pandas DataFrame
BBC_Tweets_df = pd.read_csv(csv_path, low_memory = False)
BBC_Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1220256711589683207""",https://twitter.com/bbcbreaking/status/1220256...,2020-01-23 08:07:25,"""Africa's richest woman, Angolan Isabel Dos Sa...",Tweet,SocialFlow,173,511,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
1,"""1220221131795390472""",https://twitter.com/bbcbreaking/status/1220221...,2020-01-23 05:46:03,"""The crew of the large air tanker were helping...",Tweet,SocialFlow,316,727,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
2,"""1220060752326905857""",https://twitter.com/bbcbreaking/status/1220060...,2020-01-22 19:08:45,"""Wuhan, a Chinese city of nearly 9m people, is...",Tweet,SocialFlow,2299,2815,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
3,"""1219964102484905984""",https://twitter.com/bbcbreaking/status/1219964...,2020-01-22 12:44:42,"""Monty Python star Terry Jones has died at the...",Tweet,SocialFlow,4505,7144,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
4,"""1219819207883415557""",https://twitter.com/bbcbreaking/status/1219819...,2020-01-22 03:08:56,"""The new virus could mutate and spread further...",Tweet,SocialFlow,1668,2017,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""908620348161216512""",https://twitter.com/bbcbreaking/status/9086203...,2017-09-15 09:15:47,"""Parsons Green tube explosion is being treated...",Reply,TweetDeck,1871,796,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
3196,"""908607797150998528""",https://twitter.com/bbcbreaking/status/9086077...,2017-09-15 08:25:54,""".@sophieraworth saw woman taken to ambulance ...",Tweet,SnappyTV.com,2029,1467,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
3197,"""908604541465018370""",https://twitter.com/bbcbreaking/status/9086045...,2017-09-15 08:12:58,"""""She says she saw people injured"" - Sophie Ra...",Tweet,SnappyTV.com,1852,945,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
3198,"""908603688272502784""",https://twitter.com/bbcbreaking/status/9086036...,2017-09-15 08:09:34,"""Armed police and emergency services at London...",Reply,TweetDeck,1245,478,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected
3199,"""908597697166364673""",https://twitter.com/bbcbreaking/status/9085976...,2017-09-15 07:45:46,"""Officials investigating ""incident"" on Distric...",Tweet,SocialFlow,3333,1491,"""5402612""","""BBC Breaking News""",bbcbreaking,Verified,https://twitter.com/bbcbreaking,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = BBC_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
BBC_Tweets_df = BBC_Tweets_df[["Username", "User Id", "Tweet Type", "Tweet Content", "Client", "Retweets received",
                                     "Likes received", "Tweet Posted Time"]]

#Show the 'shape' of the dataframe
shape = BBC_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

In [5]:
#Print the dataframe
BBC_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Tweet Posted Time
0,bbcbreaking,"""5402612""",Tweet,"""Africa's richest woman, Angolan Isabel Dos Sa...",SocialFlow,173,511,2020-01-23 08:07:25
1,bbcbreaking,"""5402612""",Tweet,"""The crew of the large air tanker were helping...",SocialFlow,316,727,2020-01-23 05:46:03
2,bbcbreaking,"""5402612""",Tweet,"""Wuhan, a Chinese city of nearly 9m people, is...",SocialFlow,2299,2815,2020-01-22 19:08:45
3,bbcbreaking,"""5402612""",Tweet,"""Monty Python star Terry Jones has died at the...",SocialFlow,4505,7144,2020-01-22 12:44:42
4,bbcbreaking,"""5402612""",Tweet,"""The new virus could mutate and spread further...",SocialFlow,1668,2017,2020-01-22 03:08:56
...,...,...,...,...,...,...,...,...
3195,bbcbreaking,"""5402612""",Reply,"""Parsons Green tube explosion is being treated...",TweetDeck,1871,796,2017-09-15 09:15:47
3196,bbcbreaking,"""5402612""",Tweet,""".@sophieraworth saw woman taken to ambulance ...",SnappyTV.com,2029,1467,2017-09-15 08:25:54
3197,bbcbreaking,"""5402612""",Tweet,"""""She says she saw people injured"" - Sophie Ra...",SnappyTV.com,1852,945,2017-09-15 08:12:58
3198,bbcbreaking,"""5402612""",Reply,"""Armed police and emergency services at London...",TweetDeck,1245,478,2017-09-15 08:09:34
3199,bbcbreaking,"""5402612""",Tweet,"""Officials investigating ""incident"" on Distric...",SocialFlow,3333,1491,2017-09-15 07:45:46

##### REMOVE ALL ROWS WITH NO DATA

In [6]:
#Filter out those rows which does not contain any data 
BBC_Tweets_df = BBC_Tweets_df.dropna() 

#Confirm rows are dropped
shape = BBC_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

##### SEPERATE THE DATE AND TIME

In [7]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
BBC_Tweets_df['Tweet Posted Time'] = BBC_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = BBC_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
BBC_Tweets_df["Date"] = date

In [8]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
BBC_Tweets_df['Tweet Posted Time'] = BBC_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = BBC_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
BBC_Tweets_df["Time"] = time

In [9]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
BBC_Tweets_df = BBC_Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = BBC_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 9)

In [10]:
#Print the dataframe
BBC_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time
0,bbcbreaking,"""5402612""",Tweet,"""Africa's richest woman, Angolan Isabel Dos Sa...",SocialFlow,173,511,2020-01-23,08:07:25
1,bbcbreaking,"""5402612""",Tweet,"""The crew of the large air tanker were helping...",SocialFlow,316,727,2020-01-23,05:46:03
2,bbcbreaking,"""5402612""",Tweet,"""Wuhan, a Chinese city of nearly 9m people, is...",SocialFlow,2299,2815,2020-01-22,19:08:45
3,bbcbreaking,"""5402612""",Tweet,"""Monty Python star Terry Jones has died at the...",SocialFlow,4505,7144,2020-01-22,12:44:42
4,bbcbreaking,"""5402612""",Tweet,"""The new virus could mutate and spread further...",SocialFlow,1668,2017,2020-01-22,03:08:56
...,...,...,...,...,...,...,...,...,...
3195,bbcbreaking,"""5402612""",Reply,"""Parsons Green tube explosion is being treated...",TweetDeck,1871,796,2017-09-15,09:15:47
3196,bbcbreaking,"""5402612""",Tweet,""".@sophieraworth saw woman taken to ambulance ...",SnappyTV.com,2029,1467,2017-09-15,08:25:54
3197,bbcbreaking,"""5402612""",Tweet,"""""She says she saw people injured"" - Sophie Ra...",SnappyTV.com,1852,945,2017-09-15,08:12:58
3198,bbcbreaking,"""5402612""",Reply,"""Armed police and emergency services at London...",TweetDeck,1245,478,2017-09-15,08:09:34
3199,bbcbreaking,"""5402612""",Tweet,"""Officials investigating ""incident"" on Distric...",SocialFlow,3333,1491,2017-09-15,07:45:46

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND FILL

In [11]:
#Create an Gender column for Gender
BBC_Tweets_df['Gender'] = "Organisation"

#Create an Gender column for Gender
BBC_Tweets_df['Vocation'] = "News/Media"

#Show the 'shape' of the dataframe
shape = BBC_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 11)

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [12]:
#The original dataframe had an index, so re-arrange the index 
BBC_Tweets_df.index = [x for x in range(1, len(BBC_Tweets_df.values)+1)]
BBC_Tweets_df.index.name = 'Index'

In [13]:
#Print the dataframe
BBC_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time,Gender,Vocation
Index,,,,,,,,,,,
1,bbcbreaking,"""5402612""",Tweet,"""Africa's richest woman, Angolan Isabel Dos Sa...",SocialFlow,173,511,2020-01-23,08:07:25,Organisation,News/Media
2,bbcbreaking,"""5402612""",Tweet,"""The crew of the large air tanker were helping...",SocialFlow,316,727,2020-01-23,05:46:03,Organisation,News/Media
3,bbcbreaking,"""5402612""",Tweet,"""Wuhan, a Chinese city of nearly 9m people, is...",SocialFlow,2299,2815,2020-01-22,19:08:45,Organisation,News/Media
4,bbcbreaking,"""5402612""",Tweet,"""Monty Python star Terry Jones has died at the...",SocialFlow,4505,7144,2020-01-22,12:44:42,Organisation,News/Media
5,bbcbreaking,"""5402612""",Tweet,"""The new virus could mutate and spread further...",SocialFlow,1668,2017,2020-01-22,03:08:56,Organisation,News/Media
...,...,...,...,...,...,...,...,...,...,...,...
3196,bbcbreaking,"""5402612""",Reply,"""Parsons Green tube explosion is being treated...",TweetDeck,1871,796,2017-09-15,09:15:47,Organisation,News/Media
3197,bbcbreaking,"""5402612""",Tweet,""".@sophieraworth saw woman taken to ambulance ...",SnappyTV.com,2029,1467,2017-09-15,08:25:54,Organisation,News/Media
3198,bbcbreaking,"""5402612""",Tweet,"""""She says she saw people injured"" - Sophie Ra...",SnappyTV.com,1852,945,2017-09-15,08:12:58,Organisation,News/Media
3199,bbcbreaking,"""5402612""",Reply,"""Armed police and emergency services at London...",TweetDeck,1245,478,2017-09-15,08:09:34,Organisation,News/Media
3200,bbcbreaking,"""5402612""",Tweet,"""Officials investigating ""incident"" on Distric...",SocialFlow,3333,1491,2017-09-15,07:45:46,Organisation,News/Media

##### SAVE DATAFRAME TO CSV

In [14]:
#Save dataframe as csv file
BBC_Tweets_df.to_csv('BBC_Tweets_df.csv')