##### ===================================================================================================================

# Harry Styles Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

In [2]:
#Create reference to CSV file
csv_path = "HarryStylesTweets.csv"

#Import the CSV into a pandas DataFrame
HStyles_Tweets_df = pd.read_csv(csv_path, low_memory = False)
HStyles_Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1217562122307227649""",https://twitter.com/harry_styles/status/121756...,2020-01-15 21:40:05,"""18 FEB 2020 https://t.co/nk3GRVMufe""",Tweet,Twitter for iPhone,46829,267621,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
1,"""1216363331864485888""",https://twitter.com/harry_styles/status/121636...,2020-01-12 14:16:31,"""HAPPY NEW YEAR! Thank you @BRITs for the nomi...",Tweet,Twitter for iPhone,55571,273738,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
2,"""1209062698484412418""",https://twitter.com/harry_styles/status/120906...,2019-12-23 10:46:25,"""Wishing everyone a wonderful Christmas time. ...",Tweet,Twitter for iPhone,142828,666466,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
3,"""1208085367481614337""",https://twitter.com/harry_styles/status/120808...,2019-12-20 18:02:51,"""FINE LINE LIVE IN LONDON.\nDEC 19 2019. https...",Tweet,Twitter for iPhone,31828,218063,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
4,"""1206686730285441027""",https://twitter.com/harry_styles/status/120668...,2019-12-16 21:25:10,"""Thank you to everyone listening to FINE LINE,...",Tweet,Twitter for iPhone,66469,320991,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""141492074947162113""",https://twitter.com/harry_styles/status/141492...,2011-11-29 12:21:54,"""Big thanks to everyone who got involved in ou...",Tweet,Twitter for iPhone,2924,1045,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
3196,"""141491790871138304""",https://twitter.com/harry_styles/status/141491...,2011-11-29 12:20:46,"""@emmaaclaire happy birthday!!! :) have a good...",Reply,Twitter for iPhone,244,178,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
3197,"""141490261246222336""",https://twitter.com/harry_styles/status/141490...,2011-11-29 12:14:41,"""@niallervibes very well thank :) woke up in a...",Reply,Twitter for iPhone,250,191,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
3198,"""141488568303484928""",https://twitter.com/harry_styles/status/141488...,2011-11-29 12:07:58,"""RT @hotpatooties If you're on Orange please v...",Tweet,Twitter for iPhone,504,376,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected
3199,"""141176393508732928""",https://twitter.com/harry_styles/status/141176...,2011-11-28 15:27:29,"""Trafalgar Square... Let's Do It!!!""",Tweet,Twitter for BlackBerry®,2794,935,"""181561712""","""Harry Styles.""",harry_styles,Verified,https://twitter.com/harry_styles,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = HStyles_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
HStyles_Tweets_df = HStyles_Tweets_df[["Username", "User Id", "Tweet Type", "Tweet Content", "Client", "Retweets received",
                                     "Likes received", "Tweet Posted Time"]]

#Show the 'shape' of the dataframe
shape = HStyles_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

In [5]:
#Print the dataframe
HStyles_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Tweet Posted Time
0,harry_styles,"""181561712""",Tweet,"""18 FEB 2020 https://t.co/nk3GRVMufe""",Twitter for iPhone,46829,267621,2020-01-15 21:40:05
1,harry_styles,"""181561712""",Tweet,"""HAPPY NEW YEAR! Thank you @BRITs for the nomi...",Twitter for iPhone,55571,273738,2020-01-12 14:16:31
2,harry_styles,"""181561712""",Tweet,"""Wishing everyone a wonderful Christmas time. ...",Twitter for iPhone,142828,666466,2019-12-23 10:46:25
3,harry_styles,"""181561712""",Tweet,"""FINE LINE LIVE IN LONDON.\nDEC 19 2019. https...",Twitter for iPhone,31828,218063,2019-12-20 18:02:51
4,harry_styles,"""181561712""",Tweet,"""Thank you to everyone listening to FINE LINE,...",Twitter for iPhone,66469,320991,2019-12-16 21:25:10
...,...,...,...,...,...,...,...,...
3195,harry_styles,"""181561712""",Tweet,"""Big thanks to everyone who got involved in ou...",Twitter for iPhone,2924,1045,2011-11-29 12:21:54
3196,harry_styles,"""181561712""",Reply,"""@emmaaclaire happy birthday!!! :) have a good...",Twitter for iPhone,244,178,2011-11-29 12:20:46
3197,harry_styles,"""181561712""",Reply,"""@niallervibes very well thank :) woke up in a...",Twitter for iPhone,250,191,2011-11-29 12:14:41
3198,harry_styles,"""181561712""",Tweet,"""RT @hotpatooties If you're on Orange please v...",Twitter for iPhone,504,376,2011-11-29 12:07:58
3199,harry_styles,"""181561712""",Tweet,"""Trafalgar Square... Let's Do It!!!""",Twitter for BlackBerry®,2794,935,2011-11-28 15:27:29

##### REMOVE ALL ROWS WITH NO DATA

In [6]:
#Filter out those rows which does not contain any data 
HStyles_Tweets_df = HStyles_Tweets_df.dropna() 

#Confirm rows are dropped
shape = HStyles_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

##### SEPERATE THE DATE AND TIME

In [7]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
HStyles_Tweets_df['Tweet Posted Time'] = HStyles_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = HStyles_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
HStyles_Tweets_df["Date"] = date

In [8]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
HStyles_Tweets_df['Tweet Posted Time'] = HStyles_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = HStyles_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
HStyles_Tweets_df["Time"] = time

In [9]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
HStyles_Tweets_df = HStyles_Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = HStyles_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 9)

In [10]:
#Print the dataframe
HStyles_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time
0,harry_styles,"""181561712""",Tweet,"""18 FEB 2020 https://t.co/nk3GRVMufe""",Twitter for iPhone,46829,267621,2020-01-15,21:40:05
1,harry_styles,"""181561712""",Tweet,"""HAPPY NEW YEAR! Thank you @BRITs for the nomi...",Twitter for iPhone,55571,273738,2020-01-12,14:16:31
2,harry_styles,"""181561712""",Tweet,"""Wishing everyone a wonderful Christmas time. ...",Twitter for iPhone,142828,666466,2019-12-23,10:46:25
3,harry_styles,"""181561712""",Tweet,"""FINE LINE LIVE IN LONDON.\nDEC 19 2019. https...",Twitter for iPhone,31828,218063,2019-12-20,18:02:51
4,harry_styles,"""181561712""",Tweet,"""Thank you to everyone listening to FINE LINE,...",Twitter for iPhone,66469,320991,2019-12-16,21:25:10
...,...,...,...,...,...,...,...,...,...
3195,harry_styles,"""181561712""",Tweet,"""Big thanks to everyone who got involved in ou...",Twitter for iPhone,2924,1045,2011-11-29,12:21:54
3196,harry_styles,"""181561712""",Reply,"""@emmaaclaire happy birthday!!! :) have a good...",Twitter for iPhone,244,178,2011-11-29,12:20:46
3197,harry_styles,"""181561712""",Reply,"""@niallervibes very well thank :) woke up in a...",Twitter for iPhone,250,191,2011-11-29,12:14:41
3198,harry_styles,"""181561712""",Tweet,"""RT @hotpatooties If you're on Orange please v...",Twitter for iPhone,504,376,2011-11-29,12:07:58
3199,harry_styles,"""181561712""",Tweet,"""Trafalgar Square... Let's Do It!!!""",Twitter for BlackBerry®,2794,935,2011-11-28,15:27:29

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND FILL

In [11]:
#Create an Gender column for Gender
HStyles_Tweets_df['Gender'] = "Male"

#Create an Gender column for Gender
HStyles_Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = HStyles_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 11)

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [12]:
#The original dataframe had an index, so re-arrange the index 
HStyles_Tweets_df.index = [x for x in range(1, len(HStyles_Tweets_df.values)+1)]
HStyles_Tweets_df.index.name = 'Index'

In [13]:
#Print the dataframe
HStyles_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time,Gender,Vocation
Index,,,,,,,,,,,
1,harry_styles,"""181561712""",Tweet,"""18 FEB 2020 https://t.co/nk3GRVMufe""",Twitter for iPhone,46829,267621,2020-01-15,21:40:05,Male,Music
2,harry_styles,"""181561712""",Tweet,"""HAPPY NEW YEAR! Thank you @BRITs for the nomi...",Twitter for iPhone,55571,273738,2020-01-12,14:16:31,Male,Music
3,harry_styles,"""181561712""",Tweet,"""Wishing everyone a wonderful Christmas time. ...",Twitter for iPhone,142828,666466,2019-12-23,10:46:25,Male,Music
4,harry_styles,"""181561712""",Tweet,"""FINE LINE LIVE IN LONDON.\nDEC 19 2019. https...",Twitter for iPhone,31828,218063,2019-12-20,18:02:51,Male,Music
5,harry_styles,"""181561712""",Tweet,"""Thank you to everyone listening to FINE LINE,...",Twitter for iPhone,66469,320991,2019-12-16,21:25:10,Male,Music
...,...,...,...,...,...,...,...,...,...,...,...
3196,harry_styles,"""181561712""",Tweet,"""Big thanks to everyone who got involved in ou...",Twitter for iPhone,2924,1045,2011-11-29,12:21:54,Male,Music
3197,harry_styles,"""181561712""",Reply,"""@emmaaclaire happy birthday!!! :) have a good...",Twitter for iPhone,244,178,2011-11-29,12:20:46,Male,Music
3198,harry_styles,"""181561712""",Reply,"""@niallervibes very well thank :) woke up in a...",Twitter for iPhone,250,191,2011-11-29,12:14:41,Male,Music
3199,harry_styles,"""181561712""",Tweet,"""RT @hotpatooties If you're on Orange please v...",Twitter for iPhone,504,376,2011-11-29,12:07:58,Male,Music
3200,harry_styles,"""181561712""",Tweet,"""Trafalgar Square... Let's Do It!!!""",Twitter for BlackBerry®,2794,935,2011-11-28,15:27:29,Male,Music

##### SAVE DATAFRAME TO CSV

In [14]:
#Save dataframe as csv file
HStyles_Tweets_df.to_csv('HStyles_Tweets_df.csv')