##### ===================================================================================================================

# Jimmy Fallon Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

In [2]:
#Create reference to CSV file
csv_path = "JimmyFallonTweets.csv"

#Import the CSV into a pandas DataFrame
JFallon_Tweets_df = pd.read_csv(csv_path, low_memory = False)
JFallon_Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1219730046694383618""",https://twitter.com/jimmyfallon/status/1219730...,2020-01-21 21:14:39,"""#ThereShouldBeALaw that people who pronounce ...",Tweet,Twitter for iPhone,236,3132,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
1,"""1219729849583067136""",https://twitter.com/jimmyfallon/status/1219729...,2020-01-21 21:13:52,"""It’s Hashtags time! Tag a tweet with #ThereSh...",Tweet,Twitter for iPhone,207,3255,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
2,"""1218196761271054341""",https://twitter.com/jimmyfallon/status/1218196...,2020-01-17 15:41:55,"""Friend goals. #happybirthdaylin""",Reply,Twitter for iPhone,51,1825,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
3,"""1218195511787782144""",https://twitter.com/jimmyfallon/status/1218195...,2020-01-17 15:36:57,"""https://t.co/l6mMb0Tdzc""",Reply,Twitter for iPhone,342,9455,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
4,"""1217937309410131969""",https://twitter.com/jimmyfallon/status/1217937...,2020-01-16 22:30:57,"""Kid monologues, kid games, kid interviews, bi...",Tweet,Twitter for iPhone,63,658,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""753569949671645184""",https://twitter.com/jimmyfallon/status/7535699...,2016-07-14 12:40:51,"""Unfortunately had to bump Kristen Wiig, but i...",Tweet,Twitter Web Client,563,2110,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
3196,"""753564046457274368""",https://twitter.com/jimmyfallon/status/7535640...,2016-07-14 12:17:23,""".@ArianaGrande and I combine snaps into a #Sn...",Tweet,Twitter Web Client,6546,17178,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
3197,"""753561347351248897""",https://twitter.com/jimmyfallon/status/7535613...,2016-07-14 12:06:40,"""Tonight is our 500th show! Thanks to all of y...",Tweet,Twitter for iPhone,1032,8778,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
3198,"""753561070304890880""",https://twitter.com/jimmyfallon/status/7535610...,2016-07-14 12:05:34,"""Thank you!! We are very lucky. I feel the lov...",Tweet,Twitter for iPhone,160,1563,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected
3199,"""753397108997259265""",https://twitter.com/jimmyfallon/status/7533971...,2016-07-14 01:14:02,"""That is the monologue mark I stand over every...",Tweet,Twitter for iPhone,219,2411,"""15485441""","""jimmy fallon""",jimmyfallon,Verified,https://twitter.com/jimmyfallon,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = JFallon_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
JFallon_Tweets_df = JFallon_Tweets_df[["Username", "User Id", "Tweet Type", "Tweet Content", "Client", "Retweets received",
                                     "Likes received", "Tweet Posted Time"]]

#Show the 'shape' of the dataframe
shape = JFallon_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

In [5]:
#Print the dataframe
JFallon_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Tweet Posted Time
0,jimmyfallon,"""15485441""",Tweet,"""#ThereShouldBeALaw that people who pronounce ...",Twitter for iPhone,236,3132,2020-01-21 21:14:39
1,jimmyfallon,"""15485441""",Tweet,"""It’s Hashtags time! Tag a tweet with #ThereSh...",Twitter for iPhone,207,3255,2020-01-21 21:13:52
2,jimmyfallon,"""15485441""",Reply,"""Friend goals. #happybirthdaylin""",Twitter for iPhone,51,1825,2020-01-17 15:41:55
3,jimmyfallon,"""15485441""",Reply,"""https://t.co/l6mMb0Tdzc""",Twitter for iPhone,342,9455,2020-01-17 15:36:57
4,jimmyfallon,"""15485441""",Tweet,"""Kid monologues, kid games, kid interviews, bi...",Twitter for iPhone,63,658,2020-01-16 22:30:57
...,...,...,...,...,...,...,...,...
3195,jimmyfallon,"""15485441""",Tweet,"""Unfortunately had to bump Kristen Wiig, but i...",Twitter Web Client,563,2110,2016-07-14 12:40:51
3196,jimmyfallon,"""15485441""",Tweet,""".@ArianaGrande and I combine snaps into a #Sn...",Twitter Web Client,6546,17178,2016-07-14 12:17:23
3197,jimmyfallon,"""15485441""",Tweet,"""Tonight is our 500th show! Thanks to all of y...",Twitter for iPhone,1032,8778,2016-07-14 12:06:40
3198,jimmyfallon,"""15485441""",Tweet,"""Thank you!! We are very lucky. I feel the lov...",Twitter for iPhone,160,1563,2016-07-14 12:05:34
3199,jimmyfallon,"""15485441""",Tweet,"""That is the monologue mark I stand over every...",Twitter for iPhone,219,2411,2016-07-14 01:14:02

##### REMOVE ALL ROWS WITH NO DATA

In [6]:
#Filter out those rows which does not contain any data 
JFallon_Tweets_df = JFallon_Tweets_df.dropna() 

#Confirm rows are dropped
shape = JFallon_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

##### SEPERATE THE DATE AND TIME

In [7]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
JFallon_Tweets_df['Tweet Posted Time'] = JFallon_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = JFallon_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
JFallon_Tweets_df["Date"] = date

In [8]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
JFallon_Tweets_df['Tweet Posted Time'] = JFallon_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = JFallon_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
JFallon_Tweets_df["Time"] = time

In [9]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
JFallon_Tweets_df = JFallon_Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = JFallon_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 9)

In [10]:
#Print the dataframe
JFallon_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time
0,jimmyfallon,"""15485441""",Tweet,"""#ThereShouldBeALaw that people who pronounce ...",Twitter for iPhone,236,3132,2020-01-21,21:14:39
1,jimmyfallon,"""15485441""",Tweet,"""It’s Hashtags time! Tag a tweet with #ThereSh...",Twitter for iPhone,207,3255,2020-01-21,21:13:52
2,jimmyfallon,"""15485441""",Reply,"""Friend goals. #happybirthdaylin""",Twitter for iPhone,51,1825,2020-01-17,15:41:55
3,jimmyfallon,"""15485441""",Reply,"""https://t.co/l6mMb0Tdzc""",Twitter for iPhone,342,9455,2020-01-17,15:36:57
4,jimmyfallon,"""15485441""",Tweet,"""Kid monologues, kid games, kid interviews, bi...",Twitter for iPhone,63,658,2020-01-16,22:30:57
...,...,...,...,...,...,...,...,...,...
3195,jimmyfallon,"""15485441""",Tweet,"""Unfortunately had to bump Kristen Wiig, but i...",Twitter Web Client,563,2110,2016-07-14,12:40:51
3196,jimmyfallon,"""15485441""",Tweet,""".@ArianaGrande and I combine snaps into a #Sn...",Twitter Web Client,6546,17178,2016-07-14,12:17:23
3197,jimmyfallon,"""15485441""",Tweet,"""Tonight is our 500th show! Thanks to all of y...",Twitter for iPhone,1032,8778,2016-07-14,12:06:40
3198,jimmyfallon,"""15485441""",Tweet,"""Thank you!! We are very lucky. I feel the lov...",Twitter for iPhone,160,1563,2016-07-14,12:05:34
3199,jimmyfallon,"""15485441""",Tweet,"""That is the monologue mark I stand over every...",Twitter for iPhone,219,2411,2016-07-14,01:14:02

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND FILL

In [11]:
#Create an Gender column for Gender
JFallon_Tweets_df['Gender'] = "Male"

#Create an Gender column for Gender
JFallon_Tweets_df['Vocation'] = "Entertainment"

#Show the 'shape' of the dataframe
shape = JFallon_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 11)

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [12]:
#The original dataframe had an index, so re-arrange the index 
JFallon_Tweets_df.index = [x for x in range(1, len(JFallon_Tweets_df.values)+1)]
JFallon_Tweets_df.index.name = 'Index'

In [13]:
#Print the dataframe
JFallon_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time,Gender,Vocation
Index,,,,,,,,,,,
1,jimmyfallon,"""15485441""",Tweet,"""#ThereShouldBeALaw that people who pronounce ...",Twitter for iPhone,236,3132,2020-01-21,21:14:39,Male,Entertainment
2,jimmyfallon,"""15485441""",Tweet,"""It’s Hashtags time! Tag a tweet with #ThereSh...",Twitter for iPhone,207,3255,2020-01-21,21:13:52,Male,Entertainment
3,jimmyfallon,"""15485441""",Reply,"""Friend goals. #happybirthdaylin""",Twitter for iPhone,51,1825,2020-01-17,15:41:55,Male,Entertainment
4,jimmyfallon,"""15485441""",Reply,"""https://t.co/l6mMb0Tdzc""",Twitter for iPhone,342,9455,2020-01-17,15:36:57,Male,Entertainment
5,jimmyfallon,"""15485441""",Tweet,"""Kid monologues, kid games, kid interviews, bi...",Twitter for iPhone,63,658,2020-01-16,22:30:57,Male,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...
3196,jimmyfallon,"""15485441""",Tweet,"""Unfortunately had to bump Kristen Wiig, but i...",Twitter Web Client,563,2110,2016-07-14,12:40:51,Male,Entertainment
3197,jimmyfallon,"""15485441""",Tweet,""".@ArianaGrande and I combine snaps into a #Sn...",Twitter Web Client,6546,17178,2016-07-14,12:17:23,Male,Entertainment
3198,jimmyfallon,"""15485441""",Tweet,"""Tonight is our 500th show! Thanks to all of y...",Twitter for iPhone,1032,8778,2016-07-14,12:06:40,Male,Entertainment
3199,jimmyfallon,"""15485441""",Tweet,"""Thank you!! We are very lucky. I feel the lov...",Twitter for iPhone,160,1563,2016-07-14,12:05:34,Male,Entertainment
3200,jimmyfallon,"""15485441""",Tweet,"""That is the monologue mark I stand over every...",Twitter for iPhone,219,2411,2016-07-14,01:14:02,Male,Entertainment

##### SAVE DATAFRAME TO CSV

In [14]:
#Save dataframe as csv file
JFallon_Tweets_df.to_csv('JFallon_Tweets_df.csv')