##### ===================================================================================================================

# Liam Payne Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

In [2]:
#Create reference to CSV file
csv_path = "LiamPayneTweets.csv"

#Import the CSV into a pandas DataFrame
LPayne_Tweets_df = pd.read_csv(csv_path, low_memory = False)
LPayne_Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1219907832239329280""",https://twitter.com/liampayne/status/121990783...,2020-01-22 09:01:06,"""Proud to show you my first campaign with HUGO...",Tweet,Twitter for iPhone,6061,28537,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected
1,"""1218122712582889472""",https://twitter.com/liampayne/status/121812271...,2020-01-17 10:47:40,"""Tickets now on sale for @WolvesRaces! See you...",Tweet,Twitter for iPhone,3617,19097,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected
2,"""1217858564389330946""",https://twitter.com/liampayne/status/121785856...,2020-01-16 17:18:03,"""Thanks to the amazing team that worked so har...",Tweet,Twitter for iPhone,6602,35032,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected
3,"""1217511386877779974""",https://twitter.com/tenerifeziam/status/121751...,2020-01-15 18:18:29,"""I just made this pet playlist for my dog and ...",Retweet,Twitter for iPhone,626,5901,"""930997525""","""luiza ❯❯❯❯""",tenerifeziam,Non-Verified,https://twitter.com/tenerifeziam,Not Protected
4,"""1217504211983880192""",https://twitter.com/liampayne/status/121750421...,2020-01-15 17:49:58,"""Live Forever with @CheatCodesMusic live at th...",Tweet,Twitter for iPhone,5186,25010,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""423190253588205568""",https://twitter.com/liampayne/status/423190253...,2014-01-14 20:29:53,"""I'd just like to be able to walk outside as e...",Tweet,Twitter for iPhone,82899,122650,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected
3196,"""423189717354807296""",https://twitter.com/liampayne/status/423189717...,2014-01-14 20:27:45,"""I know my friends have tweeted a lot of pictu...",Tweet,Twitter for iPhone,82664,120309,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected
3197,"""422784589829242881""",https://twitter.com/liampayne/status/422784589...,2014-01-13 17:37:55,"""Happy birthday @Laurastanway have a good one""",Tweet,Twitter for iPhone,27960,58426,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected
3198,"""422330014093557760""",https://twitter.com/liampayne/status/422330014...,2014-01-12 11:31:36,"""Had some strange dreams yesterday wonder what...",Tweet,Twitter for iPhone,72885,108140,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected
3199,"""422158624224722944""",https://twitter.com/liampayne/status/422158624...,2014-01-12 00:10:34,"""Rap battles in the car so funny aha""",Tweet,Twitter for iPhone,71477,115884,"""158314798""","""Liam""",liampayne,Verified,https://twitter.com/liampayne,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = LPayne_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
LPayne_Tweets_df = LPayne_Tweets_df[["Username", "User Id", "Tweet Type", "Tweet Content", "Client", "Retweets received",
                                     "Likes received", "Tweet Posted Time"]]

#Show the 'shape' of the dataframe
shape = LPayne_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

In [5]:
#Print the dataframe
LPayne_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Tweet Posted Time
0,liampayne,"""158314798""",Tweet,"""Proud to show you my first campaign with HUGO...",Twitter for iPhone,6061,28537,2020-01-22 09:01:06
1,liampayne,"""158314798""",Tweet,"""Tickets now on sale for @WolvesRaces! See you...",Twitter for iPhone,3617,19097,2020-01-17 10:47:40
2,liampayne,"""158314798""",Tweet,"""Thanks to the amazing team that worked so har...",Twitter for iPhone,6602,35032,2020-01-16 17:18:03
3,tenerifeziam,"""930997525""",Retweet,"""I just made this pet playlist for my dog and ...",Twitter for iPhone,626,5901,2020-01-15 18:18:29
4,liampayne,"""158314798""",Tweet,"""Live Forever with @CheatCodesMusic live at th...",Twitter for iPhone,5186,25010,2020-01-15 17:49:58
...,...,...,...,...,...,...,...,...
3195,liampayne,"""158314798""",Tweet,"""I'd just like to be able to walk outside as e...",Twitter for iPhone,82899,122650,2014-01-14 20:29:53
3196,liampayne,"""158314798""",Tweet,"""I know my friends have tweeted a lot of pictu...",Twitter for iPhone,82664,120309,2014-01-14 20:27:45
3197,liampayne,"""158314798""",Tweet,"""Happy birthday @Laurastanway have a good one""",Twitter for iPhone,27960,58426,2014-01-13 17:37:55
3198,liampayne,"""158314798""",Tweet,"""Had some strange dreams yesterday wonder what...",Twitter for iPhone,72885,108140,2014-01-12 11:31:36
3199,liampayne,"""158314798""",Tweet,"""Rap battles in the car so funny aha""",Twitter for iPhone,71477,115884,2014-01-12 00:10:34

##### REMOVE ALL ROWS WITH NO DATA

In [6]:
#Filter out those rows which does not contain any data 
LPayne_Tweets_df = LPayne_Tweets_df.dropna() 

#Confirm rows are dropped
shape = LPayne_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

##### SEPERATE THE DATE AND TIME

In [7]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
LPayne_Tweets_df['Tweet Posted Time'] = LPayne_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = LPayne_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
LPayne_Tweets_df["Date"] = date

In [8]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
LPayne_Tweets_df['Tweet Posted Time'] = LPayne_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = LPayne_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
LPayne_Tweets_df["Time"] = time

In [9]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
LPayne_Tweets_df = LPayne_Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = LPayne_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 9)

In [10]:
#Print the dataframe
LPayne_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time
0,liampayne,"""158314798""",Tweet,"""Proud to show you my first campaign with HUGO...",Twitter for iPhone,6061,28537,2020-01-22,09:01:06
1,liampayne,"""158314798""",Tweet,"""Tickets now on sale for @WolvesRaces! See you...",Twitter for iPhone,3617,19097,2020-01-17,10:47:40
2,liampayne,"""158314798""",Tweet,"""Thanks to the amazing team that worked so har...",Twitter for iPhone,6602,35032,2020-01-16,17:18:03
3,tenerifeziam,"""930997525""",Retweet,"""I just made this pet playlist for my dog and ...",Twitter for iPhone,626,5901,2020-01-15,18:18:29
4,liampayne,"""158314798""",Tweet,"""Live Forever with @CheatCodesMusic live at th...",Twitter for iPhone,5186,25010,2020-01-15,17:49:58
...,...,...,...,...,...,...,...,...,...
3195,liampayne,"""158314798""",Tweet,"""I'd just like to be able to walk outside as e...",Twitter for iPhone,82899,122650,2014-01-14,20:29:53
3196,liampayne,"""158314798""",Tweet,"""I know my friends have tweeted a lot of pictu...",Twitter for iPhone,82664,120309,2014-01-14,20:27:45
3197,liampayne,"""158314798""",Tweet,"""Happy birthday @Laurastanway have a good one""",Twitter for iPhone,27960,58426,2014-01-13,17:37:55
3198,liampayne,"""158314798""",Tweet,"""Had some strange dreams yesterday wonder what...",Twitter for iPhone,72885,108140,2014-01-12,11:31:36
3199,liampayne,"""158314798""",Tweet,"""Rap battles in the car so funny aha""",Twitter for iPhone,71477,115884,2014-01-12,00:10:34

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND FILL

In [11]:
#Create an Gender column for Gender
LPayne_Tweets_df['Gender'] = "Male"

#Create an Gender column for Gender
LPayne_Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = LPayne_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 11)

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [12]:
#The original dataframe had an index, so re-arrange the index 
LPayne_Tweets_df.index = [x for x in range(1, len(LPayne_Tweets_df.values)+1)]
LPayne_Tweets_df.index.name = 'Index'

In [13]:
#Print the dataframe
LPayne_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time,Gender,Vocation
Index,,,,,,,,,,,
1,liampayne,"""158314798""",Tweet,"""Proud to show you my first campaign with HUGO...",Twitter for iPhone,6061,28537,2020-01-22,09:01:06,Male,Music
2,liampayne,"""158314798""",Tweet,"""Tickets now on sale for @WolvesRaces! See you...",Twitter for iPhone,3617,19097,2020-01-17,10:47:40,Male,Music
3,liampayne,"""158314798""",Tweet,"""Thanks to the amazing team that worked so har...",Twitter for iPhone,6602,35032,2020-01-16,17:18:03,Male,Music
4,tenerifeziam,"""930997525""",Retweet,"""I just made this pet playlist for my dog and ...",Twitter for iPhone,626,5901,2020-01-15,18:18:29,Male,Music
5,liampayne,"""158314798""",Tweet,"""Live Forever with @CheatCodesMusic live at th...",Twitter for iPhone,5186,25010,2020-01-15,17:49:58,Male,Music
...,...,...,...,...,...,...,...,...,...,...,...
3196,liampayne,"""158314798""",Tweet,"""I'd just like to be able to walk outside as e...",Twitter for iPhone,82899,122650,2014-01-14,20:29:53,Male,Music
3197,liampayne,"""158314798""",Tweet,"""I know my friends have tweeted a lot of pictu...",Twitter for iPhone,82664,120309,2014-01-14,20:27:45,Male,Music
3198,liampayne,"""158314798""",Tweet,"""Happy birthday @Laurastanway have a good one""",Twitter for iPhone,27960,58426,2014-01-13,17:37:55,Male,Music
3199,liampayne,"""158314798""",Tweet,"""Had some strange dreams yesterday wonder what...",Twitter for iPhone,72885,108140,2014-01-12,11:31:36,Male,Music
3200,liampayne,"""158314798""",Tweet,"""Rap battles in the car so funny aha""",Twitter for iPhone,71477,115884,2014-01-12,00:10:34,Male,Music

##### SAVE DATAFRAME TO CSV

In [14]:
#Save dataframe as csv file
LPayne_Tweets_df.to_csv('LPayne_Tweets_df.csv')