##### ===================================================================================================================

# Rihanna Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

In [2]:
#Create reference to CSV file
csv_path = "RihannaTweets.csv"

#Import the CSV into a pandas DataFrame
Rihanna_Tweets_df = pd.read_csv(csv_path, low_memory = False)
Rihanna_Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1216521751972024321""",https://twitter.com/rihanna/status/12165217519...,2020-01-13 00:46:02,"""The @SavageXFenty Valentine collection design...",Tweet,Twitter for iPhone,13733,127356,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected
1,"""1216489076091523072""",https://twitter.com/rihanna/status/12164890760...,2020-01-12 22:36:11,"""New Year, New Valentineâ€™s gift! Get ready to ...",Tweet,Twitter for iPhone,10925,114439,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected
2,"""1214655618394378240""",https://twitter.com/rihanna/status/12146556183...,2020-01-07 21:10:41,"""Ya done know that @fentybeauty was coming to ...",Tweet,Twitter for iPhone,6789,75299,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected
3,"""1214305599069929473""",https://twitter.com/rihanna/status/12143055990...,2020-01-06 21:59:50,"""first selfie of the year doe. #2020 https://t...",Tweet,Twitter for iPhone,98232,983297,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected
4,"""1214227610911170561""",https://twitter.com/rihanna/status/12142276109...,2020-01-06 16:49:56,"""devastating. ðŸ˜¢ #Australia https://t.co/VB2czi...",Tweet,Twitter for iPhone,75458,347205,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""291913209290567684""",https://twitter.com/rihanna/status/29191320929...,2013-01-17 14:21:47,"""All I see is $ign$ tho #SlayItUp #navi â€œ@Stef...",Tweet,Twitter for iPhone,1064,624,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected
3196,"""291868014926778369""",https://twitter.com/britishvogue/status/291868...,2013-01-17 11:22:12,"""Vogue cover girl @rihanna will launch her @ri...",Retweet,Twitter Web Client,866,348,"""27844479""","""British Vogue""",britishvogue,Verified,https://twitter.com/britishvogue,Not Protected
3197,"""291675410876465152""",https://twitter.com/rihanna/status/29167541087...,2013-01-16 22:36:51,"""All I got are these photographs #phuckyoshirt...",Tweet,Instagram,1533,958,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected
3198,"""291670929329762304""",https://twitter.com/rihanna/status/29167092932...,2013-01-16 22:19:03,"""#SINGLEcover for #STAY http://t.co/Ta8Y8dHd""",Tweet,Instagram,2320,1172,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected
3199,"""291670595358322688""",https://twitter.com/rihanna/status/29167059535...,2013-01-16 22:17:43,"""#SINGLEcover for #POURitUP http://t.co/Xz6jHY7e""",Tweet,Instagram,1970,1013,"""79293791""","""Rihanna""",rihanna,Verified,https://twitter.com/rihanna,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = Rihanna_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
Rihanna_Tweets_df = Rihanna_Tweets_df[["Username", "User Id", "Tweet Type", "Tweet Content", "Client", "Retweets received",
                                     "Likes received", "Tweet Posted Time"]]

#Show the 'shape' of the dataframe
shape = Rihanna_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

In [5]:
#Print the dataframe
Rihanna_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Tweet Posted Time
0,rihanna,"""79293791""",Tweet,"""The @SavageXFenty Valentine collection design...",Twitter for iPhone,13733,127356,2020-01-13 00:46:02
1,rihanna,"""79293791""",Tweet,"""New Year, New Valentineâ€™s gift! Get ready to ...",Twitter for iPhone,10925,114439,2020-01-12 22:36:11
2,rihanna,"""79293791""",Tweet,"""Ya done know that @fentybeauty was coming to ...",Twitter for iPhone,6789,75299,2020-01-07 21:10:41
3,rihanna,"""79293791""",Tweet,"""first selfie of the year doe. #2020 https://t...",Twitter for iPhone,98232,983297,2020-01-06 21:59:50
4,rihanna,"""79293791""",Tweet,"""devastating. ðŸ˜¢ #Australia https://t.co/VB2czi...",Twitter for iPhone,75458,347205,2020-01-06 16:49:56
...,...,...,...,...,...,...,...,...
3195,rihanna,"""79293791""",Tweet,"""All I see is $ign$ tho #SlayItUp #navi â€œ@Stef...",Twitter for iPhone,1064,624,2013-01-17 14:21:47
3196,britishvogue,"""27844479""",Retweet,"""Vogue cover girl @rihanna will launch her @ri...",Twitter Web Client,866,348,2013-01-17 11:22:12
3197,rihanna,"""79293791""",Tweet,"""All I got are these photographs #phuckyoshirt...",Instagram,1533,958,2013-01-16 22:36:51
3198,rihanna,"""79293791""",Tweet,"""#SINGLEcover for #STAY http://t.co/Ta8Y8dHd""",Instagram,2320,1172,2013-01-16 22:19:03
3199,rihanna,"""79293791""",Tweet,"""#SINGLEcover for #POURitUP http://t.co/Xz6jHY7e""",Instagram,1970,1013,2013-01-16 22:17:43

##### REMOVE ALL ROWS WITH NO DATA

In [6]:
#Filter out those rows which does not contain any data 
Rihanna_Tweets_df = Rihanna_Tweets_df.dropna() 

#Confirm rows are dropped
shape = Rihanna_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

##### SEPERATE THE DATE AND TIME

In [7]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Rihanna_Tweets_df['Tweet Posted Time'] = Rihanna_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Rihanna_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
Rihanna_Tweets_df["Date"] = date

In [8]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
Rihanna_Tweets_df['Tweet Posted Time'] = Rihanna_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = Rihanna_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
Rihanna_Tweets_df["Time"] = time

In [9]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
Rihanna_Tweets_df = Rihanna_Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = Rihanna_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 9)

In [10]:
#Print the dataframe
Rihanna_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time
0,rihanna,"""79293791""",Tweet,"""The @SavageXFenty Valentine collection design...",Twitter for iPhone,13733,127356,2020-01-13,00:46:02
1,rihanna,"""79293791""",Tweet,"""New Year, New Valentineâ€™s gift! Get ready to ...",Twitter for iPhone,10925,114439,2020-01-12,22:36:11
2,rihanna,"""79293791""",Tweet,"""Ya done know that @fentybeauty was coming to ...",Twitter for iPhone,6789,75299,2020-01-07,21:10:41
3,rihanna,"""79293791""",Tweet,"""first selfie of the year doe. #2020 https://t...",Twitter for iPhone,98232,983297,2020-01-06,21:59:50
4,rihanna,"""79293791""",Tweet,"""devastating. ðŸ˜¢ #Australia https://t.co/VB2czi...",Twitter for iPhone,75458,347205,2020-01-06,16:49:56
...,...,...,...,...,...,...,...,...,...
3195,rihanna,"""79293791""",Tweet,"""All I see is $ign$ tho #SlayItUp #navi â€œ@Stef...",Twitter for iPhone,1064,624,2013-01-17,14:21:47
3196,britishvogue,"""27844479""",Retweet,"""Vogue cover girl @rihanna will launch her @ri...",Twitter Web Client,866,348,2013-01-17,11:22:12
3197,rihanna,"""79293791""",Tweet,"""All I got are these photographs #phuckyoshirt...",Instagram,1533,958,2013-01-16,22:36:51
3198,rihanna,"""79293791""",Tweet,"""#SINGLEcover for #STAY http://t.co/Ta8Y8dHd""",Instagram,2320,1172,2013-01-16,22:19:03
3199,rihanna,"""79293791""",Tweet,"""#SINGLEcover for #POURitUP http://t.co/Xz6jHY7e""",Instagram,1970,1013,2013-01-16,22:17:43

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND FILL

In [11]:
#Create an Gender column for Gender
Rihanna_Tweets_df['Gender'] = "Female"

#Create an Gender column for Gender
Rihanna_Tweets_df['Vocation'] = "Music"

#Show the 'shape' of the dataframe
shape = Rihanna_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 11)

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [12]:
#The original dataframe had an index, so re-arrange the index 
Rihanna_Tweets_df.index = [x for x in range(1, len(Rihanna_Tweets_df.values)+1)]
Rihanna_Tweets_df.index.name = 'Index'

In [13]:
#Print the dataframe
Rihanna_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time,Gender,Vocation
Index,,,,,,,,,,,
1,rihanna,"""79293791""",Tweet,"""The @SavageXFenty Valentine collection design...",Twitter for iPhone,13733,127356,2020-01-13,00:46:02,Female,Music
2,rihanna,"""79293791""",Tweet,"""New Year, New Valentineâ€™s gift! Get ready to ...",Twitter for iPhone,10925,114439,2020-01-12,22:36:11,Female,Music
3,rihanna,"""79293791""",Tweet,"""Ya done know that @fentybeauty was coming to ...",Twitter for iPhone,6789,75299,2020-01-07,21:10:41,Female,Music
4,rihanna,"""79293791""",Tweet,"""first selfie of the year doe. #2020 https://t...",Twitter for iPhone,98232,983297,2020-01-06,21:59:50,Female,Music
5,rihanna,"""79293791""",Tweet,"""devastating. ðŸ˜¢ #Australia https://t.co/VB2czi...",Twitter for iPhone,75458,347205,2020-01-06,16:49:56,Female,Music
...,...,...,...,...,...,...,...,...,...,...,...
3196,rihanna,"""79293791""",Tweet,"""All I see is $ign$ tho #SlayItUp #navi â€œ@Stef...",Twitter for iPhone,1064,624,2013-01-17,14:21:47,Female,Music
3197,britishvogue,"""27844479""",Retweet,"""Vogue cover girl @rihanna will launch her @ri...",Twitter Web Client,866,348,2013-01-17,11:22:12,Female,Music
3198,rihanna,"""79293791""",Tweet,"""All I got are these photographs #phuckyoshirt...",Instagram,1533,958,2013-01-16,22:36:51,Female,Music
3199,rihanna,"""79293791""",Tweet,"""#SINGLEcover for #STAY http://t.co/Ta8Y8dHd""",Instagram,2320,1172,2013-01-16,22:19:03,Female,Music
3200,rihanna,"""79293791""",Tweet,"""#SINGLEcover for #POURitUP http://t.co/Xz6jHY7e""",Instagram,1970,1013,2013-01-16,22:17:43,Female,Music

##### SAVE DATAFRAME TO CSV

In [14]:
#Save dataframe as csv file
Rihanna_Tweets_df.to_csv('Rihanna_Tweets_df.csv')