##### ===================================================================================================================

# Shah Rukh Khan Tweets

##### ===================================================================================================================

In [1]:
#Import Dependencies
import pandas as pd

In [2]:
#Create reference to CSV file
csv_path = "ShahRukhKhanTweets.csv"

#Import the CSV into a pandas DataFrame
SRK_Tweets_df = pd.read_csv(csv_path, low_memory = False)
SRK_Tweets_df

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets received,Likes received,User Id,Name,Username,Verified or Non-Verified,Profile URL,Protected or Not Protected
0,"""1219947963964723205""",https://twitter.com/iamsrk/status/121994796396...,2020-01-22 11:40:34,"""Need to go now. Nice having a chat with u all...",Tweet,Twitter for iPhone,4432,40569,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
1,"""1219946775756165125""",https://twitter.com/iamsrk/status/121994677575...,2020-01-22 11:35:51,"""My thoughts exactly... https://t.co/XLjMeBCvSw""",Tweet,Twitter for iPhone,1159,6507,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
2,"""1219945237159612416""",https://twitter.com/iamsrk/status/121994523715...,2020-01-22 11:29:44,"""Don’t let any negativity uninspire you in you...",Tweet,Twitter for iPhone,1956,10759,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
3,"""1219943862157766656""",https://twitter.com/iamsrk/status/121994386215...,2020-01-22 11:24:16,"""30 saal ki mehnat mein padega. https://t.co/Y...",Tweet,Twitter for iPhone,4242,28664,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
4,"""1219941641206648832""",https://twitter.com/iamsrk/status/121994164120...,2020-01-22 11:15:27,"""Sardi https://t.co/n8es8mo06i""",Tweet,Twitter for iPhone,1322,8907,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,"""777243869708640256""",https://twitter.com/iamsrk/status/777243869708...,2016-09-17 20:32:33,"""U killed me!!! https://t.co/BgEbDAWo1n""",Tweet,Tweetbot for iΟS,2318,7030,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
3196,"""776851369659543552""",https://twitter.com/iamsrk/status/776851369659...,2016-09-16 18:32:54,"""Surrounded by Masters keeping a Nightwatch. R...",Tweet,Tweetbot for iΟS,4351,18369,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
3197,"""776850792980414464""",https://twitter.com/iamsrk/status/776850792980...,2016-09-16 18:30:36,"""Surrounded by Masters keeping a Nightwatch. R...",Tweet,Instagram,1982,6330,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
3198,"""776706212368756736""",https://twitter.com/iamsrk/status/776706212368...,2016-09-16 08:56:06,"""Such hardwork and ur video made me nostalgic ...",Tweet,Tweetbot for iΟS,2532,7962,"""101311381""","""Shah Rukh Khan""",iamsrk,Verified,https://twitter.com/iamsrk,Not Protected
3199,"""776704899887329280""",https://twitter.com/ahmedzaman94/status/776704...,2016-09-16 08:50:53,"""@SRK_FC https://t.co/aKOSk3iKyp\nCheck out th...",Retweet,Twitter for iPhone,1263,3446,"""431033844""","""Ahmed Sher Zaman""",ahmedzaman94,Non-Verified,https://twitter.com/ahmedzaman94,Not Protected

In [3]:
#Show the 'shape' of the dataframe 
shape = SRK_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 14)

##### COLLECT ONLY REQUIRED COLUMNS

In [4]:
#Select only columns we need
SRK_Tweets_df = SRK_Tweets_df[["Username", "User Id", "Tweet Type", "Tweet Content", "Client", "Retweets received",
                                     "Likes received", "Tweet Posted Time"]]

#Show the 'shape' of the dataframe
shape = SRK_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

In [5]:
#Print the dataframe
SRK_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Tweet Posted Time
0,iamsrk,"""101311381""",Tweet,"""Need to go now. Nice having a chat with u all...",Twitter for iPhone,4432,40569,2020-01-22 11:40:34
1,iamsrk,"""101311381""",Tweet,"""My thoughts exactly... https://t.co/XLjMeBCvSw""",Twitter for iPhone,1159,6507,2020-01-22 11:35:51
2,iamsrk,"""101311381""",Tweet,"""Don’t let any negativity uninspire you in you...",Twitter for iPhone,1956,10759,2020-01-22 11:29:44
3,iamsrk,"""101311381""",Tweet,"""30 saal ki mehnat mein padega. https://t.co/Y...",Twitter for iPhone,4242,28664,2020-01-22 11:24:16
4,iamsrk,"""101311381""",Tweet,"""Sardi https://t.co/n8es8mo06i""",Twitter for iPhone,1322,8907,2020-01-22 11:15:27
...,...,...,...,...,...,...,...,...
3195,iamsrk,"""101311381""",Tweet,"""U killed me!!! https://t.co/BgEbDAWo1n""",Tweetbot for iΟS,2318,7030,2016-09-17 20:32:33
3196,iamsrk,"""101311381""",Tweet,"""Surrounded by Masters keeping a Nightwatch. R...",Tweetbot for iΟS,4351,18369,2016-09-16 18:32:54
3197,iamsrk,"""101311381""",Tweet,"""Surrounded by Masters keeping a Nightwatch. R...",Instagram,1982,6330,2016-09-16 18:30:36
3198,iamsrk,"""101311381""",Tweet,"""Such hardwork and ur video made me nostalgic ...",Tweetbot for iΟS,2532,7962,2016-09-16 08:56:06
3199,ahmedzaman94,"""431033844""",Retweet,"""@SRK_FC https://t.co/aKOSk3iKyp\nCheck out th...",Twitter for iPhone,1263,3446,2016-09-16 08:50:53

##### REMOVE ALL ROWS WITH NO DATA

In [6]:
#Filter out those rows which does not contain any data 
SRK_Tweets_df = SRK_Tweets_df.dropna() 

#Confirm rows are dropped
shape = SRK_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 8)

##### SEPERATE THE DATE AND TIME

In [7]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
SRK_Tweets_df['Tweet Posted Time'] = SRK_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = SRK_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to only show yyyy-mm-dd format
date = []
for x in dt_list:
    date.append(x.split(" ")[0])

#Add the formated lists into the dataframe as new columns
SRK_Tweets_df["Date"] = date

In [8]:
#Convert the 'Tweet Posted Time' column to string (from TimeStamp due to previous function to_datetime used)
SRK_Tweets_df['Tweet Posted Time'] = SRK_Tweets_df['Tweet Posted Time'].astype(str)

#Convert column to list
dt_list = SRK_Tweets_df["Tweet Posted Time"].tolist()

#Clean up the list to show time
time = []
for x in dt_list:
    time.append(x.split(" ")[1])

#Add the formated lists into the dataframe as new columns
SRK_Tweets_df["Time"] = time

In [9]:
#Drop the 'Tweet Posted Time' column as it is now replaced with a 'Date' and 'Time' column
SRK_Tweets_df = SRK_Tweets_df.drop(['Tweet Posted Time'], axis = 1)

#Show the 'shape' of the dataframe
shape = SRK_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 9)

In [10]:
#Print the dataframe
SRK_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time
0,iamsrk,"""101311381""",Tweet,"""Need to go now. Nice having a chat with u all...",Twitter for iPhone,4432,40569,2020-01-22,11:40:34
1,iamsrk,"""101311381""",Tweet,"""My thoughts exactly... https://t.co/XLjMeBCvSw""",Twitter for iPhone,1159,6507,2020-01-22,11:35:51
2,iamsrk,"""101311381""",Tweet,"""Don’t let any negativity uninspire you in you...",Twitter for iPhone,1956,10759,2020-01-22,11:29:44
3,iamsrk,"""101311381""",Tweet,"""30 saal ki mehnat mein padega. https://t.co/Y...",Twitter for iPhone,4242,28664,2020-01-22,11:24:16
4,iamsrk,"""101311381""",Tweet,"""Sardi https://t.co/n8es8mo06i""",Twitter for iPhone,1322,8907,2020-01-22,11:15:27
...,...,...,...,...,...,...,...,...,...
3195,iamsrk,"""101311381""",Tweet,"""U killed me!!! https://t.co/BgEbDAWo1n""",Tweetbot for iΟS,2318,7030,2016-09-17,20:32:33
3196,iamsrk,"""101311381""",Tweet,"""Surrounded by Masters keeping a Nightwatch. R...",Tweetbot for iΟS,4351,18369,2016-09-16,18:32:54
3197,iamsrk,"""101311381""",Tweet,"""Surrounded by Masters keeping a Nightwatch. R...",Instagram,1982,6330,2016-09-16,18:30:36
3198,iamsrk,"""101311381""",Tweet,"""Such hardwork and ur video made me nostalgic ...",Tweetbot for iΟS,2532,7962,2016-09-16,08:56:06
3199,ahmedzaman94,"""431033844""",Retweet,"""@SRK_FC https://t.co/aKOSk3iKyp\nCheck out th...",Twitter for iPhone,1263,3446,2016-09-16,08:50:53

##### ADD A GENDER AND VOCATION COLUMN TO THE DATAFRAME AND FILL

In [11]:
#Create an Gender column for Gender
SRK_Tweets_df['Gender'] = "Male"

#Create an Gender column for Gender
SRK_Tweets_df['Vocation'] = "Entertainment"

#Show the 'shape' of the dataframe
shape = SRK_Tweets_df.shape
print(f"The dataframes 'shape' is represented as: {shape}")

The dataframes 'shape' is represented as: (3200, 11)

##### CORRECT THE INDEX FOR VISUAL PURPOSES

In [12]:
#The original dataframe had an index, so re-arrange the index 
SRK_Tweets_df.index = [x for x in range(1, len(SRK_Tweets_df.values)+1)]
SRK_Tweets_df.index.name = 'Index'

In [13]:
#Print the dataframe
SRK_Tweets_df

,Username,User Id,Tweet Type,Tweet Content,Client,Retweets received,Likes received,Date,Time,Gender,Vocation
Index,,,,,,,,,,,
1,iamsrk,"""101311381""",Tweet,"""Need to go now. Nice having a chat with u all...",Twitter for iPhone,4432,40569,2020-01-22,11:40:34,Male,Entertainment
2,iamsrk,"""101311381""",Tweet,"""My thoughts exactly... https://t.co/XLjMeBCvSw""",Twitter for iPhone,1159,6507,2020-01-22,11:35:51,Male,Entertainment
3,iamsrk,"""101311381""",Tweet,"""Don’t let any negativity uninspire you in you...",Twitter for iPhone,1956,10759,2020-01-22,11:29:44,Male,Entertainment
4,iamsrk,"""101311381""",Tweet,"""30 saal ki mehnat mein padega. https://t.co/Y...",Twitter for iPhone,4242,28664,2020-01-22,11:24:16,Male,Entertainment
5,iamsrk,"""101311381""",Tweet,"""Sardi https://t.co/n8es8mo06i""",Twitter for iPhone,1322,8907,2020-01-22,11:15:27,Male,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...
3196,iamsrk,"""101311381""",Tweet,"""U killed me!!! https://t.co/BgEbDAWo1n""",Tweetbot for iΟS,2318,7030,2016-09-17,20:32:33,Male,Entertainment
3197,iamsrk,"""101311381""",Tweet,"""Surrounded by Masters keeping a Nightwatch. R...",Tweetbot for iΟS,4351,18369,2016-09-16,18:32:54,Male,Entertainment
3198,iamsrk,"""101311381""",Tweet,"""Surrounded by Masters keeping a Nightwatch. R...",Instagram,1982,6330,2016-09-16,18:30:36,Male,Entertainment
3199,iamsrk,"""101311381""",Tweet,"""Such hardwork and ur video made me nostalgic ...",Tweetbot for iΟS,2532,7962,2016-09-16,08:56:06,Male,Entertainment
3200,ahmedzaman94,"""431033844""",Retweet,"""@SRK_FC https://t.co/aKOSk3iKyp\nCheck out th...",Twitter for iPhone,1263,3446,2016-09-16,08:50:53,Male,Entertainment

##### SAVE DATAFRAME TO CSV

In [14]:
#Save dataframe as csv file
SRK_Tweets_df.to_csv('SRK_Tweets_df.csv')